import { DashboardShell } from "@/components/dashboard/dashboard-shell";
import { DashboardHeader } from "@/components/dashboard/dashboard-header";
import { saveAnnouncementV155, saveBannerV155, saveNewsV155, trashContentV155 } from "@/app/actions/v155";
import { getAnnouncementsV155, getBannersV155, getNewsV155 } from "@/lib/v155/data";
import styles from "@/components/v155/v155.module.css";

function localDate(value:string|null|undefined){if(!value)return "";const d=new Date(value);if(Number.isNaN(d.getTime()))return "";const z=(n:number)=>String(n).padStart(2,"0");return `${d.getFullYear()}-${z(d.getMonth()+1)}-${z(d.getDate())}T${z(d.getHours())}:${z(d.getMinutes())}`;}

export default async function CommunicationDashboard(){
  const [news,banners,announcements]=await Promise.all([getNewsV155(true),getBannersV155(true),getAnnouncementsV155(true)]);
  return <DashboardShell><DashboardHeader title="Communication Nostra Group" description="Actualités, bannières temporaires et annonces importantes diffusées sur le site, avec dates automatiques de début et de fin."/><main className={styles.page} style={{paddingTop:10}}>
    <div className={styles.grid}>
      <section className={styles.card}><h2>Nouvelle actualité</h2><form action={saveNewsV155} className={styles.stack}><select className={styles.select} name="pole"><option value="group">Nostra Group</option><option value="motors">Motors</option><option value="circuit">Circuit</option><option value="cercle">Cercle</option><option value="academy">Academy</option></select><input className={styles.input} name="title" placeholder="Titre" required/><input className={styles.input} name="excerpt" placeholder="Résumé"/><textarea className={styles.textarea} name="content" placeholder="Contenu"/><input className={styles.input} name="image_url" placeholder="URL image (facultatif)"/><div className={styles.formGrid}><label>Début<input className={styles.input} type="datetime-local" name="starts_at"/></label><label>Fin<input className={styles.input} type="datetime-local" name="ends_at"/></label></div><label><input type="checkbox" name="published" defaultChecked/> Publiée</label><label><input type="checkbox" name="featured"/> Mise en avant</label><button className={styles.button}>Publier</button></form></section>
      <section className={styles.card}><h2>Nouvelle bannière temporaire</h2><form action={saveBannerV155} className={styles.stack}><input type="hidden" name="pole" value="group"/><input className={styles.input} name="title" placeholder="Titre" required/><textarea className={styles.textarea} name="message" placeholder="Message"/><input className={styles.input} name="cta_label" placeholder="Texte bouton"/><input className={styles.input} name="cta_url" placeholder="Lien bouton"/><div className={styles.formGrid}><label>Début<input className={styles.input} type="datetime-local" name="starts_at"/></label><label>Fin<input className={styles.input} type="datetime-local" name="ends_at"/></label></div><input className={styles.input} type="number" name="priority" placeholder="Priorité"/><label><input type="checkbox" name="active" defaultChecked/> Active</label><button className={styles.button}>Créer la bannière</button></form></section>
      <section className={styles.card}><h2>Annonce importante</h2><form action={saveAnnouncementV155} className={styles.stack}><input className={styles.input} name="title" placeholder="Titre" required/><textarea className={styles.textarea} name="message" placeholder="Message affiché en haut du site" required/><select className={styles.select} name="severity"><option value="info">Information</option><option value="important">Importante</option><option value="critical">Critique</option></select><div className={styles.formGrid}><label>Début<input className={styles.input} type="datetime-local" name="starts_at"/></label><label>Fin<input className={styles.input} type="datetime-local" name="ends_at"/></label></div><label><input type="checkbox" name="active" defaultChecked/> Active</label><label><input type="checkbox" name="dismissible" defaultChecked/> Le citoyen peut la fermer</label><button className={styles.button}>Diffuser l’annonce</button></form></section>
    </div>

    <section className={styles.sectionTitle}><span className={styles.eyebrow}>MODIFICATION EN DIRECT</span><h2>Actualités</h2></section>
    <div className={styles.grid}>{news.map((x:any)=><form className={styles.card} action={saveNewsV155} key={x.id}><input type="hidden" name="id" value={x.id}/><select className={styles.select} name="pole" defaultValue={x.pole}><option value="group">Nostra Group</option><option value="motors">Motors</option><option value="circuit">Circuit</option><option value="cercle">Cercle</option><option value="academy">Academy</option></select><input className={styles.input} name="title" defaultValue={x.title}/><input className={styles.input} name="excerpt" defaultValue={x.excerpt}/><textarea className={styles.textarea} name="content" defaultValue={x.content}/><input className={styles.input} name="image_url" defaultValue={x.image_url??""}/><div className={styles.formGrid}><label>Début<input className={styles.input} type="datetime-local" name="starts_at" defaultValue={localDate(x.starts_at)}/></label><label>Fin<input className={styles.input} type="datetime-local" name="ends_at" defaultValue={localDate(x.ends_at)}/></label></div><label><input type="checkbox" name="published" defaultChecked={x.published}/> Publiée</label><label><input type="checkbox" name="featured" defaultChecked={x.featured}/> Mise en avant</label><button className={styles.button}>Enregistrer</button><button className={styles.danger} formAction={trashContentV155} name="entity_type" value="nostra_news_v155">Mettre à la corbeille</button></form>)}</div>

    <section className={styles.sectionTitle}><h2>Bannières temporaires</h2></section>
    <div className={styles.grid}>{banners.map((x:any)=><form className={styles.card} action={saveBannerV155} key={x.id}><input type="hidden" name="id" value={x.id}/><input type="hidden" name="pole" value={x.pole}/><input className={styles.input} name="title" defaultValue={x.title}/><textarea className={styles.textarea} name="message" defaultValue={x.message}/><input className={styles.input} name="cta_label" defaultValue={x.cta_label??""}/><input className={styles.input} name="cta_url" defaultValue={x.cta_url??""}/><div className={styles.formGrid}><label>Début<input className={styles.input} type="datetime-local" name="starts_at" defaultValue={localDate(x.starts_at)}/></label><label>Fin<input className={styles.input} type="datetime-local" name="ends_at" defaultValue={localDate(x.ends_at)}/></label></div><input className={styles.input} type="number" name="priority" defaultValue={x.priority}/><label><input type="checkbox" name="active" defaultChecked={x.active}/> Active</label><button className={styles.button}>Enregistrer</button><button className={styles.danger} formAction={trashContentV155} name="entity_type" value="nostra_banners_v155">Mettre à la corbeille</button></form>)}</div>

    <section className={styles.sectionTitle}><h2>Annonces importantes</h2></section>
    <div className={styles.grid}>{announcements.map((x:any)=><form className={styles.card} action={saveAnnouncementV155} key={x.id}><input type="hidden" name="id" value={x.id}/><input className={styles.input} name="title" defaultValue={x.title}/><textarea className={styles.textarea} name="message" defaultValue={x.message}/><select className={styles.select} name="severity" defaultValue={x.severity}><option value="info">Information</option><option value="important">Importante</option><option value="critical">Critique</option></select><div className={styles.formGrid}><label>Début<input className={styles.input} type="datetime-local" name="starts_at" defaultValue={localDate(x.starts_at)}/></label><label>Fin<input className={styles.input} type="datetime-local" name="ends_at" defaultValue={localDate(x.ends_at)}/></label></div><label><input type="checkbox" name="active" defaultChecked={x.active}/> Active</label><label><input type="checkbox" name="dismissible" defaultChecked={x.dismissible}/> Fermable</label><button className={styles.button}>Enregistrer</button><button className={styles.danger} formAction={trashContentV155} name="entity_type" value="nostra_announcements_v155">Mettre à la corbeille</button></form>)}</div>
  </main></DashboardShell>;
}
