-- NOSTRA GROUP V32.2 — BINGO 1 À 99
-- Cartons B-I-N-G-O de 24 numéros répartis de 1 à 99 + case centrale Nostra Motors, panier, achat,
-- tirage en direct, détection automatique des lignes et carton plein,
-- clear des numéros et réinitialisation complète.
-- Script réexécutable : les données existantes sont conservées.

create or replace function public.nostra_bingo_is_manager()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select
    coalesce(public.nostra_has_role('manager'), false)
    or coalesce(public.nostra_jwt_discord_id(), '') = '331843410962939908'
    or exists (
      select 1
      from public.member_profiles profile
      where profile.user_id = auth.uid()
        and (
          lower(coalesce(profile.role, '')) = 'manager'
          or 'manager' = any(coalesce(profile.roles, array[]::text[]))
          or profile.discord_id = '331843410962939908'
        )
    );
$$;

revoke all on function public.nostra_bingo_is_manager() from public;
grant execute on function public.nostra_bingo_is_manager() to authenticated;

create table if not exists public.bingo_rounds (
  id bigint generated by default as identity primary key,
  title text not null default 'Bingo Nostra Group',
  card_price numeric(12,2) not null default 5000,
  status text not null default 'open',
  phase text not null default 'one_line',
  archived_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint bingo_rounds_price_check check (card_price >= 0),
  constraint bingo_rounds_status_check check (status in ('open','closed','playing','completed','archived')),
  constraint bingo_rounds_phase_check check (phase in ('one_line','two_lines','three_lines','four_lines','full_card'))
);

create unique index if not exists bingo_rounds_single_current_idx
  on public.bingo_rounds ((archived_at is null))
  where archived_at is null;

insert into public.bingo_rounds (title, card_price, status, phase)
select 'Bingo Nostra Group', 5000, 'open', 'one_line'
where not exists (
  select 1 from public.bingo_rounds where archived_at is null
);

create table if not exists public.bingo_cart_items (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  round_id bigint not null references public.bingo_rounds(id) on delete cascade,
  customer_name text not null,
  quantity integer not null,
  unit_price numeric(12,2) not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint bingo_cart_quantity_check check (quantity between 1 and 20),
  constraint bingo_cart_price_check check (unit_price >= 0),
  unique (user_id, round_id)
);

create table if not exists public.bingo_purchases (
  id bigint generated by default as identity primary key,
  round_id bigint not null references public.bingo_rounds(id) on delete restrict,
  user_id uuid not null references auth.users(id) on delete cascade,
  order_number text not null unique,
  customer_name text not null,
  quantity integer not null,
  unit_price numeric(12,2) not null,
  total numeric(14,2) not null,
  created_at timestamptz not null default now(),
  constraint bingo_purchase_quantity_check check (quantity > 0),
  constraint bingo_purchase_total_check check (total >= 0)
);

create table if not exists public.bingo_cards (
  id bigint generated by default as identity primary key,
  round_id bigint not null references public.bingo_rounds(id) on delete cascade,
  purchase_id bigint not null references public.bingo_purchases(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  customer_name text not null,
  card_number integer not null,
  numbers integer[] not null,
  created_at timestamptz not null default now(),
  constraint bingo_card_number_check check (card_number > 0),
  constraint bingo_card_numbers_check check (
    cardinality(numbers) = 25
    and numbers[13] = 0
  ),
  unique (round_id, card_number)
);

create index if not exists bingo_cards_round_owner_idx
  on public.bingo_cards(round_id, user_id, card_number);

create table if not exists public.bingo_draws (
  id bigint generated by default as identity primary key,
  round_id bigint not null references public.bingo_rounds(id) on delete cascade,
  ball_number integer not null,
  draw_order integer not null,
  drawn_by uuid references auth.users(id) on delete set null,
  drawn_at timestamptz not null default now(),
  constraint bingo_draw_ball_check check (ball_number between 1 and 99),
  constraint bingo_draw_order_check check (draw_order > 0),
  unique (round_id, ball_number),
  unique (round_id, draw_order)
);

create table if not exists public.bingo_winners (
  id bigint generated by default as identity primary key,
  round_id bigint not null references public.bingo_rounds(id) on delete cascade,
  card_id bigint not null references public.bingo_cards(id) on delete cascade,
  phase text not null,
  card_number integer not null,
  customer_name text not null,
  trigger_ball integer,
  achieved_at timestamptz not null default now(),
  constraint bingo_winner_phase_check check (phase in ('one_line','two_lines','three_lines','four_lines','full_card')),
  unique (round_id, phase, card_id)
);

create index if not exists bingo_winners_round_phase_idx
  on public.bingo_winners(round_id, phase, achieved_at desc);

create or replace function public.nostra_bingo_generate_card()
returns integer[]
language plpgsql
volatile
security definer
set search_path = public
as $$
declare
  v_b integer[];
  v_i integer[];
  v_n integer[];
  v_g integer[];
  v_o integer[];
begin
  -- Carton Bingo 1 à 99 :
  -- B = 1-20, I = 21-40, N = 41-60, G = 61-80, O = 81-99.
  select array_agg(candidate order by candidate) into v_b
  from (
    select candidate
    from generate_series(1, 20) as candidates(candidate)
    order by random()
    limit 5
  ) picked;

  select array_agg(candidate order by candidate) into v_i
  from (
    select candidate
    from generate_series(21, 40) as candidates(candidate)
    order by random()
    limit 5
  ) picked;

  select array_agg(candidate order by candidate) into v_n
  from (
    select candidate
    from generate_series(41, 60) as candidates(candidate)
    order by random()
    limit 4
  ) picked;

  select array_agg(candidate order by candidate) into v_g
  from (
    select candidate
    from generate_series(61, 80) as candidates(candidate)
    order by random()
    limit 5
  ) picked;

  select array_agg(candidate order by candidate) into v_o
  from (
    select candidate
    from generate_series(81, 99) as candidates(candidate)
    order by random()
    limit 5
  ) picked;

  return array[
    v_b[1], v_i[1], v_n[1], v_g[1], v_o[1],
    v_b[2], v_i[2], v_n[2], v_g[2], v_o[2],
    v_b[3], v_i[3], 0,      v_g[3], v_o[3],
    v_b[4], v_i[4], v_n[3], v_g[4], v_o[4],
    v_b[5], v_i[5], v_n[4], v_g[5], v_o[5]
  ];
end;
$$;

create or replace function public.nostra_bingo_completed_lines(
  p_numbers integer[],
  p_drawn integer[]
)
returns integer
language plpgsql
immutable
as $$
declare
  v_row integer;
  v_col integer;
  v_index integer;
  v_value integer;
  v_complete boolean;
  v_lines integer := 0;
begin
  if cardinality(p_numbers) <> 25 then return 0; end if;

  for v_row in 0..4 loop
    v_complete := true;
    for v_col in 0..4 loop
      v_index := (v_row * 5) + v_col + 1;
      v_value := p_numbers[v_index];
      if v_value <> 0 and not (v_value = any(coalesce(p_drawn, array[]::integer[]))) then
        v_complete := false;
        exit;
      end if;
    end loop;
    if v_complete then v_lines := v_lines + 1; end if;
  end loop;

  return v_lines;
end;
$$;

create or replace function public.nostra_bingo_is_full_card(
  p_numbers integer[],
  p_drawn integer[]
)
returns boolean
language sql
immutable
as $$
  select not exists (
    select 1
    from unnest(coalesce(p_numbers, array[]::integer[])) value
    where value <> 0
      and not (value = any(coalesce(p_drawn, array[]::integer[])))
  );
$$;

create or replace function public.nostra_bingo_card_matches(
  p_numbers integer[],
  p_drawn integer[],
  p_phase text
)
returns boolean
language sql
immutable
as $$
  select case p_phase
    when 'one_line' then public.nostra_bingo_completed_lines(p_numbers, p_drawn) >= 1
    when 'two_lines' then public.nostra_bingo_completed_lines(p_numbers, p_drawn) >= 2
    when 'three_lines' then public.nostra_bingo_completed_lines(p_numbers, p_drawn) >= 3
    when 'four_lines' then public.nostra_bingo_completed_lines(p_numbers, p_drawn) >= 4
    when 'full_card' then public.nostra_bingo_is_full_card(p_numbers, p_drawn)
    else false
  end;
$$;

create or replace function public.nostra_bingo_register_winners(
  p_round_id bigint,
  p_trigger_ball integer default null
)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_phase text;
  v_drawn integer[];
  v_count integer := 0;
begin
  select phase into v_phase
  from public.bingo_rounds
  where id = p_round_id;

  select coalesce(array_agg(ball_number order by draw_order), array[]::integer[])
    into v_drawn
  from public.bingo_draws
  where round_id = p_round_id;

  insert into public.bingo_winners (
    round_id,
    card_id,
    phase,
    card_number,
    customer_name,
    trigger_ball
  )
  select
    card.round_id,
    card.id,
    v_phase,
    card.card_number,
    card.customer_name,
    p_trigger_ball
  from public.bingo_cards card
  where card.round_id = p_round_id
    and public.nostra_bingo_card_matches(card.numbers, v_drawn, v_phase)
  on conflict (round_id, phase, card_id) do nothing;

  get diagnostics v_count = row_count;
  return v_count;
end;
$$;

create or replace function public.add_bingo_to_cart(
  p_customer_name text,
  p_quantity integer
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_round public.bingo_rounds%rowtype;
begin
  if v_user_id is null then raise exception 'not_authenticated'; end if;
  if length(trim(coalesce(p_customer_name, ''))) < 3 then raise exception 'invalid_name'; end if;
  if p_quantity < 1 or p_quantity > 20 then raise exception 'invalid_quantity'; end if;

  select * into v_round
  from public.bingo_rounds
  where archived_at is null
  limit 1;

  if v_round.id is null then raise exception 'bingo_setup_missing'; end if;
  if v_round.status <> 'open' then raise exception 'round_closed'; end if;

  insert into public.bingo_cart_items (
    user_id, round_id, customer_name, quantity, unit_price, updated_at
  ) values (
    v_user_id, v_round.id, trim(p_customer_name), p_quantity, v_round.card_price, now()
  )
  on conflict (user_id, round_id) do update
  set customer_name = excluded.customer_name,
      quantity = excluded.quantity,
      unit_price = excluded.unit_price,
      updated_at = now();

  return jsonb_build_object(
    'quantity', p_quantity,
    'unit_price', v_round.card_price,
    'total', v_round.card_price * p_quantity
  );
end;
$$;

create or replace function public.checkout_bingo_cart()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_round public.bingo_rounds%rowtype;
  v_cart public.bingo_cart_items%rowtype;
  v_purchase_id bigint;
  v_order_number text;
  v_next_card integer;
  v_index integer;
  v_numbers integer[];
begin
  if v_user_id is null then raise exception 'not_authenticated'; end if;

  select * into v_round
  from public.bingo_rounds
  where archived_at is null
  limit 1
  for update;

  if v_round.id is null then raise exception 'bingo_setup_missing'; end if;
  if v_round.status <> 'open' then raise exception 'round_closed'; end if;

  select * into v_cart
  from public.bingo_cart_items
  where user_id = v_user_id
    and round_id = v_round.id
  for update;

  if v_cart.id is null then raise exception 'empty_cart'; end if;

  v_order_number := 'BINGO-' || to_char(clock_timestamp(), 'YYYYMMDDHH24MISSMS') || '-' || upper(substr(md5(random()::text), 1, 5));

  insert into public.bingo_purchases (
    round_id, user_id, order_number, customer_name, quantity, unit_price, total
  ) values (
    v_round.id,
    v_user_id,
    v_order_number,
    v_cart.customer_name,
    v_cart.quantity,
    v_cart.unit_price,
    v_cart.quantity * v_cart.unit_price
  ) returning id into v_purchase_id;

  select coalesce(max(card_number), 0) + 1
    into v_next_card
  from public.bingo_cards
  where round_id = v_round.id;

  for v_index in 1..v_cart.quantity loop
    v_numbers := public.nostra_bingo_generate_card();

    insert into public.bingo_cards (
      round_id, purchase_id, user_id, customer_name, card_number, numbers
    ) values (
      v_round.id,
      v_purchase_id,
      v_user_id,
      v_cart.customer_name,
      v_next_card + v_index - 1,
      v_numbers
    );
  end loop;

  delete from public.bingo_cart_items where id = v_cart.id;

  return jsonb_build_object(
    'order_number', v_order_number,
    'cards_count', v_cart.quantity,
    'total', v_cart.quantity * v_cart.unit_price
  );
end;
$$;

create or replace function public.update_bingo_settings(
  p_title text,
  p_card_price numeric,
  p_status text
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.nostra_bingo_is_manager() then raise exception 'manager_required'; end if;
  if length(trim(coalesce(p_title, ''))) < 2 then raise exception 'invalid_title'; end if;
  if p_card_price < 0 then raise exception 'invalid_price'; end if;
  if p_status not in ('open','closed') then raise exception 'invalid_status'; end if;

  update public.bingo_rounds
  set title = trim(p_title),
      card_price = p_card_price,
      status = p_status,
      updated_at = now()
  where archived_at is null;
end;
$$;

create or replace function public.set_bingo_phase(p_phase text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_round_id bigint;
  v_winners integer;
begin
  if not public.nostra_bingo_is_manager() then raise exception 'manager_required'; end if;
  if p_phase not in ('one_line','two_lines','three_lines','four_lines','full_card') then
    raise exception 'invalid_phase';
  end if;

  update public.bingo_rounds
  set phase = p_phase,
      status = case when status = 'completed' then 'playing' else status end,
      updated_at = now()
  where archived_at is null
  returning id into v_round_id;

  if v_round_id is null then raise exception 'bingo_setup_missing'; end if;
  v_winners := public.nostra_bingo_register_winners(v_round_id, null);

  return jsonb_build_object('phase', p_phase, 'new_winners', v_winners);
end;
$$;

create or replace function public.draw_bingo_number()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_round public.bingo_rounds%rowtype;
  v_ball integer;
  v_order integer;
  v_new_winners integer;
  v_winners jsonb;
begin
  if not public.nostra_bingo_is_manager() then raise exception 'manager_required'; end if;

  select * into v_round
  from public.bingo_rounds
  where archived_at is null
  limit 1
  for update;

  if v_round.id is null then raise exception 'bingo_setup_missing'; end if;

  if v_round.phase = 'full_card' and exists (
    select 1 from public.bingo_winners
    where round_id = v_round.id and phase = 'full_card'
  ) then
    raise exception 'full_card_complete';
  end if;

  select candidate into v_ball
  from generate_series(1, 99) as candidates(candidate)
  where not exists (
    select 1 from public.bingo_draws draw
    where draw.round_id = v_round.id
      and draw.ball_number = candidate
  )
  order by random()
  limit 1;

  if v_ball is null then raise exception 'no_numbers_left'; end if;

  select coalesce(max(draw_order), 0) + 1
    into v_order
  from public.bingo_draws
  where round_id = v_round.id;

  insert into public.bingo_draws (
    round_id, ball_number, draw_order, drawn_by
  ) values (
    v_round.id, v_ball, v_order, v_user_id
  );

  update public.bingo_rounds
  set status = 'playing', updated_at = now()
  where id = v_round.id;

  v_new_winners := public.nostra_bingo_register_winners(v_round.id, v_ball);

  if v_round.phase = 'full_card' and v_new_winners > 0 then
    update public.bingo_rounds
    set status = 'completed', updated_at = now()
    where id = v_round.id;
  end if;

  select coalesce(jsonb_agg(jsonb_build_object(
    'card_number', winner.card_number,
    'customer_name', winner.customer_name,
    'phase', winner.phase
  ) order by winner.card_number), '[]'::jsonb)
  into v_winners
  from public.bingo_winners winner
  where winner.round_id = v_round.id
    and winner.phase = v_round.phase
    and winner.trigger_ball = v_ball;

  return jsonb_build_object(
    'ball_number', v_ball,
    'draw_order', v_order,
    'phase', v_round.phase,
    'new_winners', v_winners
  );
end;
$$;

create or replace function public.clear_bingo_draws()
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_round_id bigint;
begin
  if not public.nostra_bingo_is_manager() then raise exception 'manager_required'; end if;

  select id into v_round_id
  from public.bingo_rounds
  where archived_at is null
  limit 1;

  if v_round_id is null then raise exception 'bingo_setup_missing'; end if;

  delete from public.bingo_winners where round_id = v_round_id;
  delete from public.bingo_draws where round_id = v_round_id;

  update public.bingo_rounds
  set phase = 'one_line', status = 'closed', updated_at = now()
  where id = v_round_id;
end;
$$;

create or replace function public.reset_bingo_round()
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_current public.bingo_rounds%rowtype;
  v_new_id bigint;
begin
  if not public.nostra_bingo_is_manager() then raise exception 'manager_required'; end if;

  select * into v_current
  from public.bingo_rounds
  where archived_at is null
  limit 1
  for update;

  if v_current.id is null then raise exception 'bingo_setup_missing'; end if;

  update public.bingo_rounds
  set status = 'archived', archived_at = now(), updated_at = now()
  where id = v_current.id;

  insert into public.bingo_rounds (title, card_price, status, phase)
  values (v_current.title, v_current.card_price, 'open', 'one_line')
  returning id into v_new_id;

  return v_new_id;
end;
$$;

revoke all on function public.nostra_bingo_generate_card() from public;
revoke all on function public.add_bingo_to_cart(text, integer) from public;
revoke all on function public.checkout_bingo_cart() from public;
revoke all on function public.update_bingo_settings(text, numeric, text) from public;
revoke all on function public.set_bingo_phase(text) from public;
revoke all on function public.draw_bingo_number() from public;
revoke all on function public.clear_bingo_draws() from public;
revoke all on function public.reset_bingo_round() from public;

grant execute on function public.add_bingo_to_cart(text, integer) to authenticated;
grant execute on function public.checkout_bingo_cart() to authenticated;
grant execute on function public.update_bingo_settings(text, numeric, text) to authenticated;
grant execute on function public.set_bingo_phase(text) to authenticated;
grant execute on function public.draw_bingo_number() to authenticated;
grant execute on function public.clear_bingo_draws() to authenticated;
grant execute on function public.reset_bingo_round() to authenticated;

alter table public.bingo_rounds enable row level security;
alter table public.bingo_cart_items enable row level security;
alter table public.bingo_purchases enable row level security;
alter table public.bingo_cards enable row level security;
alter table public.bingo_draws enable row level security;
alter table public.bingo_winners enable row level security;

drop policy if exists "bingo authenticated read round" on public.bingo_rounds;
create policy "bingo authenticated read round"
on public.bingo_rounds for select to authenticated using (true);

drop policy if exists "bingo owner manages cart" on public.bingo_cart_items;
create policy "bingo owner manages cart"
on public.bingo_cart_items for all to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid());

drop policy if exists "bingo owner reads purchases" on public.bingo_purchases;
create policy "bingo owner reads purchases"
on public.bingo_purchases for select to authenticated
using (user_id = auth.uid() or public.nostra_bingo_is_manager());

drop policy if exists "bingo owner reads cards" on public.bingo_cards;
create policy "bingo owner reads cards"
on public.bingo_cards for select to authenticated
using (user_id = auth.uid() or public.nostra_bingo_is_manager());

drop policy if exists "bingo authenticated read draws" on public.bingo_draws;
create policy "bingo authenticated read draws"
on public.bingo_draws for select to authenticated using (true);

drop policy if exists "bingo authenticated read winners" on public.bingo_winners;
create policy "bingo authenticated read winners"
on public.bingo_winners for select to authenticated using (true);

grant select on public.bingo_rounds to authenticated;
grant select, insert, update, delete on public.bingo_cart_items to authenticated;
grant select on public.bingo_purchases to authenticated;
grant select on public.bingo_cards to authenticated;
grant select on public.bingo_draws to authenticated;
grant select on public.bingo_winners to authenticated;

do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'bingo_rounds'
  ) then alter publication supabase_realtime add table public.bingo_rounds; end if;

  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'bingo_draws'
  ) then alter publication supabase_realtime add table public.bingo_draws; end if;

  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'bingo_winners'
  ) then alter publication supabase_realtime add table public.bingo_winners; end if;
end $$;

notify pgrst, 'reload schema';

-- NOSTRA GROUP V32.3 — RÉCOMPENSES DU BINGO
-- Tableau public des récompenses, configuration depuis le Dashboard
-- et validation du cadeau remis aux gagnants.
-- Script réexécutable : les données existantes sont conservées.

create table if not exists public.bingo_rewards (
  round_id bigint primary key references public.bingo_rounds(id) on delete cascade,
  one_line text not null default '',
  two_lines text not null default '',
  three_lines text not null default '',
  four_lines text not null default '',
  full_card text not null default '',
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id) on delete set null
);

insert into public.bingo_rewards (round_id)
select round.id
from public.bingo_rounds round
on conflict (round_id) do nothing;

alter table public.bingo_winners
  add column if not exists reward_text text not null default '',
  add column if not exists reward_status text not null default 'pending',
  add column if not exists reward_validated_at timestamptz,
  add column if not exists reward_validated_by uuid references auth.users(id) on delete set null;

alter table public.bingo_winners
  drop constraint if exists bingo_winner_reward_status_check;

alter table public.bingo_winners
  add constraint bingo_winner_reward_status_check
  check (reward_status in ('pending', 'validated'));

update public.bingo_winners winner
set reward_text = case winner.phase
  when 'one_line' then rewards.one_line
  when 'two_lines' then rewards.two_lines
  when 'three_lines' then rewards.three_lines
  when 'four_lines' then rewards.four_lines
  when 'full_card' then rewards.full_card
  else ''
end
from public.bingo_rewards rewards
where rewards.round_id = winner.round_id
  and coalesce(winner.reward_text, '') = '';

create or replace function public.update_bingo_rewards(
  p_one_line text,
  p_two_lines text,
  p_three_lines text,
  p_four_lines text,
  p_full_card text
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_round_id bigint;
begin
  if not public.nostra_bingo_is_manager() then
    raise exception 'manager_required';
  end if;

  select id into v_round_id
  from public.bingo_rounds
  where archived_at is null
  limit 1;

  if v_round_id is null then
    raise exception 'bingo_setup_missing';
  end if;

  insert into public.bingo_rewards (
    round_id,
    one_line,
    two_lines,
    three_lines,
    four_lines,
    full_card,
    updated_at,
    updated_by
  ) values (
    v_round_id,
    left(trim(coalesce(p_one_line, '')), 240),
    left(trim(coalesce(p_two_lines, '')), 240),
    left(trim(coalesce(p_three_lines, '')), 240),
    left(trim(coalesce(p_four_lines, '')), 240),
    left(trim(coalesce(p_full_card, '')), 240),
    now(),
    auth.uid()
  )
  on conflict (round_id) do update set
    one_line = excluded.one_line,
    two_lines = excluded.two_lines,
    three_lines = excluded.three_lines,
    four_lines = excluded.four_lines,
    full_card = excluded.full_card,
    updated_at = now(),
    updated_by = auth.uid();

  -- Un cadeau modifié avant sa remise est également actualisé
  -- sur les Bingo déjà détectés mais pas encore validés.
  update public.bingo_winners winner
  set reward_text = case winner.phase
    when 'one_line' then left(trim(coalesce(p_one_line, '')), 240)
    when 'two_lines' then left(trim(coalesce(p_two_lines, '')), 240)
    when 'three_lines' then left(trim(coalesce(p_three_lines, '')), 240)
    when 'four_lines' then left(trim(coalesce(p_four_lines, '')), 240)
    when 'full_card' then left(trim(coalesce(p_full_card, '')), 240)
    else winner.reward_text
  end
  where winner.round_id = v_round_id
    and winner.reward_status = 'pending';
end;
$$;

create or replace function public.validate_bingo_winner_reward(
  p_winner_id bigint
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.nostra_bingo_is_manager() then
    raise exception 'manager_required';
  end if;

  update public.bingo_winners
  set
    reward_status = 'validated',
    reward_validated_at = now(),
    reward_validated_by = auth.uid()
  where id = p_winner_id
    and reward_status = 'pending';

  if not found then
    raise exception 'winner_not_found_or_already_validated';
  end if;
end;
$$;

create or replace function public.nostra_bingo_register_winners(
  p_round_id bigint,
  p_trigger_ball integer default null
)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_phase text;
  v_drawn integer[];
  v_reward_text text := '';
  v_count integer := 0;
begin
  select phase into v_phase
  from public.bingo_rounds
  where id = p_round_id;

  select case v_phase
    when 'one_line' then rewards.one_line
    when 'two_lines' then rewards.two_lines
    when 'three_lines' then rewards.three_lines
    when 'four_lines' then rewards.four_lines
    when 'full_card' then rewards.full_card
    else ''
  end
  into v_reward_text
  from public.bingo_rewards rewards
  where rewards.round_id = p_round_id;

  v_reward_text := coalesce(v_reward_text, '');

  select coalesce(array_agg(ball_number order by draw_order), array[]::integer[])
    into v_drawn
  from public.bingo_draws
  where round_id = p_round_id;

  insert into public.bingo_winners (
    round_id,
    card_id,
    phase,
    card_number,
    customer_name,
    trigger_ball,
    reward_text,
    reward_status
  )
  select
    card.round_id,
    card.id,
    v_phase,
    card.card_number,
    card.customer_name,
    p_trigger_ball,
    v_reward_text,
    'pending'
  from public.bingo_cards card
  where card.round_id = p_round_id
    and public.nostra_bingo_card_matches(card.numbers, v_drawn, v_phase)
  on conflict (round_id, phase, card_id) do nothing;

  get diagnostics v_count = row_count;
  return v_count;
end;
$$;

create or replace function public.reset_bingo_round()
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_current public.bingo_rounds%rowtype;
  v_new_id bigint;
  v_rewards public.bingo_rewards%rowtype;
begin
  if not public.nostra_bingo_is_manager() then
    raise exception 'manager_required';
  end if;

  select * into v_current
  from public.bingo_rounds
  where archived_at is null
  limit 1
  for update;

  if v_current.id is null then
    raise exception 'bingo_setup_missing';
  end if;

  select * into v_rewards
  from public.bingo_rewards
  where round_id = v_current.id;

  update public.bingo_rounds
  set status = 'archived', archived_at = now(), updated_at = now()
  where id = v_current.id;

  insert into public.bingo_rounds (title, card_price, status, phase)
  values (v_current.title, v_current.card_price, 'open', 'one_line')
  returning id into v_new_id;

  insert into public.bingo_rewards (
    round_id,
    one_line,
    two_lines,
    three_lines,
    four_lines,
    full_card,
    updated_at,
    updated_by
  ) values (
    v_new_id,
    coalesce(v_rewards.one_line, ''),
    coalesce(v_rewards.two_lines, ''),
    coalesce(v_rewards.three_lines, ''),
    coalesce(v_rewards.four_lines, ''),
    coalesce(v_rewards.full_card, ''),
    now(),
    auth.uid()
  );

  return v_new_id;
end;
$$;

revoke all on function public.update_bingo_rewards(text, text, text, text, text) from public;
revoke all on function public.validate_bingo_winner_reward(bigint) from public;
grant execute on function public.update_bingo_rewards(text, text, text, text, text) to authenticated;
grant execute on function public.validate_bingo_winner_reward(bigint) to authenticated;

alter table public.bingo_rewards enable row level security;

drop policy if exists "bingo authenticated read rewards" on public.bingo_rewards;
create policy "bingo authenticated read rewards"
on public.bingo_rewards
for select
to authenticated
using (true);

grant select on public.bingo_rewards to authenticated;

-- La table des récompenses se met à jour en direct sur la page publique.
do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'bingo_rewards'
  ) then
    alter publication supabase_realtime add table public.bingo_rewards;
  end if;
end $$;

notify pgrst, 'reload schema';

