-- V15 — Catalogue Nostra Motors avec photos
create table if not exists public.catalog_vehicles (
  id bigint generated by default as identity primary key,
  brand text not null,
  model text not null,
  trunk_capacity text not null default '',
  top_speed text not null default '',
  power text not null default '',
  price numeric(14,2) not null default 0,
  description text not null default '',
  images jsonb not null default '[]'::jsonb,
  published boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id) on delete set null
);

create index if not exists catalog_vehicles_brand_index
on public.catalog_vehicles (brand, sort_order, model);

alter table public.catalog_vehicles enable row level security;

drop policy if exists "members read published catalog vehicles" on public.catalog_vehicles;
create policy "members read published catalog vehicles" on public.catalog_vehicles
for select to authenticated
using (published or public.has_nostra_dashboard_access());

drop policy if exists "dashboard manages catalog vehicles" on public.catalog_vehicles;
create policy "dashboard manages catalog vehicles" on public.catalog_vehicles
for all to authenticated
using (public.has_nostra_dashboard_access())
with check (public.has_nostra_dashboard_access());

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'vehicle-images',
  'vehicle-images',
  true,
  5242880,
  array['image/jpeg','image/png','image/webp']::text[]
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "public reads vehicle images" on storage.objects;
create policy "public reads vehicle images" on storage.objects
for select to public
using (bucket_id = 'vehicle-images');

drop policy if exists "dashboard uploads vehicle images" on storage.objects;
create policy "dashboard uploads vehicle images" on storage.objects
for insert to authenticated
with check (bucket_id = 'vehicle-images' and public.has_nostra_dashboard_access());

drop policy if exists "dashboard updates vehicle images" on storage.objects;
create policy "dashboard updates vehicle images" on storage.objects
for update to authenticated
using (bucket_id = 'vehicle-images' and public.has_nostra_dashboard_access())
with check (bucket_id = 'vehicle-images' and public.has_nostra_dashboard_access());

drop policy if exists "dashboard deletes vehicle images" on storage.objects;
create policy "dashboard deletes vehicle images" on storage.objects
for delete to authenticated
using (bucket_id = 'vehicle-images' and public.has_nostra_dashboard_access());
