-- NOSTRA GROUP — Tableaux d'événements en direct V103
-- Script réexécutable : il conserve les événements déjà créés.

create table if not exists public.live_event_boards (
  id bigint generated by default as identity primary key,
  title text not null,
  subtitle text not null default '',
  location text not null default '',
  starts_at timestamptz,
  format text not null default 'bracket' check (format in ('bracket','table')),
  status text not null default 'draft' check (status in ('draft','live','completed')),
  accent_color text not null default '#d4af37',
  bracket_data jsonb not null default '{"size":8,"participants":[null,null,null,null,null,null,null,null],"winners":{}}'::jsonb,
  table_data jsonb not null default '{"columns":[{"id":"participant","label":"Nom et prénom","kind":"citizen"},{"id":"score","label":"Score","kind":"text"},{"id":"statut","label":"Statut","kind":"text"}],"rows":[]}'::jsonb,
  created_by uuid references auth.users(id) on delete set null default auth.uid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function public.nostra_touch_live_event_board()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists touch_live_event_board on public.live_event_boards;
create trigger touch_live_event_board
before update on public.live_event_boards
for each row execute function public.nostra_touch_live_event_board();

alter table public.live_event_boards enable row level security;

drop policy if exists "citizens read launched live boards" on public.live_event_boards;
create policy "citizens read launched live boards"
on public.live_event_boards for select to authenticated
using (status in ('live','completed') or public.has_nostra_dashboard_access());

drop policy if exists "manager creates live boards" on public.live_event_boards;
create policy "manager creates live boards"
on public.live_event_boards for insert to authenticated
with check (public.has_nostra_dashboard_access());

drop policy if exists "manager updates live boards" on public.live_event_boards;
create policy "manager updates live boards"
on public.live_event_boards for update to authenticated
using (public.has_nostra_dashboard_access())
with check (public.has_nostra_dashboard_access());

drop policy if exists "manager deletes live boards" on public.live_event_boards;
create policy "manager deletes live boards"
on public.live_event_boards for delete to authenticated
using (public.has_nostra_dashboard_access());

grant select, insert, update, delete on public.live_event_boards to authenticated;
grant usage, select on sequence public.live_event_boards_id_seq to authenticated;

do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'live_event_boards'
  ) then
    alter publication supabase_realtime add table public.live_event_boards;
  end if;
end $$;
