-- NOSTRA GROUP — V134
-- Mandats de recherche et dépôts-vente. Script réexécutable, sans suppression.

begin;

create sequence if not exists public.vehicle_search_mandate_v134_seq;
create sequence if not exists public.vehicle_consignment_v134_seq;

create table if not exists public.vehicle_search_mandates_v134 (
  id bigint generated by default as identity primary key,
  mandate_number text not null unique default (
    'MR-' || to_char(current_date, 'YYYY') || '-' || lpad(nextval('public.vehicle_search_mandate_v134_seq')::text, 5, '0')
  ),
  user_id uuid not null references auth.users(id) on delete cascade,
  customer_name text not null,
  customer_email text,
  customer_phone text,
  brand text,
  model text,
  vehicle_type text,
  budget_min numeric(14,2) not null default 0 check (budget_min >= 0),
  budget_max numeric(14,2) not null check (budget_max > 0),
  year_min integer,
  max_mileage integer check (max_mileage is null or max_mileage >= 0),
  required_features text,
  notes text,
  status text not null default 'new'
    check (status in ('new','searching','proposed','selected','closed','refused','cancelled')),
  assigned_staff text,
  staff_note text,
  selected_proposal_id bigint,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.vehicle_search_proposals_v134 (
  id bigint generated by default as identity primary key,
  mandate_id bigint not null references public.vehicle_search_mandates_v134(id) on delete cascade,
  vehicle_name text not null,
  price numeric(14,2) not null check (price > 0),
  year integer,
  mileage integer check (mileage is null or mileage >= 0),
  source_url text,
  details text,
  status text not null default 'proposed'
    check (status in ('proposed','selected','rejected','withdrawn')),
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

do $$ begin
  alter table public.vehicle_search_mandates_v134
    add constraint vehicle_search_selected_proposal_v134_fk
    foreign key (selected_proposal_id)
    references public.vehicle_search_proposals_v134(id) on delete set null;
exception when duplicate_object then null; end $$;

create table if not exists public.vehicle_consignments_v134 (
  id bigint generated by default as identity primary key,
  consignment_number text not null unique default (
    'DV-' || to_char(current_date, 'YYYY') || '-' || lpad(nextval('public.vehicle_consignment_v134_seq')::text, 5, '0')
  ),
  user_id uuid not null references auth.users(id) on delete cascade,
  owner_name text not null,
  owner_email text,
  owner_phone text,
  brand text not null,
  model text not null,
  version text,
  registration text,
  mileage integer not null default 0 check (mileage >= 0),
  first_registration_year integer,
  vehicle_condition text not null default 'good'
    check (vehicle_condition in ('excellent','very_good','good','fair','repair')),
  description text not null,
  images jsonb not null default '[]'::jsonb,
  desired_price numeric(14,2) not null check (desired_price > 0),
  agreed_sale_price numeric(14,2),
  commission_rate numeric(6,2) check (commission_rate is null or commission_rate between 0 and 100),
  commission_amount numeric(14,2),
  owner_net_amount numeric(14,2),
  status text not null default 'new'
    check (status in ('new','reviewing','offer_sent','accepted','published','reserved','sold','refused','cancelled')),
  assigned_staff text,
  public_description text,
  staff_note text,
  customer_accepted_at timestamptz,
  catalog_vehicle_id bigint references public.catalog_vehicles(id) on delete set null,
  sold_order_id bigint references public.orders(id) on delete set null,
  sold_at timestamptz,
  owner_paid_at timestamptz,
  owner_accounting_entry_id bigint references public.accounting_entries(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists vehicle_search_mandates_v134_user_idx
  on public.vehicle_search_mandates_v134(user_id, created_at desc);
create index if not exists vehicle_search_proposals_v134_mandate_idx
  on public.vehicle_search_proposals_v134(mandate_id, created_at desc);
create index if not exists vehicle_consignments_v134_user_idx
  on public.vehicle_consignments_v134(user_id, created_at desc);
create unique index if not exists vehicle_consignments_v134_catalog_uq
  on public.vehicle_consignments_v134(catalog_vehicle_id) where catalog_vehicle_id is not null;

alter table public.vehicle_search_mandates_v134 enable row level security;
alter table public.vehicle_search_proposals_v134 enable row level security;
alter table public.vehicle_consignments_v134 enable row level security;

drop policy if exists "mandate owner reads v134" on public.vehicle_search_mandates_v134;
create policy "mandate owner reads v134" on public.vehicle_search_mandates_v134
  for select to authenticated using (user_id = auth.uid() or public.nostra_can_manage_used_vehicles_v92());
drop policy if exists "mandate owner inserts v134" on public.vehicle_search_mandates_v134;
create policy "mandate owner inserts v134" on public.vehicle_search_mandates_v134
  for insert to authenticated with check (user_id = auth.uid());
drop policy if exists "mandate staff updates v134" on public.vehicle_search_mandates_v134;
create policy "mandate staff updates v134" on public.vehicle_search_mandates_v134
  for update to authenticated using (user_id = auth.uid() or public.nostra_can_manage_used_vehicles_v92())
  with check (user_id = auth.uid() or public.nostra_can_manage_used_vehicles_v92());

drop policy if exists "mandate proposals read v134" on public.vehicle_search_proposals_v134;
create policy "mandate proposals read v134" on public.vehicle_search_proposals_v134
  for select to authenticated using (
    exists (select 1 from public.vehicle_search_mandates_v134 m where m.id = mandate_id and (m.user_id = auth.uid() or public.nostra_can_manage_used_vehicles_v92()))
  );
drop policy if exists "mandate proposals staff v134" on public.vehicle_search_proposals_v134;
create policy "mandate proposals staff v134" on public.vehicle_search_proposals_v134
  for all to authenticated using (public.nostra_can_manage_used_vehicles_v92())
  with check (public.nostra_can_manage_used_vehicles_v92());

drop policy if exists "consignment owner reads v134" on public.vehicle_consignments_v134;
create policy "consignment owner reads v134" on public.vehicle_consignments_v134
  for select to authenticated using (user_id = auth.uid() or public.nostra_can_manage_used_vehicles_v92());
drop policy if exists "consignment owner inserts v134" on public.vehicle_consignments_v134;
create policy "consignment owner inserts v134" on public.vehicle_consignments_v134
  for insert to authenticated with check (user_id = auth.uid());
drop policy if exists "consignment updates v134" on public.vehicle_consignments_v134;
create policy "consignment updates v134" on public.vehicle_consignments_v134
  for update to authenticated using (user_id = auth.uid() or public.nostra_can_manage_used_vehicles_v92())
  with check (user_id = auth.uid() or public.nostra_can_manage_used_vehicles_v92());

drop policy if exists "consignment images insert v134" on storage.objects;
create policy "consignment images insert v134" on storage.objects
  for insert to authenticated with check (
    bucket_id = 'vehicle-images' and name like ('consignments/' || auth.uid()::text || '/%')
  );

create or replace function public.choose_vehicle_search_proposal_v134(p_proposal_id bigint)
returns void language plpgsql security definer set search_path = public as $$
declare v_mandate_id bigint;
begin
  select p.mandate_id into v_mandate_id
  from public.vehicle_search_proposals_v134 p
  join public.vehicle_search_mandates_v134 m on m.id = p.mandate_id
  where p.id = p_proposal_id and m.user_id = auth.uid() and m.status in ('searching','proposed')
  for update of p, m;
  if not found then raise exception using message = 'proposal_unavailable'; end if;
  update public.vehicle_search_proposals_v134 set status = case when id = p_proposal_id then 'selected' else 'rejected' end where mandate_id = v_mandate_id;
  update public.vehicle_search_mandates_v134 set selected_proposal_id = p_proposal_id, status = 'selected', updated_at = now() where id = v_mandate_id;
end $$;

create or replace function public.accept_vehicle_consignment_v134(p_consignment_id bigint)
returns void language plpgsql security definer set search_path = public as $$
begin
  update public.vehicle_consignments_v134
  set status = 'accepted', customer_accepted_at = now(), updated_at = now()
  where id = p_consignment_id and user_id = auth.uid() and status = 'offer_sent'
    and coalesce(agreed_sale_price,0) > 0 and coalesce(commission_amount,0) >= 0;
  if not found then raise exception using message = 'consignment_unavailable'; end if;
end $$;

create or replace function public.publish_vehicle_consignment_v134(p_consignment_id bigint)
returns bigint language plpgsql security definer set search_path = public as $$
declare c public.vehicle_consignments_v134%rowtype; v_vehicle_id bigint;
begin
  if not public.nostra_can_manage_used_vehicles_v92() then raise exception using message = 'forbidden'; end if;
  select * into c from public.vehicle_consignments_v134 where id = p_consignment_id for update;
  if not found or c.status <> 'accepted' then raise exception using message = 'consignment_not_accepted'; end if;
  if c.catalog_vehicle_id is not null then return c.catalog_vehicle_id; end if;
  insert into public.catalog_vehicles (
    brand,model,price,description,images,published,stock_quantity,sort_order,catalog_type,used_vehicle_status,used_condition,updated_at
  ) values (
    c.brand,c.model,c.agreed_sale_price,coalesce(c.public_description,c.description),c.images,true,1,0,'used','available',c.vehicle_condition,now()
  ) returning id into v_vehicle_id;
  insert into public.used_vehicle_details (
    vehicle_id,version,registration,previous_owner,purchase_date,purchase_price,resale_price,purchase_quantity,vehicle_condition,internal_notes,sale_status,created_by,updated_by
  ) values (
    v_vehicle_id,c.version,nullif(upper(btrim(coalesce(c.registration,''))),''),c.owner_name,current_date,0,c.agreed_sale_price,1,c.vehicle_condition,
    'Dépôt-vente ' || c.consignment_number || ' — Le véhicule reste la propriété du déposant jusqu’à la vente.','available',auth.uid(),auth.uid()
  );
  update public.vehicle_consignments_v134 set catalog_vehicle_id=v_vehicle_id,status='published',updated_at=now() where id=c.id;
  return v_vehicle_id;
end $$;

create or replace function public.sync_vehicle_consignment_sale_v134()
returns trigger language plpgsql security definer set search_path = public as $$
declare c public.vehicle_consignments_v134%rowtype; owner_entry bigint;
begin
  select * into c from public.vehicle_consignments_v134 where catalog_vehicle_id = new.vehicle_id for update;
  if not found then return new; end if;
  update public.used_vehicle_sales set unit_purchase_price = greatest(0,new.unit_sale_price-c.commission_amount),
    total_purchase_price = greatest(0,new.total_sale_price-c.commission_amount), margin=c.commission_amount, updated_at=now()
  where id=new.id and margin is distinct from c.commission_amount;
  insert into public.accounting_entries(entry_date,entry_type,category,label,amount,notes,nostra_source_type,nostra_source_id)
  values (new.sold_at::date,'expense','Dépôt-vente — Règlement propriétaire','Règlement ' || c.consignment_number,c.owner_net_amount,
    new.order_number || ' · ' || c.owner_name,'consignment_owner_payment',c.id::text)
  on conflict (nostra_source_type,nostra_source_id) do update set amount=excluded.amount,notes=excluded.notes
  returning id into owner_entry;
  update public.vehicle_consignments_v134 set status='sold',sold_order_id=new.order_id,sold_at=new.sold_at,
    owner_accounting_entry_id=owner_entry,updated_at=now() where id=c.id;
  return new;
end $$;

drop trigger if exists sync_vehicle_consignment_sale_v134 on public.used_vehicle_sales;
create trigger sync_vehicle_consignment_sale_v134 after insert on public.used_vehicle_sales
for each row execute function public.sync_vehicle_consignment_sale_v134();

grant select,insert,update on public.vehicle_search_mandates_v134 to authenticated;
grant select,insert,update on public.vehicle_search_proposals_v134 to authenticated;
grant select,insert,update on public.vehicle_consignments_v134 to authenticated;
grant usage,select on sequence public.vehicle_search_mandate_v134_seq to authenticated;
grant usage,select on sequence public.vehicle_consignment_v134_seq to authenticated;
grant execute on function public.choose_vehicle_search_proposal_v134(bigint) to authenticated;
grant execute on function public.accept_vehicle_consignment_v134(bigint) to authenticated;
grant execute on function public.publish_vehicle_consignment_v134(bigint) to authenticated;

commit;
