-- NOSTRA GROUP V164 — Dossier véhicule, entretien, transferts, démonstration,
-- notifications intelligentes, statistiques Motors et employés Nostra Motors.
-- À exécuter APRÈS les migrations V162 / V163 / V163.1 (et V163.2 si utilisée).
-- Réexécutable : conserve les données existantes.

begin;

-- -----------------------------------------------------------------------------
-- 0) Helpers d'accès Nostra Motors
-- -----------------------------------------------------------------------------
create or replace function public.nostra_v164_is_manager()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.member_profiles mp
    where mp.user_id = auth.uid()
      and (
        lower(coalesce(to_jsonb(mp)->>'role','')) in ('manager','gerant','direction')
        or exists (
          select 1
          from jsonb_array_elements_text(coalesce(to_jsonb(mp)->'roles','[]'::jsonb)) r(value)
          where lower(r.value) in ('manager','gerant','direction')
        )
      )
  );
$$;

grant execute on function public.nostra_v164_is_manager() to authenticated;

-- -----------------------------------------------------------------------------
-- 1) Employés Nostra Motors + permissions + journal d'activité
-- -----------------------------------------------------------------------------
create table if not exists public.motors_employees_v164 (
  user_id uuid primary key references auth.users(id) on delete cascade,
  job_role text not null default 'vendeur',
  active boolean not null default true,
  permissions jsonb not null default '{}'::jsonb,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references auth.users(id) on delete set null,
  updated_by uuid references auth.users(id) on delete set null
);

create table if not exists public.motors_employee_audit_v164 (
  id bigint generated by default as identity primary key,
  actor_user_id uuid references auth.users(id) on delete set null,
  action_key text not null,
  entity_type text not null,
  entity_id text,
  title text not null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists motors_employee_audit_v164_created_idx
on public.motors_employee_audit_v164(created_at desc);

alter table public.motors_employees_v164 enable row level security;
alter table public.motors_employee_audit_v164 enable row level security;

drop policy if exists "v164 employees manager read" on public.motors_employees_v164;
create policy "v164 employees manager read" on public.motors_employees_v164
for select to authenticated using (public.nostra_v164_is_manager() or user_id = auth.uid());

drop policy if exists "v164 employees manager manage" on public.motors_employees_v164;
create policy "v164 employees manager manage" on public.motors_employees_v164
for all to authenticated using (public.nostra_v164_is_manager()) with check (public.nostra_v164_is_manager());

drop policy if exists "v164 audit manager read" on public.motors_employee_audit_v164;
create policy "v164 audit manager read" on public.motors_employee_audit_v164
for select to authenticated using (public.nostra_v164_is_manager());

drop policy if exists "v164 audit staff insert" on public.motors_employee_audit_v164;
create policy "v164 audit staff insert" on public.motors_employee_audit_v164
for insert to authenticated with check (actor_user_id = auth.uid());

create or replace function public.nostra_v164_has_permission(p_permission text)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select public.nostra_v164_is_manager()
    or exists (
      select 1
      from public.motors_employees_v164 e
      where e.user_id = auth.uid()
        and e.active
        and coalesce(e.permissions, '{}'::jsonb) ? p_permission
        and coalesce((e.permissions ->> p_permission)::boolean, false)
    );
$$;

grant execute on function public.nostra_v164_has_permission(text) to authenticated;

-- Pré-remplit les collaborateurs déjà connus sans retirer aucun rôle existant.
insert into public.motors_employees_v164(user_id, job_role, permissions, created_by, updated_by)
select
  mp.user_id,
  case
    when lower(coalesce(to_jsonb(mp)->>'role','')) = 'commercial' then 'vendeur'
    else 'employe_polyvalent'
  end,
  case
    when lower(coalesce(to_jsonb(mp)->>'role','')) = 'commercial' then
      jsonb_build_object(
        'catalogue_read',true,'orders_manage',true,'crm_manage',true,'garage_read',true,
        'transfer_manage',true,'warranty_read',true
      )
    else
      jsonb_build_object(
        'catalogue_read',true,'inventory_manage',true,'orders_manage',true,'garage_read',true,
        'maintenance_manage',true,'workshop_manage',true,'deliveries_manage',true,
        'transfer_manage',true,'warranty_read',true,'crm_manage',true
      )
  end,
  auth.uid(), auth.uid()
from public.member_profiles mp
where (
  lower(coalesce(to_jsonb(mp)->>'role','')) in ('employee','commercial')
  or exists (
    select 1 from jsonb_array_elements_text(coalesce(to_jsonb(mp)->'roles','[]'::jsonb)) r(value)
    where lower(r.value) in ('employee','commercial')
  )
)
on conflict (user_id) do nothing;

-- -----------------------------------------------------------------------------
-- 2) Dossier véhicule enrichi
-- -----------------------------------------------------------------------------
alter table public.customer_vehicles
  add column if not exists current_mileage integer not null default 0;
alter table public.customer_vehicles
  add column if not exists nostra_vin text;

update public.customer_vehicles
set nostra_vin = 'NM-' || lpad(id::text, 8, '0')
where nostra_vin is null or btrim(nostra_vin) = '';

alter table public.customer_vehicles
  alter column nostra_vin set default ('NM-' || upper(substr(replace(gen_random_uuid()::text,'-',''),1,10)));

create unique index if not exists customer_vehicles_nostra_vin_uidx
on public.customer_vehicles(nostra_vin) where nostra_vin is not null;

-- -----------------------------------------------------------------------------
-- 3) Carnet d'entretien Nostra Motors
-- -----------------------------------------------------------------------------
create table if not exists public.motors_vehicle_maintenance_v164 (
  id bigint generated by default as identity primary key,
  customer_vehicle_id bigint not null,
  owner_user_id uuid not null references auth.users(id) on delete cascade,
  maintenance_type text not null default 'entretien',
  title text not null,
  service_date date not null default current_date,
  mileage integer,
  work_done text,
  parts_replaced text,
  vehicle_condition text,
  staff_comment text,
  next_service_date date,
  next_service_mileage integer,
  cost numeric(14,2) not null default 0,
  warranty_covered boolean not null default false,
  warranty_contract_id bigint references public.motors_warranty_contracts_v163(id) on delete set null,
  technician_user_id uuid references auth.users(id) on delete set null,
  technician_name text,
  status text not null default 'completed' check (status in ('planned','in_progress','completed','cancelled')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz,
  deleted_by uuid references auth.users(id) on delete set null
);

create index if not exists motors_vehicle_maintenance_v164_vehicle_idx
on public.motors_vehicle_maintenance_v164(customer_vehicle_id, service_date desc, created_at desc);

alter table public.motors_vehicle_maintenance_v164 enable row level security;

drop policy if exists "v164 maintenance owner read" on public.motors_vehicle_maintenance_v164;
create policy "v164 maintenance owner read" on public.motors_vehicle_maintenance_v164
for select to authenticated using (
  owner_user_id = auth.uid()
  or public.nostra_v164_has_permission('garage_read')
  or public.nostra_v164_has_permission('maintenance_manage')
);

drop policy if exists "v164 maintenance staff insert" on public.motors_vehicle_maintenance_v164;
create policy "v164 maintenance staff insert" on public.motors_vehicle_maintenance_v164
for insert to authenticated with check (public.nostra_v164_has_permission('maintenance_manage'));

drop policy if exists "v164 maintenance staff update" on public.motors_vehicle_maintenance_v164;
create policy "v164 maintenance staff update" on public.motors_vehicle_maintenance_v164
for update to authenticated using (public.nostra_v164_has_permission('maintenance_manage'))
with check (public.nostra_v164_has_permission('maintenance_manage'));

-- -----------------------------------------------------------------------------
-- 4) Transfert / revente véhicule + règle de transfert Nostra Care
-- -----------------------------------------------------------------------------
create table if not exists public.motors_settings_v164 (
  id integer primary key default 1 check (id = 1),
  warranty_transfer_policy text not null default 'transfer'
    check (warranty_transfer_policy in ('transfer','cancel','manual')),
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id) on delete set null
);

insert into public.motors_settings_v164(id) values(1) on conflict (id) do nothing;

alter table public.motors_settings_v164 enable row level security;
drop policy if exists "v164 settings read" on public.motors_settings_v164;
create policy "v164 settings read" on public.motors_settings_v164
for select to authenticated using (true);
drop policy if exists "v164 settings manager" on public.motors_settings_v164;
create policy "v164 settings manager" on public.motors_settings_v164
for all to authenticated using (public.nostra_v164_is_manager()) with check (public.nostra_v164_is_manager());

create table if not exists public.motors_vehicle_transfers_v164 (
  id bigint generated by default as identity primary key,
  transfer_number text not null unique,
  customer_vehicle_id bigint not null,
  seller_user_id uuid not null references auth.users(id) on delete cascade,
  target_user_id uuid not null references auth.users(id) on delete restrict,
  transfer_type text not null default 'sale' check (transfer_type in ('sale','gift','administrative')),
  sale_price numeric(14,2) not null default 0,
  seller_note text,
  warranty_action text check (warranty_action in ('transfer','cancel')),
  status text not null default 'pending' check (status in ('pending','approved','rejected','cancelled')),
  staff_note text,
  processed_by uuid references auth.users(id) on delete set null,
  processed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists motors_vehicle_transfers_v164_vehicle_idx
on public.motors_vehicle_transfers_v164(customer_vehicle_id,status,created_at desc);

alter table public.motors_vehicle_transfers_v164 enable row level security;

drop policy if exists "v164 transfers own read" on public.motors_vehicle_transfers_v164;
create policy "v164 transfers own read" on public.motors_vehicle_transfers_v164
for select to authenticated using (
  seller_user_id = auth.uid()
  or target_user_id = auth.uid()
  or public.nostra_v164_has_permission('transfer_manage')
);

drop policy if exists "v164 transfers own insert" on public.motors_vehicle_transfers_v164;
create policy "v164 transfers own insert" on public.motors_vehicle_transfers_v164
for insert to authenticated with check (
  seller_user_id = auth.uid()
  and target_user_id <> auth.uid()
  and status = 'pending'
  and processed_by is null
  and processed_at is null
  and warranty_action is null
);

drop policy if exists "v164 transfers staff update" on public.motors_vehicle_transfers_v164;
create policy "v164 transfers staff update" on public.motors_vehicle_transfers_v164
for update to authenticated using (public.nostra_v164_has_permission('transfer_manage'))
with check (public.nostra_v164_has_permission('transfer_manage'));

-- Le vendeur annule sa propre demande via une RPC sécurisée : il ne peut donc
-- jamais forcer lui-même un statut approved/rejected côté API.
create or replace function public.nostra_v164_cancel_vehicle_transfer(p_request_id bigint)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null then raise exception using message='not_authenticated'; end if;

  update public.motors_vehicle_transfers_v164
  set status='cancelled', updated_at=now()
  where id=p_request_id and seller_user_id=auth.uid() and status='pending';

  if not found then raise exception using message='transfer_not_found'; end if;
end;
$$;

grant execute on function public.nostra_v164_cancel_vehicle_transfer(bigint) to authenticated;

-- Répertoire RP minimal pour sélectionner le nouveau propriétaire sans exposer de données privées.
create or replace function public.nostra_v164_citizen_directory()
returns table(user_id uuid, display_name text)
language sql
stable
security definer
set search_path = public
as $$
  select
    mp.user_id,
    coalesce(
      nullif(btrim(concat_ws(' ', mp.rp_first_name, mp.rp_last_name)), ''),
      nullif(btrim(mp.discord_name), ''),
      'Citoyen Nostra'
    ) as display_name
  from public.member_profiles mp
  order by display_name;
$$;

grant execute on function public.nostra_v164_citizen_directory() to authenticated;

-- -----------------------------------------------------------------------------
-- 5) Véhicules de démonstration (le champ price reste LE prix réellement vendu)
-- -----------------------------------------------------------------------------
alter table public.catalog_vehicles add column if not exists is_demo boolean not null default false;
alter table public.catalog_vehicles add column if not exists demo_mileage integer not null default 0;
alter table public.catalog_vehicles add column if not exists demo_original_price numeric(14,2);
alter table public.catalog_vehicles add column if not exists demo_note text;

-- -----------------------------------------------------------------------------
-- 5B) Journal / notifications automatiques autour du carnet et des transferts
-- -----------------------------------------------------------------------------
create or replace function public.nostra_v164_maintenance_event()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_title text;
  v_details text;
  v_notify boolean := true;
begin
  if new.mileage is not null then
    update public.customer_vehicles
    set current_mileage = greatest(coalesce(current_mileage,0), new.mileage), updated_at=now()
    where id=new.customer_vehicle_id;
  end if;

  if tg_op='INSERT' then
    v_title := 'Entretien Nostra · '||new.title;
    v_details := concat_ws(' · ', nullif(new.work_done,''), nullif(new.staff_comment,''),
      case when new.mileage is not null then new.mileage::text||' km' else null end);
  elsif old.deleted_at is null and new.deleted_at is not null then
    v_title := 'Entrée du carnet archivée';
    v_details := new.title;
  else
    v_title := 'Carnet d’entretien mis à jour · '||new.title;
    v_details := concat_ws(' · ', nullif(new.work_done,''), nullif(new.staff_comment,''),
      case when new.mileage is not null then new.mileage::text||' km' else null end);
  end if;

  if to_regclass('public.customer_vehicle_history') is not null then
    insert into public.customer_vehicle_history(customer_vehicle_id,event_type,status,title,details,created_at)
    values(new.customer_vehicle_id,'maintenance',new.status,v_title,nullif(v_details,''),now());
  end if;

  if tg_op = 'UPDATE' and old.deleted_at is null and new.deleted_at is not null then
    v_notify := false;
  end if;

  if to_regclass('public.user_notifications') is not null and v_notify then
    insert into public.user_notifications(user_id,notification_type,title,message,target_url,source_type,source_id,priority,category)
    values(new.owner_user_id,'maintenance',case when tg_op='INSERT' then 'Carnet d’entretien mis à jour' else 'Entretien Nostra mis à jour' end,
      new.title||case when new.staff_comment is not null and btrim(new.staff_comment)<>'' then ' · '||new.staff_comment else '' end,
      '/profil/garage/'||new.customer_vehicle_id,'maintenance_v164',new.id::text,'normal','motors');
  end if;

  return new;
end;
$$;

drop trigger if exists nostra_v164_maintenance_event on public.motors_vehicle_maintenance_v164;
create trigger nostra_v164_maintenance_event
after insert or update on public.motors_vehicle_maintenance_v164
for each row execute function public.nostra_v164_maintenance_event();

create or replace function public.nostra_v164_transfer_created_notify_staff()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if to_regclass('public.user_notifications') is null then return new; end if;

  insert into public.user_notifications(user_id,notification_type,title,message,target_url,source_type,source_id,priority,category)
  select distinct target.user_id,'staff_motors_transfer','Transfert véhicule à valider',
    'Une nouvelle demande de transfert / revente attend la validation Nostra Motors.',
    '/dashboard/transferts-vehicules','vehicle_transfer_v164',new.id::text,'high','motors'
  from (
    select e.user_id
    from public.motors_employees_v164 e
    where e.active and coalesce((e.permissions->>'transfer_manage')::boolean,false)
    union
    select mp.user_id
    from public.member_profiles mp
    where lower(coalesce(to_jsonb(mp)->>'role','')) in ('manager','gerant','direction')
       or exists (
         select 1 from jsonb_array_elements_text(coalesce(to_jsonb(mp)->'roles','[]'::jsonb)) r(value)
         where lower(r.value) in ('manager','gerant','direction')
       )
  ) target
  where target.user_id is not null;

  return new;
end;
$$;

drop trigger if exists nostra_v164_transfer_created_notify_staff on public.motors_vehicle_transfers_v164;
create trigger nostra_v164_transfer_created_notify_staff
after insert on public.motors_vehicle_transfers_v164
for each row execute function public.nostra_v164_transfer_created_notify_staff();

-- Nostra Care alimente aussi la timeline du véhicule au moment des changements
-- de statut importants (paiement, expiration, annulation).
create or replace function public.nostra_v164_warranty_history_event()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_title text;
  v_details text;
begin
  if new.status is not distinct from old.status then return new; end if;

  if new.status='active' then
    v_title := 'Nostra Care activé · '||new.plan_name;
    v_details := 'Contrat '||new.contract_number||' · '||new.duration_days||' jour(s) · '||new.amount||' €.';
  elsif new.status='expired' then
    v_title := 'Nostra Care expiré · '||new.plan_name;
    v_details := 'Le contrat '||new.contract_number||' est arrivé à expiration.';
  elsif new.status='cancelled' then
    v_title := 'Nostra Care annulé · '||new.plan_name;
    v_details := 'Le contrat '||new.contract_number||' a été annulé.';
  else
    return new;
  end if;

  if to_regclass('public.customer_vehicle_history') is not null then
    insert into public.customer_vehicle_history(customer_vehicle_id,event_type,status,title,details,created_at)
    values(new.customer_vehicle_id,'warranty',new.status,v_title,v_details,now());
  end if;

  if new.status='active' and to_regclass('public.user_notifications') is not null and not exists (
    select 1 from public.user_notifications n
    where n.user_id=new.user_id and n.source_type='warranty_active_v164' and n.source_id=new.id::text
  ) then
    insert into public.user_notifications(user_id,notification_type,title,message,target_url,source_type,source_id,priority,category)
    values(new.user_id,'contract','Nostra Care activé',new.plan_name||' est maintenant actif sur ton véhicule.','/profil/garage/'||new.customer_vehicle_id,'warranty_active_v164',new.id::text,'high','motors');
  end if;

  return new;
end;
$$;

drop trigger if exists nostra_v164_warranty_history_event on public.motors_warranty_contracts_v163;
create trigger nostra_v164_warranty_history_event
after update of status on public.motors_warranty_contracts_v163
for each row execute function public.nostra_v164_warranty_history_event();

-- -----------------------------------------------------------------------------
-- 6) Notifications intelligentes Nostra Care + entretien
-- -----------------------------------------------------------------------------
create or replace function public.nostra_v164_refresh_my_vehicle_notifications()
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
  v_count integer := 0;
  v_row record;
  v_days integer;
begin
  if v_uid is null then return 0; end if;
  if to_regclass('public.user_notifications') is null then return 0; end if;

  -- Expire les contrats arrivés à échéance.
  update public.motors_warranty_contracts_v163
  set status = 'expired', updated_at = now()
  where user_id = v_uid and status = 'active' and ends_at <= now();

  for v_row in
    select id, contract_number, plan_name, customer_vehicle_id, ends_at, status
    from public.motors_warranty_contracts_v163
    where user_id = v_uid and status in ('active','expired')
  loop
    v_days := ceil(extract(epoch from (v_row.ends_at - now())) / 86400.0)::integer;

    if v_row.status = 'active' and v_days between 2 and 7 and not exists (
      select 1 from public.user_notifications n
      where n.user_id=v_uid and n.source_type='warranty_7d_v164' and n.source_id=v_row.id::text
    ) then
      insert into public.user_notifications(user_id,notification_type,title,message,target_url,source_type,source_id,priority,category)
      values(v_uid,'contract','Nostra Care expire bientôt',v_row.plan_name||' expire dans '||v_days||' jour(s).','/profil/garage/'||v_row.customer_vehicle_id,'warranty_7d_v164',v_row.id::text,'high','motors');
      v_count := v_count + 1;
    end if;

    if v_row.status = 'active' and v_days between 0 and 1 and not exists (
      select 1 from public.user_notifications n
      where n.user_id=v_uid and n.source_type='warranty_1d_v164' and n.source_id=v_row.id::text
    ) then
      insert into public.user_notifications(user_id,notification_type,title,message,target_url,source_type,source_id,priority,category)
      values(v_uid,'contract','Nostra Care arrive à expiration','Ton contrat '||v_row.plan_name||' expire dans moins de 24 h.','/profil/garage/'||v_row.customer_vehicle_id,'warranty_1d_v164',v_row.id::text,'urgent','motors');
      v_count := v_count + 1;
    end if;

    if v_row.status = 'expired' and not exists (
      select 1 from public.user_notifications n
      where n.user_id=v_uid and n.source_type='warranty_expired_v164' and n.source_id=v_row.id::text
    ) then
      insert into public.user_notifications(user_id,notification_type,title,message,target_url,source_type,source_id,priority,category)
      values(v_uid,'contract','Nostra Care expiré','Ton contrat '||v_row.plan_name||' est arrivé à expiration.','/profil/garage/'||v_row.customer_vehicle_id,'warranty_expired_v164',v_row.id::text,'high','motors');
      v_count := v_count + 1;
    end if;
  end loop;

  -- Prochain entretien : date à moins de 7 jours ou kilométrage à moins de 500 km.
  for v_row in
    select distinct on (m.customer_vehicle_id)
           m.id, m.customer_vehicle_id, m.next_service_date, m.next_service_mileage,
           cv.current_mileage, cv.brand, cv.model, cv.vehicle_name
    from public.motors_vehicle_maintenance_v164 m
    join public.customer_vehicles cv on cv.id=m.customer_vehicle_id
    where m.owner_user_id=v_uid and m.deleted_at is null and m.status='completed'
      and (m.next_service_date is not null or m.next_service_mileage is not null)
    order by m.customer_vehicle_id, m.service_date desc, m.id desc
  loop
    if (
      (v_row.next_service_date is not null and v_row.next_service_date <= current_date + 7)
      or (v_row.next_service_mileage is not null and v_row.next_service_mileage - coalesce(v_row.current_mileage,0) <= 500)
    ) and not exists (
      select 1 from public.user_notifications n
      where n.user_id=v_uid and n.source_type='maintenance_due_v164' and n.source_id=v_row.id::text
    ) then
      insert into public.user_notifications(user_id,notification_type,title,message,target_url,source_type,source_id,priority,category)
      values(
        v_uid,'maintenance','Entretien Nostra à prévoir',
        'Un entretien est bientôt recommandé pour '||coalesce(nullif(btrim(concat_ws(' ',v_row.brand,v_row.model)),''),v_row.vehicle_name,'ton véhicule')||'.',
        '/profil/garage/'||v_row.customer_vehicle_id,'maintenance_due_v164',v_row.id::text,'high','motors'
      );
      v_count := v_count + 1;
    end if;
  end loop;

  return v_count;
end;
$$;

grant execute on function public.nostra_v164_refresh_my_vehicle_notifications() to authenticated;

-- -----------------------------------------------------------------------------
-- 7) Validation sécurisée d'un transfert
-- -----------------------------------------------------------------------------
create or replace function public.nostra_v164_process_vehicle_transfer(
  p_request_id bigint,
  p_decision text,
  p_warranty_action text default null,
  p_staff_note text default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_req public.motors_vehicle_transfers_v164%rowtype;
  v_policy text;
  v_warranty_action text;
  v_vehicle_label text;
begin
  if not public.nostra_v164_has_permission('transfer_manage') then
    raise exception using message='forbidden';
  end if;

  if p_decision not in ('approved','rejected') then
    raise exception using message='invalid_decision';
  end if;

  select * into v_req
  from public.motors_vehicle_transfers_v164
  where id=p_request_id and status='pending'
  for update;

  if not found then raise exception using message='transfer_not_found'; end if;

  select warranty_transfer_policy into v_policy from public.motors_settings_v164 where id=1;
  v_warranty_action := coalesce(nullif(p_warranty_action,''), case when v_policy='cancel' then 'cancel' else 'transfer' end);

  if p_decision='rejected' then
    update public.motors_vehicle_transfers_v164
    set status='rejected', staff_note=nullif(p_staff_note,''), processed_by=auth.uid(), processed_at=now(), updated_at=now()
    where id=v_req.id;

    if to_regclass('public.user_notifications') is not null then
      insert into public.user_notifications(user_id,notification_type,title,message,target_url,source_type,source_id,priority,category)
      values(v_req.seller_user_id,'general','Transfert de véhicule refusé','La demande de transfert a été refusée par Nostra Motors.','/profil/garage/'||v_req.customer_vehicle_id,'vehicle_transfer_v164',v_req.id::text,'high','motors');
    end if;
    return;
  end if;

  if not exists(select 1 from public.customer_vehicles where id=v_req.customer_vehicle_id and user_id=v_req.seller_user_id and garage_status <> 'cancelled') then
    raise exception using message='vehicle_owner_changed';
  end if;

  select coalesce(nullif(btrim(concat_ws(' ',brand,model)),''),vehicle_name,'Véhicule Nostra')
  into v_vehicle_label
  from public.customer_vehicles where id=v_req.customer_vehicle_id;

  -- Les contrats en panier sont toujours annulés avant un changement de propriétaire.
  update public.motors_warranty_contracts_v163
  set status='cancelled', updated_at=now()
  where customer_vehicle_id=v_req.customer_vehicle_id and status='pending_payment';

  if v_warranty_action='transfer' then
    update public.motors_warranty_contracts_v163
    set user_id=v_req.target_user_id, updated_at=now()
    where customer_vehicle_id=v_req.customer_vehicle_id and status='active' and ends_at>now();
  else
    update public.motors_warranty_contracts_v163
    set status='cancelled', updated_at=now()
    where customer_vehicle_id=v_req.customer_vehicle_id and status='active';
  end if;

  update public.customer_vehicles
  set user_id=v_req.target_user_id, updated_at=now()
  where id=v_req.customer_vehicle_id;

  update public.motors_vehicle_maintenance_v164
  set owner_user_id=v_req.target_user_id, updated_at=now()
  where customer_vehicle_id=v_req.customer_vehicle_id;

  update public.motors_vehicle_transfers_v164
  set status='approved', warranty_action=v_warranty_action, staff_note=nullif(p_staff_note,''),
      processed_by=auth.uid(), processed_at=now(), updated_at=now()
  where id=v_req.id;

  if to_regclass('public.customer_vehicle_history') is not null then
    insert into public.customer_vehicle_history(customer_vehicle_id,event_type,status,title,details,created_at)
    values(v_req.customer_vehicle_id,'ownership_transfer','completed','Changement de propriétaire',
      'Transfert validé par Nostra Motors. Type : '||v_req.transfer_type||'. Nostra Care : '||v_warranty_action||'.',now());
  end if;

  if to_regclass('public.user_notifications') is not null then
    insert into public.user_notifications(user_id,notification_type,title,message,target_url,source_type,source_id,priority,category)
    values
      (v_req.seller_user_id,'general','Transfert de véhicule validé',v_vehicle_label||' a été retiré de ton garage.','/profil/garage','vehicle_transfer_v164',v_req.id::text,'high','motors'),
      (v_req.target_user_id,'general','Nouveau véhicule dans ton garage',v_vehicle_label||' est maintenant enregistré dans ton garage Nostra Motors.','/profil/garage/'||v_req.customer_vehicle_id,'vehicle_transfer_v164',v_req.id::text,'high','motors');
  end if;

  insert into public.motors_employee_audit_v164(actor_user_id,action_key,entity_type,entity_id,title,details)
  values(auth.uid(),'vehicle_transfer_approved','customer_vehicle',v_req.customer_vehicle_id::text,'Transfert véhicule validé',jsonb_build_object('request_id',v_req.id,'seller',v_req.seller_user_id,'buyer',v_req.target_user_id,'warranty_action',v_warranty_action));
end;
$$;

grant execute on function public.nostra_v164_process_vehicle_transfer(bigint,text,text,text) to authenticated;

-- Privilèges explicites : RLS reste la barrière d'accès métier.
grant select,insert,update,delete on public.motors_employees_v164 to authenticated;
grant select,insert on public.motors_employee_audit_v164 to authenticated;
grant select,insert,update on public.motors_vehicle_maintenance_v164 to authenticated;
grant select,insert,update on public.motors_vehicle_transfers_v164 to authenticated;
grant select,insert,update on public.motors_settings_v164 to authenticated;
grant usage,select on sequence public.motors_employee_audit_v164_id_seq to authenticated;
grant usage,select on sequence public.motors_vehicle_maintenance_v164_id_seq to authenticated;
grant usage,select on sequence public.motors_vehicle_transfers_v164_id_seq to authenticated;

commit;

select
  to_regclass('public.motors_vehicle_maintenance_v164') as maintenance,
  to_regclass('public.motors_vehicle_transfers_v164') as transfers,
  to_regclass('public.motors_employees_v164') as employees,
  to_regclass('public.motors_employee_audit_v164') as audit,
  to_regprocedure('public.nostra_v164_refresh_my_vehicle_notifications()') as smart_notifications;
