-- NOSTRA GROUP V142
-- Licences : suppression réellement définitive + prise en compte par la Racing Academy.
-- Prérequis : générateur licences V74/V75 + Academy V140.
-- Script réexécutable.

begin;

-- ---------------------------------------------------------------------------
-- 1. LIAISON EXPLICITE ENTRE UNE LICENCE OFFICIELLE ET UN NIVEAU ACADEMY
-- ---------------------------------------------------------------------------

create table if not exists public.academy_generated_licence_links_v142 (
  licence_id text primary key,
  holder_user_id uuid not null references auth.users(id) on delete cascade,
  license_code text not null,
  licence_name text,
  source text not null default 'auto',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists academy_generated_licence_links_v142_holder_idx
  on public.academy_generated_licence_links_v142(holder_user_id, license_code);

alter table public.academy_generated_licence_links_v142 enable row level security;

drop policy if exists "academy generated licence links read v142"
  on public.academy_generated_licence_links_v142;
create policy "academy generated licence links read v142"
on public.academy_generated_licence_links_v142
for select to authenticated
using (
  holder_user_id = auth.uid()
  or public.nostra_v137_has_any_role(array['manager','commissioner'])
);

drop policy if exists "academy generated licence links manage v142"
  on public.academy_generated_licence_links_v142;
create policy "academy generated licence links manage v142"
on public.academy_generated_licence_links_v142
for all to authenticated
using (public.nostra_v137_has_any_role(array['manager','commissioner']))
with check (public.nostra_v137_has_any_role(array['manager','commissioner']));

grant select,insert,update,delete on public.academy_generated_licence_links_v142 to authenticated;

create or replace function public.nostra_v142_official_licence_code(
  p_licence_id text,
  p_licence_name text
)
returns text
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_code text;
begin
  select l.license_code into v_code
  from public.academy_generated_licence_links_v142 l
  where l.licence_id = p_licence_id
  limit 1;

  if nullif(trim(coalesce(v_code,'')), '') is not null then
    return v_code;
  end if;

  return public.nostra_v140_license_code_from_name(p_licence_name);
end;
$$;

revoke all on function public.nostra_v142_official_licence_code(text,text) from public;
grant execute on function public.nostra_v142_official_licence_code(text,text) to authenticated;

create or replace function public.nostra_v142_link_official_licence(
  p_licence_id text,
  p_holder_user_id uuid,
  p_licence_name text,
  p_license_code text default null,
  p_source text default 'auto'
)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  v_code text;
begin
  if auth.uid() is null then
    raise exception using message = 'authentication_required';
  end if;

  if p_holder_user_id <> auth.uid()
     and not public.nostra_v137_has_any_role(array['manager','commissioner']) then
    raise exception using message = 'academy_staff_required';
  end if;

  if nullif(trim(coalesce(p_license_code,'')), '') is not null then
    select t.code into v_code
    from public.pilot_license_types t
    where public.nostra_v140_normalize(t.code) = public.nostra_v140_normalize(p_license_code)
    limit 1;

    if v_code is null then
      raise exception using message = 'academy_license_code_invalid';
    end if;
  else
    v_code := public.nostra_v140_license_code_from_name(p_licence_name);
  end if;

  if v_code is null then
    return null;
  end if;

  insert into public.academy_generated_licence_links_v142(
    licence_id, holder_user_id, license_code, licence_name, source, updated_at
  ) values (
    p_licence_id, p_holder_user_id, v_code, p_licence_name,
    coalesce(nullif(trim(p_source),''),'auto'), now()
  )
  on conflict (licence_id) do update set
    holder_user_id = excluded.holder_user_id,
    license_code = excluded.license_code,
    licence_name = excluded.licence_name,
    source = excluded.source,
    updated_at = now();

  return v_code;
end;
$$;

revoke all on function public.nostra_v142_link_official_licence(text,uuid,text,text,text) from public;
grant execute on function public.nostra_v142_link_official_licence(text,uuid,text,text,text) to authenticated;

-- ---------------------------------------------------------------------------
-- 2. TRACE DE SUPPRESSION : INTERDIT LA REGENERATION AUTOMATIQUE
-- ---------------------------------------------------------------------------

create table if not exists public.nostra_deleted_licences_v142 (
  id bigint generated by default as identity primary key,
  deleted_licence_id text not null,
  holder_user_id uuid,
  license_code text,
  licence_name text,
  licence_number text,
  deleted_by uuid references auth.users(id) on delete set null,
  deleted_at timestamptz not null default now()
);

create index if not exists nostra_deleted_licences_v142_lookup_idx
  on public.nostra_deleted_licences_v142(holder_user_id, license_code, deleted_at desc);

alter table public.nostra_deleted_licences_v142 enable row level security;

drop policy if exists "deleted licences v142 staff read" on public.nostra_deleted_licences_v142;
create policy "deleted licences v142 staff read"
on public.nostra_deleted_licences_v142
for select to authenticated
using (public.nostra_v137_has_any_role(array['manager','commissioner']));

grant select on public.nostra_deleted_licences_v142 to authenticated;

create or replace function public.nostra_v142_before_official_licence_insert()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_code text;
  v_allow boolean := coalesce(current_setting('nostra.allow_licence_reissue', true), '') = 'on';
  v_deleted_id bigint;
begin
  v_code := public.nostra_v140_license_code_from_name(new.licence_name);

  select d.id into v_deleted_id
  from public.nostra_deleted_licences_v142 d
  where d.holder_user_id = new.holder_user_id
    and (
      (v_code is not null and public.nostra_v140_normalize(d.license_code) = public.nostra_v140_normalize(v_code))
      or (
        v_code is null
        and public.nostra_v140_normalize(d.licence_name) = public.nostra_v140_normalize(new.licence_name)
      )
    )
  order by d.deleted_at desc
  limit 1;

  if v_deleted_id is not null and not v_allow then
    raise exception using
      message = 'licence_deleted_no_auto_reissue',
      hint = 'La licence a été supprimée par la Direction et ne peut pas être recréée par une ancienne synchronisation.';
  end if;

  if v_deleted_id is not null and v_allow then
    delete from public.nostra_deleted_licences_v142 d
    where d.holder_user_id = new.holder_user_id
      and (
        (v_code is not null and public.nostra_v140_normalize(d.license_code) = public.nostra_v140_normalize(v_code))
        or (
          v_code is null
          and public.nostra_v140_normalize(d.licence_name) = public.nostra_v140_normalize(new.licence_name)
        )
      );
  end if;

  return new;
end;
$$;

create or replace function public.nostra_v142_after_official_licence_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_code text;
begin
  if tg_op = 'DELETE' then
    v_code := public.nostra_v142_official_licence_code(old.id::text, old.licence_name);

    insert into public.nostra_deleted_licences_v142(
      deleted_licence_id, holder_user_id, license_code, licence_name,
      licence_number, deleted_by, deleted_at
    ) values (
      old.id::text, old.holder_user_id, v_code, old.licence_name,
      old.licence_number, auth.uid(), now()
    );

    delete from public.academy_generated_licence_links_v142
    where licence_id = old.id::text;

    if to_regclass('public.academy_licence_controls_v140') is not null then
      delete from public.academy_licence_controls_v140
      where licence_id = old.id::text;
    end if;

    return old;
  end if;

  -- INSERT / UPDATE : toute licence officielle reconnue est liée à l'Academy.
  v_code := public.nostra_v140_license_code_from_name(new.licence_name);
  if v_code is not null then
    insert into public.academy_generated_licence_links_v142(
      licence_id, holder_user_id, license_code, licence_name, source, updated_at
    ) values (
      new.id::text, new.holder_user_id, v_code, new.licence_name, 'auto', now()
    )
    on conflict (licence_id) do update set
      holder_user_id = excluded.holder_user_id,
      licence_name = excluded.licence_name,
      license_code = case
        when public.academy_generated_licence_links_v142.source = 'generator-explicit'
          then public.academy_generated_licence_links_v142.license_code
        else excluded.license_code
      end,
      source = case
        when public.academy_generated_licence_links_v142.source = 'generator-explicit'
          then public.academy_generated_licence_links_v142.source
        else excluded.source
      end,
      updated_at = now();
  end if;

  return new;
end;
$$;

drop trigger if exists nostra_v142_before_licence_insert on public.nostra_licences;
create trigger nostra_v142_before_licence_insert
before insert on public.nostra_licences
for each row execute function public.nostra_v142_before_official_licence_insert();

drop trigger if exists nostra_v142_after_licence_insert_update on public.nostra_licences;
create trigger nostra_v142_after_licence_insert_update
after insert or update of holder_user_id, licence_name on public.nostra_licences
for each row execute function public.nostra_v142_after_official_licence_change();

drop trigger if exists nostra_v142_after_licence_delete on public.nostra_licences;
create trigger nostra_v142_after_licence_delete
after delete on public.nostra_licences
for each row execute function public.nostra_v142_after_official_licence_change();

-- Backfill des licences déjà présentes au moment de la migration.
insert into public.academy_generated_licence_links_v142(
  licence_id, holder_user_id, license_code, licence_name, source
)
select
  l.id::text,
  l.holder_user_id,
  public.nostra_v140_license_code_from_name(l.licence_name),
  l.licence_name,
  'backfill'
from public.nostra_licences l
where l.holder_user_id is not null
  and public.nostra_v140_license_code_from_name(l.licence_name) is not null
on conflict (licence_id) do nothing;

-- ---------------------------------------------------------------------------
-- 3. GENERATEUR DIRECTION : DELIVRANCE + LIAISON ACADEMY EN UNE ACTION
-- ---------------------------------------------------------------------------

create or replace function public.issue_nostra_licence_academy_v142(
  p_holder_user_id uuid,
  p_licence_name text,
  p_category text,
  p_authority text,
  p_valid_from date,
  p_valid_until date,
  p_permissions text,
  p_notes text,
  p_send_to_citizen boolean,
  p_academy_license_code text default null
)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  v_result text;
begin
  if not public.nostra_v137_has_any_role(array['manager']) then
    raise exception using message = 'manager_required';
  end if;

  -- Une délivrance volontaire Direction est autorisée à recréer une licence
  -- précédemment supprimée. Les anciennes synchronisations automatiques, non.
  perform set_config('nostra.allow_licence_reissue', 'on', true);

  select public.issue_nostra_licence_safe_v74(
    p_holder_user_id,
    p_licence_name,
    p_category,
    p_authority,
    p_valid_from,
    p_valid_until,
    p_permissions,
    p_notes,
    p_send_to_citizen
  ) into v_result;

  perform public.nostra_v142_link_official_licence(
    v_result,
    p_holder_user_id,
    p_licence_name,
    p_academy_license_code,
    case when nullif(trim(coalesce(p_academy_license_code,'')), '') is null
      then 'generator-auto'
      else 'generator-explicit'
    end
  );

  return v_result;
end;
$$;

revoke all on function public.issue_nostra_licence_academy_v142(
  uuid,text,text,text,date,date,text,text,boolean,text
) from public;
grant execute on function public.issue_nostra_licence_academy_v142(
  uuid,text,text,text,date,date,text,text,boolean,text
) to authenticated;

-- ---------------------------------------------------------------------------
-- 4. SIGNATURE D'UN NOUVEAU DOSSIER : DELIVRANCE VOLONTAIRE AUTORISEE
-- ---------------------------------------------------------------------------

create or replace function public.nostra_v142_sync_signed_pilot_licence(
  p_document_id text
)
returns void
language plpgsql
security invoker
set search_path = public
as $$
begin
  perform set_config('nostra.allow_licence_reissue', 'on', true);

  if to_regprocedure('public.nostra_sync_signed_pilot_licence_v75(text)') is not null then
    execute 'select public.nostra_sync_signed_pilot_licence_v75($1::text)'
      using p_document_id;
  elsif to_regprocedure('public.nostra_sync_signed_pilot_licence_v75(bigint)') is not null then
    execute 'select public.nostra_sync_signed_pilot_licence_v75($1::bigint)'
      using p_document_id;
  elsif to_regprocedure('public.nostra_sync_signed_pilot_licence_v75(uuid)') is not null then
    execute 'select public.nostra_sync_signed_pilot_licence_v75($1::uuid)'
      using p_document_id;
  else
    raise exception using message = 'signed_license_sync_missing';
  end if;
end;
$$;

revoke all on function public.nostra_v142_sync_signed_pilot_licence(text) from public;
grant execute on function public.nostra_v142_sync_signed_pilot_licence(text) to authenticated;

-- ---------------------------------------------------------------------------
-- 5. SUPPRESSION DIRECTION DEFINITIVE
-- ---------------------------------------------------------------------------

create or replace function public.nostra_v142_delete_licence_permanently(
  p_licence_id text
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.nostra_v137_has_any_role(array['manager']) then
    raise exception using message = 'manager_required';
  end if;

  if not exists (
    select 1 from public.nostra_licences l where l.id::text = p_licence_id
  ) then
    raise exception using message = 'licence_not_found';
  end if;

  -- On ne met PAS le drapeau de réémission : le trigger DELETE conserve la
  -- trace et interdit toute réparation automatique ultérieure.
  if to_regprocedure('public.delete_nostra_licence(text)') is not null then
    execute 'select public.delete_nostra_licence($1::text)' using p_licence_id;
  elsif to_regprocedure('public.delete_nostra_licence(uuid)') is not null then
    execute 'select public.delete_nostra_licence($1::uuid)' using p_licence_id;
  else
    delete from public.nostra_licences where id::text = p_licence_id;
  end if;
end;
$$;

revoke all on function public.nostra_v142_delete_licence_permanently(text) from public;
grant execute on function public.nostra_v142_delete_licence_permanently(text) to authenticated;

-- ---------------------------------------------------------------------------
-- 6. ACADEMY V140 : LES PREREQUIS UTILISENT DESORMAIS LA LIAISON OFFICIELLE
-- ---------------------------------------------------------------------------

create or replace function public.nostra_v140_license_eligibility(
  p_user uuid,
  p_license_code text
)
returns table (
  eligible boolean,
  reason text,
  license_code text,
  license_label text,
  required_course_id bigint,
  required_course_title text,
  qualification_id bigint,
  qualification_label text,
  qualification_valid_until date,
  prerequisite_license_code text,
  prerequisite_license_label text,
  training_ok boolean,
  prerequisite_ok boolean,
  license_validity_months integer
)
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_req public.academy_license_requirements_v140%rowtype;
  v_course_title text;
  v_q public.academy_qualifications_v137%rowtype;
  v_any_matching boolean := false;
  v_any_unexpired boolean := false;
  v_prereq_label text;
  v_prereq_ok boolean := true;
  v_prereq_code text;
  v_licence_id text;
  v_target_block_reason text := null;
  v_target_control_state text;
begin
  select * into v_req
  from public.academy_license_requirements_v140 r
  where public.nostra_v140_normalize(r.license_code) = public.nostra_v140_normalize(p_license_code)
  limit 1;

  if not found then
    v_req.license_code := p_license_code;
    v_req.license_label := p_license_code;
    v_req.required_course_id := null;
    v_req.prerequisite_license_code := null;
    v_req.min_theory_score := 0;
    v_req.min_practical_score := 0;
    v_req.license_validity_months := 5;
    v_req.active := true;
  end if;

  if v_req.required_course_id is not null then
    select c.title into v_course_title
    from public.academy_courses_v137 c
    where c.id = v_req.required_course_id;
  end if;

  select exists (
    select 1
    from public.academy_qualifications_v137 q
    join public.academy_enrollments_v137 e on e.id = q.enrollment_id
    where q.user_id = p_user
      and q.active = true
      and e.status = 'passed'
      and (v_req.required_course_id is null or q.course_id = v_req.required_course_id)
      and q.theory_score >= v_req.min_theory_score
      and q.practical_score >= v_req.min_practical_score
  ) into v_any_matching;

  select exists (
    select 1
    from public.academy_qualifications_v137 q
    join public.academy_enrollments_v137 e on e.id = q.enrollment_id
    where q.user_id = p_user
      and q.active = true
      and e.status = 'passed'
      and (v_req.required_course_id is null or q.course_id = v_req.required_course_id)
      and q.theory_score >= v_req.min_theory_score
      and q.practical_score >= v_req.min_practical_score
      and (q.valid_until is null or q.valid_until >= current_date)
  ) into v_any_unexpired;

  select q.* into v_q
  from public.academy_qualifications_v137 q
  join public.academy_enrollments_v137 e on e.id = q.enrollment_id
  where q.user_id = p_user
    and q.active = true
    and e.status = 'passed'
    and (v_req.required_course_id is null or q.course_id = v_req.required_course_id)
    and q.theory_score >= v_req.min_theory_score
    and q.practical_score >= v_req.min_practical_score
    and (q.valid_until is null or q.valid_until >= current_date)
  order by q.issued_at desc
  limit 1;

  v_prereq_code := nullif(trim(coalesce(v_req.prerequisite_license_code,'')), '');

  if v_prereq_code is not null then
    if to_regclass('public.pilot_license_types') is not null then
      select label into v_prereq_label
      from public.pilot_license_types
      where public.nostra_v140_normalize(code) = public.nostra_v140_normalize(v_prereq_code)
      limit 1;
    end if;

    v_prereq_ok := false;

    if to_regclass('public.nostra_licences') is not null then
      for v_licence_id in
        select l.id::text
        from public.nostra_licences l
        where l.holder_user_id = p_user
          and public.nostra_v140_normalize(
            public.nostra_v142_official_licence_code(l.id::text, l.licence_name)
          ) = public.nostra_v140_normalize(v_prereq_code)
          and l.valid_from <= current_date
          and (l.valid_until is null or l.valid_until >= current_date)
          and lower(coalesce(l.status,'')) not like '%retir%'
          and lower(coalesce(l.status,'')) not like '%revok%'
          and lower(coalesce(l.status,'')) not like '%suspend%'
        order by l.valid_until desc nulls first
      loop
        if not public.nostra_v140_licence_is_blocked(v_licence_id) then
          v_prereq_ok := true;
          exit;
        end if;
      end loop;
    end if;
  end if;

  if to_regclass('public.nostra_licences') is not null then
    for v_licence_id in
      select l.id::text
      from public.nostra_licences l
      where l.holder_user_id = p_user
        and public.nostra_v140_normalize(
          public.nostra_v142_official_licence_code(l.id::text, l.licence_name)
        ) = public.nostra_v140_normalize(p_license_code)
      order by l.valid_until desc nulls first
    loop
      v_target_control_state := null;
      if to_regclass('public.academy_licence_controls_v140') is not null then
        select c.control_state into v_target_control_state
        from public.academy_licence_controls_v140 c
        where c.licence_id = v_licence_id
        limit 1;
      end if;

      if v_target_control_state = 'revoked' then
        v_target_block_reason := 'license_revoked';
        exit;
      end if;

      if public.nostra_v140_licence_is_blocked(v_licence_id) then
        v_target_block_reason := 'license_suspended';
        exit;
      end if;
    end loop;
  end if;

  eligible := coalesce(v_req.active, true)
    and v_any_unexpired
    and v_prereq_ok
    and v_target_block_reason is null;

  reason := case
    when v_target_block_reason is not null then v_target_block_reason
    when coalesce(v_req.active, true) = false then 'academy_requirement_disabled'
    when not v_any_matching then
      case when v_req.required_course_id is null
        then 'academy_training_required'
        else 'academy_specific_training_required'
      end
    when v_any_matching and not v_any_unexpired then 'academy_training_expired'
    when not v_prereq_ok then 'prerequisite_license_required'
    else 'ok'
  end;

  license_code := coalesce(v_req.license_code, p_license_code);
  license_label := coalesce(v_req.license_label, p_license_code);
  required_course_id := v_req.required_course_id;
  required_course_title := v_course_title;
  qualification_id := v_q.id;
  qualification_label := v_q.qualification_label;
  qualification_valid_until := v_q.valid_until;
  prerequisite_license_code := v_prereq_code;
  prerequisite_license_label := coalesce(v_prereq_label, v_prereq_code);
  training_ok := v_any_unexpired;
  prerequisite_ok := v_prereq_ok;
  license_validity_months := coalesce(v_req.license_validity_months, 5);

  return next;
end;
$$;

revoke all on function public.nostra_v140_license_eligibility(uuid,text) from public;
grant execute on function public.nostra_v140_license_eligibility(uuid,text) to authenticated;

commit;
