-- NOSTRA GROUP V153 — Suite Direction & expérience citoyen
-- Réexécutable. Conserve les données existantes.

-- ---------------------------------------------------------------------------
-- 0. Helpers
-- ---------------------------------------------------------------------------
create or replace function public.nostra_v153_is_manager()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(public.has_nostra_dashboard_access(), false);
$$;

grant execute on function public.nostra_v153_is_manager() to authenticated;

-- ---------------------------------------------------------------------------
-- 1. Maintenance par pôle
-- ---------------------------------------------------------------------------
create table if not exists public.nostra_pole_maintenance_v153 (
  pole_key text primary key check (pole_key in ('motors','circuit','cercle','academy','events')),
  enabled boolean not null default false,
  title text not null,
  message text not null,
  eta_text text,
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id) on delete set null
);

insert into public.nostra_pole_maintenance_v153 (pole_key,title,message)
values
  ('motors','Nostra Motors en maintenance','La concession est temporairement indisponible. Nos équipes préparent le retour du service.'),
  ('circuit','Nostra Circuit en maintenance','Le portail Nostra Circuit est temporairement indisponible.'),
  ('cercle','Nostra Cercle en maintenance','Le Cercle est temporairement fermé pour maintenance.'),
  ('academy','Racing Academy en maintenance','Les services de la Nostra Racing Academy sont temporairement indisponibles.'),
  ('events','Événements & Jeux en maintenance','Le portail Événements & Jeux est temporairement indisponible.')
on conflict (pole_key) do nothing;

alter table public.nostra_pole_maintenance_v153 enable row level security;
drop policy if exists "v153 maintenance read" on public.nostra_pole_maintenance_v153;
create policy "v153 maintenance read" on public.nostra_pole_maintenance_v153 for select to authenticated using (true);
drop policy if exists "v153 maintenance manage" on public.nostra_pole_maintenance_v153;
create policy "v153 maintenance manage" on public.nostra_pole_maintenance_v153 for all to authenticated
using (public.nostra_v153_is_manager()) with check (public.nostra_v153_is_manager());
grant select,insert,update,delete on public.nostra_pole_maintenance_v153 to authenticated;

-- ---------------------------------------------------------------------------
-- 2. Codes promotionnels Direction
-- ---------------------------------------------------------------------------
create table if not exists public.nostra_promo_codes_v153 (
  id uuid primary key default gen_random_uuid(),
  code text not null unique,
  label text not null,
  scope text not null default 'global' check (scope in ('global','motors','ticketing','cercle')),
  discount_type text not null default 'percent' check (discount_type in ('percent','fixed')),
  discount_value numeric(14,2) not null check (discount_value > 0),
  min_amount numeric(14,2) not null default 0 check (min_amount >= 0),
  max_discount numeric(14,2),
  max_uses integer,
  max_uses_per_user integer not null default 1 check (max_uses_per_user > 0),
  starts_at timestamptz,
  ends_at timestamptz,
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  created_by uuid references auth.users(id) on delete set null,
  updated_at timestamptz not null default now()
);

create table if not exists public.nostra_promo_redemptions_v153 (
  id bigint generated by default as identity primary key,
  promo_id uuid not null references public.nostra_promo_codes_v153(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  scope text not null,
  source_type text,
  source_id text,
  base_amount numeric(14,2) not null default 0,
  discount_amount numeric(14,2) not null default 0,
  created_at timestamptz not null default now()
);
create index if not exists nostra_promo_redemptions_v153_user_idx on public.nostra_promo_redemptions_v153(user_id, created_at desc);

alter table public.nostra_promo_codes_v153 enable row level security;
alter table public.nostra_promo_redemptions_v153 enable row level security;
drop policy if exists "v153 promo read enabled" on public.nostra_promo_codes_v153;
create policy "v153 promo read enabled" on public.nostra_promo_codes_v153 for select to authenticated using (enabled or public.nostra_v153_is_manager());
drop policy if exists "v153 promo manage" on public.nostra_promo_codes_v153;
create policy "v153 promo manage" on public.nostra_promo_codes_v153 for all to authenticated using (public.nostra_v153_is_manager()) with check (public.nostra_v153_is_manager());
drop policy if exists "v153 redemption own" on public.nostra_promo_redemptions_v153;
create policy "v153 redemption own" on public.nostra_promo_redemptions_v153 for select to authenticated using (user_id = auth.uid() or public.nostra_v153_is_manager());
grant select,insert,update,delete on public.nostra_promo_codes_v153 to authenticated;
grant select on public.nostra_promo_redemptions_v153 to authenticated;
grant usage,select on sequence public.nostra_promo_redemptions_v153_id_seq to authenticated;

create or replace function public.nostra_promo_quote_v153(
  p_code text,
  p_scope text,
  p_amount numeric
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
  v_code public.nostra_promo_codes_v153%rowtype;
  v_total_uses integer := 0;
  v_user_uses integer := 0;
  v_discount numeric(14,2) := 0;
begin
  if v_uid is null then raise exception using message='not_authenticated'; end if;
  if coalesce(btrim(p_code),'') = '' then return jsonb_build_object('valid',false,'reason','empty'); end if;
  select * into v_code from public.nostra_promo_codes_v153 where upper(code)=upper(btrim(p_code)) limit 1;
  if not found then return jsonb_build_object('valid',false,'reason','unknown'); end if;
  if not v_code.enabled then return jsonb_build_object('valid',false,'reason','disabled'); end if;
  if v_code.scope <> 'global' and v_code.scope <> p_scope then return jsonb_build_object('valid',false,'reason','scope'); end if;
  if v_code.starts_at is not null and now() < v_code.starts_at then return jsonb_build_object('valid',false,'reason','not_started'); end if;
  if v_code.ends_at is not null and now() > v_code.ends_at then return jsonb_build_object('valid',false,'reason','expired'); end if;
  if coalesce(p_amount,0) < v_code.min_amount then return jsonb_build_object('valid',false,'reason','minimum','minimum',v_code.min_amount); end if;
  select count(*) into v_total_uses from public.nostra_promo_redemptions_v153 where promo_id=v_code.id;
  select count(*) into v_user_uses from public.nostra_promo_redemptions_v153 where promo_id=v_code.id and user_id=v_uid;
  if v_code.max_uses is not null and v_total_uses >= v_code.max_uses then return jsonb_build_object('valid',false,'reason','limit'); end if;
  if v_user_uses >= v_code.max_uses_per_user then return jsonb_build_object('valid',false,'reason','user_limit'); end if;
  if v_code.discount_type='percent' then
    v_discount := round(greatest(0,p_amount) * least(100,v_code.discount_value) / 100, 2);
  else
    v_discount := least(greatest(0,p_amount),v_code.discount_value);
  end if;
  if v_code.max_discount is not null then v_discount := least(v_discount,v_code.max_discount); end if;
  return jsonb_build_object(
    'valid',true,'promo_id',v_code.id,'code',v_code.code,'label',v_code.label,
    'discount_type',v_code.discount_type,'discount_value',v_code.discount_value,
    'discount_amount',v_discount,'final_amount',greatest(0,p_amount-v_discount)
  );
end;
$$;
grant execute on function public.nostra_promo_quote_v153(text,text,numeric) to authenticated;

create or replace function public.nostra_redeem_promo_v153(
  p_code text,
  p_scope text,
  p_amount numeric,
  p_source_type text default null,
  p_source_id text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
  v_quote jsonb;
  v_promo uuid;
begin
  v_quote := public.nostra_promo_quote_v153(p_code,p_scope,p_amount);
  if coalesce((v_quote->>'valid')::boolean,false) is false then return v_quote; end if;
  v_promo := (v_quote->>'promo_id')::uuid;
  insert into public.nostra_promo_redemptions_v153(promo_id,user_id,scope,source_type,source_id,base_amount,discount_amount)
  values(v_promo,v_uid,p_scope,p_source_type,p_source_id,p_amount,(v_quote->>'discount_amount')::numeric);
  return v_quote;
end;
$$;
grant execute on function public.nostra_redeem_promo_v153(text,text,numeric,text,text) to authenticated;

-- Wrapper de commande : conserve le moteur V93, puis applique la remise dans la même transaction.
create or replace function public.place_nostra_order_v153(
  p_order_number text,
  p_customer_name text,
  p_customer_note text default null,
  p_promo_code text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_result jsonb;
  v_order_id bigint;
  v_total numeric(14,2);
  v_quote jsonb;
  v_discount numeric(14,2) := 0;
begin
  v_result := public.place_nostra_order_v93(p_order_number,p_customer_name,p_customer_note);
  v_order_id := (v_result->>'id')::bigint;
  select total into v_total from public.orders where id=v_order_id;
  if coalesce(btrim(p_promo_code),'') <> '' then
    v_quote := public.nostra_redeem_promo_v153(p_promo_code,'motors',v_total,'order',v_order_id::text);
    if coalesce((v_quote->>'valid')::boolean,false) is false then
      raise exception using message='promo_' || coalesce(v_quote->>'reason','invalid');
    end if;
    v_discount := coalesce((v_quote->>'discount_amount')::numeric,0);
    update public.orders
      set total=greatest(0,total-v_discount),
          items=coalesce(items,'[]'::jsonb) || jsonb_build_array(jsonb_build_object(
            'item_type','discount','name','Code promo ' || upper(btrim(p_promo_code)),
            'quantity',1,'unit_price',-v_discount,'image_url',null
          )), updated_at=now()
      where id=v_order_id;
  end if;
  select total into v_total from public.orders where id=v_order_id;
  return v_result || jsonb_build_object('total',v_total,'discount',v_discount);
end;
$$;
grant execute on function public.place_nostra_order_v153(text,text,text,text) to authenticated;

-- Codes promo applicables aussi à la caisse Nostra Cercle (V148).
do $$
begin
  if to_regclass('public.casino_conversion_requests') is not null then
    alter table public.casino_conversion_requests add column if not exists discount_amount bigint not null default 0;
    alter table public.casino_conversion_requests add column if not exists promo_code text;
  end if;
end $$;

-- ---------------------------------------------------------------------------
-- 3. Suivi avancé des commandes + CRM Motors
-- ---------------------------------------------------------------------------
create table if not exists public.order_progress_v153 (
  order_id bigint primary key references public.orders(id) on delete cascade,
  stage text not null default 'received' check (stage in ('received','confirmed','preparing','paint','plate','quality','ready','collected','cancelled')),
  progress_percent integer not null default 5 check (progress_percent between 0 and 100),
  payment_status text not null default 'paid' check (payment_status in ('pending','paid','refunded')),
  estimated_ready_at timestamptz,
  internal_note text,
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id) on delete set null
);

create table if not exists public.order_progress_history_v153 (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  stage text not null,
  progress_percent integer not null,
  public_message text,
  created_at timestamptz not null default now(),
  created_by uuid references auth.users(id) on delete set null
);
create index if not exists order_progress_history_v153_order_idx on public.order_progress_history_v153(order_id,created_at);

create table if not exists public.motors_crm_profiles_v153 (
  user_id uuid primary key references auth.users(id) on delete cascade,
  customer_status text not null default 'standard' check (customer_status in ('standard','premium','vip','black')),
  preferred_contact text not null default 'mail' check (preferred_contact in ('mail','phone','site')),
  assigned_commercial uuid references auth.users(id) on delete set null,
  tags text[] not null default '{}',
  last_contact_at timestamptz,
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id) on delete set null
);

create table if not exists public.motors_crm_notes_v153 (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  category text not null default 'suivi',
  note text not null,
  created_at timestamptz not null default now(),
  created_by uuid references auth.users(id) on delete set null
);
create index if not exists motors_crm_notes_v153_user_idx on public.motors_crm_notes_v153(user_id,created_at desc);

alter table public.order_progress_v153 enable row level security;
alter table public.order_progress_history_v153 enable row level security;
alter table public.motors_crm_profiles_v153 enable row level security;
alter table public.motors_crm_notes_v153 enable row level security;

drop policy if exists "v153 order progress read" on public.order_progress_v153;
create policy "v153 order progress read" on public.order_progress_v153 for select to authenticated using (
  public.nostra_v153_is_manager() or exists(select 1 from public.orders o where o.id=order_id and o.user_id=auth.uid()) or public.nostra_role() in ('employee','commercial')
);
drop policy if exists "v153 order history read" on public.order_progress_history_v153;
create policy "v153 order history read" on public.order_progress_history_v153 for select to authenticated using (
  public.nostra_v153_is_manager() or exists(select 1 from public.orders o where o.id=order_id and o.user_id=auth.uid()) or public.nostra_role() in ('employee','commercial')
);
drop policy if exists "v153 order progress staff write" on public.order_progress_v153;
create policy "v153 order progress staff write" on public.order_progress_v153 for all to authenticated
using (public.nostra_role() in ('manager','employee','commercial'))
with check (public.nostra_role() in ('manager','employee','commercial'));
drop policy if exists "v153 order history staff insert" on public.order_progress_history_v153;
create policy "v153 order history staff insert" on public.order_progress_history_v153 for insert to authenticated
with check (public.nostra_role() in ('manager','employee','commercial'));

drop policy if exists "v153 crm staff" on public.motors_crm_profiles_v153;
create policy "v153 crm staff" on public.motors_crm_profiles_v153 for all to authenticated using (public.nostra_role() in ('manager','employee','commercial')) with check (public.nostra_role() in ('manager','employee','commercial'));
drop policy if exists "v153 crm notes staff" on public.motors_crm_notes_v153;
create policy "v153 crm notes staff" on public.motors_crm_notes_v153 for all to authenticated using (public.nostra_role() in ('manager','employee','commercial')) with check (public.nostra_role() in ('manager','employee','commercial'));

grant select,insert,update,delete on public.order_progress_v153,public.order_progress_history_v153,public.motors_crm_profiles_v153,public.motors_crm_notes_v153 to authenticated;
grant usage,select on sequence public.order_progress_history_v153_id_seq,public.motors_crm_notes_v153_id_seq to authenticated;

create or replace function public.nostra_v153_init_order_progress()
returns trigger language plpgsql security definer set search_path=public as $$
begin
  insert into public.order_progress_v153(order_id,stage,progress_percent,payment_status)
  values(new.id,'received',5,'paid') on conflict(order_id) do nothing;
  insert into public.order_progress_history_v153(order_id,stage,progress_percent,public_message)
  values(new.id,'received',5,'Commande reçue par Nostra Motors.');
  return new;
end; $$;
drop trigger if exists nostra_v153_init_order_progress on public.orders;
create trigger nostra_v153_init_order_progress after insert on public.orders for each row execute function public.nostra_v153_init_order_progress();

insert into public.order_progress_v153(order_id,stage,progress_percent,payment_status)
select o.id,
  case o.status when 'confirmed' then 'confirmed' when 'preparing' then 'preparing' when 'ready' then 'ready' when 'completed' then 'collected' when 'cancelled' then 'cancelled' else 'received' end,
  case o.status when 'confirmed' then 20 when 'preparing' then 45 when 'ready' then 95 when 'completed' then 100 when 'cancelled' then 0 else 5 end,
  'paid'
from public.orders o
on conflict(order_id) do nothing;

-- ---------------------------------------------------------------------------
-- 4. Contrats de vente générés après signature + paiement
-- ---------------------------------------------------------------------------
create table if not exists public.nostra_vehicle_contracts_v153 (
  id uuid primary key default gen_random_uuid(),
  order_id bigint not null unique references public.orders(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  contract_number text not null unique,
  customer_name text not null,
  amount numeric(14,2) not null,
  vehicle_snapshot jsonb not null default '[]'::jsonb,
  signed_at timestamptz not null,
  paid_at timestamptz not null,
  status text not null default 'active' check (status in ('active','cancelled')),
  verification_code text not null unique default upper(substr(replace(gen_random_uuid()::text,'-',''),1,12)),
  created_at timestamptz not null default now()
);

alter table public.nostra_vehicle_contracts_v153 enable row level security;
drop policy if exists "v153 contracts own" on public.nostra_vehicle_contracts_v153;
create policy "v153 contracts own" on public.nostra_vehicle_contracts_v153 for select to authenticated using (user_id=auth.uid() or public.nostra_role() in ('manager','employee','commercial'));
grant select on public.nostra_vehicle_contracts_v153 to authenticated;

create or replace function public.nostra_generate_vehicle_contract_v153(p_order_id bigint)
returns uuid
language plpgsql
security definer
set search_path=public
as $$
declare
  v_order public.orders%rowtype;
  v_progress public.order_progress_v153%rowtype;
  v_signed_at timestamptz;
  v_contract_id uuid;
  v_number text;
  v_invoice_id bigint;
begin
  select * into v_order from public.orders where id=p_order_id;
  if not found then return null; end if;
  if auth.uid() is distinct from v_order.user_id and public.nostra_role() not in ('manager','employee','commercial') then
    raise exception using message='forbidden';
  end if;
  select * into v_progress from public.order_progress_v153 where order_id=p_order_id;
  if not found or v_progress.payment_status <> 'paid' then return null; end if;

  -- Recherche d'un bon de commande signé via le registre documentaire.
  if to_regclass('public.nostra_document_registry') is not null then
    select r.signed_at into v_signed_at
    from public.nostra_document_registry r
    join public.invoices i on (
      (r.source_table='invoices' and r.source_id=i.id::text)
      or (r.metadata->>'invoice_id'=i.id::text)
    )
    where i.order_id=p_order_id
      and i.document_type='order_form'
      and r.signature_status='signed'
    order by r.signed_at desc nulls last limit 1;
  end if;
  if v_signed_at is null then return null; end if;

  select id into v_contract_id from public.nostra_vehicle_contracts_v153 where order_id=p_order_id;
  if v_contract_id is not null then return v_contract_id; end if;
  v_number := 'NM-CTR-' || to_char(now(),'YYYYMMDD') || '-' || lpad(p_order_id::text,6,'0');
  insert into public.nostra_vehicle_contracts_v153(order_id,user_id,contract_number,customer_name,amount,vehicle_snapshot,signed_at,paid_at)
  values(p_order_id,v_order.user_id,v_number,coalesce(nullif(v_order.customer_name,''),'Client Nostra Motors'),v_order.total,coalesce(v_order.items,'[]'::jsonb),v_signed_at,now())
  returning id into v_contract_id;

  -- Ajoute un document au centre documentaire lorsqu'il existe.
  if to_regclass('public.invoices') is not null then
    insert into public.invoices(user_id,invoice_number,status,amount,issued_at,download_url,order_id,document_type,document_title,document_payload)
    values(v_order.user_id,v_number,'issued',v_order.total,now(),'/profil/contrats/'||v_contract_id::text,p_order_id,'contract','Contrat de vente Nostra Motors',jsonb_build_object('contract_id',v_contract_id,'order_number',v_order.order_number,'signed_at',v_signed_at,'paid_at',now()))
    on conflict(invoice_number) do update set download_url=excluded.download_url,document_payload=excluded.document_payload
    returning id into v_invoice_id;
  end if;

  if to_regclass('public.user_notifications') is not null then
    insert into public.user_notifications(user_id,notification_type,title,message,target_url,source_type,source_id,priority,category)
    values(v_order.user_id,'contract','Votre contrat de vente est disponible','La signature et le paiement ont été validés. Votre contrat définitif Nostra Motors a été généré.','/profil/contrats/'||v_contract_id::text,'vehicle_contract',v_contract_id::text,'high','motors');
  end if;
  return v_contract_id;
end;
$$;
grant execute on function public.nostra_generate_vehicle_contract_v153(bigint) to authenticated;

-- ---------------------------------------------------------------------------
-- 5. Profils complets d'écurie
-- ---------------------------------------------------------------------------
create table if not exists public.nostra_team_profiles_v153 (
  team_registration_id bigint primary key references public.team_registration_requests(id) on delete cascade,
  owner_user_id uuid not null references auth.users(id) on delete cascade,
  logo_url text,
  slogan text,
  description text,
  primary_color text not null default '#111111',
  secondary_color text not null default '#d6b25e',
  headquarters text,
  principal_driver text,
  second_driver text,
  reserve_driver text,
  vehicle_model text,
  achievements text,
  sponsors text,
  public_visible boolean not null default true,
  updated_at timestamptz not null default now()
);
alter table public.nostra_team_profiles_v153 enable row level security;
drop policy if exists "v153 team profile read" on public.nostra_team_profiles_v153;
create policy "v153 team profile read" on public.nostra_team_profiles_v153 for select to authenticated using (public_visible or owner_user_id=auth.uid() or public.nostra_v153_is_manager());
drop policy if exists "v153 team profile owner" on public.nostra_team_profiles_v153;
create policy "v153 team profile owner" on public.nostra_team_profiles_v153 for all to authenticated using (owner_user_id=auth.uid() or public.nostra_v153_is_manager()) with check (owner_user_id=auth.uid() or public.nostra_v153_is_manager());
grant select,insert,update,delete on public.nostra_team_profiles_v153 to authenticated;

-- ---------------------------------------------------------------------------
-- 6. Statuts Nostra Cercle
-- ---------------------------------------------------------------------------
create table if not exists public.casino_status_tiers_v153 (
  id bigint generated by default as identity primary key,
  name text not null unique,
  min_wagered numeric(18,2) not null default 0,
  icon text not null default '◆',
  benefits text not null default '',
  sort_order integer not null default 0,
  enabled boolean not null default true,
  updated_at timestamptz not null default now()
);
insert into public.casino_status_tiers_v153(name,min_wagered,icon,benefits,sort_order)
values
 ('Membre',0,'♣','Accès au Cercle et à la caisse.',10),
 ('Bronze',250000,'◆','Badge Bronze et accès aux événements Bronze.',20),
 ('Argent',1000000,'◇','Accès prioritaire aux inscriptions du Cercle.',30),
 ('Or',5000000,'♛','Avantages et événements privés Or.',40),
 ('Platine',15000000,'✦','Priorité haute sur les événements privés.',50),
 ('Black',50000000,'◈','Statut Black et invitations premium.',60),
 ('VIP',100000000,'👑','Statut VIP du Cercle et accès aux opérations très privées.',70)
on conflict(name) do nothing;
alter table public.casino_status_tiers_v153 enable row level security;
drop policy if exists "v153 casino tiers read" on public.casino_status_tiers_v153;
create policy "v153 casino tiers read" on public.casino_status_tiers_v153 for select to authenticated using (enabled or public.nostra_v153_is_manager());
drop policy if exists "v153 casino tiers manage" on public.casino_status_tiers_v153;
create policy "v153 casino tiers manage" on public.casino_status_tiers_v153 for all to authenticated using (public.nostra_v153_is_manager()) with check (public.nostra_v153_is_manager());
grant select,insert,update,delete on public.casino_status_tiers_v153 to authenticated;
grant usage,select on sequence public.casino_status_tiers_v153_id_seq to authenticated;

-- ---------------------------------------------------------------------------
-- 7. Billetterie globale Nostra
-- ---------------------------------------------------------------------------
create table if not exists public.nostra_ticket_events_v153 (
  id uuid primary key default gen_random_uuid(),
  pole text not null default 'group' check (pole in ('group','motors','circuit','cercle','academy','events')),
  title text not null,
  description text not null default '',
  location text not null default '',
  starts_at timestamptz not null,
  ends_at timestamptz,
  ticket_price numeric(14,2) not null default 0 check(ticket_price>=0),
  capacity integer,
  sales_open boolean not null default false,
  published boolean not null default false,
  created_at timestamptz not null default now(),
  created_by uuid references auth.users(id) on delete set null,
  updated_at timestamptz not null default now()
);
create table if not exists public.nostra_ticket_orders_v153 (
  id uuid primary key default gen_random_uuid(),
  ticket_event_id uuid not null references public.nostra_ticket_events_v153(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  ticket_number text not null unique,
  quantity integer not null default 1 check(quantity>0 and quantity<=20),
  unit_price numeric(14,2) not null,
  discount_amount numeric(14,2) not null default 0,
  total numeric(14,2) not null,
  status text not null default 'paid' check(status in ('paid','cancelled','used','refunded')),
  qr_code text not null unique default upper(substr(replace(gen_random_uuid()::text,'-',''),1,16)),
  purchased_at timestamptz not null default now(),
  used_at timestamptz
);
create index if not exists nostra_ticket_orders_v153_user_idx on public.nostra_ticket_orders_v153(user_id,purchased_at desc);
alter table public.nostra_ticket_events_v153 enable row level security;
alter table public.nostra_ticket_orders_v153 enable row level security;
drop policy if exists "v153 ticket events read" on public.nostra_ticket_events_v153;
create policy "v153 ticket events read" on public.nostra_ticket_events_v153 for select to authenticated using (published or public.nostra_v153_is_manager());
drop policy if exists "v153 ticket events manage" on public.nostra_ticket_events_v153;
create policy "v153 ticket events manage" on public.nostra_ticket_events_v153 for all to authenticated using (public.nostra_v153_is_manager()) with check(public.nostra_v153_is_manager());
drop policy if exists "v153 ticket orders own" on public.nostra_ticket_orders_v153;
create policy "v153 ticket orders own" on public.nostra_ticket_orders_v153 for select to authenticated using (user_id=auth.uid() or public.nostra_v153_is_manager());
drop policy if exists "v153 ticket orders insert" on public.nostra_ticket_orders_v153;
-- Les billets sont créés uniquement par l'action serveur sécurisée après débit RP.
drop policy if exists "v153 ticket orders staff update" on public.nostra_ticket_orders_v153;
create policy "v153 ticket orders staff update" on public.nostra_ticket_orders_v153 for update to authenticated using(public.nostra_v153_is_manager()) with check(public.nostra_v153_is_manager());
grant select,insert,update,delete on public.nostra_ticket_events_v153 to authenticated;
revoke insert on public.nostra_ticket_orders_v153 from authenticated;
grant select,update,delete on public.nostra_ticket_orders_v153 to authenticated;

-- ---------------------------------------------------------------------------
-- 7B. Motifs de rendez-vous Nostra Motors étendus
-- ---------------------------------------------------------------------------
do $$
begin
  if to_regclass('public.motors_appointments') is not null then
    alter table public.motors_appointments drop constraint if exists motors_appointments_appointment_type_check;
    alter table public.motors_appointments drop constraint if exists motors_appointments_type_check;
    alter table public.motors_appointments add constraint motors_appointments_appointment_type_check
      check (appointment_type in ('showroom','test_drive','purchase','pickup','paint','plate','sav','financing','trade_in','consignment','search_mandate','other'));
  end if;
end $$;

-- ---------------------------------------------------------------------------
-- 8. Centre de notifications enrichi
-- ---------------------------------------------------------------------------
do $$
begin
  if to_regclass('public.user_notifications') is not null then
    alter table public.user_notifications add column if not exists priority text not null default 'normal';
    alter table public.user_notifications add column if not exists category text not null default 'general';
    alter table public.user_notifications add column if not exists archived_at timestamptz;
    alter table public.user_notifications drop constraint if exists user_notifications_type_check;
    alter table public.user_notifications drop constraint if exists user_notifications_notification_type_check;
    alter table public.user_notifications add constraint user_notifications_type_check check(notification_type in(
      'order','event','championship','homologation','team','reservation','invoice','loyalty','general','mail',
      'appointment','ticket','contract','promo','casino','maintenance','academy'
    ));
  end if;
end $$;

create or replace function public.nostra_v153_notify_order_progress()
returns trigger language plpgsql security definer set search_path=public as $$
declare v_uid uuid; v_number text; v_label text;
begin
  select user_id,order_number into v_uid,v_number from public.orders where id=new.order_id;
  v_label := case new.stage
    when 'received' then 'Commande reçue' when 'confirmed' then 'Commande confirmée'
    when 'preparing' then 'Préparation du véhicule' when 'paint' then 'Passage en peinture'
    when 'plate' then 'Installation de la nouvelle plaque' when 'quality' then 'Contrôle qualité'
    when 'ready' then 'Véhicule prêt en concession' when 'collected' then 'Véhicule récupéré'
    when 'cancelled' then 'Commande annulée' else 'Mise à jour de commande' end;
  if to_regclass('public.user_notifications') is not null then
    insert into public.user_notifications(user_id,notification_type,title,message,target_url,source_type,source_id,priority,category)
    values(v_uid,'order',v_label,'La commande '||coalesce(v_number,new.order_id::text)||' est maintenant à '||new.progress_percent||' %.','/profil/commandes','order_progress',new.order_id::text,case when new.stage='ready' then 'high' else 'normal' end,'motors');
  end if;
  return new;
end $$;
drop trigger if exists nostra_v153_notify_order_progress on public.order_progress_v153;
create trigger nostra_v153_notify_order_progress after update of stage,progress_percent on public.order_progress_v153 for each row
when (old.stage is distinct from new.stage or old.progress_percent is distinct from new.progress_percent)
execute function public.nostra_v153_notify_order_progress();

create or replace function public.nostra_v153_notify_appointment_status()
returns trigger language plpgsql security definer set search_path=public as $$
declare v_label text; v_message text;
begin
  if old.status is not distinct from new.status then return new; end if;
  v_label := case new.status
    when 'confirmed' then 'Rendez-vous Nostra Motors confirmé'
    when 'declined' then 'Rendez-vous Nostra Motors refusé'
    when 'completed' then 'Rendez-vous Nostra Motors terminé'
    when 'cancelled' then 'Rendez-vous Nostra Motors annulé'
    else 'Mise à jour de votre rendez-vous' end;
  v_message := coalesce(nullif(new.direction_note,''),'Votre demande de rendez-vous a été mise à jour par Nostra Motors.');
  if to_regclass('public.user_notifications') is not null and new.user_id is not null then
    insert into public.user_notifications(user_id,notification_type,title,message,target_url,source_type,source_id,priority,category)
    values(new.user_id,'appointment',v_label,v_message,'/motors/rendez-vous','motors_appointment',new.id::text,case when new.status='confirmed' then 'high' else 'normal' end,'motors');
  end if;
  return new;
end $$;
drop trigger if exists nostra_v153_notify_appointment_status on public.motors_appointments;
create trigger nostra_v153_notify_appointment_status after update of status on public.motors_appointments
for each row execute function public.nostra_v153_notify_appointment_status();

-- ---------------------------------------------------------------------------
-- 9. Sauvegardes / restaurations de configuration
-- ---------------------------------------------------------------------------
create table if not exists public.nostra_backups_v153 (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  scope text not null default 'configuration',
  snapshot jsonb not null,
  created_at timestamptz not null default now(),
  created_by uuid references auth.users(id) on delete set null
);
alter table public.nostra_backups_v153 enable row level security;
drop policy if exists "v153 backups manager" on public.nostra_backups_v153;
create policy "v153 backups manager" on public.nostra_backups_v153 for all to authenticated using(public.nostra_v153_is_manager()) with check(public.nostra_v153_is_manager());
grant select,insert,delete on public.nostra_backups_v153 to authenticated;

create or replace function public.nostra_v153_table_snapshot(p_table text)
returns jsonb language plpgsql security definer set search_path=public as $$
declare v_data jsonb;
begin
  if not public.nostra_v153_is_manager() then raise exception using message='forbidden'; end if;
  if p_table not in ('site_pages','custom_circuit_pages','hidden_circuit_pages','circuit_settings','motors_settings','catalog_vehicles','events','casino_settings','casino_cashier_packages_v148','nostra_promo_codes_v153','casino_status_tiers_v153','nostra_pole_maintenance_v153','nostra_ticket_events_v153') then
    raise exception using message='table_not_allowed';
  end if;
  if to_regclass('public.'||p_table) is null then return '[]'::jsonb; end if;
  execute format('select coalesce(jsonb_agg(to_jsonb(t)),''[]''::jsonb) from public.%I t',p_table) into v_data;
  return coalesce(v_data,'[]'::jsonb);
end $$;

create or replace function public.nostra_v153_restore_table_snapshot(p_table text, p_data jsonb)
returns void language plpgsql security definer set search_path=public as $$
declare
  v_cols text;
  v_select_cols text;
  v_pk text;
  v_updates text;
  v_sql text;
begin
  if p_table not in ('site_pages','custom_circuit_pages','hidden_circuit_pages','circuit_settings','motors_settings','catalog_vehicles','events','casino_settings','casino_cashier_packages_v148','nostra_promo_codes_v153','casino_status_tiers_v153','nostra_pole_maintenance_v153','nostra_ticket_events_v153') then
    raise exception using message='table_not_allowed';
  end if;
  if to_regclass('public.'||p_table) is null or coalesce(jsonb_array_length(coalesce(p_data,'[]'::jsonb)),0)=0 then return; end if;

  select string_agg(format('%I',a.attname),',' order by a.attnum),
         string_agg(format('r.%I',a.attname),',' order by a.attnum)
    into v_cols,v_select_cols
  from pg_attribute a
  where a.attrelid=to_regclass('public.'||p_table) and a.attnum>0 and not a.attisdropped and a.attgenerated='';

  select string_agg(format('%I',a.attname),',' order by x.ord)
    into v_pk
  from pg_index i
  cross join lateral unnest(i.indkey) with ordinality as x(attnum,ord)
  join pg_attribute a on a.attrelid=i.indrelid and a.attnum=x.attnum
  where i.indrelid=to_regclass('public.'||p_table) and i.indisprimary;

  if v_pk is null then raise exception using message='missing_primary_key'; end if;

  select string_agg(format('%1$I=excluded.%1$I',a.attname),',' order by a.attnum)
    into v_updates
  from pg_attribute a
  where a.attrelid=to_regclass('public.'||p_table) and a.attnum>0 and not a.attisdropped and a.attgenerated=''
    and not (a.attname = any(string_to_array(replace(v_pk,'"',''),',')));

  v_sql := format('insert into public.%I (%s) select %s from jsonb_populate_recordset(null::public.%I,$1) r on conflict (%s) do %s',
    p_table,v_cols,v_select_cols,p_table,v_pk,case when coalesce(v_updates,'')='' then 'nothing' else 'update set '||v_updates end);
  execute v_sql using p_data;
end $$;
revoke all on function public.nostra_v153_restore_table_snapshot(text,jsonb) from public, anon, authenticated;

create or replace function public.nostra_create_backup_v153(p_name text)
returns uuid language plpgsql security definer set search_path=public as $$
declare v_id uuid; v_snapshot jsonb;
begin
  if not public.nostra_v153_is_manager() then raise exception using message='forbidden'; end if;
  v_snapshot := jsonb_build_object(
    'version','V153','created_at',now(),
    'site_pages',public.nostra_v153_table_snapshot('site_pages'),
    'custom_circuit_pages',public.nostra_v153_table_snapshot('custom_circuit_pages'),
    'hidden_circuit_pages',public.nostra_v153_table_snapshot('hidden_circuit_pages'),
    'circuit_settings',public.nostra_v153_table_snapshot('circuit_settings'),
    'motors_settings',public.nostra_v153_table_snapshot('motors_settings'),
    'catalog_vehicles',public.nostra_v153_table_snapshot('catalog_vehicles'),
    'events',public.nostra_v153_table_snapshot('events'),
    'casino_settings',public.nostra_v153_table_snapshot('casino_settings'),
    'casino_cashier_packages_v148',public.nostra_v153_table_snapshot('casino_cashier_packages_v148'),
    'promo_codes',public.nostra_v153_table_snapshot('nostra_promo_codes_v153'),
    'casino_status_tiers',public.nostra_v153_table_snapshot('casino_status_tiers_v153'),
    'maintenance',public.nostra_v153_table_snapshot('nostra_pole_maintenance_v153'),
    'ticket_events',public.nostra_v153_table_snapshot('nostra_ticket_events_v153')
  );
  insert into public.nostra_backups_v153(name,snapshot,created_by) values(coalesce(nullif(btrim(p_name),''),'Sauvegarde '||to_char(now(),'DD/MM/YYYY HH24:MI')),v_snapshot,auth.uid()) returning id into v_id;
  return v_id;
end $$;
grant execute on function public.nostra_create_backup_v153(text) to authenticated;

create or replace function public.nostra_restore_backup_v153(p_backup_id uuid)
returns boolean language plpgsql security definer set search_path=public as $$
declare v jsonb;
begin
  if not public.nostra_v153_is_manager() then raise exception using message='forbidden'; end if;
  select snapshot into v from public.nostra_backups_v153 where id=p_backup_id;
  if v is null then raise exception using message='backup_not_found'; end if;

  -- Filet de sécurité : l'état courant est sauvegardé automatiquement avant toute restauration.
  perform public.nostra_create_backup_v153('Sauvegarde automatique avant restauration '||to_char(now(),'DD/MM/YYYY HH24:MI'));

  -- Restauration non destructive : les lignes présentes dans le snapshot sont réappliquées,
  -- mais aucune commande, transaction, citoyen, licence, billet vendu ou historique n'est supprimé.
  perform public.nostra_v153_restore_table_snapshot('site_pages',coalesce(v->'site_pages','[]'::jsonb));
  perform public.nostra_v153_restore_table_snapshot('custom_circuit_pages',coalesce(v->'custom_circuit_pages','[]'::jsonb));
  perform public.nostra_v153_restore_table_snapshot('hidden_circuit_pages',coalesce(v->'hidden_circuit_pages','[]'::jsonb));
  perform public.nostra_v153_restore_table_snapshot('circuit_settings',coalesce(v->'circuit_settings','[]'::jsonb));
  perform public.nostra_v153_restore_table_snapshot('motors_settings',coalesce(v->'motors_settings','[]'::jsonb));
  perform public.nostra_v153_restore_table_snapshot('catalog_vehicles',coalesce(v->'catalog_vehicles','[]'::jsonb));
  perform public.nostra_v153_restore_table_snapshot('events',coalesce(v->'events','[]'::jsonb));
  perform public.nostra_v153_restore_table_snapshot('casino_settings',coalesce(v->'casino_settings','[]'::jsonb));
  perform public.nostra_v153_restore_table_snapshot('casino_cashier_packages_v148',coalesce(v->'casino_cashier_packages_v148','[]'::jsonb));
  perform public.nostra_v153_restore_table_snapshot('nostra_promo_codes_v153',coalesce(v->'promo_codes','[]'::jsonb));
  perform public.nostra_v153_restore_table_snapshot('casino_status_tiers_v153',coalesce(v->'casino_status_tiers','[]'::jsonb));
  perform public.nostra_v153_restore_table_snapshot('nostra_pole_maintenance_v153',coalesce(v->'maintenance','[]'::jsonb));
  perform public.nostra_v153_restore_table_snapshot('nostra_ticket_events_v153',coalesce(v->'ticket_events','[]'::jsonb));
  return true;
end $$;
grant execute on function public.nostra_restore_backup_v153(uuid) to authenticated;

-- ---------------------------------------------------------------------------
-- 10. Permissions pratiques
-- ---------------------------------------------------------------------------
-- Le SQL est prévu pour être exécuté après les migrations existantes.
-- Les séquences et tables V153 sont désormais disponibles au site.
