-- NOSTRA GROUP — V125
-- Financement 3x / 4x pour les véhicules strictement supérieurs à 500 000 €.
-- Apport obligatoire de 30 %, frais automatiques et décision réservée au Gérant.
-- Script réexécutable : il ne supprime aucun dossier, paiement ou commande existant.

begin;

-- ---------------------------------------------------------------------------
-- 1. Accès Gérant
-- ---------------------------------------------------------------------------

create or replace function public.nostra_is_manager_v125()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select auth.uid() is not null
    and (
      coalesce(
        auth.jwt() -> 'user_metadata' ->> 'provider_id',
        auth.jwt() -> 'user_metadata' ->> 'discord_id',
        auth.jwt() -> 'user_metadata' ->> 'sub'
      ) = '331843410962939908'
      or exists (
        select 1
        from public.member_profiles profile
        where profile.user_id = auth.uid()
          and (
            lower(coalesce(to_jsonb(profile) ->> 'role', ''))
              in ('manager', 'gerant', 'direction', 'administrator', 'admin')
            or lower(coalesce((to_jsonb(profile) -> 'roles')::text, ''))
              ~ '(manager|gerant|direction|administrator|admin)'
          )
      )
    );
$$;

-- ---------------------------------------------------------------------------
-- 2. Réglages fixes et frais configurables
-- ---------------------------------------------------------------------------

create table if not exists public.vehicle_financing_settings (
  id boolean primary key default true check (id = true),
  enabled boolean not null default true,
  three_times_enabled boolean not null default true,
  four_times_enabled boolean not null default true,
  minimum_vehicle_price numeric(14,2) not null default 500000
    check (minimum_vehicle_price = 500000),
  down_payment_percent numeric(5,2) not null default 30
    check (down_payment_percent = 30),
  three_times_fee_percent numeric(5,2) not null default 6
    check (three_times_fee_percent between 0 and 50),
  four_times_fee_percent numeric(5,2) not null default 9
    check (four_times_fee_percent between 0 and 50),
  installment_interval_days integer not null default 30
    check (installment_interval_days between 1 and 365),
  updated_by uuid references auth.users(id) on delete set null,
  updated_at timestamptz not null default now()
);

insert into public.vehicle_financing_settings (id)
values (true)
on conflict (id) do nothing;

-- ---------------------------------------------------------------------------
-- 3. Dossiers et échéances
-- ---------------------------------------------------------------------------

create table if not exists public.vehicle_financing_applications (
  id bigint generated by default as identity primary key,
  application_number text not null unique,
  user_id uuid not null references auth.users(id) on delete cascade,
  steam_id text,
  vehicle_id bigint not null references public.catalog_vehicles(id) on delete restrict,
  customer_name text not null,
  customer_phone text,
  vehicle_name text not null,
  catalog_type text not null default 'standard',
  vehicle_price numeric(14,2) not null check (vehicle_price > 500000),
  term_count integer not null check (term_count in (3, 4)),
  down_payment_percent numeric(5,2) not null default 30 check (down_payment_percent = 30),
  down_payment_amount numeric(14,2) not null check (down_payment_amount > 0),
  financed_principal numeric(14,2) not null check (financed_principal > 0),
  fee_percent numeric(5,2) not null check (fee_percent between 0 and 50),
  fee_amount numeric(14,2) not null check (fee_amount >= 0),
  financed_total numeric(14,2) not null check (financed_total > 0),
  delivery_mode text not null default 'showroom' check (delivery_mode in ('showroom', 'home')),
  delivery_fee numeric(14,2) not null default 0 check (delivery_fee >= 0),
  delivery_address text,
  delivery_phone text,
  customer_note text,
  status text not null default 'pending_review'
    check (status in ('pending_review', 'deposit_due', 'active', 'completed', 'rejected', 'cancelled')),
  review_note text,
  reviewed_by uuid references auth.users(id) on delete set null,
  bank_balance_at_review numeric(16,2),
  bank_checked_at timestamptz,
  reviewed_at timestamptz,
  deposit_due_at timestamptz,
  deposit_paid_at timestamptz,
  completed_at timestamptz,
  stock_reserved boolean not null default false,
  final_order_id bigint references public.orders(id) on delete set null,
  final_order_number text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.vehicle_financing_installments (
  id bigint generated by default as identity primary key,
  application_id bigint not null references public.vehicle_financing_applications(id) on delete cascade,
  installment_number integer not null check (installment_number between 1 and 4),
  amount numeric(14,2) not null check (amount > 0),
  due_at timestamptz not null,
  status text not null default 'pending' check (status in ('pending', 'paid', 'cancelled')),
  paid_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (application_id, installment_number)
);

create unique index if not exists vehicle_financing_active_user_vehicle_v125_uq
  on public.vehicle_financing_applications (user_id, vehicle_id)
  where status in ('pending_review', 'deposit_due', 'active');
create index if not exists vehicle_financing_status_v125_idx
  on public.vehicle_financing_applications (status, created_at desc);
create index if not exists vehicle_financing_user_v125_idx
  on public.vehicle_financing_applications (user_id, created_at desc);
create index if not exists vehicle_financing_installments_due_v125_idx
  on public.vehicle_financing_installments (status, due_at);

-- ---------------------------------------------------------------------------
-- 4. Lignes de paiement dans le panier existant
-- ---------------------------------------------------------------------------

alter table public.cart_items add column if not exists financing_application_id bigint;
alter table public.cart_items add column if not exists financing_installment_id bigint;

do $$
declare constraint_row record;
begin
  for constraint_row in
    select conname
    from pg_constraint
    where conrelid = 'public.cart_items'::regclass
      and contype = 'c'
      and pg_get_constraintdef(oid) ilike '%item_type%'
  loop
    execute format('alter table public.cart_items drop constraint if exists %I', constraint_row.conname);
  end loop;
end;
$$;

alter table public.cart_items
  add constraint cart_items_item_type_v125_check
  check (item_type in (
    'vehicle', 'delivery', 'reservation_deposit', 'reservation_balance',
    'financing_deposit', 'financing_installment'
  )) not valid;
alter table public.cart_items validate constraint cart_items_item_type_v125_check;

do $$
begin
  if exists (
    select 1 from pg_constraint
    where conname = 'cart_items_financing_application_id_fkey'
      and conrelid = 'public.cart_items'::regclass
  ) then
    alter table public.cart_items drop constraint cart_items_financing_application_id_fkey;
  end if;
  alter table public.cart_items
    add constraint cart_items_financing_application_id_fkey
    foreign key (financing_application_id)
    references public.vehicle_financing_applications(id)
    on delete cascade;

  if exists (
    select 1 from pg_constraint
    where conname = 'cart_items_financing_installment_id_fkey'
      and conrelid = 'public.cart_items'::regclass
  ) then
    alter table public.cart_items drop constraint cart_items_financing_installment_id_fkey;
  end if;
  alter table public.cart_items
    add constraint cart_items_financing_installment_id_fkey
    foreign key (financing_installment_id)
    references public.vehicle_financing_installments(id)
    on delete cascade;
end;
$$;

create index if not exists cart_items_financing_v125_idx
  on public.cart_items (user_id, financing_application_id, item_type);

-- ---------------------------------------------------------------------------
-- 5. Sécurité : un citoyen ne voit que ses dossiers, le Gérant voit tout
-- ---------------------------------------------------------------------------

alter table public.vehicle_financing_settings enable row level security;
alter table public.vehicle_financing_applications enable row level security;
alter table public.vehicle_financing_installments enable row level security;

drop policy if exists "financing settings readable v125" on public.vehicle_financing_settings;
create policy "financing settings readable v125"
  on public.vehicle_financing_settings for select to authenticated using (true);

drop policy if exists "financing owner reads v125" on public.vehicle_financing_applications;
create policy "financing owner reads v125"
  on public.vehicle_financing_applications for select to authenticated
  using (user_id = auth.uid());
drop policy if exists "financing manager manages v125" on public.vehicle_financing_applications;
create policy "financing manager manages v125"
  on public.vehicle_financing_applications for all to authenticated
  using (public.nostra_is_manager_v125())
  with check (public.nostra_is_manager_v125());

drop policy if exists "financing installment owner reads v125" on public.vehicle_financing_installments;
create policy "financing installment owner reads v125"
  on public.vehicle_financing_installments for select to authenticated
  using (exists (
    select 1 from public.vehicle_financing_applications application
    where application.id = application_id and application.user_id = auth.uid()
  ));
drop policy if exists "financing installment manager manages v125" on public.vehicle_financing_installments;
create policy "financing installment manager manages v125"
  on public.vehicle_financing_installments for all to authenticated
  using (public.nostra_is_manager_v125())
  with check (public.nostra_is_manager_v125());

revoke all on public.vehicle_financing_settings from public, anon;
revoke all on public.vehicle_financing_applications from public, anon;
revoke all on public.vehicle_financing_installments from public, anon;
grant select on public.vehicle_financing_settings to authenticated;
grant select on public.vehicle_financing_applications to authenticated;
grant select on public.vehicle_financing_installments to authenticated;

-- ---------------------------------------------------------------------------
-- 6. Réglages du Gérant
-- ---------------------------------------------------------------------------

create or replace function public.update_vehicle_financing_settings_v125(
  p_enabled boolean,
  p_three_times_enabled boolean,
  p_four_times_enabled boolean,
  p_three_times_fee_percent numeric,
  p_four_times_fee_percent numeric,
  p_installment_interval_days integer
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.nostra_is_manager_v125() then
    raise exception using message = 'manager_required';
  end if;
  if p_three_times_fee_percent not between 0 and 50
     or p_four_times_fee_percent not between 0 and 50
     or p_installment_interval_days not between 1 and 365 then
    raise exception using message = 'invalid_financing_settings';
  end if;

  update public.vehicle_financing_settings
  set enabled = coalesce(p_enabled, false),
      three_times_enabled = coalesce(p_three_times_enabled, false),
      four_times_enabled = coalesce(p_four_times_enabled, false),
      three_times_fee_percent = p_three_times_fee_percent,
      four_times_fee_percent = p_four_times_fee_percent,
      installment_interval_days = p_installment_interval_days,
      updated_by = auth.uid(),
      updated_at = now()
  where id = true;

  return jsonb_build_object('status', 'saved');
end;
$$;

-- ---------------------------------------------------------------------------
-- 7. Dépôt du dossier par le citoyen
-- ---------------------------------------------------------------------------

create or replace function public.submit_vehicle_financing_v125(
  p_vehicle_id bigint,
  p_term_count integer,
  p_delivery_mode text,
  p_delivery_address text default null,
  p_delivery_phone text default null,
  p_customer_name text default null,
  p_customer_phone text default null,
  p_customer_note text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_settings public.vehicle_financing_settings%rowtype;
  v_vehicle public.catalog_vehicles%rowtype;
  v_application_id bigint;
  v_application_number text;
  v_steam_id text;
  v_vehicle_price numeric(14,2);
  v_down_payment numeric(14,2);
  v_principal numeric(14,2);
  v_fee_percent numeric(5,2);
  v_fee numeric(14,2);
  v_financed_total numeric(14,2);
  v_delivery_fee numeric(14,2) := 0;
begin
  if v_user_id is null then raise exception using message = 'not_authenticated'; end if;
  if p_term_count not in (3, 4) then raise exception using message = 'invalid_financing_term'; end if;
  if coalesce(p_delivery_mode, '') not in ('showroom', 'home') then
    raise exception using message = 'invalid_delivery_mode';
  end if;

  select * into v_settings from public.vehicle_financing_settings where id = true;
  if not found or not v_settings.enabled then raise exception using message = 'financing_disabled'; end if;
  if (p_term_count = 3 and not v_settings.three_times_enabled)
     or (p_term_count = 4 and not v_settings.four_times_enabled) then
    raise exception using message = 'financing_term_disabled';
  end if;

  select * into v_vehicle
  from public.catalog_vehicles
  where id = p_vehicle_id and published = true
  for share;
  if not found then raise exception using message = 'vehicle_unavailable'; end if;
  if greatest(coalesce(v_vehicle.stock_quantity, 0), 0) <= 0 then
    raise exception using message = 'insufficient_stock';
  end if;
  if coalesce(to_jsonb(v_vehicle) ->> 'sale_enabled', 'true') = 'false' then
    raise exception using message = 'vehicle_sale_disabled';
  end if;
  if coalesce(to_jsonb(v_vehicle) ->> 'catalog_type', 'standard') = 'heavy'
     and p_delivery_mode = 'home' then
    raise exception using message = 'heavy_home_delivery_disabled';
  end if;
  if coalesce(to_jsonb(v_vehicle) ->> 'catalog_type', 'standard') = 'used'
     and coalesce(to_jsonb(v_vehicle) ->> 'used_vehicle_status', 'available') <> 'available' then
    raise exception using message = 'used_vehicle_unavailable';
  end if;
  if p_delivery_mode = 'home' and length(btrim(coalesce(p_delivery_address, ''))) < 5 then
    raise exception using message = 'invalid_delivery_address';
  end if;
  if p_delivery_mode = 'home' and length(btrim(coalesce(p_delivery_phone, ''))) < 3 then
    raise exception using message = 'invalid_delivery_phone';
  end if;

  v_vehicle_price := round(greatest(coalesce(v_vehicle.price, 0), 0), 2);
  if v_vehicle_price <= v_settings.minimum_vehicle_price then
    raise exception using message = 'financing_minimum_price';
  end if;
  if exists (
    select 1 from public.vehicle_financing_applications
    where user_id = v_user_id and vehicle_id = p_vehicle_id
      and status in ('pending_review', 'deposit_due', 'active')
  ) then
    raise exception using message = 'financing_already_exists';
  end if;

  select nullif(btrim(coalesce(to_jsonb(profile) ->> 'steam_id', '')), '')
  into v_steam_id
  from public.member_profiles profile
  where profile.user_id = v_user_id;
  v_steam_id := coalesce(
    v_steam_id,
    nullif(btrim(coalesce(auth.jwt() -> 'user_metadata' ->> 'steam_id', '')), '')
  );
  if v_steam_id is null then raise exception using message = 'steam_identity_required'; end if;

  v_down_payment := round(v_vehicle_price * 0.30, 2);
  v_principal := round(v_vehicle_price - v_down_payment, 2);
  v_fee_percent := case when p_term_count = 3 then v_settings.three_times_fee_percent else v_settings.four_times_fee_percent end;
  v_fee := round(v_principal * v_fee_percent / 100, 2);
  v_financed_total := round(v_principal + v_fee, 2);
  v_delivery_fee := case when p_delivery_mode = 'home' then 75000 else 0 end;
  v_application_number := 'NF-' || to_char(clock_timestamp(), 'YYYYMMDD') || '-' || upper(substr(md5(random()::text || clock_timestamp()::text || v_user_id::text), 1, 7));

  insert into public.vehicle_financing_applications (
    application_number, user_id, steam_id, vehicle_id, customer_name,
    customer_phone, vehicle_name, catalog_type, vehicle_price, term_count,
    down_payment_percent, down_payment_amount, financed_principal, fee_percent,
    fee_amount, financed_total, delivery_mode, delivery_fee, delivery_address,
    delivery_phone, customer_note, status, updated_at
  ) values (
    v_application_number, v_user_id, left(v_steam_id, 80), p_vehicle_id,
    coalesce(nullif(btrim(coalesce(p_customer_name, '')), ''), 'Client Nostra Motors'),
    nullif(left(btrim(coalesce(p_customer_phone, '')), 40), ''),
    btrim(v_vehicle.brand || ' ' || v_vehicle.model),
    coalesce(to_jsonb(v_vehicle) ->> 'catalog_type', 'standard'),
    v_vehicle_price, p_term_count, 30, v_down_payment, v_principal,
    v_fee_percent, v_fee, v_financed_total, p_delivery_mode, v_delivery_fee,
    case when p_delivery_mode = 'home' then btrim(p_delivery_address) else null end,
    nullif(left(btrim(coalesce(p_delivery_phone, '')), 40), ''),
    nullif(left(btrim(coalesce(p_customer_note, '')), 1500), ''),
    'pending_review', now()
  ) returning id into v_application_id;

  return jsonb_build_object(
    'application_id', v_application_id,
    'application_number', v_application_number,
    'status', 'pending_review',
    'down_payment_amount', v_down_payment,
    'fee_amount', v_fee,
    'financed_total', v_financed_total
  );
exception
  when unique_violation then
    raise exception using message = 'financing_already_exists';
end;
$$;

-- ---------------------------------------------------------------------------
-- 8. Décision du Gérant et création de l'apport obligatoire
-- ---------------------------------------------------------------------------

create or replace function public.review_vehicle_financing_v125(
  p_application_id bigint,
  p_decision text,
  p_review_note text default null,
  p_bank_balance numeric default null,
  p_bank_checked_at timestamptz default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_application public.vehicle_financing_applications%rowtype;
  v_vehicle public.catalog_vehicles%rowtype;
  v_image_url text;
  v_initial_payment numeric(14,2);
begin
  if not public.nostra_is_manager_v125() then raise exception using message = 'manager_required'; end if;
  if coalesce(p_decision, '') not in ('approve', 'reject') then raise exception using message = 'invalid_decision'; end if;
  if p_decision = 'reject' and length(btrim(coalesce(p_review_note, ''))) < 2 then
    raise exception using message = 'review_note_required';
  end if;

  select * into v_application
  from public.vehicle_financing_applications
  where id = p_application_id
  for update;
  if not found then raise exception using message = 'financing_not_found'; end if;
  if v_application.status <> 'pending_review' then raise exception using message = 'financing_not_pending'; end if;

  if p_decision = 'reject' then
    update public.vehicle_financing_applications
    set status = 'rejected',
        review_note = nullif(btrim(coalesce(p_review_note, '')), ''),
        reviewed_by = auth.uid(),
        reviewed_at = now(),
        bank_balance_at_review = p_bank_balance,
        bank_checked_at = p_bank_checked_at,
        updated_at = now()
    where id = v_application.id;
    return jsonb_build_object('status', 'rejected');
  end if;

  select * into v_vehicle
  from public.catalog_vehicles
  where id = v_application.vehicle_id and published = true
  for update;
  if not found then raise exception using message = 'vehicle_unavailable'; end if;
  if coalesce(v_vehicle.stock_quantity, 0) <= 0 then raise exception using message = 'insufficient_stock'; end if;
  if coalesce(to_jsonb(v_vehicle) ->> 'sale_enabled', 'true') = 'false' then
    raise exception using message = 'vehicle_sale_disabled';
  end if;

  update public.catalog_vehicles
  set stock_quantity = stock_quantity - 1, updated_at = now()
  where id = v_vehicle.id;

  v_image_url := case
    when jsonb_typeof(v_vehicle.images) = 'array' and jsonb_array_length(v_vehicle.images) > 0
    then v_vehicle.images -> 0 ->> 'url'
    else null
  end;
  v_initial_payment := v_application.down_payment_amount + v_application.delivery_fee;

  delete from public.cart_items
  where user_id = v_application.user_id
    and financing_application_id = v_application.id
    and item_type in ('financing_deposit', 'financing_installment');

  insert into public.cart_items (
    user_id, vehicle_id, related_vehicle_id, reservation_id,
    financing_application_id, financing_installment_id, item_type,
    delivery_mode, delivery_address, delivery_phone, item_name, quantity,
    unit_price, original_unit_price, image_url, locked
  ) values (
    v_application.user_id, v_application.vehicle_id, v_application.vehicle_id, null,
    v_application.id, null, 'financing_deposit', v_application.delivery_mode,
    v_application.delivery_address, v_application.delivery_phone,
    'Apport financement 30 % — ' || v_application.vehicle_name,
    1, v_initial_payment, v_application.vehicle_price, v_image_url, true
  );

  update public.vehicle_financing_applications
  set status = 'deposit_due',
      review_note = nullif(btrim(coalesce(p_review_note, '')), ''),
      reviewed_by = auth.uid(),
      reviewed_at = now(),
      bank_balance_at_review = p_bank_balance,
      bank_checked_at = p_bank_checked_at,
      deposit_due_at = now() + interval '7 days',
      stock_reserved = true,
      updated_at = now()
  where id = v_application.id;

  return jsonb_build_object('status', 'deposit_due', 'amount', v_initial_payment);
end;
$$;

-- ---------------------------------------------------------------------------
-- 9. Paiement de l'apport puis des échéances successives
-- ---------------------------------------------------------------------------

create or replace function public.checkout_vehicle_financing_payment_v125(
  p_application_id bigint
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_application public.vehicle_financing_applications%rowtype;
  v_settings public.vehicle_financing_settings%rowtype;
  v_installment public.vehicle_financing_installments%rowtype;
  v_next public.vehicle_financing_installments%rowtype;
  v_vehicle public.catalog_vehicles%rowtype;
  v_number integer;
  v_regular_amount numeric(14,2);
  v_amount numeric(14,2);
  v_first_installment_id bigint;
  v_image_url text;
  v_order_id bigint;
  v_order_number text;
  v_items jsonb;
begin
  if v_user_id is null then raise exception using message = 'not_authenticated'; end if;
  select * into v_application
  from public.vehicle_financing_applications
  where id = p_application_id and user_id = v_user_id
  for update;
  if not found then raise exception using message = 'financing_not_found'; end if;

  select * into v_vehicle from public.catalog_vehicles where id = v_application.vehicle_id;
  if not found then raise exception using message = 'vehicle_unavailable'; end if;
  v_image_url := case
    when jsonb_typeof(v_vehicle.images) = 'array' and jsonb_array_length(v_vehicle.images) > 0
    then v_vehicle.images -> 0 ->> 'url'
    else null
  end;

  if v_application.status = 'deposit_due' then
    if not exists (
      select 1 from public.cart_items
      where user_id = v_user_id
        and financing_application_id = v_application.id
        and item_type = 'financing_deposit'
    ) then raise exception using message = 'financing_payment_missing'; end if;

    delete from public.cart_items
    where user_id = v_user_id
      and financing_application_id = v_application.id
      and item_type = 'financing_deposit';
    delete from public.vehicle_financing_installments where application_id = v_application.id;

    select * into v_settings from public.vehicle_financing_settings where id = true;
    v_regular_amount := round(v_application.financed_total / v_application.term_count, 2);
    for v_number in 1..v_application.term_count loop
      v_amount := case
        when v_number = v_application.term_count
        then round(v_application.financed_total - (v_regular_amount * (v_application.term_count - 1)), 2)
        else v_regular_amount
      end;
      insert into public.vehicle_financing_installments (
        application_id, installment_number, amount, due_at, status, updated_at
      ) values (
        v_application.id, v_number, v_amount,
        now() + make_interval(days => v_settings.installment_interval_days * v_number),
        'pending', now()
      ) returning id into v_first_installment_id;
      if v_number = 1 then
        insert into public.cart_items (
          user_id, vehicle_id, related_vehicle_id, reservation_id,
          financing_application_id, financing_installment_id, item_type,
          delivery_mode, delivery_address, delivery_phone, item_name, quantity,
          unit_price, original_unit_price, image_url, locked
        ) values (
          v_user_id, v_application.vehicle_id, v_application.vehicle_id, null,
          v_application.id, v_first_installment_id, 'financing_installment',
          v_application.delivery_mode, v_application.delivery_address,
          v_application.delivery_phone,
          'Échéance 1/' || v_application.term_count || ' — ' || v_application.vehicle_name,
          1, v_amount, v_application.vehicle_price, v_image_url, true
        );
      end if;
    end loop;

    update public.vehicle_financing_applications
    set status = 'active', deposit_paid_at = now(), updated_at = now()
    where id = v_application.id;
    return jsonb_build_object('payment_type', 'deposit', 'status', 'active');
  end if;

  if v_application.status <> 'active' then raise exception using message = 'financing_not_payable'; end if;
  select * into v_installment
  from public.vehicle_financing_installments
  where application_id = v_application.id and status = 'pending'
  order by installment_number
  limit 1
  for update;
  if not found then raise exception using message = 'financing_payment_missing'; end if;
  if not exists (
    select 1 from public.cart_items
    where user_id = v_user_id
      and financing_application_id = v_application.id
      and financing_installment_id = v_installment.id
      and item_type = 'financing_installment'
  ) then raise exception using message = 'financing_payment_missing'; end if;

  delete from public.cart_items
  where user_id = v_user_id
    and financing_application_id = v_application.id
    and financing_installment_id = v_installment.id
    and item_type = 'financing_installment';
  update public.vehicle_financing_installments
  set status = 'paid', paid_at = now(), updated_at = now()
  where id = v_installment.id;

  select * into v_next
  from public.vehicle_financing_installments
  where application_id = v_application.id and status = 'pending'
  order by installment_number
  limit 1;

  if found then
    insert into public.cart_items (
      user_id, vehicle_id, related_vehicle_id, reservation_id,
      financing_application_id, financing_installment_id, item_type,
      delivery_mode, delivery_address, delivery_phone, item_name, quantity,
      unit_price, original_unit_price, image_url, locked
    ) values (
      v_user_id, v_application.vehicle_id, v_application.vehicle_id, null,
      v_application.id, v_next.id, 'financing_installment',
      v_application.delivery_mode, v_application.delivery_address,
      v_application.delivery_phone,
      'Échéance ' || v_next.installment_number || '/' || v_application.term_count || ' — ' || v_application.vehicle_name,
      1, v_next.amount, v_application.vehicle_price, v_image_url, true
    );
    return jsonb_build_object(
      'payment_type', 'installment',
      'paid_installment', v_installment.installment_number,
      'next_installment', v_next.installment_number
    );
  end if;

  v_order_number := 'NFI-' || to_char(clock_timestamp(), 'YYYYMMDD') || '-' || upper(substr(md5(random()::text || clock_timestamp()::text || v_application.id::text), 1, 7));
  v_items := jsonb_build_array(jsonb_build_object(
    'item_type', 'vehicle',
    'vehicle_id', v_application.vehicle_id,
    'financing_application_id', v_application.id,
    'name', v_application.vehicle_name,
    'quantity', 1,
    'unit_price', v_application.vehicle_price,
    'deposit_paid', v_application.down_payment_amount,
    'financing_fees', v_application.fee_amount,
    'term_count', v_application.term_count,
    'image_url', v_image_url
  ));
  if v_application.delivery_mode = 'home' then
    v_items := v_items || jsonb_build_array(jsonb_build_object(
      'item_type', 'delivery',
      'vehicle_id', null,
      'related_vehicle_id', v_application.vehicle_id,
      'financing_application_id', v_application.id,
      'name', 'Livraison à domicile — ' || v_application.vehicle_name,
      'delivery_address', v_application.delivery_address,
      'delivery_phone', v_application.delivery_phone,
      'quantity', 1,
      'unit_price', v_application.delivery_fee,
      'image_url', null
    ));
  end if;

  insert into public.orders (
    user_id, order_number, customer_name, status, total, items,
    customer_note, stock_deducted, updated_at
  ) values (
    v_user_id, v_order_number, v_application.customer_name, 'pending',
    v_application.vehicle_price + v_application.fee_amount + v_application.delivery_fee,
    v_items,
    'Commande intégralement payée via le financement ' || v_application.application_number,
    true, now()
  ) returning id into v_order_id;

  update public.vehicle_financing_applications
  set status = 'completed', completed_at = now(), final_order_id = v_order_id,
      final_order_number = v_order_number, updated_at = now()
  where id = v_application.id;

  return jsonb_build_object(
    'payment_type', 'final_installment',
    'paid_installment', v_installment.installment_number,
    'order_number', v_order_number,
    'status', 'completed'
  );
end;
$$;

-- ---------------------------------------------------------------------------
-- 10. Permissions des fonctions et contrôle final
-- ---------------------------------------------------------------------------

revoke all on function public.nostra_is_manager_v125() from public, anon;
revoke all on function public.update_vehicle_financing_settings_v125(boolean,boolean,boolean,numeric,numeric,integer) from public, anon;
revoke all on function public.submit_vehicle_financing_v125(bigint,integer,text,text,text,text,text,text) from public, anon;
revoke all on function public.review_vehicle_financing_v125(bigint,text,text,numeric,timestamptz) from public, anon;
revoke all on function public.checkout_vehicle_financing_payment_v125(bigint) from public, anon;

grant execute on function public.nostra_is_manager_v125() to authenticated;
grant execute on function public.update_vehicle_financing_settings_v125(boolean,boolean,boolean,numeric,numeric,integer) to authenticated;
grant execute on function public.submit_vehicle_financing_v125(bigint,integer,text,text,text,text,text,text) to authenticated;
grant execute on function public.review_vehicle_financing_v125(bigint,text,text,numeric,timestamptz) to authenticated;
grant execute on function public.checkout_vehicle_financing_payment_v125(bigint) to authenticated;

commit;

select
  'V125 prête · financement 3x/4x avec apport 30 %' as resultat,
  to_regclass('public.vehicle_financing_applications') is not null as dossiers,
  to_regclass('public.vehicle_financing_installments') is not null as echeances,
  to_regprocedure('public.submit_vehicle_financing_v125(bigint,integer,text,text,text,text,text,text)') is not null as depot_securise,
  to_regprocedure('public.review_vehicle_financing_v125(bigint,text,text,numeric,timestamptz)') is not null as decision_gerant;
