-- Nostra Group V143
-- Nostra Racing Academy : questionnaires théoriques par formation.
-- Prérequis : V137 Academy + correctifs V140/V142 recommandés.

begin;

-- ---------------------------------------------------------------------------
-- 1. CONFIGURATION DES QUESTIONNAIRES
-- ---------------------------------------------------------------------------

create table if not exists public.academy_quizzes_v143 (
  id bigint generated by default as identity primary key,
  course_id bigint not null unique references public.academy_courses_v137(id) on delete cascade,
  title text not null,
  instructions text,
  pass_score numeric(5,2) not null default 70 check (pass_score between 0 and 100),
  max_attempts integer not null default 3 check (max_attempts between 1 and 20),
  time_limit_minutes integer not null default 20 check (time_limit_minutes between 0 and 180),
  question_count integer not null default 0 check (question_count between 0 and 200),
  randomize_questions boolean not null default true,
  show_correction boolean not null default true,
  active boolean not null default false,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.academy_quiz_questions_v143 (
  id bigint generated by default as identity primary key,
  quiz_id bigint not null references public.academy_quizzes_v143(id) on delete cascade,
  prompt text not null,
  option_a text not null,
  option_b text not null,
  option_c text,
  option_d text,
  correct_option text not null check (correct_option in ('A','B','C','D')),
  explanation text,
  points integer not null default 1 check (points between 1 and 100),
  sort_order integer not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists academy_quiz_questions_quiz_v143_idx
  on public.academy_quiz_questions_v143(quiz_id,active,sort_order,id);

create table if not exists public.academy_quiz_attempts_v143 (
  id bigint generated by default as identity primary key,
  quiz_id bigint not null references public.academy_quizzes_v143(id) on delete cascade,
  enrollment_id bigint not null references public.academy_enrollments_v137(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  attempt_number integer not null,
  question_ids bigint[] not null default '{}'::bigint[],
  status text not null default 'in_progress' check (status in ('in_progress','passed','failed','expired')),
  score numeric(5,2),
  correct_count integer not null default 0,
  total_questions integer not null default 0,
  started_at timestamptz not null default now(),
  submitted_at timestamptz,
  unique(quiz_id,enrollment_id,attempt_number)
);

create index if not exists academy_quiz_attempts_user_v143_idx
  on public.academy_quiz_attempts_v143(user_id,started_at desc);
create index if not exists academy_quiz_attempts_enrollment_v143_idx
  on public.academy_quiz_attempts_v143(enrollment_id,quiz_id,attempt_number desc);

create table if not exists public.academy_quiz_answers_v143 (
  id bigint generated by default as identity primary key,
  attempt_id bigint not null references public.academy_quiz_attempts_v143(id) on delete cascade,
  question_id bigint not null references public.academy_quiz_questions_v143(id) on delete restrict,
  selected_option text check (selected_option in ('A','B','C','D')),
  is_correct boolean not null default false,
  points_awarded numeric(8,2) not null default 0,
  answered_at timestamptz not null default now(),
  unique(attempt_id,question_id)
);

alter table public.academy_enrollments_v137
  add column if not exists theory_quiz_passed_at timestamptz,
  add column if not exists theory_quiz_attempt_id bigint;

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'academy_enrollments_theory_quiz_attempt_v143_fkey'
  ) then
    alter table public.academy_enrollments_v137
      add constraint academy_enrollments_theory_quiz_attempt_v143_fkey
      foreign key (theory_quiz_attempt_id)
      references public.academy_quiz_attempts_v143(id)
      on delete set null;
  end if;
end;
$$;

-- Un questionnaire désactivé est préparé automatiquement pour chaque formation existante.
insert into public.academy_quizzes_v143(course_id,title,pass_score,active)
select c.id, 'Questionnaire théorique · ' || c.title, c.theory_pass_score, false
from public.academy_courses_v137 c
on conflict (course_id) do nothing;

-- Les nouvelles formations créées après V143 reçoivent elles aussi leur questionnaire prêt à configurer.
create or replace function public.academy_create_course_quiz_v143()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.academy_quizzes_v143(course_id,title,pass_score,active)
  values(new.id,'Questionnaire théorique · ' || new.title,new.theory_pass_score,false)
  on conflict (course_id) do nothing;
  return new;
end;
$$;

drop trigger if exists academy_create_course_quiz_v143 on public.academy_courses_v137;
create trigger academy_create_course_quiz_v143
after insert on public.academy_courses_v137
for each row execute function public.academy_create_course_quiz_v143();

-- ---------------------------------------------------------------------------
-- 2. RLS
-- ---------------------------------------------------------------------------

alter table public.academy_quizzes_v143 enable row level security;
alter table public.academy_quiz_questions_v143 enable row level security;
alter table public.academy_quiz_attempts_v143 enable row level security;
alter table public.academy_quiz_answers_v143 enable row level security;

drop policy if exists "academy quizzes read v143" on public.academy_quizzes_v143;
create policy "academy quizzes read v143"
on public.academy_quizzes_v143 for select to authenticated
using (active or public.nostra_v137_has_any_role(array['manager','commissioner']));

drop policy if exists "academy quizzes staff manage v143" on public.academy_quizzes_v143;
create policy "academy quizzes staff manage v143"
on public.academy_quizzes_v143 for all to authenticated
using (public.nostra_v137_has_any_role(array['manager','commissioner']))
with check (public.nostra_v137_has_any_role(array['manager','commissioner']));

-- Les bonnes réponses ne sont JAMAIS lisibles directement par un citoyen.
drop policy if exists "academy quiz questions staff read v143" on public.academy_quiz_questions_v143;
create policy "academy quiz questions staff read v143"
on public.academy_quiz_questions_v143 for select to authenticated
using (public.nostra_v137_has_any_role(array['manager','commissioner']));

drop policy if exists "academy quiz questions staff manage v143" on public.academy_quiz_questions_v143;
create policy "academy quiz questions staff manage v143"
on public.academy_quiz_questions_v143 for all to authenticated
using (public.nostra_v137_has_any_role(array['manager','commissioner']))
with check (public.nostra_v137_has_any_role(array['manager','commissioner']));

drop policy if exists "academy quiz attempts read v143" on public.academy_quiz_attempts_v143;
create policy "academy quiz attempts read v143"
on public.academy_quiz_attempts_v143 for select to authenticated
using (user_id = auth.uid() or public.nostra_v137_has_any_role(array['manager','commissioner']));

drop policy if exists "academy quiz attempts staff manage v143" on public.academy_quiz_attempts_v143;
create policy "academy quiz attempts staff manage v143"
on public.academy_quiz_attempts_v143 for all to authenticated
using (public.nostra_v137_has_any_role(array['manager','commissioner']))
with check (public.nostra_v137_has_any_role(array['manager','commissioner']));

drop policy if exists "academy quiz answers read v143" on public.academy_quiz_answers_v143;
create policy "academy quiz answers read v143"
on public.academy_quiz_answers_v143 for select to authenticated
using (
  exists (
    select 1 from public.academy_quiz_attempts_v143 a
    where a.id = attempt_id
      and (a.user_id = auth.uid() or public.nostra_v137_has_any_role(array['manager','commissioner']))
  )
);

drop policy if exists "academy quiz answers staff manage v143" on public.academy_quiz_answers_v143;
create policy "academy quiz answers staff manage v143"
on public.academy_quiz_answers_v143 for all to authenticated
using (public.nostra_v137_has_any_role(array['manager','commissioner']))
with check (public.nostra_v137_has_any_role(array['manager','commissioner']));

grant select,insert,update,delete on public.academy_quizzes_v143 to authenticated;
grant select,insert,update,delete on public.academy_quiz_questions_v143 to authenticated;
grant select,insert,update,delete on public.academy_quiz_attempts_v143 to authenticated;
grant select,insert,update,delete on public.academy_quiz_answers_v143 to authenticated;
grant usage,select on sequence public.academy_quizzes_v143_id_seq to authenticated;
grant usage,select on sequence public.academy_quiz_questions_v143_id_seq to authenticated;
grant usage,select on sequence public.academy_quiz_attempts_v143_id_seq to authenticated;
grant usage,select on sequence public.academy_quiz_answers_v143_id_seq to authenticated;

-- ---------------------------------------------------------------------------
-- 3. DÉMARRER UN QUESTIONNAIRE
-- ---------------------------------------------------------------------------

create or replace function public.academy_start_quiz_v143(p_quiz_id bigint)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
  v_quiz public.academy_quizzes_v143%rowtype;
  v_enrollment public.academy_enrollments_v137%rowtype;
  v_existing public.academy_quiz_attempts_v143%rowtype;
  v_attempt_count integer;
  v_attempt_id bigint;
  v_question_ids bigint[];
  v_limit integer;
begin
  if v_uid is null then raise exception using message='not_authenticated'; end if;

  select * into v_quiz
  from public.academy_quizzes_v143
  where id = p_quiz_id and active = true;
  if not found then raise exception using message='quiz_closed'; end if;

  select * into v_enrollment
  from public.academy_enrollments_v137
  where course_id = v_quiz.course_id
    and user_id = v_uid
  limit 1;
  if not found then raise exception using message='enrollment_required'; end if;
  if v_enrollment.status not in ('accepted','training') then
    raise exception using message='training_not_open';
  end if;

  -- Une tentative en cours est reprise. Si son chrono est dépassé, elle devient expirée.
  select * into v_existing
  from public.academy_quiz_attempts_v143
  where quiz_id = v_quiz.id
    and enrollment_id = v_enrollment.id
    and status = 'in_progress'
  order by attempt_number desc
  limit 1;

  if found then
    if v_quiz.time_limit_minutes > 0
       and now() > v_existing.started_at + make_interval(mins => v_quiz.time_limit_minutes) then
      update public.academy_quiz_attempts_v143
      set status='expired', score=0, submitted_at=now()
      where id=v_existing.id;
    else
      return v_existing.id;
    end if;
  end if;

  if exists (
    select 1 from public.academy_quiz_attempts_v143
    where quiz_id=v_quiz.id and enrollment_id=v_enrollment.id and status='passed'
  ) then
    raise exception using message='quiz_already_passed';
  end if;

  select count(*) into v_attempt_count
  from public.academy_quiz_attempts_v143
  where quiz_id=v_quiz.id
    and enrollment_id=v_enrollment.id
    and status in ('passed','failed','expired');
  if v_attempt_count >= v_quiz.max_attempts then
    raise exception using message='max_attempts_reached';
  end if;

  v_limit := case when v_quiz.question_count > 0 then v_quiz.question_count else 2147483647 end;

  if v_quiz.randomize_questions then
    select coalesce(array_agg(x.id), '{}'::bigint[])
    into v_question_ids
    from (
      select q.id
      from public.academy_quiz_questions_v143 q
      where q.quiz_id=v_quiz.id and q.active=true
      order by random()
      limit v_limit
    ) x;
  else
    select coalesce(array_agg(x.id order by x.sort_order,x.id), '{}'::bigint[])
    into v_question_ids
    from (
      select q.id,q.sort_order
      from public.academy_quiz_questions_v143 q
      where q.quiz_id=v_quiz.id and q.active=true
      order by q.sort_order,q.id
      limit v_limit
    ) x;
  end if;

  if coalesce(array_length(v_question_ids,1),0) = 0 then
    raise exception using message='quiz_has_no_questions';
  end if;

  insert into public.academy_quiz_attempts_v143(
    quiz_id,enrollment_id,user_id,attempt_number,question_ids,total_questions
  ) values(
    v_quiz.id,v_enrollment.id,v_uid,v_attempt_count+1,v_question_ids,array_length(v_question_ids,1)
  ) returning id into v_attempt_id;

  update public.academy_enrollments_v137
  set status = case when status='accepted' then 'training' else status end,
      updated_at=now()
  where id=v_enrollment.id;

  return v_attempt_id;
end;
$$;

grant execute on function public.academy_start_quiz_v143(bigint) to authenticated;

-- ---------------------------------------------------------------------------
-- 4. LIRE UNE TENTATIVE SANS EXPOSER LA CORRECTION AVANT LA FIN
-- ---------------------------------------------------------------------------

create or replace function public.academy_get_quiz_attempt_v143(p_attempt_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
  v_attempt public.academy_quiz_attempts_v143%rowtype;
  v_quiz public.academy_quizzes_v143%rowtype;
  v_course public.academy_courses_v137%rowtype;
  v_can_correct boolean := false;
  v_questions jsonb;
begin
  if v_uid is null then raise exception using message='not_authenticated'; end if;

  select * into v_attempt from public.academy_quiz_attempts_v143 where id=p_attempt_id;
  if not found then raise exception using message='attempt_not_found'; end if;
  if v_attempt.user_id <> v_uid and not public.nostra_v137_has_any_role(array['manager','commissioner']) then
    raise exception using message='forbidden';
  end if;

  select * into v_quiz from public.academy_quizzes_v143 where id=v_attempt.quiz_id;
  select * into v_course from public.academy_courses_v137 where id=v_quiz.course_id;
  v_can_correct := v_attempt.status <> 'in_progress' and (v_quiz.show_correction or v_attempt.status='passed');

  select coalesce(jsonb_agg(
    jsonb_build_object(
      'id', q.id,
      'prompt', q.prompt,
      'optionA', q.option_a,
      'optionB', q.option_b,
      'optionC', q.option_c,
      'optionD', q.option_d,
      'points', q.points,
      'selectedOption', a.selected_option,
      'isCorrect', case when v_attempt.status <> 'in_progress' then a.is_correct else null end,
      'correctOption', case when v_can_correct then q.correct_option else null end,
      'explanation', case when v_can_correct then q.explanation else null end
    ) order by array_position(v_attempt.question_ids,q.id)
  ), '[]'::jsonb)
  into v_questions
  from public.academy_quiz_questions_v143 q
  left join public.academy_quiz_answers_v143 a
    on a.attempt_id=v_attempt.id and a.question_id=q.id
  where q.id = any(v_attempt.question_ids);

  return jsonb_build_object(
    'id', v_attempt.id,
    'status', v_attempt.status,
    'score', v_attempt.score,
    'attemptNumber', v_attempt.attempt_number,
    'startedAt', v_attempt.started_at,
    'submittedAt', v_attempt.submitted_at,
    'correctCount', v_attempt.correct_count,
    'totalQuestions', v_attempt.total_questions,
    'quizId', v_quiz.id,
    'quizTitle', v_quiz.title,
    'instructions', v_quiz.instructions,
    'timeLimitMinutes', v_quiz.time_limit_minutes,
    'passScore', greatest(v_quiz.pass_score,v_course.theory_pass_score),
    'maxAttempts', v_quiz.max_attempts,
    'courseId', v_course.id,
    'courseTitle', v_course.title,
    'questions', v_questions
  );
end;
$$;

grant execute on function public.academy_get_quiz_attempt_v143(bigint) to authenticated;

-- ---------------------------------------------------------------------------
-- 5. CORRIGER ET NOTER CÔTÉ SERVEUR
-- ---------------------------------------------------------------------------

create or replace function public.academy_submit_quiz_v143(p_attempt_id bigint, p_answers jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
  v_attempt public.academy_quiz_attempts_v143%rowtype;
  v_quiz public.academy_quizzes_v143%rowtype;
  v_course public.academy_courses_v137%rowtype;
  v_question public.academy_quiz_questions_v143%rowtype;
  v_selected text;
  v_total numeric := 0;
  v_awarded numeric := 0;
  v_score numeric(5,2) := 0;
  v_correct integer := 0;
  v_status text;
  v_required_score numeric(5,2);
begin
  if v_uid is null then raise exception using message='not_authenticated'; end if;
  if p_answers is null or jsonb_typeof(p_answers) <> 'object' then
    raise exception using message='invalid_answers';
  end if;

  select * into v_attempt
  from public.academy_quiz_attempts_v143
  where id=p_attempt_id
  for update;
  if not found then raise exception using message='attempt_not_found'; end if;
  if v_attempt.user_id <> v_uid then raise exception using message='forbidden'; end if;
  if v_attempt.status <> 'in_progress' then return public.academy_get_quiz_attempt_v143(v_attempt.id); end if;

  select * into v_quiz from public.academy_quizzes_v143 where id=v_attempt.quiz_id;
  select * into v_course from public.academy_courses_v137 where id=v_quiz.course_id;

  if v_quiz.time_limit_minutes > 0
     and now() > v_attempt.started_at + make_interval(mins => v_quiz.time_limit_minutes) then
    update public.academy_quiz_attempts_v143
    set status='expired',score=0,correct_count=0,submitted_at=now()
    where id=v_attempt.id;
    return public.academy_get_quiz_attempt_v143(v_attempt.id);
  end if;

  delete from public.academy_quiz_answers_v143 where attempt_id=v_attempt.id;

  for v_question in
    select * from public.academy_quiz_questions_v143
    where id=any(v_attempt.question_ids)
  loop
    v_total := v_total + v_question.points;
    v_selected := upper(nullif(trim(coalesce(p_answers ->> v_question.id::text,'')),''));
    if v_selected not in ('A','B','C','D') then v_selected := null; end if;

    if v_selected = v_question.correct_option then
      v_awarded := v_awarded + v_question.points;
      v_correct := v_correct + 1;
    end if;

    insert into public.academy_quiz_answers_v143(
      attempt_id,question_id,selected_option,is_correct,points_awarded
    ) values(
      v_attempt.id,v_question.id,v_selected,
      v_selected = v_question.correct_option,
      case when v_selected = v_question.correct_option then v_question.points else 0 end
    );
  end loop;

  if v_total > 0 then v_score := round((v_awarded / v_total) * 100,2); end if;
  v_required_score := greatest(v_quiz.pass_score,v_course.theory_pass_score);
  v_status := case when v_score >= v_required_score then 'passed' else 'failed' end;

  update public.academy_quiz_attempts_v143
  set status=v_status,score=v_score,correct_count=v_correct,submitted_at=now()
  where id=v_attempt.id;

  update public.academy_enrollments_v137
  set theory_score = case
        when theory_score is null then v_score
        else greatest(theory_score,v_score)
      end,
      theory_quiz_passed_at = case when v_status='passed' then now() else theory_quiz_passed_at end,
      theory_quiz_attempt_id = case when v_status='passed' then v_attempt.id else theory_quiz_attempt_id end,
      status = case when status='accepted' then 'training' else status end,
      updated_at=now()
  where id=v_attempt.enrollment_id;

  return public.academy_get_quiz_attempt_v143(v_attempt.id);
end;
$$;

grant execute on function public.academy_submit_quiz_v143(bigint,jsonb) to authenticated;

-- ---------------------------------------------------------------------------
-- 6. BLOQUER LA VALIDATION D'UNE FORMATION SI LE QCM ACTIF N'EST PAS RÉUSSI
-- ---------------------------------------------------------------------------

create or replace function public.academy_require_quiz_before_pass_v143()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_quiz_id bigint;
begin
  if new.status <> 'passed' then return new; end if;

  select id into v_quiz_id
  from public.academy_quizzes_v143
  where course_id=new.course_id and active=true
  limit 1;

  if v_quiz_id is null then return new; end if;

  if not exists (
    select 1 from public.academy_quiz_attempts_v143
    where quiz_id=v_quiz_id
      and enrollment_id=new.id
      and status='passed'
  ) then
    raise exception using message='academy_quiz_required';
  end if;

  return new;
end;
$$;

drop trigger if exists academy_require_quiz_before_pass_v143 on public.academy_enrollments_v137;
create trigger academy_require_quiz_before_pass_v143
before update of status on public.academy_enrollments_v137
for each row execute function public.academy_require_quiz_before_pass_v143();

commit;
