-- NOSTRA GROUP — V96
-- 1. Gestion complète des candidatures
-- 2. Suivi détaillé des réservations véhicules
-- 3. Demandes de reprise et transformation en véhicule d'occasion
--
-- Prérequis : les modules Véhicules rachetés V92 et Réservations V93 doivent
-- déjà être installés. Script réexécutable, sans suppression de données.

begin;

-- ===========================================================================
-- A. FONCTIONS D'ACCÈS
-- ===========================================================================

create or replace function public.nostra_is_manager_v96()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select auth.uid() is not null
    and (
      coalesce(
        auth.jwt() -> 'user_metadata' ->> 'provider_id',
        auth.jwt() -> 'user_metadata' ->> 'discord_id',
        auth.jwt() -> 'user_metadata' ->> 'sub'
      ) = '331843410962939908'
      or exists (
        select 1
        from public.member_profiles profile
        where profile.user_id = auth.uid()
          and (
            lower(coalesce(to_jsonb(profile) ->> 'role', ''))
              in ('manager', 'gerant', 'direction', 'administrator', 'admin')
            or lower(coalesce((to_jsonb(profile) -> 'roles')::text, ''))
              ~ '(manager|gerant|direction|administrator|admin)'
          )
      )
    );
$$;

create or replace function public.nostra_can_manage_trade_ins_v96()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select auth.uid() is not null
    and (
      public.nostra_is_manager_v96()
      or exists (
        select 1
        from public.member_profiles profile
        where profile.user_id = auth.uid()
          and (
            lower(coalesce(to_jsonb(profile) ->> 'role', ''))
              in ('employee', 'employe', 'commercial', 'vendeur')
            or lower(coalesce((to_jsonb(profile) -> 'roles')::text, ''))
              ~ '(employee|employe|commercial|vendeur)'
          )
      )
    );
$$;

-- ===========================================================================
-- B. RECRUTEMENT
-- ===========================================================================

create table if not exists public.recruitment_applications (
  id bigint generated by default as identity primary key,
  application_number text not null unique,
  user_id uuid not null references auth.users(id) on delete cascade,
  candidate_name text not null,
  discord_name text,
  phone text,
  position text not null,
  availability text not null,
  motivation text not null,
  experience text,
  strengths text,
  status text not null default 'new'
    check (status in ('new', 'reviewing', 'interview', 'accepted', 'refused', 'archived')),
  assigned_to text,
  interview_at timestamptz,
  manager_response text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.recruitment_application_history (
  id bigint generated by default as identity primary key,
  application_id bigint not null references public.recruitment_applications(id) on delete cascade,
  actor_user_id uuid references auth.users(id) on delete set null,
  from_status text,
  to_status text not null,
  note text,
  created_at timestamptz not null default now()
);

create table if not exists public.recruitment_application_private_v96 (
  application_id bigint primary key references public.recruitment_applications(id) on delete cascade,
  internal_notes text,
  updated_at timestamptz not null default now()
);

-- Migre une éventuelle première exécution de la V96 puis retire la note privée
-- de la table lisible par le candidat.
do $$
begin
  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public'
      and table_name = 'recruitment_applications'
      and column_name = 'internal_notes'
  ) then
    execute $migration$
      insert into public.recruitment_application_private_v96 (application_id, internal_notes, updated_at)
      select id, internal_notes, now()
      from public.recruitment_applications
      where internal_notes is not null
      on conflict (application_id) do update
      set internal_notes = excluded.internal_notes, updated_at = now()
    $migration$;
    execute 'alter table public.recruitment_applications drop column internal_notes';
  end if;
end;
$$;

create index if not exists recruitment_applications_status_v96_idx
  on public.recruitment_applications (status, created_at desc);
create index if not exists recruitment_applications_user_v96_idx
  on public.recruitment_applications (user_id, created_at desc);
create unique index if not exists recruitment_applications_active_user_v96_uq
  on public.recruitment_applications (user_id)
  where status in ('new', 'reviewing', 'interview');
create index if not exists recruitment_history_application_v96_idx
  on public.recruitment_application_history (application_id, created_at desc);

alter table public.recruitment_applications enable row level security;
alter table public.recruitment_application_history enable row level security;
alter table public.recruitment_application_private_v96 enable row level security;

drop policy if exists "recruitment owner reads v96" on public.recruitment_applications;
create policy "recruitment owner reads v96"
  on public.recruitment_applications
  for select to authenticated
  using (user_id = auth.uid());

drop policy if exists "recruitment manager manages v96" on public.recruitment_applications;
create policy "recruitment manager manages v96"
  on public.recruitment_applications
  for all to authenticated
  using (public.nostra_is_manager_v96())
  with check (public.nostra_is_manager_v96());

drop policy if exists "recruitment history manager reads v96" on public.recruitment_application_history;
create policy "recruitment history manager reads v96"
  on public.recruitment_application_history
  for select to authenticated
  using (public.nostra_is_manager_v96());

drop policy if exists "recruitment private manager v96" on public.recruitment_application_private_v96;
create policy "recruitment private manager v96"
  on public.recruitment_application_private_v96
  for all to authenticated
  using (public.nostra_is_manager_v96())
  with check (public.nostra_is_manager_v96());

create or replace function public.submit_recruitment_application_v96(
  p_candidate_name text,
  p_discord_name text,
  p_phone text,
  p_position text,
  p_availability text,
  p_motivation text,
  p_experience text default null,
  p_strengths text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_application_id bigint;
  v_application_number text;
begin
  if v_user_id is null then
    raise exception using message = 'not_authenticated';
  end if;

  if length(btrim(coalesce(p_candidate_name, ''))) < 2
     or length(btrim(coalesce(p_position, ''))) < 2
     or length(btrim(coalesce(p_availability, ''))) < 3
     or length(btrim(coalesce(p_motivation, ''))) < 20 then
    raise exception using message = 'invalid_application';
  end if;

  if exists (
    select 1
    from public.recruitment_applications
    where user_id = v_user_id
      and status in ('new', 'reviewing', 'interview')
  ) then
    raise exception using message = 'application_already_active';
  end if;

  v_application_number := 'REC-' || to_char(clock_timestamp(), 'YYYYMMDD') || '-' ||
    upper(substr(md5(random()::text || clock_timestamp()::text || v_user_id::text), 1, 7));

  insert into public.recruitment_applications (
    application_number,
    user_id,
    candidate_name,
    discord_name,
    phone,
    position,
    availability,
    motivation,
    experience,
    strengths,
    status,
    created_at,
    updated_at
  ) values (
    v_application_number,
    v_user_id,
    btrim(p_candidate_name),
    nullif(btrim(coalesce(p_discord_name, '')), ''),
    nullif(btrim(coalesce(p_phone, '')), ''),
    btrim(p_position),
    btrim(p_availability),
    btrim(p_motivation),
    nullif(btrim(coalesce(p_experience, '')), ''),
    nullif(btrim(coalesce(p_strengths, '')), ''),
    'new',
    now(),
    now()
  ) returning id into v_application_id;

  insert into public.recruitment_application_history (
    application_id, actor_user_id, from_status, to_status, note
  ) values (
    v_application_id, v_user_id, null, 'new', 'Candidature envoyée depuis le site.'
  );

  return jsonb_build_object(
    'id', v_application_id,
    'application_number', v_application_number
  );
end;
$$;

create or replace function public.review_recruitment_application_v96(
  p_application_id bigint,
  p_status text,
  p_assigned_to text default null,
  p_interview_at timestamptz default null,
  p_internal_notes text default null,
  p_manager_response text default null,
  p_history_note text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_application public.recruitment_applications%rowtype;
begin
  if not public.nostra_is_manager_v96() then
    raise exception using message = 'forbidden';
  end if;
  if coalesce(p_status, '') not in ('new', 'reviewing', 'interview', 'accepted', 'refused', 'archived') then
    raise exception using message = 'invalid_application';
  end if;

  select * into v_application
  from public.recruitment_applications
  where id = p_application_id
  for update;

  if not found then
    raise exception using message = 'application_not_found';
  end if;

  if p_status = 'interview' and p_interview_at is null then
    raise exception using message = 'interview_date_required';
  end if;

  update public.recruitment_applications
  set status = p_status,
      assigned_to = nullif(btrim(coalesce(p_assigned_to, '')), ''),
      interview_at = p_interview_at,
      manager_response = nullif(btrim(coalesce(p_manager_response, '')), ''),
      updated_at = now()
  where id = p_application_id;

  insert into public.recruitment_application_private_v96 (
    application_id, internal_notes, updated_at
  ) values (
    p_application_id,
    nullif(btrim(coalesce(p_internal_notes, '')), ''),
    now()
  )
  on conflict (application_id) do update
  set internal_notes = excluded.internal_notes,
      updated_at = now();

  if v_application.status is distinct from p_status
     or nullif(btrim(coalesce(p_history_note, '')), '') is not null then
    insert into public.recruitment_application_history (
      application_id, actor_user_id, from_status, to_status, note
    ) values (
      p_application_id,
      auth.uid(),
      v_application.status,
      p_status,
      nullif(btrim(coalesce(p_history_note, '')), '')
    );
  end if;

  return jsonb_build_object('status', p_status);
end;
$$;

-- ===========================================================================
-- C. SUIVI DÉTAILLÉ DES RÉSERVATIONS VÉHICULES
-- ===========================================================================

alter table public.vehicle_reservations add column if not exists assigned_staff text;
alter table public.vehicle_reservations add column if not exists payment_due_at timestamptz;
alter table public.vehicle_reservations add column if not exists preparation_started_at timestamptz;
alter table public.vehicle_reservations add column if not exists ready_at timestamptz;
alter table public.vehicle_reservations add column if not exists delivered_at timestamptz;

create table if not exists public.vehicle_reservation_private_v96 (
  reservation_id bigint primary key references public.vehicle_reservations(id) on delete cascade,
  internal_note text,
  updated_at timestamptz not null default now()
);

do $$
begin
  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public'
      and table_name = 'vehicle_reservations'
      and column_name = 'internal_note'
  ) then
    execute $migration$
      insert into public.vehicle_reservation_private_v96 (reservation_id, internal_note, updated_at)
      select id, internal_note, now()
      from public.vehicle_reservations
      where internal_note is not null
      on conflict (reservation_id) do update
      set internal_note = excluded.internal_note, updated_at = now()
    $migration$;
    execute 'alter table public.vehicle_reservations drop column internal_note';
  end if;
end;
$$;

alter table public.vehicle_reservation_private_v96 enable row level security;
drop policy if exists "reservation private staff v96" on public.vehicle_reservation_private_v96;
create policy "reservation private staff v96"
  on public.vehicle_reservation_private_v96
  for all to authenticated
  using (public.nostra_can_manage_vehicle_reservations_v93())
  with check (public.nostra_can_manage_vehicle_reservations_v93());

-- Remplace uniquement la contrainte de statut de la table des réservations.
do $$
declare
  constraint_row record;
begin
  for constraint_row in
    select conname
    from pg_constraint
    where conrelid = 'public.vehicle_reservations'::regclass
      and contype = 'c'
      and pg_get_constraintdef(oid) ilike '%status%'
  loop
    execute format(
      'alter table public.vehicle_reservations drop constraint if exists %I',
      constraint_row.conname
    );
  end loop;
end;
$$;

alter table public.vehicle_reservations
  add constraint vehicle_reservations_status_v96_check
  check (status in (
    'pending_validation',
    'balance_due',
    'paid_full',
    'preparing',
    'ready',
    'rejected',
    'cancelled',
    'completed'
  )) not valid;
alter table public.vehicle_reservations
  validate constraint vehicle_reservations_status_v96_check;

create or replace function public.nostra_reservation_followup_defaults_v96()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if new.status = 'balance_due' and new.payment_due_at is null then
    new.payment_due_at := now() + interval '7 days';
  end if;

  if new.status = 'preparing' and new.preparation_started_at is null then
    new.preparation_started_at := now();
  end if;
  if new.status = 'ready' then
    new.preparation_started_at := coalesce(new.preparation_started_at, now());
    new.ready_at := coalesce(new.ready_at, now());
  end if;
  if new.status = 'completed' then
    new.preparation_started_at := coalesce(new.preparation_started_at, now());
    new.ready_at := coalesce(new.ready_at, now());
    new.delivered_at := coalesce(new.delivered_at, now());
  end if;

  return new;
end;
$$;

drop trigger if exists reservation_followup_defaults_v96 on public.vehicle_reservations;
create trigger reservation_followup_defaults_v96
  before insert or update of status, payment_due_at
  on public.vehicle_reservations
  for each row
  execute function public.nostra_reservation_followup_defaults_v96();

create or replace function public.update_vehicle_reservation_followup_v96(
  p_reservation_id bigint,
  p_status text default null,
  p_assigned_staff text default null,
  p_payment_due_at timestamptz default null,
  p_admin_note text default null,
  p_internal_note text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_reservation public.vehicle_reservations%rowtype;
  v_order_status text;
begin
  if not public.nostra_can_manage_vehicle_reservations_v93() then
    raise exception using message = 'forbidden';
  end if;

  select * into v_reservation
  from public.vehicle_reservations
  where id = p_reservation_id
  for update;

  if not found then
    raise exception using message = 'reservation_not_found';
  end if;

  if p_status is not null then
    if p_status not in ('paid_full', 'preparing', 'ready', 'completed') then
      raise exception using message = 'invalid_reservation_status';
    end if;
    if v_reservation.status not in ('paid_full', 'preparing', 'ready', 'completed') then
      raise exception using message = 'reservation_status_locked';
    end if;

    v_order_status := case p_status
      when 'paid_full' then 'confirmed'
      when 'preparing' then 'preparing'
      when 'ready' then 'ready'
      when 'completed' then 'completed'
      else 'confirmed'
    end;

    if v_reservation.final_order_id is not null then
      update public.orders
      set status = v_order_status,
          admin_note = nullif(btrim(coalesce(p_admin_note, '')), ''),
          updated_at = now()
      where id = v_reservation.final_order_id;
    else
      update public.vehicle_reservations
      set status = p_status
      where id = p_reservation_id;
    end if;
  end if;

  update public.vehicle_reservations
  set assigned_staff = nullif(btrim(coalesce(p_assigned_staff, '')), ''),
      payment_due_at = p_payment_due_at,
      admin_note = nullif(btrim(coalesce(p_admin_note, '')), ''),
      updated_at = now()
  where id = p_reservation_id;

  insert into public.vehicle_reservation_private_v96 (
    reservation_id, internal_note, updated_at
  ) values (
    p_reservation_id,
    nullif(btrim(coalesce(p_internal_note, '')), ''),
    now()
  )
  on conflict (reservation_id) do update
  set internal_note = excluded.internal_note,
      updated_at = now();

  return jsonb_build_object(
    'id', p_reservation_id,
    'status', coalesce(p_status, v_reservation.status)
  );
end;
$$;

-- Le statut de la commande finale alimente automatiquement la frise client.
create or replace function public.nostra_sync_reservation_order_status_v93()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'DELETE' then
    update public.vehicle_reservations
    set status = 'cancelled',
        stock_reserved = false,
        final_order_id = null,
        updated_at = now()
    where final_order_id = old.id;
    return old;
  end if;

  update public.vehicle_reservations
  set status = case
        when new.status = 'completed' then 'completed'
        when new.status = 'ready' then 'ready'
        when new.status = 'preparing' then 'preparing'
        when new.status = 'cancelled' then 'cancelled'
        else 'paid_full'
      end,
      stock_reserved = case when new.status = 'cancelled' then false else stock_reserved end,
      preparation_started_at = case
        when new.status in ('preparing', 'ready', 'completed')
          then coalesce(preparation_started_at, now())
        else preparation_started_at
      end,
      ready_at = case
        when new.status in ('ready', 'completed') then coalesce(ready_at, now())
        else ready_at
      end,
      delivered_at = case
        when new.status = 'completed' then coalesce(delivered_at, now())
        else delivered_at
      end,
      updated_at = now()
  where final_order_id = new.id;
  return new;
end;
$$;

-- Les triggers V93 gardent le même nom, la fonction ci-dessus est remplacée.

-- ===========================================================================
-- D. DEMANDES DE REPRISE DE VÉHICULES
-- ===========================================================================

create table if not exists public.vehicle_trade_in_requests (
  id bigint generated by default as identity primary key,
  request_number text not null unique,
  user_id uuid not null references auth.users(id) on delete cascade,
  customer_name text not null,
  customer_email text,
  customer_phone text,
  brand text not null,
  model text not null,
  version text,
  registration text,
  mileage integer not null default 0 check (mileage >= 0),
  first_registration_year integer,
  vehicle_condition text not null default 'good'
    check (vehicle_condition in ('excellent', 'very_good', 'good', 'fair', 'repair')),
  modifications text,
  desired_price numeric(14,2),
  description text not null,
  images jsonb not null default '[]'::jsonb,
  status text not null default 'new'
    check (status in ('new', 'reviewing', 'offer_sent', 'accepted', 'refused', 'converted', 'cancelled')),
  proposed_purchase_price numeric(14,2),
  assigned_staff text,
  appointment_at timestamptz,
  admin_note text,
  converted_vehicle_id bigint references public.catalog_vehicles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.vehicle_trade_in_private_v96 (
  request_id bigint primary key references public.vehicle_trade_in_requests(id) on delete cascade,
  planned_resale_price numeric(14,2),
  internal_note text,
  updated_at timestamptz not null default now()
);

-- Migre une éventuelle version intermédiaire où ces informations privées
-- étaient stockées dans la table visible par le client.
do $$
begin
  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public'
      and table_name = 'vehicle_trade_in_requests'
      and column_name = 'planned_resale_price'
  ) then
    execute $migration$
      insert into public.vehicle_trade_in_private_v96 (request_id, planned_resale_price, updated_at)
      select id, planned_resale_price, now()
      from public.vehicle_trade_in_requests
      where planned_resale_price is not null
      on conflict (request_id) do update
      set planned_resale_price = excluded.planned_resale_price, updated_at = now()
    $migration$;
    execute 'alter table public.vehicle_trade_in_requests drop column planned_resale_price';
  end if;

  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public'
      and table_name = 'vehicle_trade_in_requests'
      and column_name = 'internal_note'
  ) then
    execute $migration$
      insert into public.vehicle_trade_in_private_v96 (request_id, internal_note, updated_at)
      select id, internal_note, now()
      from public.vehicle_trade_in_requests
      where internal_note is not null
      on conflict (request_id) do update
      set internal_note = excluded.internal_note, updated_at = now()
    $migration$;
    execute 'alter table public.vehicle_trade_in_requests drop column internal_note';
  end if;
end;
$$;

alter table public.vehicle_trade_in_requests
  drop constraint if exists vehicle_trade_in_requests_vehicle_condition_check;
alter table public.vehicle_trade_in_requests
  drop constraint if exists vehicle_trade_in_condition_v96_check;

update public.vehicle_trade_in_requests
set vehicle_condition = 'repair'
where vehicle_condition = 'poor';

alter table public.vehicle_trade_in_requests
  add constraint vehicle_trade_in_condition_v96_check
  check (vehicle_condition in ('excellent', 'very_good', 'good', 'fair', 'repair')) not valid;
alter table public.vehicle_trade_in_requests
  validate constraint vehicle_trade_in_condition_v96_check;

create index if not exists vehicle_trade_in_user_v96_idx
  on public.vehicle_trade_in_requests (user_id, created_at desc);
create index if not exists vehicle_trade_in_status_v96_idx
  on public.vehicle_trade_in_requests (status, created_at desc);
create index if not exists vehicle_trade_in_registration_v96_idx
  on public.vehicle_trade_in_requests (registration)
  where registration is not null;

alter table public.vehicle_trade_in_requests enable row level security;
alter table public.vehicle_trade_in_private_v96 enable row level security;

drop policy if exists "trade in owner reads v96" on public.vehicle_trade_in_requests;
create policy "trade in owner reads v96"
  on public.vehicle_trade_in_requests
  for select to authenticated
  using (user_id = auth.uid());

drop policy if exists "trade in staff manages v96" on public.vehicle_trade_in_requests;
create policy "trade in staff manages v96"
  on public.vehicle_trade_in_requests
  for all to authenticated
  using (public.nostra_can_manage_trade_ins_v96())
  with check (public.nostra_can_manage_trade_ins_v96());

drop policy if exists "trade in private staff v96" on public.vehicle_trade_in_private_v96;
create policy "trade in private staff v96"
  on public.vehicle_trade_in_private_v96
  for all to authenticated
  using (public.nostra_can_manage_trade_ins_v96())
  with check (public.nostra_can_manage_trade_ins_v96());

-- Autorise un citoyen connecté à envoyer uniquement des images de reprise dans
-- son propre dossier du bucket déjà utilisé par les véhicules rachetés V92.
drop policy if exists "trade in image upload v96" on storage.objects;
create policy "trade in image upload v96"
  on storage.objects
  for insert to authenticated
  with check (
    bucket_id = 'vehicle-images'
    and name like ('used/' || auth.uid()::text || '/trade-in-%')
    and lower(name) ~ '\.(jpg|jpeg|png|webp)$'
  );

create or replace function public.submit_vehicle_trade_in_v96(
  p_customer_name text,
  p_customer_email text,
  p_customer_phone text,
  p_brand text,
  p_model text,
  p_version text,
  p_registration text,
  p_mileage integer,
  p_first_registration_year integer,
  p_vehicle_condition text,
  p_modifications text,
  p_desired_price numeric,
  p_description text,
  p_images jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_request_id bigint;
  v_request_number text;
  v_condition text := lower(btrim(coalesce(p_vehicle_condition, 'good')));
begin
  if v_user_id is null then
    raise exception using message = 'not_authenticated';
  end if;
  if length(btrim(coalesce(p_brand, ''))) < 1
     or length(btrim(coalesce(p_model, ''))) < 1
     or length(btrim(coalesce(p_description, ''))) < 10
     or coalesce(p_mileage, 0) < 0
     or v_condition not in ('excellent', 'very_good', 'good', 'fair', 'repair') then
    raise exception using message = 'invalid_trade_in';
  end if;

  v_request_number := 'REP-' || to_char(clock_timestamp(), 'YYYYMMDD') || '-' ||
    upper(substr(md5(random()::text || clock_timestamp()::text || v_user_id::text), 1, 7));

  insert into public.vehicle_trade_in_requests (
    request_number,
    user_id,
    customer_name,
    customer_email,
    customer_phone,
    brand,
    model,
    version,
    registration,
    mileage,
    first_registration_year,
    vehicle_condition,
    modifications,
    desired_price,
    description,
    images,
    status,
    created_at,
    updated_at
  ) values (
    v_request_number,
    v_user_id,
    btrim(p_customer_name),
    nullif(btrim(coalesce(p_customer_email, '')), ''),
    nullif(btrim(coalesce(p_customer_phone, '')), ''),
    btrim(p_brand),
    btrim(p_model),
    nullif(btrim(coalesce(p_version, '')), ''),
    nullif(upper(btrim(coalesce(p_registration, ''))), ''),
    greatest(coalesce(p_mileage, 0), 0),
    case
      when p_first_registration_year between 1950 and 2100 then p_first_registration_year
      else null
    end,
    v_condition,
    nullif(btrim(coalesce(p_modifications, '')), ''),
    case when coalesce(p_desired_price, 0) > 0 then p_desired_price else null end,
    btrim(p_description),
    case when jsonb_typeof(coalesce(p_images, '[]'::jsonb)) = 'array'
      then coalesce(p_images, '[]'::jsonb)
      else '[]'::jsonb
    end,
    'new',
    now(),
    now()
  ) returning id into v_request_id;

  return jsonb_build_object(
    'id', v_request_id,
    'request_number', v_request_number
  );
end;
$$;

create or replace function public.review_vehicle_trade_in_v96(
  p_request_id bigint,
  p_status text,
  p_proposed_purchase_price numeric default null,
  p_planned_resale_price numeric default null,
  p_assigned_staff text default null,
  p_appointment_at timestamptz default null,
  p_admin_note text default null,
  p_internal_note text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_request public.vehicle_trade_in_requests%rowtype;
begin
  if not public.nostra_can_manage_trade_ins_v96() then
    raise exception using message = 'forbidden';
  end if;
  if coalesce(p_status, '') not in ('new', 'reviewing', 'offer_sent', 'accepted', 'refused', 'cancelled') then
    raise exception using message = 'invalid_trade_in';
  end if;

  select * into v_request
  from public.vehicle_trade_in_requests
  where id = p_request_id
  for update;

  if not found then
    raise exception using message = 'trade_in_not_found';
  end if;
  if v_request.status = 'converted' then
    raise exception using message = 'request_not_convertible';
  end if;
  if p_status in ('offer_sent', 'accepted')
     and coalesce(p_proposed_purchase_price, 0) <= 0 then
    raise exception using message = 'purchase_price_required';
  end if;
  if p_status = 'accepted'
     and coalesce(p_planned_resale_price, 0) <= 0 then
    raise exception using message = 'resale_price_required';
  end if;

  update public.vehicle_trade_in_requests
  set status = p_status,
      proposed_purchase_price = case
        when coalesce(p_proposed_purchase_price, 0) > 0 then p_proposed_purchase_price
        else null
      end,
      assigned_staff = nullif(btrim(coalesce(p_assigned_staff, '')), ''),
      appointment_at = p_appointment_at,
      admin_note = nullif(btrim(coalesce(p_admin_note, '')), ''),
      updated_at = now()
  where id = p_request_id;

  insert into public.vehicle_trade_in_private_v96 (
    request_id, planned_resale_price, internal_note, updated_at
  ) values (
    p_request_id,
    case
      when coalesce(p_planned_resale_price, 0) > 0 then p_planned_resale_price
      else null
    end,
    nullif(btrim(coalesce(p_internal_note, '')), ''),
    now()
  )
  on conflict (request_id) do update
  set planned_resale_price = excluded.planned_resale_price,
      internal_note = excluded.internal_note,
      updated_at = now();

  return jsonb_build_object('status', p_status);
end;
$$;

create or replace function public.convert_vehicle_trade_in_to_used_vehicle_v96(
  p_request_id bigint
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_request public.vehicle_trade_in_requests%rowtype;
  v_private public.vehicle_trade_in_private_v96%rowtype;
  v_vehicle_id bigint;
begin
  if not public.nostra_can_manage_trade_ins_v96() then
    raise exception using message = 'forbidden';
  end if;

  select * into v_request
  from public.vehicle_trade_in_requests
  where id = p_request_id
  for update;

  if not found then
    raise exception using message = 'trade_in_not_found';
  end if;

  select * into v_private
  from public.vehicle_trade_in_private_v96
  where request_id = p_request_id;

  if v_request.status <> 'accepted'
     or coalesce(v_request.proposed_purchase_price, 0) <= 0
     or coalesce(v_private.planned_resale_price, 0) <= 0 then
    raise exception using message = 'request_not_convertible';
  end if;

  select public.create_used_vehicle_v92(
    p_brand => v_request.brand,
    p_model => v_request.model,
    p_version => v_request.version,
    p_registration => v_request.registration,
    p_previous_owner => v_request.customer_name,
    p_purchase_date => current_date,
    p_purchase_price => v_request.proposed_purchase_price,
    p_resale_price => v_private.planned_resale_price,
    p_quantity => 1,
    p_images => v_request.images,
    p_description => v_request.description,
    p_condition => v_request.vehicle_condition,
    p_internal_notes => btrim(
      'Créé depuis la demande de reprise ' || v_request.request_number || '. ' ||
      coalesce(v_private.internal_note, '')
    ),
    p_trunk_capacity => '',
    p_top_speed => '',
    p_power => '',
    p_sort_order => 0,
    p_published => false
  ) into v_vehicle_id;

  if coalesce(v_vehicle_id, 0) <= 0 then
    raise exception using message = 'vehicle_creation_failed';
  end if;

  update public.vehicle_trade_in_requests
  set status = 'converted',
      converted_vehicle_id = v_vehicle_id,
      updated_at = now()
  where id = p_request_id;

  return jsonb_build_object(
    'status', 'converted',
    'vehicle_id', v_vehicle_id,
    'request_number', v_request.request_number
  );
end;
$$;

create or replace function public.mark_vehicle_trade_in_converted_v96(
  p_request_id bigint,
  p_vehicle_id bigint
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_request public.vehicle_trade_in_requests%rowtype;
  v_private public.vehicle_trade_in_private_v96%rowtype;
begin
  if not public.nostra_can_manage_trade_ins_v96() then
    raise exception using message = 'forbidden';
  end if;

  select * into v_request
  from public.vehicle_trade_in_requests
  where id = p_request_id
  for update;

  if not found then
    raise exception using message = 'request_not_convertible';
  end if;

  select * into v_private
  from public.vehicle_trade_in_private_v96
  where request_id = p_request_id;

  if v_request.status <> 'accepted'
     or coalesce(v_request.proposed_purchase_price, 0) <= 0
     or coalesce(v_private.planned_resale_price, 0) <= 0 then
    raise exception using message = 'request_not_convertible';
  end if;
  if not exists (
    select 1 from public.catalog_vehicles
    where id = p_vehicle_id and catalog_type = 'used'
  ) then
    raise exception using message = 'vehicle_not_found';
  end if;

  update public.vehicle_trade_in_requests
  set status = 'converted',
      converted_vehicle_id = p_vehicle_id,
      updated_at = now()
  where id = p_request_id;

  return jsonb_build_object('status', 'converted', 'vehicle_id', p_vehicle_id);
end;
$$;

create or replace function public.cancel_vehicle_trade_in_v96(
  p_request_id bigint
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_request public.vehicle_trade_in_requests%rowtype;
begin
  if auth.uid() is null then
    raise exception using message = 'not_authenticated';
  end if;

  select * into v_request
  from public.vehicle_trade_in_requests
  where id = p_request_id
    and user_id = auth.uid()
  for update;

  if not found then
    raise exception using message = 'trade_in_not_found';
  end if;
  if v_request.status not in ('new', 'reviewing', 'offer_sent') then
    raise exception using message = 'request_not_cancellable';
  end if;

  update public.vehicle_trade_in_requests
  set status = 'cancelled', updated_at = now()
  where id = p_request_id;

  return jsonb_build_object('status', 'cancelled');
end;
$$;

-- ===========================================================================
-- E. DROITS
-- ===========================================================================

grant select on public.recruitment_applications to authenticated;
grant select on public.recruitment_application_history to authenticated;
grant select on public.recruitment_application_private_v96 to authenticated;
grant select on public.vehicle_reservation_private_v96 to authenticated;
grant select on public.vehicle_trade_in_requests to authenticated;
grant select on public.vehicle_trade_in_private_v96 to authenticated;

revoke all on function public.submit_recruitment_application_v96(text,text,text,text,text,text,text,text) from public, anon;
revoke all on function public.review_recruitment_application_v96(bigint,text,text,timestamptz,text,text,text) from public, anon;
revoke all on function public.update_vehicle_reservation_followup_v96(bigint,text,text,timestamptz,text,text) from public, anon;
revoke all on function public.submit_vehicle_trade_in_v96(text,text,text,text,text,text,text,integer,integer,text,text,numeric,text,jsonb) from public, anon;
revoke all on function public.review_vehicle_trade_in_v96(bigint,text,numeric,numeric,text,timestamptz,text,text) from public, anon;
revoke all on function public.convert_vehicle_trade_in_to_used_vehicle_v96(bigint) from public, anon;
revoke all on function public.mark_vehicle_trade_in_converted_v96(bigint,bigint) from public, anon;
revoke all on function public.cancel_vehicle_trade_in_v96(bigint) from public, anon;

grant execute on function public.submit_recruitment_application_v96(text,text,text,text,text,text,text,text) to authenticated;
grant execute on function public.review_recruitment_application_v96(bigint,text,text,timestamptz,text,text,text) to authenticated;
grant execute on function public.update_vehicle_reservation_followup_v96(bigint,text,text,timestamptz,text,text) to authenticated;
grant execute on function public.submit_vehicle_trade_in_v96(text,text,text,text,text,text,text,integer,integer,text,text,numeric,text,jsonb) to authenticated;
grant execute on function public.review_vehicle_trade_in_v96(bigint,text,numeric,numeric,text,timestamptz,text,text) to authenticated;
grant execute on function public.convert_vehicle_trade_in_to_used_vehicle_v96(bigint) to authenticated;
grant execute on function public.mark_vehicle_trade_in_converted_v96(bigint,bigint) to authenticated;
grant execute on function public.cancel_vehicle_trade_in_v96(bigint) to authenticated;
grant execute on function public.nostra_is_manager_v96() to authenticated;
grant execute on function public.nostra_can_manage_trade_ins_v96() to authenticated;

notify pgrst, 'reload schema';

commit;

select
  to_regclass('public.recruitment_applications') is not null as recrutement,
  to_regclass('public.vehicle_trade_in_requests') is not null as reprises,
  to_regprocedure('public.update_vehicle_reservation_followup_v96(bigint,text,text,timestamptz,text,text)') is not null as suivi_reservations,
  to_regprocedure('public.convert_vehicle_trade_in_to_used_vehicle_v96(bigint)') is not null as conversion_occasion,
  'V96_OK' as resultat;
