-- NOSTRA GROUP V136
-- Roue de la chance : cases modifiables, activation et message citoyen.

create table if not exists public.game_wheel_settings (
  id integer primary key default 1 check (id = 1),
  enabled boolean not null default true,
  disabled_message text not null default 'La roue de la chance est temporairement indisponible. Reviens prochainement pour tenter ta chance.',
  updated_by uuid references auth.users(id) on delete set null,
  updated_at timestamptz not null default now(),
  constraint game_wheel_settings_message_length check (char_length(disabled_message) between 1 and 500)
);

create table if not exists public.game_wheel_segments (
  id bigint generated by default as identity primary key,
  slot_index integer not null unique check (slot_index between 0 and 39),
  prize_key text not null,
  label text not null check (char_length(label) between 1 and 100),
  short_label text not null check (char_length(short_label) between 1 and 18),
  prize_type text not null check (prize_type in ('bonus', 'loss')),
  color text not null check (color ~ '^#[0-9A-Fa-f]{6}$'),
  text_color text not null check (text_color ~ '^#[0-9A-Fa-f]{6}$'),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

insert into public.game_wheel_settings (id, enabled, disabled_message)
values (1, true, 'La roue de la chance est temporairement indisponible. Reviens prochainement pour tenter ta chance.')
on conflict (id) do nothing;

insert into public.game_wheel_segments (slot_index, prize_key, label, short_label, prize_type, color, text_color)
select * from (values
  (0, 'lost', 'Perdu', 'PERDU', 'loss', '#2b2b2b', '#f2f2f2'),
  (1, 'paint', 'Peinture offerte', 'PEINTURE', 'bonus', '#c79a22', '#111111'),
  (2, 'lost', 'Perdu', 'PERDU', 'loss', '#151515', '#f2f2f2'),
  (3, 'discount_5', '-5 % sur la prochaine commande', '-5 %', 'bonus', '#9f7615', '#ffffff'),
  (4, 'coffee', '1 café offert', 'CAFÉ', 'bonus', '#6f4b2a', '#ffffff'),
  (5, 'lost', 'Perdu', 'PERDU', 'loss', '#242424', '#f2f2f2'),
  (6, 'circuit_lap', '1 tour de circuit offert', '1 TOUR', 'bonus', '#1b5e5a', '#ffffff'),
  (7, 'paint', 'Peinture offerte', 'PEINTURE', 'bonus', '#d6ad3f', '#111111'),
  (8, 'lost', 'Perdu', 'PERDU', 'loss', '#111111', '#f2f2f2'),
  (9, 'circuit_10_laps', '10 tours de circuit offerts', '10 TOURS', 'bonus', '#7c2e2e', '#ffffff'),
  (10, 'discount_5', '-5 % sur la prochaine commande', '-5 %', 'bonus', '#b0851e', '#ffffff'),
  (11, 'circuit_5_laps', '5 tours de circuit offerts', '5 TOURS', 'bonus', '#2f477d', '#ffffff'),
  (12, 'lost', 'Perdu', 'PERDU', 'loss', '#303030', '#f2f2f2'),
  (13, 'silver_card', 'Carte fidélité Silver', 'SILVER', 'bonus', '#bfc5cc', '#111111'),
  (14, 'coffee', '1 café offert', 'CAFÉ', 'bonus', '#80583a', '#ffffff'),
  (15, 'discount_5', '-5 % sur la prochaine commande', '-5 %', 'bonus', '#90690e', '#ffffff'),
  (16, 'circuit_lap', '1 tour de circuit offert', '1 TOUR', 'bonus', '#23746e', '#ffffff'),
  (17, 'lost', 'Perdu', 'PERDU', 'loss', '#1c1c1c', '#f2f2f2'),
  (18, 'vehicle_test', 'Essai d’un véhicule de la concession', 'ESSAI VL', 'bonus', '#5e3f87', '#ffffff'),
  (19, 'paint', 'Peinture offerte', 'PEINTURE', 'bonus', '#c99b25', '#111111'),
  (20, 'circuit_5_laps', '5 tours de circuit offerts', '5 TOURS', 'bonus', '#36548f', '#ffffff'),
  (21, 'discount_10k', '-10 000 € sur la prochaine commande', '-10K', 'bonus', '#8b5b18', '#ffffff'),
  (22, 'discount_10k', '-10 000 € sur la prochaine commande', '-10K', 'bonus', '#a36d20', '#ffffff')
) as defaults(slot_index, prize_key, label, short_label, prize_type, color, text_color)
where not exists (select 1 from public.game_wheel_segments);

alter table public.game_wheel_spins
  drop constraint if exists game_wheel_spins_slot_index_check;
alter table public.game_wheel_spins
  add constraint game_wheel_spins_slot_index_check check (slot_index between 0 and 39);

alter table public.game_wheel_settings enable row level security;
alter table public.game_wheel_segments enable row level security;

drop policy if exists "wheel settings authenticated read" on public.game_wheel_settings;
create policy "wheel settings authenticated read"
on public.game_wheel_settings for select to authenticated using (true);

drop policy if exists "wheel segments authenticated read" on public.game_wheel_segments;
create policy "wheel segments authenticated read"
on public.game_wheel_segments for select to authenticated using (true);

grant select on public.game_wheel_settings to authenticated;
grant select on public.game_wheel_segments to authenticated;

create or replace function public.save_nostra_wheel_configuration(
  p_enabled boolean,
  p_disabled_message text,
  p_segments jsonb
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_count integer;
begin
  if auth.uid() is null or not public.nostra_games_is_manager() then
    raise exception using errcode = '42501', message = 'manager_access_required';
  end if;

  if p_disabled_message is null or char_length(trim(p_disabled_message)) not between 1 and 500 then
    raise exception using errcode = '22023', message = 'invalid_disabled_message';
  end if;

  if p_segments is null or jsonb_typeof(p_segments) <> 'array' then
    raise exception using errcode = '22023', message = 'invalid_wheel_segments';
  end if;

  v_count := jsonb_array_length(p_segments);
  if v_count not between 2 and 40 then
    raise exception using errcode = '22023', message = 'wheel_segment_count_must_be_between_2_and_40';
  end if;

  if exists (
    select 1
    from jsonb_array_elements(p_segments) with ordinality as item(value, position)
    where coalesce(char_length(trim(value->>'label')), 0) not between 1 and 100
       or coalesce(char_length(trim(value->>'short_label')), 0) not between 1 and 18
       or coalesce(value->>'prize_type', '') not in ('bonus', 'loss')
       or coalesce(value->>'color', '') !~ '^#[0-9A-Fa-f]{6}$'
       or coalesce(value->>'text_color', '') !~ '^#[0-9A-Fa-f]{6}$'
  ) then
    raise exception using errcode = '22023', message = 'invalid_wheel_segment';
  end if;

  update public.game_wheel_settings
  set enabled = coalesce(p_enabled, false),
      disabled_message = trim(p_disabled_message),
      updated_by = auth.uid(),
      updated_at = now()
  where id = 1;

  delete from public.game_wheel_segments;

  insert into public.game_wheel_segments (
    slot_index,
    prize_key,
    label,
    short_label,
    prize_type,
    color,
    text_color,
    created_at,
    updated_at
  )
  select
    position::integer - 1,
    coalesce(nullif(trim(value->>'prize_key'), ''), 'custom_' || (position::integer - 1)::text),
    trim(value->>'label'),
    trim(value->>'short_label'),
    value->>'prize_type',
    value->>'color',
    value->>'text_color',
    now(),
    now()
  from jsonb_array_elements(p_segments) with ordinality as item(value, position)
  order by position;
end;
$$;

revoke all on function public.save_nostra_wheel_configuration(boolean, text, jsonb) from public;
grant execute on function public.save_nostra_wheel_configuration(boolean, text, jsonb) to authenticated;

create or replace function public.spin_nostra_wheel()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_player_name text;
  v_slot integer;
  v_prize_key text;
  v_prize_label text;
  v_prize_type text;
  v_status text;
  v_spin_id bigint;
  v_draw_date date := (clock_timestamp() at time zone 'Europe/Paris')::date;
  v_enabled boolean;
begin
  if v_user_id is null then
    raise exception using errcode = '42501', message = 'not_authenticated';
  end if;

  select enabled into v_enabled from public.game_wheel_settings where id = 1;
  if coalesce(v_enabled, false) is not true then
    raise exception using errcode = 'P0001', message = 'wheel_disabled';
  end if;

  if exists (
    select 1 from public.game_wheel_spins
    where user_id = v_user_id and draw_date = v_draw_date
  ) then
    raise exception using errcode = 'P0001', message = 'daily_spin_limit';
  end if;

  select nullif(trim(concat_ws(' ', rp_first_name, rp_last_name)), '')
    into v_player_name
  from public.member_profiles
  where user_id = v_user_id;

  if v_player_name is null then
    select nullif(trim(coalesce(discord_name, '')), '')
      into v_player_name
    from public.member_profiles
    where user_id = v_user_id;
  end if;

  v_player_name := coalesce(v_player_name, 'Citoyen Nostra Group');

  select slot_index, prize_key, label, prize_type
    into v_slot, v_prize_key, v_prize_label, v_prize_type
  from public.game_wheel_segments
  order by random()
  limit 1;

  if v_slot is null then
    raise exception using errcode = 'P0001', message = 'wheel_has_no_segments';
  end if;

  v_status := case when v_prize_type = 'loss' then 'lost' else 'unused' end;

  begin
    insert into public.game_wheel_spins (
      user_id, player_name, slot_index, prize_key, prize_label,
      prize_type, redemption_status, draw_date
    ) values (
      v_user_id, v_player_name, v_slot, v_prize_key, v_prize_label,
      v_prize_type, v_status, v_draw_date
    ) returning id into v_spin_id;
  exception when unique_violation then
    raise exception using errcode = 'P0001', message = 'daily_spin_limit';
  end;

  return jsonb_build_object(
    'id', v_spin_id,
    'slot_index', v_slot,
    'prize_key', v_prize_key,
    'prize_label', v_prize_label,
    'prize_type', v_prize_type,
    'redemption_status', v_status
  );
end;
$$;

revoke all on function public.spin_nostra_wheel() from public;
grant execute on function public.spin_nostra_wheel() to authenticated;

notify pgrst, 'reload schema';
