-- Nostra Group V137
-- Commissions/objectifs commerciaux + Nostra Racing Academy.
-- Script réexécutable. Aucun ancien SQL ne doit être relancé.

create or replace function public.nostra_v137_has_any_role(p_roles text[])
returns boolean
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_profile jsonb := '{}'::jsonb;
  v_claims jsonb := coalesce(auth.jwt(), '{}'::jsonb);
  v_role_text text := '';
begin
  if auth.uid() is null then return false; end if;

  select to_jsonb(profile) into v_profile
  from public.member_profiles profile
  where profile.user_id = auth.uid()
  limit 1;

  v_role_text := lower(
    coalesce(v_profile->>'role','') || ' ' ||
    coalesce(v_profile->>'roles','') || ' ' ||
    coalesce(v_claims->>'role','') || ' ' ||
    coalesce(v_claims->'app_metadata'->>'role','') || ' ' ||
    coalesce(v_claims->'app_metadata'->>'roles','') || ' ' ||
    coalesce(v_claims->'user_metadata'->>'role','') || ' ' ||
    coalesce(v_claims->'user_metadata'->>'roles','')
  );

  if coalesce(v_profile->>'discord_id','') = '331843410962939908' then
    return 'manager' = any(p_roles);
  end if;

  return exists (
    select 1 from unnest(p_roles) wanted
    where v_role_text like '%' || lower(wanted) || '%'
       or (wanted = 'manager' and v_role_text ~ '(gerant|gérant|direction|administrator|admin)')
       or (wanted = 'commissioner' and v_role_text ~ '(commissaire|steward)')
       or (wanted = 'commercial' and v_role_text ~ '(commercial|vendeur)')
       or (wanted = 'employee' and v_role_text ~ '(employe|employé|staff)')
  );
end;
$$;

revoke all on function public.nostra_v137_has_any_role(text[]) from public, anon;
grant execute on function public.nostra_v137_has_any_role(text[]) to authenticated;

-- ---------------------------------------------------------------------------
-- 1. COMMISSIONS ET OBJECTIFS DES COMMERCIAUX
-- ---------------------------------------------------------------------------

create table if not exists public.commercial_commission_settings_v137 (
  id smallint primary key default 1 check (id = 1),
  enabled boolean not null default true,
  commission_mode text not null default 'percent' check (commission_mode in ('percent','fixed')),
  commission_value numeric(14,2) not null default 2 check (commission_value >= 0),
  updated_by uuid references auth.users(id) on delete set null,
  updated_at timestamptz not null default now()
);

insert into public.commercial_commission_settings_v137 (id)
values (1) on conflict (id) do nothing;

create table if not exists public.commercial_objectives_v137 (
  id bigint generated by default as identity primary key,
  commercial_user_id uuid not null references auth.users(id) on delete cascade,
  commercial_name text not null,
  objective_month date not null,
  sales_target integer not null default 0 check (sales_target >= 0),
  revenue_target numeric(14,2) not null default 0 check (revenue_target >= 0),
  target_bonus numeric(14,2) not null default 0 check (target_bonus >= 0),
  paid_at timestamptz,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (commercial_user_id, objective_month),
  check (objective_month = date_trunc('month', objective_month)::date)
);

create table if not exists public.commercial_commissions_v137 (
  id bigint generated by default as identity primary key,
  order_id bigint not null unique references public.orders(id) on delete cascade,
  order_number text not null,
  commercial_user_id uuid not null references auth.users(id) on delete cascade,
  commercial_name text not null,
  sale_amount numeric(14,2) not null default 0 check (sale_amount >= 0),
  commission_mode text not null check (commission_mode in ('percent','fixed')),
  commission_value numeric(14,2) not null default 0 check (commission_value >= 0),
  commission_amount numeric(14,2) not null default 0 check (commission_amount >= 0),
  status text not null default 'pending' check (status in ('pending','approved','paid','cancelled')),
  sale_date date not null default current_date,
  paid_at timestamptz,
  payment_id bigint,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.commercial_payments_v137 (
  id bigint generated by default as identity primary key,
  commercial_user_id uuid not null references auth.users(id) on delete cascade,
  commercial_name text not null,
  payment_month date not null,
  commission_total numeric(14,2) not null default 0,
  objective_bonus numeric(14,2) not null default 0,
  total_paid numeric(14,2) not null default 0,
  accounting_entry_id bigint references public.accounting_entries(id) on delete set null,
  paid_by uuid references auth.users(id) on delete set null,
  paid_at timestamptz not null default now(),
  unique (commercial_user_id, payment_month),
  check (payment_month = date_trunc('month', payment_month)::date)
);

alter table public.orders add column if not exists commercial_user_id uuid references auth.users(id) on delete set null;
alter table public.orders add column if not exists commercial_name text;

create index if not exists commercial_commissions_month_v137_idx
  on public.commercial_commissions_v137 (commercial_user_id, sale_date desc);
create index if not exists commercial_objectives_month_v137_idx
  on public.commercial_objectives_v137 (objective_month desc, commercial_user_id);

create or replace function public.sync_order_commission_v137()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_settings public.commercial_commission_settings_v137%rowtype;
  v_amount numeric(14,2);
begin
  if new.status = 'completed' and new.commercial_user_id is not null then
    select * into v_settings from public.commercial_commission_settings_v137 where id = 1;
    if coalesce(v_settings.enabled, false) then
      v_amount := case
        when v_settings.commission_mode = 'fixed' then v_settings.commission_value
        else round(greatest(0, coalesce(new.total,0)) * v_settings.commission_value / 100, 2)
      end;

      insert into public.commercial_commissions_v137 (
        order_id, order_number, commercial_user_id, commercial_name, sale_amount,
        commission_mode, commission_value, commission_amount, status, sale_date, updated_at
      ) values (
        new.id, new.order_number, new.commercial_user_id,
        coalesce(nullif(new.commercial_name,''),'Commercial'), greatest(0,coalesce(new.total,0)),
        v_settings.commission_mode, v_settings.commission_value, greatest(0,v_amount),
        'pending', current_date, now()
      )
      on conflict (order_id) do update set
        commercial_user_id = excluded.commercial_user_id,
        commercial_name = excluded.commercial_name,
        sale_amount = excluded.sale_amount,
        commission_mode = case when public.commercial_commissions_v137.status = 'paid' then public.commercial_commissions_v137.commission_mode else excluded.commission_mode end,
        commission_value = case when public.commercial_commissions_v137.status = 'paid' then public.commercial_commissions_v137.commission_value else excluded.commission_value end,
        commission_amount = case when public.commercial_commissions_v137.status = 'paid' then public.commercial_commissions_v137.commission_amount else excluded.commission_amount end,
        status = case when public.commercial_commissions_v137.status = 'paid' then 'paid' else 'pending' end,
        updated_at = now();
    end if;
  elsif new.status = 'cancelled' or (old.status = 'completed' and new.status <> 'completed') then
    update public.commercial_commissions_v137
    set status = 'cancelled', updated_at = now()
    where order_id = new.id and status <> 'paid';
  end if;
  return new;
end;
$$;

drop trigger if exists sync_order_commission_v137 on public.orders;
create trigger sync_order_commission_v137
after insert or update of status, total, commercial_user_id, commercial_name on public.orders
for each row execute function public.sync_order_commission_v137();

create or replace function public.assign_order_commercial_v137(
  p_order_id bigint,
  p_commercial_user_id uuid
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare v_name text;
begin
  if not public.nostra_v137_has_any_role(array['manager']) then
    raise exception using message = 'manager_required';
  end if;

  if p_commercial_user_id is null then
    update public.orders set commercial_user_id = null, commercial_name = null where id = p_order_id;
    return;
  end if;

  select nullif(btrim(concat_ws(' ', rp_first_name, rp_last_name)),'')
  into v_name from public.member_profiles where user_id = p_commercial_user_id;
  if v_name is null then
    select coalesce(discord_name, email, 'Commercial') into v_name
    from public.member_profiles where user_id = p_commercial_user_id;
  end if;
  if v_name is null then raise exception using message = 'commercial_not_found'; end if;

  update public.orders
  set commercial_user_id = p_commercial_user_id, commercial_name = v_name
  where id = p_order_id;
end;
$$;

create or replace function public.pay_commercial_month_v137(
  p_commercial_user_id uuid,
  p_month date
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_month date := date_trunc('month', p_month)::date;
  v_name text;
  v_commission numeric(14,2) := 0;
  v_revenue numeric(14,2) := 0;
  v_sales integer := 0;
  v_bonus numeric(14,2) := 0;
  v_total numeric(14,2) := 0;
  v_payment_id bigint;
  v_accounting_id bigint;
  v_objective public.commercial_objectives_v137%rowtype;
begin
  if not public.nostra_v137_has_any_role(array['manager']) then
    raise exception using message = 'manager_required';
  end if;

  if exists (select 1 from public.commercial_payments_v137 where commercial_user_id=p_commercial_user_id and payment_month=v_month) then
    raise exception using message = 'month_already_paid';
  end if;

  select coalesce(max(commercial_name),'Commercial'), coalesce(sum(commission_amount),0),
         coalesce(sum(sale_amount),0), count(*)::integer
  into v_name, v_commission, v_revenue, v_sales
  from public.commercial_commissions_v137
  where commercial_user_id=p_commercial_user_id
    and sale_date >= v_month and sale_date < (v_month + interval '1 month')::date
    and status in ('pending','approved');

  select * into v_objective from public.commercial_objectives_v137
  where commercial_user_id=p_commercial_user_id and objective_month=v_month;

  if found and v_sales >= v_objective.sales_target and v_revenue >= v_objective.revenue_target then
    v_bonus := v_objective.target_bonus;
  end if;
  v_total := v_commission + v_bonus;
  if v_total <= 0 then raise exception using message = 'nothing_to_pay'; end if;

  insert into public.accounting_entries(entry_date,entry_type,category,label,amount,notes)
  values(current_date,'expense','Commissions commerciales','Commissions ' || v_name || ' — ' || to_char(v_month,'MM/YYYY'),v_total,
    'Commissions : ' || v_commission || ' € · Bonus objectif : ' || v_bonus || ' €')
  returning id into v_accounting_id;

  insert into public.commercial_payments_v137(
    commercial_user_id,commercial_name,payment_month,commission_total,objective_bonus,total_paid,accounting_entry_id,paid_by
  ) values(p_commercial_user_id,v_name,v_month,v_commission,v_bonus,v_total,v_accounting_id,auth.uid())
  returning id into v_payment_id;

  update public.commercial_commissions_v137 set status='paid',paid_at=now(),payment_id=v_payment_id,updated_at=now()
  where commercial_user_id=p_commercial_user_id and sale_date >= v_month
    and sale_date < (v_month + interval '1 month')::date and status in ('pending','approved');
  update public.commercial_objectives_v137 set paid_at=now(),updated_at=now()
  where commercial_user_id=p_commercial_user_id and objective_month=v_month;

  return jsonb_build_object('payment_id',v_payment_id,'commission',v_commission,'bonus',v_bonus,'total',v_total);
end;
$$;

revoke all on function public.assign_order_commercial_v137(bigint,uuid) from public, anon;
revoke all on function public.pay_commercial_month_v137(uuid,date) from public, anon;
grant execute on function public.assign_order_commercial_v137(bigint,uuid) to authenticated;
grant execute on function public.pay_commercial_month_v137(uuid,date) to authenticated;

alter table public.commercial_commission_settings_v137 enable row level security;
alter table public.commercial_objectives_v137 enable row level security;
alter table public.commercial_commissions_v137 enable row level security;
alter table public.commercial_payments_v137 enable row level security;

drop policy if exists "commission settings read v137" on public.commercial_commission_settings_v137;
create policy "commission settings read v137" on public.commercial_commission_settings_v137 for select to authenticated using (public.nostra_v137_has_any_role(array['manager','commercial']));
drop policy if exists "commission settings manager v137" on public.commercial_commission_settings_v137;
create policy "commission settings manager v137" on public.commercial_commission_settings_v137 for all to authenticated using (public.nostra_v137_has_any_role(array['manager'])) with check (public.nostra_v137_has_any_role(array['manager']));

drop policy if exists "commercial objectives read v137" on public.commercial_objectives_v137;
create policy "commercial objectives read v137" on public.commercial_objectives_v137 for select to authenticated using (commercial_user_id=auth.uid() or public.nostra_v137_has_any_role(array['manager']));
drop policy if exists "commercial objectives manager v137" on public.commercial_objectives_v137;
create policy "commercial objectives manager v137" on public.commercial_objectives_v137 for all to authenticated using (public.nostra_v137_has_any_role(array['manager'])) with check (public.nostra_v137_has_any_role(array['manager']));

drop policy if exists "commercial commissions read v137" on public.commercial_commissions_v137;
create policy "commercial commissions read v137" on public.commercial_commissions_v137 for select to authenticated using (commercial_user_id=auth.uid() or public.nostra_v137_has_any_role(array['manager']));
drop policy if exists "commercial commissions manager v137" on public.commercial_commissions_v137;
create policy "commercial commissions manager v137" on public.commercial_commissions_v137 for all to authenticated using (public.nostra_v137_has_any_role(array['manager'])) with check (public.nostra_v137_has_any_role(array['manager']));

drop policy if exists "commercial payments read v137" on public.commercial_payments_v137;
create policy "commercial payments read v137" on public.commercial_payments_v137 for select to authenticated using (commercial_user_id=auth.uid() or public.nostra_v137_has_any_role(array['manager']));

grant select,insert,update,delete on public.commercial_commission_settings_v137 to authenticated;
grant select,insert,update,delete on public.commercial_objectives_v137 to authenticated;
grant select,insert,update,delete on public.commercial_commissions_v137 to authenticated;
grant select on public.commercial_payments_v137 to authenticated;
grant usage,select on sequence public.commercial_objectives_v137_id_seq to authenticated;
grant usage,select on sequence public.commercial_commissions_v137_id_seq to authenticated;
grant usage,select on sequence public.commercial_payments_v137_id_seq to authenticated;

-- ---------------------------------------------------------------------------
-- 2. NOSTRA RACING ACADEMY
-- ---------------------------------------------------------------------------

create table if not exists public.academy_courses_v137 (
  id bigint generated by default as identity primary key,
  title text not null,
  description text not null,
  duration_label text not null default 'À définir',
  max_participants integer not null default 10 check (max_participants > 0),
  theory_pass_score numeric(5,2) not null default 70 check (theory_pass_score between 0 and 100),
  practical_pass_score numeric(5,2) not null default 70 check (practical_pass_score between 0 and 100),
  qualification_label text not null,
  active boolean not null default true,
  sort_order integer not null default 0,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.academy_enrollments_v137 (
  id bigint generated by default as identity primary key,
  course_id bigint not null references public.academy_courses_v137(id) on delete restrict,
  user_id uuid not null references auth.users(id) on delete cascade,
  applicant_name text not null,
  motivation text,
  status text not null default 'pending' check (status in ('pending','accepted','training','passed','failed','cancelled')),
  theory_score numeric(5,2) check (theory_score between 0 and 100),
  practical_score numeric(5,2) check (practical_score between 0 and 100),
  instructor_name text,
  staff_note text,
  applied_at timestamptz not null default now(),
  completed_at timestamptz,
  updated_at timestamptz not null default now(),
  unique (course_id,user_id)
);

create table if not exists public.academy_qualifications_v137 (
  id bigint generated by default as identity primary key,
  qualification_number text unique not null,
  enrollment_id bigint unique not null references public.academy_enrollments_v137(id) on delete restrict,
  course_id bigint not null references public.academy_courses_v137(id) on delete restrict,
  user_id uuid not null references auth.users(id) on delete cascade,
  holder_name text not null,
  qualification_label text not null,
  theory_score numeric(5,2) not null,
  practical_score numeric(5,2) not null,
  issued_at timestamptz not null default now(),
  active boolean not null default true
);

create index if not exists academy_enrollments_status_v137_idx on public.academy_enrollments_v137(status,applied_at desc);
create index if not exists academy_qualifications_user_v137_idx on public.academy_qualifications_v137(user_id,issued_at desc);

create or replace function public.issue_academy_qualification_v137()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare v_course public.academy_courses_v137%rowtype;
begin
  if new.status <> 'passed' then return new; end if;
  select * into v_course from public.academy_courses_v137 where id=new.course_id;
  if new.theory_score is null or new.practical_score is null
     or new.theory_score < v_course.theory_pass_score
     or new.practical_score < v_course.practical_pass_score then
    raise exception using message='passing_scores_required';
  end if;

  insert into public.academy_qualifications_v137(
    qualification_number,enrollment_id,course_id,user_id,holder_name,qualification_label,theory_score,practical_score
  ) values(
    'NRA-' || to_char(current_date,'YYYY') || '-' || lpad(new.id::text,6,'0'),
    new.id,new.course_id,new.user_id,new.applicant_name,v_course.qualification_label,new.theory_score,new.practical_score
  ) on conflict (enrollment_id) do update set
    holder_name=excluded.holder_name,qualification_label=excluded.qualification_label,
    theory_score=excluded.theory_score,practical_score=excluded.practical_score,active=true;

  new.completed_at := coalesce(new.completed_at,now());
  return new;
end;
$$;

drop trigger if exists issue_academy_qualification_v137 on public.academy_enrollments_v137;
create trigger issue_academy_qualification_v137
before insert or update of status,theory_score,practical_score on public.academy_enrollments_v137
for each row execute function public.issue_academy_qualification_v137();

alter table public.academy_courses_v137 enable row level security;
alter table public.academy_enrollments_v137 enable row level security;
alter table public.academy_qualifications_v137 enable row level security;

drop policy if exists "academy courses public read v137" on public.academy_courses_v137;
create policy "academy courses public read v137" on public.academy_courses_v137 for select to authenticated using (active or public.nostra_v137_has_any_role(array['manager','commissioner']));
drop policy if exists "academy courses staff manage v137" on public.academy_courses_v137;
create policy "academy courses staff manage v137" on public.academy_courses_v137 for all to authenticated using (public.nostra_v137_has_any_role(array['manager','commissioner'])) with check (public.nostra_v137_has_any_role(array['manager','commissioner']));

drop policy if exists "academy enrollments read v137" on public.academy_enrollments_v137;
create policy "academy enrollments read v137" on public.academy_enrollments_v137 for select to authenticated using (user_id=auth.uid() or public.nostra_v137_has_any_role(array['manager','commissioner']));
drop policy if exists "academy enrollments citizen create v137" on public.academy_enrollments_v137;
create policy "academy enrollments citizen create v137" on public.academy_enrollments_v137 for insert to authenticated with check (user_id=auth.uid() and status='pending');
drop policy if exists "academy enrollments citizen cancel v137" on public.academy_enrollments_v137;
create policy "academy enrollments citizen cancel v137" on public.academy_enrollments_v137 for update to authenticated using (user_id=auth.uid() and status in ('pending','accepted')) with check (user_id=auth.uid() and status='cancelled');
drop policy if exists "academy enrollments staff manage v137" on public.academy_enrollments_v137;
create policy "academy enrollments staff manage v137" on public.academy_enrollments_v137 for all to authenticated using (public.nostra_v137_has_any_role(array['manager','commissioner'])) with check (public.nostra_v137_has_any_role(array['manager','commissioner']));

drop policy if exists "academy qualifications read v137" on public.academy_qualifications_v137;
create policy "academy qualifications read v137" on public.academy_qualifications_v137 for select to authenticated using (user_id=auth.uid() or public.nostra_v137_has_any_role(array['manager','commissioner']));
drop policy if exists "academy qualifications staff manage v137" on public.academy_qualifications_v137;
create policy "academy qualifications staff manage v137" on public.academy_qualifications_v137 for all to authenticated using (public.nostra_v137_has_any_role(array['manager','commissioner'])) with check (public.nostra_v137_has_any_role(array['manager','commissioner']));

grant select,insert,update,delete on public.academy_courses_v137 to authenticated;
grant select,insert,update,delete on public.academy_enrollments_v137 to authenticated;
grant select,insert,update on public.academy_qualifications_v137 to authenticated;
grant usage,select on sequence public.academy_courses_v137_id_seq to authenticated;
grant usage,select on sequence public.academy_enrollments_v137_id_seq to authenticated;
grant usage,select on sequence public.academy_qualifications_v137_id_seq to authenticated;

select 'V137 prête · commissions commerciaux et Nostra Racing Academy' as resultat;
