-- NOSTRA V163 — Gestion commerciale concessionnaire
-- Fournisseurs / arrivages, marges réelles, CRM après-vente et garanties Nostra Care.
-- AUCUN module assurance dans cette version.
-- À exécuter après V162.

begin;

-- -----------------------------------------------------------------------------
-- 1) FOURNISSEURS / ARRIVAGES
-- -----------------------------------------------------------------------------
create table if not exists public.motors_suppliers_v163 (
  id bigint generated by default as identity primary key,
  name text not null,
  contact_name text,
  email text,
  phone text,
  brands text[] not null default '{}'::text[],
  lead_time_days integer not null default 0 check (lead_time_days >= 0),
  default_discount_percent numeric(7,3) not null default 0,
  payment_terms text,
  notes text,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references auth.users(id) on delete set null
);

create table if not exists public.motors_supplier_orders_v163 (
  id bigint generated by default as identity primary key,
  order_number text not null unique,
  supplier_id bigint not null references public.motors_suppliers_v163(id) on delete restrict,
  status text not null default 'draft' check (status in ('draft','ordered','confirmed','in_transit','arrived','received','cancelled')),
  ordered_at timestamptz,
  expected_at timestamptz,
  received_at timestamptz,
  inbound_transport_cost numeric(14,2) not null default 0,
  other_cost numeric(14,2) not null default 0,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references auth.users(id) on delete set null
);

create table if not exists public.motors_supplier_order_items_v163 (
  id bigint generated by default as identity primary key,
  supplier_order_id bigint not null references public.motors_supplier_orders_v163(id) on delete cascade,
  catalog_vehicle_id bigint not null references public.catalog_vehicles(id) on delete restrict,
  quantity integer not null default 1 check (quantity > 0),
  unit_purchase_cost numeric(14,2) not null default 0,
  preparation_cost_per_unit numeric(14,2) not null default 0,
  received_quantity integer not null default 0 check (received_quantity >= 0),
  created_at timestamptz not null default now()
);

create table if not exists public.motors_vehicle_costs_v163 (
  catalog_vehicle_id bigint primary key references public.catalog_vehicles(id) on delete cascade,
  supplier_id bigint references public.motors_suppliers_v163(id) on delete set null,
  purchase_cost numeric(14,2) not null default 0,
  inbound_transport_per_unit numeric(14,2) not null default 0,
  preparation_cost numeric(14,2) not null default 0,
  other_cost numeric(14,2) not null default 0,
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id) on delete set null
);

-- -----------------------------------------------------------------------------
-- 2) GARANTIES NOSTRA CARE
-- -----------------------------------------------------------------------------
create table if not exists public.motors_warranty_plans_v163 (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  duration_days integer not null default 30 check (duration_days > 0),
  price numeric(14,2) not null default 0,
  deductible numeric(14,2) not null default 0,
  engine boolean not null default true,
  gearbox boolean not null default true,
  electronics boolean not null default true,
  suspension boolean not null default true,
  bodywork boolean not null default false,
  tyres boolean not null default false,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references auth.users(id) on delete set null
);

create table if not exists public.motors_warranty_contracts_v163 (
  id bigint generated by default as identity primary key,
  contract_number text not null unique,
  user_id uuid not null references auth.users(id) on delete cascade,
  customer_vehicle_id bigint not null,
  plan_id bigint references public.motors_warranty_plans_v163(id) on delete set null,
  plan_name text not null,
  duration_days integer not null,
  amount numeric(14,2) not null default 0,
  deductible numeric(14,2) not null default 0,
  starts_at timestamptz not null,
  ends_at timestamptz not null,
  status text not null default 'pending_payment' check (status in ('pending_payment','active','expired','cancelled')),
  coverage_snapshot jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- -----------------------------------------------------------------------------
-- 3) INDEXES
-- -----------------------------------------------------------------------------
create index if not exists motors_supplier_orders_v163_supplier_idx on public.motors_supplier_orders_v163(supplier_id,status,expected_at);
create index if not exists motors_warranty_contracts_v163_user_idx on public.motors_warranty_contracts_v163(user_id,customer_vehicle_id,status,ends_at);

-- -----------------------------------------------------------------------------
-- 4) RLS
-- -----------------------------------------------------------------------------
alter table public.motors_suppliers_v163 enable row level security;
alter table public.motors_supplier_orders_v163 enable row level security;
alter table public.motors_supplier_order_items_v163 enable row level security;
alter table public.motors_vehicle_costs_v163 enable row level security;
alter table public.motors_warranty_plans_v163 enable row level security;
alter table public.motors_warranty_contracts_v163 enable row level security;

drop policy if exists "v163 staff suppliers" on public.motors_suppliers_v163;
create policy "v163 staff suppliers" on public.motors_suppliers_v163 for all to authenticated using (public.has_nostra_dashboard_access()) with check (public.has_nostra_dashboard_access());
drop policy if exists "v163 staff supplier orders" on public.motors_supplier_orders_v163;
create policy "v163 staff supplier orders" on public.motors_supplier_orders_v163 for all to authenticated using (public.has_nostra_dashboard_access()) with check (public.has_nostra_dashboard_access());
drop policy if exists "v163 staff supplier items" on public.motors_supplier_order_items_v163;
create policy "v163 staff supplier items" on public.motors_supplier_order_items_v163 for all to authenticated using (public.has_nostra_dashboard_access()) with check (public.has_nostra_dashboard_access());
drop policy if exists "v163 staff vehicle costs" on public.motors_vehicle_costs_v163;
create policy "v163 staff vehicle costs" on public.motors_vehicle_costs_v163 for all to authenticated using (public.has_nostra_dashboard_access()) with check (public.has_nostra_dashboard_access());

drop policy if exists "v163 read warranty plans" on public.motors_warranty_plans_v163;
create policy "v163 read warranty plans" on public.motors_warranty_plans_v163 for select to authenticated using (active or public.has_nostra_dashboard_access());
drop policy if exists "v163 manage warranty plans" on public.motors_warranty_plans_v163;
create policy "v163 manage warranty plans" on public.motors_warranty_plans_v163 for all to authenticated using (public.has_nostra_dashboard_access()) with check (public.has_nostra_dashboard_access());

drop policy if exists "v163 own warranty contracts" on public.motors_warranty_contracts_v163;
create policy "v163 own warranty contracts" on public.motors_warranty_contracts_v163 for select to authenticated using (user_id=auth.uid() or public.has_nostra_dashboard_access());
drop policy if exists "v163 staff warranty contracts" on public.motors_warranty_contracts_v163;
create policy "v163 staff warranty contracts" on public.motors_warranty_contracts_v163 for all to authenticated using (public.has_nostra_dashboard_access()) with check (public.has_nostra_dashboard_access());

-- -----------------------------------------------------------------------------
-- 5) SOUSCRIPTION GARANTIE NOSTRA CARE
-- -----------------------------------------------------------------------------
create or replace function public.nostra_subscribe_warranty_v163(
  p_customer_vehicle_id bigint,
  p_plan_id bigint,
  p_start_at timestamptz default now()
)
returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare
  v_uid uuid := auth.uid();
  v_vehicle record;
  v_plan record;
  v_id bigint;
  v_number text;
  v_start timestamptz := coalesce(p_start_at,now());
begin
  if v_uid is null then raise exception using message='not_authenticated'; end if;
  select id,user_id into v_vehicle from public.customer_vehicles where id=p_customer_vehicle_id and user_id=v_uid and garage_status <> 'cancelled';
  if not found then raise exception using message='vehicle_not_found'; end if;
  select * into v_plan from public.motors_warranty_plans_v163 where id=p_plan_id and active;
  if not found then raise exception using message='warranty_plan_not_found'; end if;
  if exists(select 1 from public.motors_warranty_contracts_v163 where user_id=v_uid and customer_vehicle_id=p_customer_vehicle_id and status in ('pending_payment','active') and ends_at>now()) then
    raise exception using message='warranty_already_exists';
  end if;
  v_number := 'NG-' || to_char(now(),'YYYYMMDD') || '-' || upper(substr(replace(gen_random_uuid()::text,'-',''),1,7));
  insert into public.motors_warranty_contracts_v163(contract_number,user_id,customer_vehicle_id,plan_id,plan_name,duration_days,amount,deductible,starts_at,ends_at,status,coverage_snapshot)
  values(v_number,v_uid,p_customer_vehicle_id,v_plan.id,v_plan.name,v_plan.duration_days,v_plan.price,v_plan.deductible,v_start,v_start+make_interval(days=>v_plan.duration_days),'pending_payment',jsonb_build_object('engine',v_plan.engine,'gearbox',v_plan.gearbox,'electronics',v_plan.electronics,'suspension',v_plan.suspension,'bodywork',v_plan.bodywork,'tyres',v_plan.tyres)) returning id into v_id;
  return jsonb_build_object('id',v_id,'contract_number',v_number,'amount',v_plan.price,'duration_days',v_plan.duration_days);
end;
$$;
grant execute on function public.nostra_subscribe_warranty_v163(bigint,bigint,timestamptz) to authenticated;

-- -----------------------------------------------------------------------------
-- 6) RÉCEPTION FOURNISSEUR : STOCK + COÛT RÉEL + EXEMPLAIRES V162
-- -----------------------------------------------------------------------------
create or replace function public.nostra_receive_supplier_order_v163(p_order_id bigint)
returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare
  v_order record;
  v_item record;
  v_total_qty integer := 0;
  v_total_units integer := 0;
  v_transport_per_unit numeric(14,2) := 0;
  i integer;
begin
  if not public.has_nostra_dashboard_access() then raise exception using message='forbidden'; end if;
  select * into v_order from public.motors_supplier_orders_v163 where id=p_order_id for update;
  if not found then raise exception using message='supplier_order_not_found'; end if;
  if v_order.status='received' then return jsonb_build_object('already_received',true); end if;
  select coalesce(sum(quantity),0)::integer into v_total_units from public.motors_supplier_order_items_v163 where supplier_order_id=p_order_id;
  if v_total_units>0 then v_transport_per_unit := round(coalesce(v_order.inbound_transport_cost,0)/v_total_units,2); end if;
  for v_item in select * from public.motors_supplier_order_items_v163 where supplier_order_id=p_order_id loop
    update public.catalog_vehicles set stock_quantity=coalesce(stock_quantity,0)+v_item.quantity,updated_at=now() where id=v_item.catalog_vehicle_id;
    update public.motors_supplier_order_items_v163 set received_quantity=v_item.quantity where id=v_item.id;
    insert into public.motors_vehicle_costs_v163(catalog_vehicle_id,supplier_id,purchase_cost,inbound_transport_per_unit,preparation_cost,other_cost,updated_at,updated_by)
    values(v_item.catalog_vehicle_id,v_order.supplier_id,v_item.unit_purchase_cost,v_transport_per_unit,v_item.preparation_cost_per_unit,case when v_total_units>0 then round(coalesce(v_order.other_cost,0)/v_total_units,2) else 0 end,now(),auth.uid())
    on conflict(catalog_vehicle_id) do update set supplier_id=excluded.supplier_id,purchase_cost=excluded.purchase_cost,inbound_transport_per_unit=excluded.inbound_transport_per_unit,preparation_cost=excluded.preparation_cost,other_cost=excluded.other_cost,updated_at=now(),updated_by=auth.uid();
    begin
      for i in 1..v_item.quantity loop
        execute format('insert into public.motors_physical_vehicle_units_v162(unit_code,catalog_vehicle_id,status,location) values ($1,$2,$3,$4)')
        using 'NM-'||v_item.catalog_vehicle_id||'-'||upper(substr(replace(gen_random_uuid()::text,'-',''),1,7)),v_item.catalog_vehicle_id,'arrived','Réception fournisseur';
      end loop;
    exception when undefined_table then null;
    end;
    v_total_qty := v_total_qty + v_item.quantity;
  end loop;
  update public.motors_supplier_orders_v163 set status='received',received_at=now(),updated_at=now() where id=p_order_id;
  return jsonb_build_object('received_quantity',v_total_qty);
end;
$$;
grant execute on function public.nostra_receive_supplier_order_v163(bigint) to authenticated;

-- -----------------------------------------------------------------------------
-- 7) DONNÉES DE DÉPART GARANTIES
-- -----------------------------------------------------------------------------
insert into public.motors_warranty_plans_v163(name,description,duration_days,price,deductible,engine,gearbox,electronics,suspension,bodywork,tyres)
select 'Nostra Care 90','Garantie mécanique courte durée.',90,75000,0,true,true,true,true,false,false
where not exists(select 1 from public.motors_warranty_plans_v163 where name='Nostra Care 90');
insert into public.motors_warranty_plans_v163(name,description,duration_days,price,deductible,engine,gearbox,electronics,suspension,bodywork,tyres)
select 'Nostra Care+ 180','Garantie étendue Nostra Motors.',180,140000,10000,true,true,true,true,true,false
where not exists(select 1 from public.motors_warranty_plans_v163 where name='Nostra Care+ 180');

commit;

select
  to_regclass('public.motors_suppliers_v163') as suppliers,
  to_regclass('public.motors_supplier_orders_v163') as supplier_orders,
  to_regclass('public.motors_vehicle_costs_v163') as vehicle_costs,
  to_regclass('public.motors_warranty_plans_v163') as warranty_plans,
  to_regclass('public.motors_warranty_contracts_v163') as warranty_contracts;
