-- NOSTRA GROUP — extension du dashboard
-- Ce script conserve les contenus déjà enregistrés.

create or replace function public.is_nostra_manager()
returns boolean
language sql
stable
as $$
  select coalesce(
    auth.jwt() -> 'user_metadata' ->> 'provider_id',
    auth.jwt() -> 'user_metadata' ->> 'discord_id',
    auth.jwt() -> 'user_metadata' ->> 'sub'
  ) = '331843410962939908';
$$;

grant execute on function public.is_nostra_manager() to authenticated;

create table if not exists public.circuit_settings (
  id integer primary key default 1 check (id = 1),
  status text not null default 'open',
  label text not null default 'Circuit ouvert',
  message text not null default 'Le Nostra Circuit est actuellement ouvert.',
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id) on delete set null
);

insert into public.circuit_settings (id)
values (1)
on conflict (id) do nothing;

create table if not exists public.inventory_items (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null default 'Général',
  sku text,
  quantity integer not null default 0 check (quantity >= 0),
  minimum_quantity integer not null default 0 check (minimum_quantity >= 0),
  unit_price numeric(12,2) not null default 0 check (unit_price >= 0),
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id) on delete set null
);

create table if not exists public.accounting_entries (
  id bigint generated by default as identity primary key,
  entry_date date not null default current_date,
  entry_type text not null check (entry_type in ('income', 'expense')),
  category text not null default 'Général',
  label text not null,
  amount numeric(12,2) not null check (amount >= 0),
  notes text,
  created_at timestamptz not null default now(),
  created_by uuid references auth.users(id) on delete set null
);

create table if not exists public.events (
  id bigint generated by default as identity primary key,
  title text not null,
  description text not null default '',
  location text not null default '',
  starts_at timestamptz not null,
  ends_at timestamptz,
  status text not null default 'draft' check (status in ('draft', 'published', 'cancelled', 'completed')),
  registration_open boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references auth.users(id) on delete set null
);

create table if not exists public.homologation_requests (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  request_type text not null check (request_type in ('vehicle', 'team')),
  applicant_name text not null,
  status text not null default 'pending' check (status in ('pending', 'reviewing', 'approved', 'rejected')),
  payload jsonb not null default '{}'::jsonb,
  admin_note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  order_number text not null unique,
  status text not null default 'pending',
  total numeric(12,2) not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.invoices (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  invoice_number text not null unique,
  status text not null default 'issued',
  amount numeric(12,2) not null default 0,
  issued_at timestamptz not null default now(),
  download_url text
);

create table if not exists public.loyalty_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  tier text not null default 'Aucun statut',
  purchases_count integer not null default 0,
  discount_percent numeric(5,2) not null default 0,
  updated_at timestamptz not null default now()
);

create table if not exists public.cart_items (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  item_name text not null,
  quantity integer not null default 1 check (quantity > 0),
  unit_price numeric(12,2) not null default 0,
  image_url text,
  created_at timestamptz not null default now()
);

alter table public.circuit_settings enable row level security;
alter table public.inventory_items enable row level security;
alter table public.accounting_entries enable row level security;
alter table public.events enable row level security;
alter table public.homologation_requests enable row level security;
alter table public.orders enable row level security;
alter table public.invoices enable row level security;
alter table public.loyalty_profiles enable row level security;
alter table public.cart_items enable row level security;

-- Lecture des informations publiques du site par les membres connectés.
drop policy if exists "circuit settings readable" on public.circuit_settings;
create policy "circuit settings readable" on public.circuit_settings
for select to authenticated using (true);

drop policy if exists "events readable" on public.events;
create policy "events readable" on public.events
for select to authenticated using (status <> 'draft' or public.is_nostra_manager());

-- Gestion complète réservée au gérant.
drop policy if exists "manager manages circuit settings" on public.circuit_settings;
create policy "manager manages circuit settings" on public.circuit_settings
for all to authenticated using (public.is_nostra_manager()) with check (public.is_nostra_manager());

drop policy if exists "manager manages inventory" on public.inventory_items;
create policy "manager manages inventory" on public.inventory_items
for all to authenticated using (public.is_nostra_manager()) with check (public.is_nostra_manager());

drop policy if exists "manager manages accounting" on public.accounting_entries;
create policy "manager manages accounting" on public.accounting_entries
for all to authenticated using (public.is_nostra_manager()) with check (public.is_nostra_manager());

drop policy if exists "manager manages events" on public.events;
create policy "manager manages events" on public.events
for all to authenticated using (public.is_nostra_manager()) with check (public.is_nostra_manager());

-- Les membres peuvent déposer et consulter leurs demandes d'homologation.
drop policy if exists "users create homologation requests" on public.homologation_requests;
create policy "users create homologation requests" on public.homologation_requests
for insert to authenticated with check (user_id = auth.uid());

drop policy if exists "users read homologation requests" on public.homologation_requests;
create policy "users read homologation requests" on public.homologation_requests
for select to authenticated using (user_id = auth.uid() or public.is_nostra_manager());

drop policy if exists "manager updates homologation requests" on public.homologation_requests;
create policy "manager updates homologation requests" on public.homologation_requests
for update to authenticated using (public.is_nostra_manager()) with check (public.is_nostra_manager());

drop policy if exists "manager deletes homologation requests" on public.homologation_requests;
create policy "manager deletes homologation requests" on public.homologation_requests
for delete to authenticated using (public.is_nostra_manager());

-- Espace client : chaque membre voit uniquement ses données, le gérant peut tout gérer.
drop policy if exists "users read own orders" on public.orders;
create policy "users read own orders" on public.orders
for select to authenticated using (user_id = auth.uid() or public.is_nostra_manager());
drop policy if exists "manager manages orders" on public.orders;
create policy "manager manages orders" on public.orders
for all to authenticated using (public.is_nostra_manager()) with check (public.is_nostra_manager());

drop policy if exists "users read own invoices" on public.invoices;
create policy "users read own invoices" on public.invoices
for select to authenticated using (user_id = auth.uid() or public.is_nostra_manager());
drop policy if exists "manager manages invoices" on public.invoices;
create policy "manager manages invoices" on public.invoices
for all to authenticated using (public.is_nostra_manager()) with check (public.is_nostra_manager());

drop policy if exists "users read own loyalty" on public.loyalty_profiles;
create policy "users read own loyalty" on public.loyalty_profiles
for select to authenticated using (user_id = auth.uid() or public.is_nostra_manager());
drop policy if exists "manager manages loyalty" on public.loyalty_profiles;
create policy "manager manages loyalty" on public.loyalty_profiles
for all to authenticated using (public.is_nostra_manager()) with check (public.is_nostra_manager());

drop policy if exists "users manage own cart" on public.cart_items;
create policy "users manage own cart" on public.cart_items
for all to authenticated using (user_id = auth.uid() or public.is_nostra_manager())
with check (user_id = auth.uid() or public.is_nostra_manager());