-- Nostra Group V161 — Réservations temporaires + adresses + centre logistique
-- À exécuter APRÈS V160.1 / V160.2.
-- Réexécutable : conserve les commandes existantes et les données déjà saisies.

begin;

-- ---------------------------------------------------------------------------
-- 1. Paramètres logistiques
-- ---------------------------------------------------------------------------
create table if not exists public.nostra_logistics_settings_v161 (
  singleton boolean primary key default true check (singleton),
  hold_minutes integer not null default 20 check (hold_minutes between 5 and 120),
  max_hold_vehicles integer not null default 10 check (max_hold_vehicles between 1 and 50),
  default_slot_minutes integer not null default 60 check (default_slot_minutes between 15 and 480),
  updated_at timestamptz not null default now()
);

insert into public.nostra_logistics_settings_v161(singleton)
values (true)
on conflict (singleton) do nothing;

alter table public.nostra_logistics_settings_v161 enable row level security;
drop policy if exists "v161 logistics settings readable" on public.nostra_logistics_settings_v161;
create policy "v161 logistics settings readable"
on public.nostra_logistics_settings_v161 for select to authenticated
using (true);

grant select on public.nostra_logistics_settings_v161 to authenticated;

-- ---------------------------------------------------------------------------
-- 2. Carnet d'adresses citoyen
-- ---------------------------------------------------------------------------
create table if not exists public.nostra_delivery_addresses_v161 (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  label text not null,
  address_line text not null,
  city text,
  zone text,
  phone text,
  instructions text,
  is_default boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists nostra_delivery_addresses_v161_user_idx
on public.nostra_delivery_addresses_v161(user_id, is_default desc, created_at);

create unique index if not exists nostra_delivery_addresses_v161_one_default_idx
on public.nostra_delivery_addresses_v161(user_id)
where is_default = true;

alter table public.nostra_delivery_addresses_v161 enable row level security;
drop policy if exists "v161 owner manages delivery addresses" on public.nostra_delivery_addresses_v161;
create policy "v161 owner manages delivery addresses"
on public.nostra_delivery_addresses_v161 for all to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid());

grant select, insert, update, delete on public.nostra_delivery_addresses_v161 to authenticated;
grant usage, select on sequence public.nostra_delivery_addresses_v161_id_seq to authenticated;

-- ---------------------------------------------------------------------------
-- 3. Réservation temporaire du stock pendant le panier
-- ---------------------------------------------------------------------------
create table if not exists public.nostra_vehicle_holds_v161 (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  vehicle_id bigint not null references public.catalog_vehicles(id) on delete cascade,
  quantity integer not null default 1 check (quantity > 0),
  status text not null default 'active' check (status in ('active','converted','released','expired')),
  expires_at timestamptz not null,
  order_id bigint references public.orders(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists nostra_vehicle_holds_v161_vehicle_active_idx
on public.nostra_vehicle_holds_v161(vehicle_id, expires_at)
where status = 'active';
create index if not exists nostra_vehicle_holds_v161_user_active_idx
on public.nostra_vehicle_holds_v161(user_id, expires_at)
where status = 'active';
create unique index if not exists nostra_vehicle_holds_v161_unique_active_idx
on public.nostra_vehicle_holds_v161(user_id, vehicle_id)
where status = 'active';

alter table public.nostra_vehicle_holds_v161 enable row level security;
drop policy if exists "v161 owner reads own vehicle holds" on public.nostra_vehicle_holds_v161;
create policy "v161 owner reads own vehicle holds"
on public.nostra_vehicle_holds_v161 for select to authenticated
using (user_id = auth.uid());

grant select on public.nostra_vehicle_holds_v161 to authenticated;

create or replace function public.nostra_cleanup_expired_holds_v161()
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_hold record;
  v_count integer := 0;
begin
  for v_hold in
    select id, user_id, vehicle_id
    from public.nostra_vehicle_holds_v161
    where status = 'active' and expires_at <= now()
    order by id
    for update skip locked
  loop
    update public.nostra_vehicle_holds_v161
    set status = 'expired', updated_at = now()
    where id = v_hold.id and status = 'active';

    if found then
      delete from public.cart_items
      where user_id = v_hold.user_id
        and (
          (item_type = 'vehicle' and vehicle_id = v_hold.vehicle_id)
          or (item_type = 'delivery' and related_vehicle_id = v_hold.vehicle_id)
        );
      v_count := v_count + 1;
    end if;
  end loop;
  return v_count;
end;
$$;

revoke all on function public.nostra_cleanup_expired_holds_v161() from public, anon;
grant execute on function public.nostra_cleanup_expired_holds_v161() to authenticated;

create or replace function public.nostra_vehicle_hold_counts_v161(p_vehicle_ids bigint[])
returns table(vehicle_id bigint, reserved_quantity integer)
language plpgsql
security definer
set search_path = public
as $$
begin
  perform public.nostra_cleanup_expired_holds_v161();
  return query
  select h.vehicle_id, coalesce(sum(h.quantity),0)::integer
  from public.nostra_vehicle_holds_v161 h
  where h.status = 'active'
    and h.expires_at > now()
    and h.vehicle_id = any(coalesce(p_vehicle_ids, array[]::bigint[]))
  group by h.vehicle_id;
end;
$$;

revoke all on function public.nostra_vehicle_hold_counts_v161(bigint[]) from public, anon;
grant execute on function public.nostra_vehicle_hold_counts_v161(bigint[]) to authenticated;

create or replace function public.nostra_refresh_my_cart_holds_v161()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
  v_hold_minutes integer := 20;
  v_max integer := 10;
  v_total integer := 0;
  v_line record;
  v_other integer;
  v_existing_id bigint;
  v_expires timestamptz;
begin
  if v_uid is null then raise exception using message='not_authenticated'; end if;
  perform public.nostra_cleanup_expired_holds_v161();

  select hold_minutes, max_hold_vehicles into v_hold_minutes, v_max
  from public.nostra_logistics_settings_v161 where singleton = true;
  v_hold_minutes := coalesce(v_hold_minutes,20);
  v_max := coalesce(v_max,10);
  v_expires := now() + make_interval(mins => v_hold_minutes);

  select coalesce(sum(greatest(ci.quantity,1)),0)::integer into v_total
  from public.cart_items ci
  join public.catalog_vehicles cv on cv.id=ci.vehicle_id
  where ci.user_id=v_uid and ci.item_type='vehicle' and ci.vehicle_id is not null
    and coalesce(cv.catalog_type,'standard')<>'concession';

  if v_total > v_max then raise exception using message='hold_limit_reached'; end if;

  -- Verrouille les fiches dans un ordre stable pour éviter les doubles réservations.
  perform 1
  from public.catalog_vehicles cv
  where cv.id in (
    select distinct ci.vehicle_id from public.cart_items ci
    join public.catalog_vehicles ccv on ccv.id=ci.vehicle_id
    where ci.user_id=v_uid and ci.item_type='vehicle' and ci.vehicle_id is not null
      and coalesce(ccv.catalog_type,'standard')<>'concession'
  )
  order by cv.id
  for update;

  for v_line in
    select ci.vehicle_id, sum(greatest(ci.quantity,1))::integer as quantity
    from public.cart_items ci
    join public.catalog_vehicles cv on cv.id=ci.vehicle_id
    where ci.user_id=v_uid and ci.item_type='vehicle' and ci.vehicle_id is not null
      and coalesce(cv.catalog_type,'standard')<>'concession'
    group by ci.vehicle_id
    order by ci.vehicle_id
  loop
    select coalesce(sum(quantity),0)::integer into v_other
    from public.nostra_vehicle_holds_v161
    where vehicle_id=v_line.vehicle_id
      and user_id<>v_uid
      and status='active' and expires_at>now();

    if (select greatest(coalesce(stock_quantity,0),0) from public.catalog_vehicles where id=v_line.vehicle_id)
       < v_other + v_line.quantity then
      raise exception using message='vehicle_temporarily_reserved';
    end if;

    select id into v_existing_id
    from public.nostra_vehicle_holds_v161
    where user_id=v_uid and vehicle_id=v_line.vehicle_id and status='active'
    order by id desc limit 1 for update;

    if v_existing_id is null then
      insert into public.nostra_vehicle_holds_v161(user_id,vehicle_id,quantity,status,expires_at)
      values(v_uid,v_line.vehicle_id,v_line.quantity,'active',v_expires);
    else
      update public.nostra_vehicle_holds_v161
      set quantity=v_line.quantity, expires_at=v_expires, updated_at=now()
      where id=v_existing_id;
    end if;
  end loop;

  -- Libère les holds qui ne correspondent plus à aucune ligne panier.
  update public.nostra_vehicle_holds_v161 h
  set status='released', updated_at=now()
  where h.user_id=v_uid and h.status='active'
    and not exists (
      select 1 from public.cart_items ci
      where ci.user_id=v_uid and ci.item_type='vehicle' and ci.vehicle_id=h.vehicle_id
    );

  return jsonb_build_object('expires_at',v_expires,'vehicle_count',v_total,'hold_minutes',v_hold_minutes);
end;
$$;

revoke all on function public.nostra_refresh_my_cart_holds_v161() from public, anon;
grant execute on function public.nostra_refresh_my_cart_holds_v161() to authenticated;

create or replace function public.nostra_add_vehicle_selection_to_cart_v161(
  p_vehicle_ids bigint[],
  p_delivery_mode text,
  p_delivery_address text default null,
  p_delivery_phone text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
  v_unique bigint[];
  v_to_add bigint[];
  v_id bigint;
  v_other integer;
  v_stock integer;
  v_result jsonb := '{}'::jsonb;
  v_hold jsonb;
begin
  if v_uid is null then raise exception using message='not_authenticated'; end if;
  perform public.nostra_cleanup_expired_holds_v161();

  select array_agg(id order by id) into v_unique
  from (
    select distinct value as id
    from unnest(coalesce(p_vehicle_ids,array[]::bigint[])) u(value)
    where value is not null and value>0
    limit 50
  ) s;
  if coalesce(array_length(v_unique,1),0)=0 then raise exception using message='selection_empty'; end if;

  select array_agg(id order by id) into v_to_add
  from unnest(v_unique) u(id)
  where not exists (
    select 1 from public.cart_items ci
    where ci.user_id=v_uid and ci.item_type='vehicle' and ci.vehicle_id=u.id
  );

  if coalesce(array_length(v_to_add,1),0)>0 then
    perform 1 from public.catalog_vehicles where id=any(v_to_add) order by id for update;
    foreach v_id in array v_to_add loop
      select greatest(coalesce(stock_quantity,0),0) into v_stock
      from public.catalog_vehicles where id=v_id and published=true;
      if v_stock is null then raise exception using message='vehicle_unavailable'; end if;
      select coalesce(sum(quantity),0)::integer into v_other
      from public.nostra_vehicle_holds_v161
      where vehicle_id=v_id and user_id<>v_uid and status='active' and expires_at>now();
      if v_stock <= v_other then raise exception using message='vehicle_temporarily_reserved'; end if;
    end loop;

    v_result := public.nostra_add_vehicle_selection_to_cart_v1601(
      v_to_add,p_delivery_mode,p_delivery_address,p_delivery_phone
    );
  else
    v_result := public.nostra_prepare_cart_delivery_v160(
      p_delivery_mode,
      case when p_delivery_mode='home' then p_delivery_address else null end,
      case when p_delivery_mode='home' then p_delivery_phone else null end
    );
  end if;

  v_hold := public.nostra_refresh_my_cart_holds_v161();
  return jsonb_build_object(
    'added_count',coalesce(array_length(v_to_add,1),0),
    'selected_count',coalesce(array_length(v_unique,1),0),
    'hold',v_hold,
    'result',coalesce(v_result,'{}'::jsonb)
  );
end;
$$;

revoke all on function public.nostra_add_vehicle_selection_to_cart_v161(bigint[],text,text,text) from public, anon;
grant execute on function public.nostra_add_vehicle_selection_to_cart_v161(bigint[],text,text,text) to authenticated;

create or replace function public.nostra_add_vehicle_purchase_to_cart_v161(
  p_vehicle_id bigint,
  p_delivery_mode text,
  p_delivery_address text default null,
  p_delivery_phone text default null,
  p_purchase_mode text default 'order'
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
  v_stock integer;
  v_other integer;
  v_cart_qty integer;
  v_result jsonb;
  v_hold jsonb;
  v_catalog_type text;
begin
  if v_uid is null then raise exception using message='not_authenticated'; end if;
  perform public.nostra_cleanup_expired_holds_v161();

  -- Les réservations avec acompte conservent leur moteur V93, mais respectent
  -- quand même les blocages temporaires déjà posés par d'autres citoyens.
  if coalesce(p_purchase_mode,'order') <> 'order' then
    select greatest(coalesce(stock_quantity,0),0), coalesce(catalog_type,'standard')
    into v_stock, v_catalog_type
    from public.catalog_vehicles where id=p_vehicle_id and published=true
    for update;
    if v_stock is null then raise exception using message='vehicle_unavailable'; end if;
    if v_catalog_type<>'concession' then
      select coalesce(sum(quantity),0)::integer into v_other
      from public.nostra_vehicle_holds_v161
      where vehicle_id=p_vehicle_id and user_id<>v_uid and status='active' and expires_at>now();
      if v_stock <= v_other then raise exception using message='vehicle_temporarily_reserved'; end if;
    end if;
    return public.add_vehicle_purchase_to_cart_v93(p_vehicle_id,p_delivery_mode,p_delivery_address,p_delivery_phone,p_purchase_mode);
  end if;

  select greatest(coalesce(stock_quantity,0),0), coalesce(catalog_type,'standard')
  into v_stock, v_catalog_type
  from public.catalog_vehicles where id=p_vehicle_id and published=true
  for update;
  if v_stock is null then raise exception using message='vehicle_unavailable'; end if;

  -- Location : pas de réservation temporaire V161.
  if v_catalog_type='concession' then
    return public.add_vehicle_purchase_to_cart_v93(p_vehicle_id,p_delivery_mode,p_delivery_address,p_delivery_phone,p_purchase_mode);
  end if;

  select coalesce(sum(quantity),0)::integer into v_other
  from public.nostra_vehicle_holds_v161
  where vehicle_id=p_vehicle_id and user_id<>v_uid and status='active' and expires_at>now();
  select coalesce(sum(greatest(quantity,1)),0)::integer into v_cart_qty
  from public.cart_items
  where user_id=v_uid and item_type='vehicle' and vehicle_id=p_vehicle_id;

  if v_stock < v_other + v_cart_qty + 1 then
    raise exception using message='vehicle_temporarily_reserved';
  end if;

  v_result := public.add_vehicle_purchase_to_cart_v93(p_vehicle_id,p_delivery_mode,p_delivery_address,p_delivery_phone,p_purchase_mode);
  v_hold := public.nostra_refresh_my_cart_holds_v161();
  return coalesce(v_result,'{}'::jsonb) || jsonb_build_object('hold',v_hold);
end;
$$;

revoke all on function public.nostra_add_vehicle_purchase_to_cart_v161(bigint,text,text,text,text) from public, anon;
grant execute on function public.nostra_add_vehicle_purchase_to_cart_v161(bigint,text,text,text,text) to authenticated;

create or replace function public.nostra_release_vehicle_hold_v161(p_vehicle_id bigint)
returns void
language plpgsql
security definer
set search_path=public
as $$
begin
  update public.nostra_vehicle_holds_v161
  set status='released',updated_at=now()
  where user_id=auth.uid() and vehicle_id=p_vehicle_id and status='active';
end;
$$;
revoke all on function public.nostra_release_vehicle_hold_v161(bigint) from public, anon;
grant execute on function public.nostra_release_vehicle_hold_v161(bigint) to authenticated;

create or replace function public.nostra_validate_my_cart_holds_v161()
returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare
  v_uid uuid:=auth.uid();
  v_line record;
  v_hold record;
begin
  if v_uid is null then raise exception using message='not_authenticated'; end if;
  perform public.nostra_cleanup_expired_holds_v161();
  for v_line in
    select ci.vehicle_id,sum(greatest(ci.quantity,1))::integer quantity
    from public.cart_items ci
    join public.catalog_vehicles cv on cv.id=ci.vehicle_id
    where ci.user_id=v_uid and ci.item_type='vehicle' and ci.vehicle_id is not null
      and coalesce(cv.catalog_type,'standard')<>'concession'
    group by ci.vehicle_id
  loop
    select * into v_hold from public.nostra_vehicle_holds_v161
    where user_id=v_uid and vehicle_id=v_line.vehicle_id and status='active' and expires_at>now()
    order by id desc limit 1;
    if not found or v_hold.quantity < v_line.quantity then
      raise exception using message='hold_expired';
    end if;
  end loop;
  return jsonb_build_object('valid',true);
end;
$$;
revoke all on function public.nostra_validate_my_cart_holds_v161() from public, anon;
grant execute on function public.nostra_validate_my_cart_holds_v161() to authenticated;

create or replace function public.nostra_convert_my_holds_v161(p_order_id bigint)
returns integer
language plpgsql
security definer
set search_path=public
as $$
declare
  v_uid uuid:=auth.uid();
  v_count integer;
begin
  if v_uid is null then raise exception using message='not_authenticated'; end if;
  if not exists(select 1 from public.orders where id=p_order_id and user_id=v_uid) then
    raise exception using message='order_not_found';
  end if;

  update public.nostra_vehicle_holds_v161 h
  set status='converted',order_id=p_order_id,updated_at=now()
  where h.user_id=v_uid
    and h.status='active'
    and exists (
      select 1
      from jsonb_array_elements(coalesce((select items from public.orders where id=p_order_id),'[]'::jsonb)) item
      where coalesce(item->>'item_type','')='vehicle'
        and coalesce(item->>'vehicle_id','')<>''
        and (item->>'vehicle_id')::bigint=h.vehicle_id
    );
  get diagnostics v_count = row_count;
  return v_count;
end;
$$;
revoke all on function public.nostra_convert_my_holds_v161(bigint) from public, anon;
grant execute on function public.nostra_convert_my_holds_v161(bigint) to authenticated;

-- Conversion transactionnelle : dès que la commande contenant les VL est créée,
-- les blocages correspondants deviennent historiques. Si la création de commande
-- est annulée par PostgreSQL, cette conversion est elle aussi annulée.
create or replace function public.nostra_convert_matching_holds_after_order_v161()
returns trigger
language plpgsql
security definer
set search_path=public
as $$
begin
  update public.nostra_vehicle_holds_v161 h
  set status='converted',order_id=new.id,updated_at=now()
  where h.user_id=new.user_id
    and h.status='active'
    and exists (
      select 1
      from jsonb_array_elements(coalesce(new.items,'[]'::jsonb)) item
      where coalesce(item->>'item_type','')='vehicle'
        and coalesce(item->>'vehicle_id','')<>''
        and (item->>'vehicle_id')::bigint=h.vehicle_id
    );
  return new;
end;
$$;

drop trigger if exists trg_nostra_convert_matching_holds_v161 on public.orders;
create trigger trg_nostra_convert_matching_holds_v161
after insert on public.orders
for each row execute function public.nostra_convert_matching_holds_after_order_v161();
revoke all on function public.nostra_convert_matching_holds_after_order_v161() from public, anon;

create or replace function public.nostra_active_vehicle_holds_admin_v161()
returns table(
  id bigint,
  user_id uuid,
  vehicle_id bigint,
  vehicle_name text,
  quantity integer,
  expires_at timestamptz,
  customer_name text
)
language plpgsql
security definer
set search_path=public
as $$
begin
  if not public.nostra_can_manage_vehicle_reservations_v93() then raise exception using message='forbidden'; end if;
  perform public.nostra_cleanup_expired_holds_v161();
  return query
  select
    h.id,
    h.user_id,
    h.vehicle_id,
    btrim(coalesce(cv.brand,'') || ' ' || coalesce(cv.model,'')) as vehicle_name,
    h.quantity,
    h.expires_at,
    coalesce(
      nullif(btrim(concat_ws(' ',mp.rp_first_name,mp.rp_last_name)),''),
      nullif(mp.discord_name,''),
      'Citoyen Nostra'
    ) as customer_name
  from public.nostra_vehicle_holds_v161 h
  join public.catalog_vehicles cv on cv.id=h.vehicle_id
  left join public.member_profiles mp on mp.user_id=h.user_id
  where h.status='active' and h.expires_at>now()
  order by h.expires_at asc,h.id asc;
end;
$$;

create or replace function public.nostra_admin_release_hold_v161(p_hold_id bigint)
returns void
language plpgsql
security definer
set search_path=public
as $$
declare v_hold public.nostra_vehicle_holds_v161%rowtype;
begin
  if not public.nostra_can_manage_vehicle_reservations_v93() then raise exception using message='forbidden'; end if;
  select * into v_hold from public.nostra_vehicle_holds_v161 where id=p_hold_id and status='active' for update;
  if not found then return; end if;
  update public.nostra_vehicle_holds_v161 set status='released',updated_at=now() where id=p_hold_id;
  delete from public.cart_items
  where user_id=v_hold.user_id
    and ((item_type='vehicle' and vehicle_id=v_hold.vehicle_id) or (item_type='delivery' and related_vehicle_id=v_hold.vehicle_id));
end;
$$;

revoke all on function public.nostra_active_vehicle_holds_admin_v161() from public, anon;
revoke all on function public.nostra_admin_release_hold_v161(bigint) from public, anon;
grant execute on function public.nostra_active_vehicle_holds_admin_v161() to authenticated;
grant execute on function public.nostra_admin_release_hold_v161(bigint) to authenticated;

-- ---------------------------------------------------------------------------
-- 4. Snapshot de l'adresse sur la commande
-- ---------------------------------------------------------------------------
alter table public.orders add column if not exists delivery_address_id bigint references public.nostra_delivery_addresses_v161(id) on delete set null;
alter table public.orders add column if not exists delivery_address_label text;
alter table public.orders add column if not exists delivery_address text;
alter table public.orders add column if not exists delivery_phone text;
alter table public.orders add column if not exists delivery_instructions text;
alter table public.orders add column if not exists delivery_stage text not null default 'awaiting_planning';
alter table public.orders add column if not exists delivery_window_end timestamptz;

create or replace function public.nostra_attach_delivery_snapshot_v161(
  p_order_id bigint,
  p_address_id bigint default null,
  p_label text default null,
  p_address text default null,
  p_phone text default null,
  p_instructions text default null
)
returns void
language plpgsql
security definer
set search_path=public
as $$
declare
  v_uid uuid:=auth.uid();
  v_addr public.nostra_delivery_addresses_v161%rowtype;
  v_label text:=nullif(btrim(coalesce(p_label,'')),'');
  v_address text:=nullif(btrim(coalesce(p_address,'')),'');
  v_phone text:=nullif(btrim(coalesce(p_phone,'')),'');
  v_instructions text:=nullif(btrim(coalesce(p_instructions,'')),'');
  v_address_id bigint:=null;
begin
  if v_uid is null then raise exception using message='not_authenticated'; end if;
  if not exists(select 1 from public.orders where id=p_order_id and user_id=v_uid) then
    raise exception using message='order_not_found';
  end if;
  if p_address_id is not null then
    select * into v_addr from public.nostra_delivery_addresses_v161
    where id=p_address_id and user_id=v_uid;
    if found then
      v_address_id:=v_addr.id;
      v_label:=v_addr.label;
      v_address:=btrim(concat_ws(', ',v_addr.address_line,nullif(v_addr.city,''),nullif(v_addr.zone,'')));
      v_phone:=coalesce(nullif(v_addr.phone,''),v_phone);
      v_instructions:=coalesce(nullif(v_addr.instructions,''),v_instructions);
    end if;
  end if;
  update public.orders set
    delivery_address_id=v_address_id,
    delivery_address_label=v_label,
    delivery_address=v_address,
    delivery_phone=v_phone,
    delivery_instructions=v_instructions,
    delivery_stage=case when v_address is null then delivery_stage else 'awaiting_planning' end,
    updated_at=now()
  where id=p_order_id and user_id=v_uid;
end;
$$;
revoke all on function public.nostra_attach_delivery_snapshot_v161(bigint,bigint,text,text,text,text) from public, anon;
grant execute on function public.nostra_attach_delivery_snapshot_v161(bigint,bigint,text,text,text,text) to authenticated;

-- ---------------------------------------------------------------------------
-- 5. Flotte de livraison + affectations + checklist
-- ---------------------------------------------------------------------------
create table if not exists public.nostra_delivery_fleet_v161 (
  id bigint generated by default as identity primary key,
  name text not null,
  fleet_type text not null default 'custom' check (fleet_type in ('plateau','semi','carrier','custom')),
  capacity integer not null check (capacity between 1 and 50),
  enabled boolean not null default true,
  status text not null default 'available' check (status in ('available','maintenance','inactive')),
  display_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

insert into public.nostra_delivery_fleet_v161(name,fleet_type,capacity,enabled,status,display_order)
select 'Plateau VL','plateau',1,true,'available',10
where not exists(select 1 from public.nostra_delivery_fleet_v161 where fleet_type='plateau' and capacity=1);
insert into public.nostra_delivery_fleet_v161(name,fleet_type,capacity,enabled,status,display_order)
select 'Semi-remorque porte-véhicules','semi',2,true,'available',20
where not exists(select 1 from public.nostra_delivery_fleet_v161 where fleet_type='semi' and capacity=2);
insert into public.nostra_delivery_fleet_v161(name,fleet_type,capacity,enabled,status,display_order)
select 'Camion porte-véhicules','carrier',5,true,'available',30
where not exists(select 1 from public.nostra_delivery_fleet_v161 where fleet_type='carrier' and capacity=5);

create table if not exists public.nostra_delivery_assignments_v161 (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  fleet_id bigint not null references public.nostra_delivery_fleet_v161(id) on delete cascade,
  scheduled_start timestamptz not null,
  scheduled_end timestamptz not null,
  status text not null default 'planned' check (status in ('planned','loading','in_transit','completed','cancelled')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(order_id,fleet_id)
);
create index if not exists nostra_delivery_assignments_v161_time_idx
on public.nostra_delivery_assignments_v161(fleet_id,scheduled_start,scheduled_end);

create table if not exists public.nostra_delivery_checklist_v161 (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  vehicle_id bigint not null,
  vehicle_name text not null,
  quantity integer not null default 1,
  prepared_quantity integer not null default 0,
  loaded_quantity integer not null default 0,
  updated_at timestamptz not null default now(),
  unique(order_id,vehicle_id)
);

alter table public.nostra_delivery_fleet_v161 enable row level security;
alter table public.nostra_delivery_assignments_v161 enable row level security;
alter table public.nostra_delivery_checklist_v161 enable row level security;

drop policy if exists "v161 staff reads fleet" on public.nostra_delivery_fleet_v161;
create policy "v161 staff reads fleet" on public.nostra_delivery_fleet_v161 for select to authenticated
using (public.nostra_can_manage_vehicle_reservations_v93());
drop policy if exists "v161 staff reads assignments" on public.nostra_delivery_assignments_v161;
create policy "v161 staff reads assignments" on public.nostra_delivery_assignments_v161 for select to authenticated using (public.nostra_can_manage_vehicle_reservations_v93());
drop policy if exists "v161 staff reads checklist" on public.nostra_delivery_checklist_v161;
create policy "v161 staff reads checklist" on public.nostra_delivery_checklist_v161 for select to authenticated using (public.nostra_can_manage_vehicle_reservations_v93());

grant select on public.nostra_delivery_fleet_v161 to authenticated;
grant select on public.nostra_delivery_assignments_v161 to authenticated;
grant select on public.nostra_delivery_checklist_v161 to authenticated;

create or replace function public.nostra_sync_delivery_checklist_v161(p_order_id bigint)
returns void
language plpgsql
security definer
set search_path=public
as $$
declare
  v_item jsonb;
  v_items jsonb := coalesce((select items from public.orders where id=p_order_id),'[]'::jsonb);
begin
  if not public.nostra_can_manage_vehicle_reservations_v93() then
    raise exception using message='forbidden';
  end if;

  -- La checklist contient uniquement les VL réellement livrés à domicile.
  -- Les poids lourds / retraits showroom éventuellement présents dans la même
  -- commande ne doivent pas apparaître dans le chargement du porte-véhicules.
  for v_item in
    select vehicle.value
    from jsonb_array_elements(v_items) as vehicle(value)
    where coalesce(vehicle.value->>'item_type','')='vehicle'
      and coalesce(vehicle.value->>'vehicle_id','')<>''
      and exists (
        select 1
        from jsonb_array_elements(v_items) as delivery(value)
        where coalesce(delivery.value->>'item_type','')='delivery'
          and delivery.value->>'related_vehicle_id'=vehicle.value->>'vehicle_id'
      )
  loop
    insert into public.nostra_delivery_checklist_v161(order_id,vehicle_id,vehicle_name,quantity)
    values(
      p_order_id,
      (v_item->>'vehicle_id')::bigint,
      coalesce(nullif(v_item->>'name',''),'Véhicule'),
      greatest(1,coalesce((v_item->>'quantity')::integer,1))
    )
    on conflict(order_id,vehicle_id) do update set
      vehicle_name=excluded.vehicle_name,
      quantity=excluded.quantity,
      prepared_quantity=least(public.nostra_delivery_checklist_v161.prepared_quantity,excluded.quantity),
      loaded_quantity=least(public.nostra_delivery_checklist_v161.loaded_quantity,excluded.quantity),
      updated_at=now();
  end loop;
end;
$$;

create or replace function public.nostra_update_delivery_plan_v161(
  p_order_id bigint,
  p_stage text,
  p_start timestamptz default null,
  p_end timestamptz default null,
  p_driver text default null,
  p_notes text default null,
  p_fleet_ids bigint[] default array[]::bigint[]
)
returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare
  v_required integer:=0;
  v_capacity integer:=0;
  v_conflicts integer:=0;
  v_delivery_status text:='not_planned';
  v_assignment_status text:='planned';
  v_end timestamptz:=p_end;
  v_slot_minutes integer:=60;
begin
  if not public.nostra_can_manage_vehicle_reservations_v93() then raise exception using message='forbidden'; end if;
  if p_stage not in ('awaiting_planning','planned','preparing','loading','departed','in_transit','delivered','closed','cancelled') then
    raise exception using message='invalid_delivery_stage';
  end if;
  if not exists(select 1 from public.orders where id=p_order_id) then raise exception using message='order_not_found'; end if;

  select coalesce(sum(greatest(1,coalesce((x->>'quantity')::integer,1))),0)::integer into v_required
  from jsonb_array_elements(coalesce((select items from public.orders where id=p_order_id),'[]'::jsonb)) x
  where coalesce(x->>'item_type','')='delivery';

  if p_stage not in ('awaiting_planning','cancelled') then
    if p_start is null then raise exception using message='invalid_delivery_date'; end if;
    if v_end is null then
      select default_slot_minutes into v_slot_minutes
      from public.nostra_logistics_settings_v161 where singleton=true;
      v_slot_minutes:=coalesce(v_slot_minutes,60);
      v_end:=p_start + make_interval(mins => v_slot_minutes);
    end if;
    if v_end<=p_start then raise exception using message='invalid_delivery_date'; end if;
    if coalesce(array_length(p_fleet_ids,1),0)=0 then raise exception using message='fleet_required'; end if;

    select coalesce(sum(capacity),0)::integer into v_capacity
    from public.nostra_delivery_fleet_v161
    where id=any(p_fleet_ids) and enabled=true and status='available';
    if v_capacity < v_required then raise exception using message='fleet_capacity_insufficient'; end if;

    select count(*)::integer into v_conflicts
    from public.nostra_delivery_assignments_v161 a
    join public.nostra_delivery_fleet_v161 f on f.id=a.fleet_id
    where a.fleet_id=any(p_fleet_ids)
      and a.order_id<>p_order_id
      and a.status not in ('completed','cancelled')
      and tstzrange(a.scheduled_start,a.scheduled_end,'[)') && tstzrange(p_start,v_end,'[)');
    if v_conflicts>0 then raise exception using message='fleet_conflict'; end if;
  end if;

  v_delivery_status := case
    when p_stage='awaiting_planning' then 'not_planned'
    when p_stage in ('planned','preparing','loading') then 'planned'
    when p_stage in ('departed','in_transit') then 'in_progress'
    when p_stage in ('delivered','closed') then 'delivered'
    when p_stage='cancelled' then 'cancelled'
    else 'not_planned' end;
  v_assignment_status := case
    when p_stage='loading' then 'loading'
    when p_stage in ('departed','in_transit') then 'in_transit'
    when p_stage in ('delivered','closed') then 'completed'
    when p_stage='cancelled' then 'cancelled'
    else 'planned' end;

  update public.orders set
    delivery_stage=p_stage,
    delivery_status=v_delivery_status,
    delivery_date=p_start,
    delivery_window_end=v_end,
    delivery_driver=nullif(btrim(coalesce(p_driver,'')),''),
    delivery_notes=nullif(btrim(coalesce(p_notes,'')),''),
    updated_at=now()
  where id=p_order_id;

  delete from public.nostra_delivery_assignments_v161 where order_id=p_order_id;
  if p_stage not in ('awaiting_planning','cancelled') then
    insert into public.nostra_delivery_assignments_v161(order_id,fleet_id,scheduled_start,scheduled_end,status)
    select p_order_id,id,p_start,v_end,v_assignment_status
    from public.nostra_delivery_fleet_v161
    where id=any(p_fleet_ids);
  end if;

  perform public.nostra_sync_delivery_checklist_v161(p_order_id);
  return jsonb_build_object('required_capacity',v_required,'assigned_capacity',v_capacity,'stage',p_stage);
end;
$$;

create or replace function public.nostra_update_delivery_checklist_v161(
  p_order_id bigint,
  p_vehicle_id bigint,
  p_prepared integer,
  p_loaded integer
)
returns void
language plpgsql
security definer
set search_path=public
as $$
declare v_qty integer;
begin
  if not public.nostra_can_manage_vehicle_reservations_v93() then raise exception using message='forbidden'; end if;
  perform public.nostra_sync_delivery_checklist_v161(p_order_id);
  select quantity into v_qty from public.nostra_delivery_checklist_v161 where order_id=p_order_id and vehicle_id=p_vehicle_id;
  if v_qty is null then raise exception using message='checklist_line_not_found'; end if;
  update public.nostra_delivery_checklist_v161 set
    prepared_quantity=least(v_qty,greatest(0,p_prepared)),
    loaded_quantity=least(v_qty,greatest(0,least(p_loaded,p_prepared))),
    updated_at=now()
  where order_id=p_order_id and vehicle_id=p_vehicle_id;
end;
$$;

create or replace function public.nostra_upsert_delivery_fleet_v161(
  p_id bigint default null,
  p_name text default null,
  p_type text default 'custom',
  p_capacity integer default 1,
  p_enabled boolean default true,
  p_status text default 'available',
  p_display_order integer default 0
)
returns bigint
language plpgsql
security definer
set search_path=public
as $$
declare v_id bigint;
begin
  if not public.nostra_can_manage_vehicle_reservations_v93() then raise exception using message='forbidden'; end if;
  if length(btrim(coalesce(p_name,'')))<2 or p_capacity<1 or p_capacity>50 then raise exception using message='invalid_fleet'; end if;
  if p_type not in ('plateau','semi','carrier','custom') or p_status not in ('available','maintenance','inactive') then raise exception using message='invalid_fleet'; end if;
  if p_id is null then
    insert into public.nostra_delivery_fleet_v161(name,fleet_type,capacity,enabled,status,display_order)
    values(btrim(p_name),p_type,p_capacity,p_enabled,p_status,p_display_order) returning id into v_id;
  else
    update public.nostra_delivery_fleet_v161 set name=btrim(p_name),fleet_type=p_type,capacity=p_capacity,enabled=p_enabled,status=p_status,display_order=p_display_order,updated_at=now()
    where id=p_id returning id into v_id;
    if v_id is null then raise exception using message='fleet_not_found'; end if;
  end if;
  return v_id;
end;
$$;

create or replace function public.nostra_update_logistics_settings_v161(
  p_hold_minutes integer,
  p_max_hold_vehicles integer,
  p_default_slot_minutes integer
)
returns void
language plpgsql
security definer
set search_path=public
as $$
begin
  if not public.nostra_can_manage_vehicle_reservations_v93() then raise exception using message='forbidden'; end if;
  if p_hold_minutes<5 or p_hold_minutes>120 or p_max_hold_vehicles<1 or p_max_hold_vehicles>50 or p_default_slot_minutes<15 or p_default_slot_minutes>480 then
    raise exception using message='invalid_settings';
  end if;
  update public.nostra_logistics_settings_v161 set hold_minutes=p_hold_minutes,max_hold_vehicles=p_max_hold_vehicles,default_slot_minutes=p_default_slot_minutes,updated_at=now() where singleton=true;
end;
$$;

revoke all on function public.nostra_sync_delivery_checklist_v161(bigint) from public, anon;
revoke all on function public.nostra_update_delivery_plan_v161(bigint,text,timestamptz,timestamptz,text,text,bigint[]) from public, anon;
revoke all on function public.nostra_update_delivery_checklist_v161(bigint,bigint,integer,integer) from public, anon;
revoke all on function public.nostra_upsert_delivery_fleet_v161(bigint,text,text,integer,boolean,text,integer) from public, anon;
revoke all on function public.nostra_update_logistics_settings_v161(integer,integer,integer) from public, anon;
grant execute on function public.nostra_sync_delivery_checklist_v161(bigint) to authenticated;
grant execute on function public.nostra_update_delivery_plan_v161(bigint,text,timestamptz,timestamptz,text,text,bigint[]) to authenticated;
grant execute on function public.nostra_update_delivery_checklist_v161(bigint,bigint,integer,integer) to authenticated;
grant execute on function public.nostra_upsert_delivery_fleet_v161(bigint,text,text,integer,boolean,text,integer) to authenticated;
grant execute on function public.nostra_update_logistics_settings_v161(integer,integer,integer) to authenticated;

commit;

select
  to_regclass('public.nostra_vehicle_holds_v161') as holds,
  to_regclass('public.nostra_delivery_addresses_v161') as addresses,
  to_regclass('public.nostra_delivery_fleet_v161') as fleet,
  to_regprocedure('public.nostra_add_vehicle_selection_to_cart_v161(bigint[],text,text,text)') as selection_hold,
  to_regprocedure('public.nostra_update_delivery_plan_v161(bigint,text,timestamptz,timestamptz,text,text,bigint[])') as logistics_plan;
