-- NOSTRA GROUP — Activation du module Réservations V11
-- Ce script peut être exécuté plusieurs fois sans effacer les demandes existantes.

create table if not exists public.circuit_reservation_requests (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  first_name text not null,
  last_name text not null,
  reservation_date date not null,
  reservation_time time not null,
  reason text not null,
  status text not null default 'pending' check (status in ('pending','approved','rejected','cancelled')),
  admin_note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists one_approved_reservation_per_slot
on public.circuit_reservation_requests (reservation_date, reservation_time)
where status = 'approved';

alter table public.circuit_reservation_requests enable row level security;

drop policy if exists "members create circuit reservations" on public.circuit_reservation_requests;
create policy "members create circuit reservations" on public.circuit_reservation_requests
for insert to authenticated with check (user_id = auth.uid());

drop policy if exists "members read circuit reservations" on public.circuit_reservation_requests;
create policy "members read circuit reservations" on public.circuit_reservation_requests
for select to authenticated using (
  user_id = auth.uid()
  or status = 'approved'
  or public.has_nostra_dashboard_access()
);

drop policy if exists "dashboard manages circuit reservations" on public.circuit_reservation_requests;
create policy "dashboard manages circuit reservations" on public.circuit_reservation_requests
for update to authenticated
using (public.has_nostra_dashboard_access())
with check (public.has_nostra_dashboard_access());

drop policy if exists "dashboard deletes circuit reservations" on public.circuit_reservation_requests;
create policy "dashboard deletes circuit reservations" on public.circuit_reservation_requests
for delete to authenticated using (public.has_nostra_dashboard_access());
