-- NOSTRA GROUP V88 — CENTRE DE REMISE À ZÉRO DES DONNÉES DE TEST
--
-- Objectifs :
--   • supprimer individuellement une ancienne partie de la Roue de la Fortune ;
--   • remettre à zéro chaque jeu séparément ou tous les jeux d'un seul coup ;
--   • vider les documents de test et remettre leurs compteurs au départ ;
--   • remettre uniquement le compteur des factures à zéro quand il n'existe plus de facture.
--
-- IMPORTANT : aucune action destructive n'est exécutée pendant l'installation.
-- Les suppressions ne se produisent qu'après une action volontaire depuis le Dashboard,
-- avec rôle Gérant et phrase de confirmation exacte.

begin;

create or replace function public.nostra_v88_is_manager()
returns boolean
language plpgsql
stable
security definer
set search_path = public, auth, pg_temp
as $$
declare
  v_allowed boolean := false;
begin
  if auth.uid() is null then
    return false;
  end if;

  begin
    if to_regprocedure('public.nostra_has_role(text)') is not null then
      execute 'select coalesce(public.nostra_has_role($1), false)'
        into v_allowed
        using 'manager';
      if v_allowed then
        return true;
      end if;
    end if;
  exception when others then
    v_allowed := false;
  end;

  begin
    if to_regprocedure('public.has_nostra_dashboard_access()') is not null then
      execute 'select coalesce(public.has_nostra_dashboard_access(), false)'
        into v_allowed;
      if v_allowed then
        return true;
      end if;
    end if;
  exception when others then
    v_allowed := false;
  end;

  if to_regclass('public.member_profiles') is not null then
    begin
      execute $query$
        select exists (
          select 1
          from public.member_profiles profile
          where profile.user_id = auth.uid()
            and (
              lower(coalesce(to_jsonb(profile) ->> 'role', ''))
                in ('manager', 'gerant', 'gérant', 'direction')
              or lower(coalesce(to_jsonb(profile) ->> 'roles', ''))
                like '%manager%'
              or lower(coalesce(to_jsonb(profile) ->> 'roles', ''))
                like '%gerant%'
              or lower(coalesce(to_jsonb(profile) ->> 'roles', ''))
                like '%gérant%'
              or lower(coalesce(to_jsonb(profile) ->> 'roles', ''))
                like '%direction%'
            )
        )
      $query$ into v_allowed;
    exception when others then
      v_allowed := false;
    end;
  end if;

  return coalesce(v_allowed, false);
end;
$$;

revoke all on function public.nostra_v88_is_manager() from public;
grant execute on function public.nostra_v88_is_manager() to authenticated;

create table if not exists public.nostra_test_reset_log_v88 (
  id bigint generated by default as identity primary key,
  actor_user_id uuid not null,
  action_key text not null,
  scope_key text not null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists nostra_test_reset_log_v88_created_idx
  on public.nostra_test_reset_log_v88(created_at desc);

alter table public.nostra_test_reset_log_v88 enable row level security;

drop policy if exists "v88 managers read reset log" on public.nostra_test_reset_log_v88;
create policy "v88 managers read reset log"
on public.nostra_test_reset_log_v88
for select
to authenticated
using (public.nostra_v88_is_manager());

revoke all on public.nostra_test_reset_log_v88 from public;
grant select on public.nostra_test_reset_log_v88 to authenticated;

create or replace function public.nostra_v88_count_rows(p_table_name text)
returns bigint
language plpgsql
stable
security definer
set search_path = public, pg_temp
as $$
declare
  v_count bigint := 0;
begin
  if p_table_name !~ '^[a-z0-9_]+$' then
    return 0;
  end if;

  if to_regclass('public.' || p_table_name) is null then
    return 0;
  end if;

  execute format('select count(*) from public.%I', p_table_name)
    into v_count;

  return coalesce(v_count, 0);
exception when others then
  return 0;
end;
$$;

revoke all on function public.nostra_v88_count_rows(text) from public, authenticated;

create or replace function public.nostra_v88_truncate_table(p_table_name text)
returns boolean
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  if p_table_name !~ '^[a-z0-9_]+$' then
    raise exception using errcode = '22023', message = 'invalid_table_name';
  end if;

  if to_regclass('public.' || p_table_name) is null then
    return false;
  end if;

  execute format(
    'truncate table public.%I restart identity cascade',
    p_table_name
  );

  return true;
end;
$$;

revoke all on function public.nostra_v88_truncate_table(text) from public, authenticated;

create or replace function public.nostra_v88_reset_owned_sequence(
  p_table_name text,
  p_column_name text default 'id'
)
returns boolean
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_sequence text;
begin
  if p_table_name !~ '^[a-z0-9_]+$'
     or p_column_name !~ '^[a-z0-9_]+$' then
    return false;
  end if;

  if to_regclass('public.' || p_table_name) is null then
    return false;
  end if;

  v_sequence := pg_get_serial_sequence(
    format('public.%I', p_table_name),
    p_column_name
  );

  if v_sequence is null then
    return false;
  end if;

  execute format('select setval(%L::regclass, 1, false)', v_sequence);
  return true;
exception when others then
  return false;
end;
$$;

revoke all on function public.nostra_v88_reset_owned_sequence(text, text)
  from public, authenticated;

create or replace function public.nostra_test_reset_overview_v88()
returns jsonb
language plpgsql
stable
security definer
set search_path = public, auth, pg_temp
as $$
declare
  v_past_fortune_games jsonb := '[]'::jsonb;
  v_logs jsonb := '[]'::jsonb;
  v_fortune_count bigint := 0;
begin
  if not public.nostra_v88_is_manager() then
    raise exception using errcode = '42501', message = 'manager_required';
  end if;

  if to_regclass('public.fortune_game_history_v87') is not null then
    execute $query$
      select coalesce(
        jsonb_agg(to_jsonb(history_row) order by history_row.finished_at desc),
        '[]'::jsonb
      )
      from (
        select *
        from public.fortune_game_history_v87
        order by finished_at desc
        limit 100
      ) history_row
    $query$ into v_past_fortune_games;

    v_fortune_count := public.nostra_v88_count_rows('fortune_game_history_v87');
  elsif to_regclass('public.fortune_games') is not null then
    execute $query$
      select coalesce(
        jsonb_agg(
          to_jsonb(game_row)
          || jsonb_build_object('game_id', to_jsonb(game_row) ->> 'id')
        ),
        '[]'::jsonb
      )
      from (
        select *
        from public.fortune_games game_source
        where lower(coalesce(to_jsonb(game_source) ->> 'status', ''))
          in ('finished', 'completed', 'cancelled', 'canceled', 'archived', 'ended')
        order by coalesce(
          to_jsonb(game_source) ->> 'updated_at',
          to_jsonb(game_source) ->> 'created_at',
          ''
        ) desc
        limit 100
      ) game_row
    $query$ into v_past_fortune_games;

    execute $query$
      select count(*)
      from public.fortune_games game_source
      where lower(coalesce(to_jsonb(game_source) ->> 'status', ''))
        in ('finished', 'completed', 'cancelled', 'canceled', 'archived', 'ended')
    $query$ into v_fortune_count;
  end if;

  select coalesce(
    jsonb_agg(to_jsonb(log_row) order by log_row.created_at desc),
    '[]'::jsonb
  )
  into v_logs
  from (
    select id, actor_user_id, action_key, scope_key, details, created_at
    from public.nostra_test_reset_log_v88
    order by created_at desc
    limit 20
  ) log_row;

  return jsonb_build_object(
    'counts', jsonb_build_object(
      'fortune', v_fortune_count,
      'daily_wheel', public.nostra_v88_count_rows('game_wheel_spins'),
      'deal', public.nostra_v88_count_rows('deal_editions'),
      'treasure', public.nostra_v88_count_rows('treasure_hunts'),
      'bingo', public.nostra_v88_count_rows('bingo_rounds'),
      'tombola', public.nostra_v88_count_rows('tombola_rounds'),
      'invoices', public.nostra_v88_count_rows('invoices'),
      'document_registry', public.nostra_v88_count_rows('nostra_document_registry')
    ),
    'past_fortune_games', coalesce(v_past_fortune_games, '[]'::jsonb),
    'logs', coalesce(v_logs, '[]'::jsonb)
  );
end;
$$;

revoke all on function public.nostra_test_reset_overview_v88() from public;
grant execute on function public.nostra_test_reset_overview_v88() to authenticated;

create or replace function public.nostra_delete_fortune_game_v88(
  p_game_id text,
  p_confirmation text
)
returns jsonb
language plpgsql
security definer
set search_path = public, auth, pg_temp
as $$
declare
  v_deleted_games integer := 0;
  v_deleted_history integer := 0;
  v_rows integer := 0;
begin
  if not public.nostra_v88_is_manager() then
    raise exception using errcode = '42501', message = 'manager_required';
  end if;

  if upper(trim(coalesce(p_confirmation, ''))) <> 'SUPPRIMER_PARTIE' then
    raise exception using errcode = '22023', message = 'confirmation_invalid';
  end if;

  if nullif(trim(coalesce(p_game_id, '')), '') is null then
    raise exception using errcode = '22023', message = 'game_id_required';
  end if;

  if to_regclass('public.fortune_game_history_v87') is not null then
    execute 'delete from public.fortune_game_history_v87 where game_id = $1'
      using p_game_id;
    get diagnostics v_rows = row_count;
    v_deleted_history := v_deleted_history + v_rows;
  end if;

  if to_regclass('public.fortune_rounds') is not null then
    execute 'delete from public.fortune_rounds where game_id::text = $1'
      using p_game_id;
  end if;

  if to_regclass('public.fortune_game_players') is not null then
    execute 'delete from public.fortune_game_players where game_id::text = $1'
      using p_game_id;
  elsif to_regclass('public.fortune_players') is not null then
    begin
      execute 'delete from public.fortune_players where game_id::text = $1'
        using p_game_id;
    exception
      when wrong_object_type or object_not_in_prerequisite_state then
        null;
    end;
  end if;

  if to_regclass('public.fortune_games') is not null then
    execute 'delete from public.fortune_games where id::text = $1'
      using p_game_id;
    get diagnostics v_deleted_games = row_count;
  end if;

  -- Le trigger d'archivage peut recréer l'historique pendant la suppression.
  if to_regclass('public.fortune_game_history_v87') is not null then
    execute 'delete from public.fortune_game_history_v87 where game_id = $1'
      using p_game_id;
    get diagnostics v_rows = row_count;
    v_deleted_history := v_deleted_history + v_rows;
  end if;

  insert into public.nostra_test_reset_log_v88 (
    actor_user_id,
    action_key,
    scope_key,
    details
  ) values (
    auth.uid(),
    'delete_past_fortune_game',
    'fortune',
    jsonb_build_object(
      'game_id', p_game_id,
      'deleted_games', v_deleted_games,
      'deleted_history_rows', v_deleted_history
    )
  );

  return jsonb_build_object(
    'ok', true,
    'game_id', p_game_id,
    'deleted_games', v_deleted_games,
    'deleted_history_rows', v_deleted_history
  );
end;
$$;

revoke all on function public.nostra_delete_fortune_game_v88(text, text) from public;
grant execute on function public.nostra_delete_fortune_game_v88(text, text) to authenticated;

create or replace function public.nostra_reset_game_data_v88(
  p_scope text,
  p_confirmation text
)
returns jsonb
language plpgsql
security definer
set search_path = public, auth, pg_temp
as $$
declare
  v_scope text := lower(trim(coalesce(p_scope, '')));
  v_expected_confirmation text;
  v_reset jsonb := '[]'::jsonb;
  v_bingo_title text := 'Bingo Nostra Group';
  v_bingo_price numeric := 5000;
  v_tombola_title text := 'Tombola Nostra Group';
  v_tombola_price numeric := 5000;
begin
  if not public.nostra_v88_is_manager() then
    raise exception using errcode = '42501', message = 'manager_required';
  end if;

  if v_scope not in (
    'fortune',
    'daily_wheel',
    'deal',
    'treasure',
    'bingo',
    'tombola',
    'all'
  ) then
    raise exception using errcode = '22023', message = 'invalid_scope';
  end if;

  v_expected_confirmation := case
    when v_scope = 'all' then 'TOUT_REMETTRE_A_ZERO'
    else 'REMETTRE_A_ZERO'
  end;

  if upper(trim(coalesce(p_confirmation, ''))) <> v_expected_confirmation then
    raise exception using errcode = '22023', message = 'confirmation_invalid';
  end if;

  if v_scope in ('fortune', 'all') then
    perform public.nostra_v88_truncate_table('fortune_games');
    perform public.nostra_v88_truncate_table('fortune_game_history_v87');

    -- La banque d'énigmes est conservée, mais ses statistiques de test repartent à zéro.
    if to_regclass('public.fortune_puzzle_bank_v87') is not null then
      execute 'update public.fortune_puzzle_bank_v87 set used_count = 0, last_used_at = null';
    end if;

    -- Le jackpot persistant est un résultat de jeu : il repart lui aussi à zéro.
    if to_regclass('public.fortune_settings') is not null
       and exists (
         select 1
         from information_schema.columns
         where table_schema = 'public'
           and table_name = 'fortune_settings'
           and column_name = 'jackpot_amount'
       ) then
      execute 'update public.fortune_settings set jackpot_amount = 0';
    end if;

    v_reset := v_reset || jsonb_build_array('fortune');
  end if;

  if v_scope in ('daily_wheel', 'all') then
    perform public.nostra_v88_truncate_table('game_wheel_spins');
    v_reset := v_reset || jsonb_build_array('daily_wheel');
  end if;

  if v_scope in ('deal', 'all') then
    perform public.nostra_v88_truncate_table('deal_editions');
    v_reset := v_reset || jsonb_build_array('deal');
  end if;

  if v_scope in ('treasure', 'all') then
    perform public.nostra_v88_truncate_table('treasure_hunts');
    v_reset := v_reset || jsonb_build_array('treasure');
  end if;

  if v_scope in ('bingo', 'all') then
    if to_regclass('public.bingo_rounds') is not null then
      begin
        execute $query$
          select
            coalesce(nullif(trim(title), ''), 'Bingo Nostra Group'),
            coalesce(card_price, 5000)
          from public.bingo_rounds
          order by (archived_at is null) desc, id desc
          limit 1
        $query$ into v_bingo_title, v_bingo_price;
      exception when others then
        v_bingo_title := 'Bingo Nostra Group';
        v_bingo_price := 5000;
      end;

      perform public.nostra_v88_truncate_table('bingo_rounds');

      execute $query$
        insert into public.bingo_rounds (
          title,
          card_price,
          status,
          phase,
          archived_at,
          updated_at
        ) values ($1, $2, 'open', 'one_line', null, now())
      $query$ using v_bingo_title, v_bingo_price;
    end if;
    v_reset := v_reset || jsonb_build_array('bingo');
  end if;

  if v_scope in ('tombola', 'all') then
    if to_regclass('public.tombola_rounds') is not null then
      begin
        execute $query$
          select
            coalesce(nullif(trim(title), ''), 'Tombola Nostra Group'),
            coalesce(ticket_price, 5000)
          from public.tombola_rounds
          order by (archived_at is null) desc, id desc
          limit 1
        $query$ into v_tombola_title, v_tombola_price;
      exception when others then
        v_tombola_title := 'Tombola Nostra Group';
        v_tombola_price := 5000;
      end;

      perform public.nostra_v88_truncate_table('tombola_rounds');

      execute $query$
        insert into public.tombola_rounds (
          title,
          ticket_price,
          status,
          archived_at,
          updated_at
        ) values ($1, $2, 'open', null, now())
      $query$ using v_tombola_title, v_tombola_price;
    end if;
    v_reset := v_reset || jsonb_build_array('tombola');
  end if;

  insert into public.nostra_test_reset_log_v88 (
    actor_user_id,
    action_key,
    scope_key,
    details
  ) values (
    auth.uid(),
    'reset_game_data',
    v_scope,
    jsonb_build_object('reset_modules', v_reset)
  );

  return jsonb_build_object(
    'ok', true,
    'scope', v_scope,
    'reset_modules', v_reset
  );
end;
$$;

revoke all on function public.nostra_reset_game_data_v88(text, text) from public;
grant execute on function public.nostra_reset_game_data_v88(text, text) to authenticated;

create or replace function public.nostra_reset_document_counter_v88(
  p_confirmation text
)
returns jsonb
language plpgsql
security definer
set search_path = public, auth, pg_temp
as $$
declare
  v_invoice_count bigint := 0;
  v_registry_count bigint := 0;
  v_invoice_sequence_reset boolean := false;
  v_registry_sequence_reset boolean := false;
begin
  if not public.nostra_v88_is_manager() then
    raise exception using errcode = '42501', message = 'manager_required';
  end if;

  if upper(trim(coalesce(p_confirmation, ''))) <> 'COMPTEUR_DOCUMENTS' then
    raise exception using errcode = '22023', message = 'confirmation_invalid';
  end if;

  v_invoice_count := public.nostra_v88_count_rows('invoices');
  v_registry_count := public.nostra_v88_count_rows('nostra_document_registry');

  if v_invoice_count > 0 then
    raise exception using
      errcode = 'P0001',
      message = 'invoices_still_present',
      detail = 'Supprime les factures restantes ou utilise la remise à zéro complète des documents de test.';
  end if;

  v_invoice_sequence_reset := public.nostra_v88_reset_owned_sequence('invoices', 'id');

  -- Le registre peut contenir des licences ou d'autres documents encore actifs.
  -- Son compteur n'est remis au départ que lorsqu'il est réellement vide.
  if v_registry_count = 0 then
    v_registry_sequence_reset := public.nostra_v88_reset_owned_sequence(
      'nostra_document_registry',
      'id'
    );
  end if;

  insert into public.nostra_test_reset_log_v88 (
    actor_user_id,
    action_key,
    scope_key,
    details
  ) values (
    auth.uid(),
    'reset_document_counter',
    'documents',
    jsonb_build_object(
      'invoice_sequence_reset', v_invoice_sequence_reset,
      'registry_sequence_reset', v_registry_sequence_reset,
      'registry_rows_preserved', v_registry_count
    )
  );

  return jsonb_build_object(
    'ok', true,
    'invoice_sequence_reset', v_invoice_sequence_reset,
    'registry_sequence_reset', v_registry_sequence_reset,
    'registry_rows_preserved', v_registry_count,
    'next_invoice_id', 1
  );
end;
$$;

revoke all on function public.nostra_reset_document_counter_v88(text) from public;
grant execute on function public.nostra_reset_document_counter_v88(text) to authenticated;

create or replace function public.nostra_clear_test_documents_v88(
  p_confirmation text
)
returns jsonb
language plpgsql
security definer
set search_path = public, auth, pg_temp
as $$
declare
  v_before_invoices bigint := 0;
  v_before_registry bigint := 0;
  v_table text;
  v_sequence text;
begin
  if not public.nostra_v88_is_manager() then
    raise exception using errcode = '42501', message = 'manager_required';
  end if;

  if upper(trim(coalesce(p_confirmation, ''))) <> 'SUPPRIMER_DOCUMENTS_TEST' then
    raise exception using errcode = '22023', message = 'confirmation_invalid';
  end if;

  v_before_invoices := public.nostra_v88_count_rows('invoices');
  v_before_registry := public.nostra_v88_count_rows('nostra_document_registry');

  -- Tables de signatures éventuelles : elles sont vidées avant le registre.
  foreach v_table in array array[
    'nostra_document_signatures',
    'document_signatures',
    'signed_documents'
  ]
  loop
    if to_regclass('public.' || v_table) is not null then
      execute format('delete from public.%I', v_table);
      perform public.nostra_v88_reset_owned_sequence(v_table, 'id');
    end if;
  end loop;

  if to_regclass('public.nostra_document_registry') is not null then
    execute 'delete from public.nostra_document_registry';
    perform public.nostra_v88_reset_owned_sequence('nostra_document_registry', 'id');
  end if;

  if to_regclass('public.invoices') is not null then
    execute 'delete from public.invoices';
    perform public.nostra_v88_reset_owned_sequence('invoices', 'id');
  end if;

  -- Certaines anciennes versions utilisent une séquence dédiée au numéro lisible.
  foreach v_sequence in array array[
    'public.invoice_number_seq',
    'public.invoices_number_seq',
    'public.nostra_invoice_number_seq',
    'public.document_number_seq',
    'public.nostra_document_number_seq'
  ]
  loop
    if to_regclass(v_sequence) is not null then
      execute format('select setval(%L::regclass, 1, false)', v_sequence);
    end if;
  end loop;

  insert into public.nostra_test_reset_log_v88 (
    actor_user_id,
    action_key,
    scope_key,
    details
  ) values (
    auth.uid(),
    'clear_test_documents',
    'documents',
    jsonb_build_object(
      'deleted_invoices', v_before_invoices,
      'deleted_registry_rows', v_before_registry,
      'counter_restarted', true
    )
  );

  return jsonb_build_object(
    'ok', true,
    'deleted_invoices', v_before_invoices,
    'deleted_registry_rows', v_before_registry,
    'counter_restarted', true,
    'next_id', 1
  );
end;
$$;

revoke all on function public.nostra_clear_test_documents_v88(text) from public;
grant execute on function public.nostra_clear_test_documents_v88(text) to authenticated;

notify pgrst, 'reload schema';

commit;

select
  'V88_OK'::text as resultat,
  to_regprocedure('public.nostra_reset_game_data_v88(text,text)') is not null
    as remise_a_zero_jeux_installee,
  to_regprocedure('public.nostra_delete_fortune_game_v88(text,text)') is not null
    as suppression_partie_fortune_installee,
  to_regprocedure('public.nostra_reset_document_counter_v88(text)') is not null
    as compteur_documents_installe;
