-- NOSTRA GROUP — V92
-- Concession « Véhicules d’occasion » / Dashboard « Véhicules rachetés »
-- Script réexécutable. Il ne supprime aucune donnée existante.

begin;

-- ---------------------------------------------------------------------------
-- 1. Extension du catalogue existant
-- ---------------------------------------------------------------------------

alter table public.catalog_vehicles
  add column if not exists catalog_type text not null default 'standard';

alter table public.catalog_vehicles
  add column if not exists used_vehicle_status text not null default 'available';

alter table public.catalog_vehicles
  add column if not exists used_condition text not null default '';

-- Remplace uniquement l'ancienne contrainte portant sur catalog_type afin
-- d'autoriser le quatrième catalogue « used ».
do $$
declare
  constraint_row record;
begin
  for constraint_row in
    select conname
    from pg_constraint
    where conrelid = 'public.catalog_vehicles'::regclass
      and contype = 'c'
      and pg_get_constraintdef(oid) ilike '%catalog_type%'
  loop
    execute format(
      'alter table public.catalog_vehicles drop constraint if exists %I',
      constraint_row.conname
    );
  end loop;
end;
$$;

alter table public.catalog_vehicles
  add constraint catalog_vehicles_catalog_type_v92_check
  check (catalog_type in ('standard', 'heavy', 'exclusive', 'used')) not valid;

alter table public.catalog_vehicles
  validate constraint catalog_vehicles_catalog_type_v92_check;

-- Remplace les anciennes contraintes éventuelles sur le statut public.
do $$
declare
  constraint_row record;
begin
  for constraint_row in
    select conname
    from pg_constraint
    where conrelid = 'public.catalog_vehicles'::regclass
      and contype = 'c'
      and pg_get_constraintdef(oid) ilike '%used_vehicle_status%'
  loop
    execute format(
      'alter table public.catalog_vehicles drop constraint if exists %I',
      constraint_row.conname
    );
  end loop;
end;
$$;

alter table public.catalog_vehicles
  add constraint catalog_vehicles_used_status_v92_check
  check (used_vehicle_status in ('available', 'reserved', 'sold')) not valid;

alter table public.catalog_vehicles
  validate constraint catalog_vehicles_used_status_v92_check;

create index if not exists catalog_vehicles_used_v92_idx
  on public.catalog_vehicles (catalog_type, published, used_vehicle_status, stock_quantity);

-- ---------------------------------------------------------------------------
-- 2. Données privées des rachats et historique des ventes
-- ---------------------------------------------------------------------------

create table if not exists public.used_vehicle_details (
  id bigint generated by default as identity primary key,
  vehicle_id bigint not null unique
    references public.catalog_vehicles(id) on delete cascade,
  version text,
  registration text,
  previous_owner text,
  purchase_date date not null default current_date,
  purchase_price numeric(14,2) not null default 0 check (purchase_price >= 0),
  resale_price numeric(14,2) not null default 0 check (resale_price >= 0),
  purchase_quantity integer not null default 1 check (purchase_quantity >= 0),
  vehicle_condition text not null default 'good'
    check (vehicle_condition in ('excellent', 'very_good', 'good', 'fair', 'repair')),
  internal_notes text,
  sale_status text not null default 'available'
    check (sale_status in ('available', 'reserved', 'sold')),
  actual_sale_price numeric(14,2),
  actual_margin numeric(14,2),
  sold_at timestamptz,
  sold_order_id bigint references public.orders(id) on delete set null,
  purchase_accounting_entry_id bigint references public.accounting_entries(id) on delete set null,
  created_by uuid references auth.users(id) on delete set null,
  updated_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists used_vehicle_registration_v92_uq
  on public.used_vehicle_details (lower(registration))
  where registration is not null and btrim(registration) <> '';

create index if not exists used_vehicle_details_status_v92_idx
  on public.used_vehicle_details (sale_status, purchase_date desc);

create table if not exists public.used_vehicle_sales (
  id bigint generated by default as identity primary key,
  vehicle_id bigint not null references public.catalog_vehicles(id) on delete restrict,
  order_id bigint not null references public.orders(id) on delete cascade,
  order_number text not null,
  user_id uuid not null references auth.users(id) on delete cascade,
  customer_name text not null default '',
  vehicle_name text not null,
  quantity integer not null default 1 check (quantity > 0),
  unit_purchase_price numeric(14,2) not null default 0,
  unit_sale_price numeric(14,2) not null default 0,
  total_purchase_price numeric(14,2) not null default 0,
  total_sale_price numeric(14,2) not null default 0,
  margin numeric(14,2) not null default 0,
  sale_accounting_entry_id bigint references public.accounting_entries(id) on delete set null,
  sold_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (order_id, vehicle_id)
);

create index if not exists used_vehicle_sales_date_v92_idx
  on public.used_vehicle_sales (sold_at desc);
create index if not exists used_vehicle_sales_customer_v92_idx
  on public.used_vehicle_sales (user_id, sold_at desc);

-- ---------------------------------------------------------------------------
-- 3. Liaison comptable et documents
-- ---------------------------------------------------------------------------

alter table public.accounting_entries
  add column if not exists nostra_source_type text;
alter table public.accounting_entries
  add column if not exists nostra_source_id text;

drop index if exists public.accounting_entries_nostra_source_v92_uq;
create unique index accounting_entries_nostra_source_v92_uq
  on public.accounting_entries (nostra_source_type, nostra_source_id);

alter table public.invoices add column if not exists order_id bigint references public.orders(id) on delete cascade;
alter table public.invoices add column if not exists document_type text not null default 'invoice';
alter table public.invoices add column if not exists document_title text;
alter table public.invoices add column if not exists document_payload jsonb not null default '{}'::jsonb;

create index if not exists invoices_order_v92_idx on public.invoices (order_id, issued_at desc);

-- ---------------------------------------------------------------------------
-- 4. Permission Employé / Commercial / Gérant
-- ---------------------------------------------------------------------------

create or replace function public.nostra_can_manage_used_vehicles_v92()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select auth.uid() is not null
    and (
      coalesce(
        auth.jwt() -> 'user_metadata' ->> 'provider_id',
        auth.jwt() -> 'user_metadata' ->> 'discord_id',
        auth.jwt() -> 'user_metadata' ->> 'sub'
      ) = '331843410962939908'
      or exists (
        select 1
        from public.member_profiles profile
        where profile.user_id = auth.uid()
          and (
            lower(coalesce(to_jsonb(profile) ->> 'role', ''))
              in ('manager', 'gerant', 'direction', 'employee', 'employe', 'commercial', 'vendeur')
            or lower(coalesce((to_jsonb(profile) -> 'roles')::text, ''))
              ~ '(manager|gerant|direction|employee|employe|commercial|vendeur)'
          )
      )
    );
$$;

grant execute on function public.nostra_can_manage_used_vehicles_v92() to authenticated;

alter table public.used_vehicle_details enable row level security;
alter table public.used_vehicle_sales enable row level security;

drop policy if exists "used vehicle staff reads details v92" on public.used_vehicle_details;
create policy "used vehicle staff reads details v92"
  on public.used_vehicle_details
  for select to authenticated
  using (public.nostra_can_manage_used_vehicles_v92());

drop policy if exists "used vehicle staff manages details v92" on public.used_vehicle_details;
create policy "used vehicle staff manages details v92"
  on public.used_vehicle_details
  for all to authenticated
  using (public.nostra_can_manage_used_vehicles_v92())
  with check (public.nostra_can_manage_used_vehicles_v92());

drop policy if exists "used vehicle staff reads sales v92" on public.used_vehicle_sales;
create policy "used vehicle staff reads sales v92"
  on public.used_vehicle_sales
  for select to authenticated
  using (public.nostra_can_manage_used_vehicles_v92());

drop policy if exists "used vehicle staff manages sales v92" on public.used_vehicle_sales;
create policy "used vehicle staff manages sales v92"
  on public.used_vehicle_sales
  for all to authenticated
  using (public.nostra_can_manage_used_vehicles_v92())
  with check (public.nostra_can_manage_used_vehicles_v92());

-- Les fichiers occasion sont rangés sous le préfixe used/ dans le bucket déjà utilisé.
drop policy if exists "used vehicle staff uploads images v92" on storage.objects;
create policy "used vehicle staff uploads images v92"
  on storage.objects
  for insert to authenticated
  with check (
    bucket_id = 'vehicle-images'
    and name like 'used/%'
    and public.nostra_can_manage_used_vehicles_v92()
  );

drop policy if exists "used vehicle staff updates images v92" on storage.objects;
create policy "used vehicle staff updates images v92"
  on storage.objects
  for update to authenticated
  using (
    bucket_id = 'vehicle-images'
    and name like 'used/%'
    and public.nostra_can_manage_used_vehicles_v92()
  )
  with check (
    bucket_id = 'vehicle-images'
    and name like 'used/%'
    and public.nostra_can_manage_used_vehicles_v92()
  );

drop policy if exists "used vehicle staff deletes images v92" on storage.objects;
create policy "used vehicle staff deletes images v92"
  on storage.objects
  for delete to authenticated
  using (
    bucket_id = 'vehicle-images'
    and name like 'used/%'
    and public.nostra_can_manage_used_vehicles_v92()
  );

-- ---------------------------------------------------------------------------
-- 5. Helpers comptabilité / statut
-- ---------------------------------------------------------------------------

create or replace function public.nostra_upsert_used_purchase_accounting_v92(
  p_detail_id bigint
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  detail_row public.used_vehicle_details%rowtype;
  vehicle_row public.catalog_vehicles%rowtype;
  accounting_id bigint;
begin
  select * into detail_row
  from public.used_vehicle_details
  where id = p_detail_id;

  if not found then
    raise exception using message = 'used_vehicle_detail_not_found';
  end if;

  select * into vehicle_row
  from public.catalog_vehicles
  where id = detail_row.vehicle_id;

  insert into public.accounting_entries (
    entry_date,
    entry_type,
    category,
    label,
    amount,
    notes,
    nostra_source_type,
    nostra_source_id
  ) values (
    detail_row.purchase_date,
    'expense',
    'Véhicules d’occasion — Rachats',
    'Rachat ' || btrim(vehicle_row.brand || ' ' || vehicle_row.model),
    detail_row.purchase_price * greatest(detail_row.purchase_quantity, 0),
    concat_ws(
      ' · ',
      nullif('Immatriculation : ' || coalesce(detail_row.registration, ''), 'Immatriculation : '),
      nullif('Ancien propriétaire : ' || coalesce(detail_row.previous_owner, ''), 'Ancien propriétaire : '),
      'Quantité : ' || detail_row.purchase_quantity::text
    ),
    'used_purchase',
    detail_row.id::text
  )
  on conflict (nostra_source_type, nostra_source_id)
  do update set
    entry_date = excluded.entry_date,
    entry_type = excluded.entry_type,
    category = excluded.category,
    label = excluded.label,
    amount = excluded.amount,
    notes = excluded.notes
  returning id into accounting_id;

  update public.used_vehicle_details
  set purchase_accounting_entry_id = accounting_id
  where id = detail_row.id;

  return accounting_id;
end;
$$;

create or replace function public.nostra_refresh_used_vehicle_status_v92(
  p_vehicle_id bigint
)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  current_stock integer := 0;
  next_status text := 'available';
begin
  select greatest(stock_quantity, 0)
  into current_stock
  from public.catalog_vehicles
  where id = p_vehicle_id
    and catalog_type = 'used';

  if not found then
    return null;
  end if;

  if current_stock > 0 then
    next_status := 'available';
  elsif exists (
    select 1
    from public.orders order_row
    cross join lateral jsonb_array_elements(coalesce(order_row.items, '[]'::jsonb)) item
    where order_row.status in ('pending', 'confirmed', 'preparing', 'ready')
      and item ->> 'item_type' = 'vehicle'
      and nullif(item ->> 'vehicle_id', '')::bigint = p_vehicle_id
  ) then
    next_status := 'reserved';
  elsif exists (
    select 1
    from public.used_vehicle_sales sale
    where sale.vehicle_id = p_vehicle_id
  ) then
    next_status := 'sold';
  else
    next_status := 'sold';
  end if;

  update public.catalog_vehicles
  set used_vehicle_status = next_status,
      updated_at = now()
  where id = p_vehicle_id;

  update public.used_vehicle_details
  set sale_status = next_status,
      updated_at = now()
  where vehicle_id = p_vehicle_id;

  return next_status;
end;
$$;

-- ---------------------------------------------------------------------------
-- 6. RPC de gestion des rachats
-- ---------------------------------------------------------------------------

create or replace function public.create_used_vehicle_v92(
  p_brand text,
  p_model text,
  p_version text,
  p_registration text,
  p_previous_owner text,
  p_purchase_date date,
  p_purchase_price numeric,
  p_resale_price numeric,
  p_quantity integer,
  p_images jsonb,
  p_description text,
  p_condition text,
  p_internal_notes text,
  p_trunk_capacity text,
  p_top_speed text,
  p_power text,
  p_sort_order integer,
  p_published boolean
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_vehicle_id bigint;
  detail_id bigint;
  normalized_registration text := nullif(upper(btrim(coalesce(p_registration, ''))), '');
  normalized_condition text := lower(btrim(coalesce(p_condition, 'good')));
begin
  if not public.nostra_can_manage_used_vehicles_v92() then
    raise exception using message = 'forbidden';
  end if;

  if btrim(coalesce(p_brand, '')) = ''
    or btrim(coalesce(p_model, '')) = ''
    or p_purchase_date is null
    or coalesce(p_purchase_price, 0) <= 0
    or coalesce(p_resale_price, 0) <= 0
    or coalesce(p_quantity, 0) <= 0
  then
    raise exception using message = 'invalid_used_vehicle';
  end if;

  if normalized_condition not in ('excellent', 'very_good', 'good', 'fair', 'repair') then
    normalized_condition := 'good';
  end if;

  if normalized_registration is not null and exists (
    select 1 from public.used_vehicle_details
    where lower(registration) = lower(normalized_registration)
  ) then
    raise exception using message = 'registration_already_exists';
  end if;

  insert into public.catalog_vehicles (
    brand,
    model,
    trunk_capacity,
    top_speed,
    power,
    price,
    description,
    images,
    published,
    stock_quantity,
    sort_order,
    catalog_type,
    used_vehicle_status,
    used_condition,
    updated_at
  ) values (
    btrim(p_brand),
    btrim(p_model),
    coalesce(btrim(p_trunk_capacity), ''),
    coalesce(btrim(p_top_speed), ''),
    coalesce(btrim(p_power), ''),
    p_resale_price,
    coalesce(p_description, ''),
    coalesce(p_images, '[]'::jsonb),
    coalesce(p_published, true),
    p_quantity,
    greatest(coalesce(p_sort_order, 0), 0),
    'used',
    'available',
    normalized_condition,
    now()
  )
  returning id into v_vehicle_id;

  insert into public.used_vehicle_details (
    vehicle_id,
    version,
    registration,
    previous_owner,
    purchase_date,
    purchase_price,
    resale_price,
    purchase_quantity,
    vehicle_condition,
    internal_notes,
    sale_status,
    created_by,
    updated_by
  ) values (
    v_vehicle_id,
    nullif(btrim(coalesce(p_version, '')), ''),
    normalized_registration,
    nullif(btrim(coalesce(p_previous_owner, '')), ''),
    p_purchase_date,
    p_purchase_price,
    p_resale_price,
    p_quantity,
    normalized_condition,
    nullif(btrim(coalesce(p_internal_notes, '')), ''),
    'available',
    auth.uid(),
    auth.uid()
  )
  returning id into detail_id;

  perform public.nostra_upsert_used_purchase_accounting_v92(detail_id);
  return v_vehicle_id;
end;
$$;

create or replace function public.update_used_vehicle_v92(
  p_vehicle_id bigint,
  p_brand text,
  p_model text,
  p_version text,
  p_registration text,
  p_previous_owner text,
  p_purchase_date date,
  p_purchase_price numeric,
  p_resale_price numeric,
  p_quantity integer,
  p_images jsonb,
  p_description text,
  p_condition text,
  p_internal_notes text,
  p_trunk_capacity text,
  p_top_speed text,
  p_power text,
  p_sort_order integer,
  p_published boolean
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  detail_id bigint;
  normalized_registration text := nullif(upper(btrim(coalesce(p_registration, ''))), '');
  normalized_condition text := lower(btrim(coalesce(p_condition, 'good')));
begin
  if not public.nostra_can_manage_used_vehicles_v92() then
    raise exception using message = 'forbidden';
  end if;

  select detail.id into detail_id
  from public.used_vehicle_details detail
  join public.catalog_vehicles vehicle on vehicle.id = detail.vehicle_id
  where detail.vehicle_id = p_vehicle_id
    and vehicle.catalog_type = 'used'
  for update of detail, vehicle;

  if not found then
    raise exception using message = 'vehicle_not_found';
  end if;

  if btrim(coalesce(p_brand, '')) = ''
    or btrim(coalesce(p_model, '')) = ''
    or p_purchase_date is null
    or coalesce(p_purchase_price, 0) <= 0
    or coalesce(p_resale_price, 0) <= 0
    or coalesce(p_quantity, 0) <= 0
  then
    raise exception using message = 'invalid_used_vehicle';
  end if;

  if normalized_condition not in ('excellent', 'very_good', 'good', 'fair', 'repair') then
    normalized_condition := 'good';
  end if;

  if normalized_registration is not null and exists (
    select 1
    from public.used_vehicle_details
    where lower(registration) = lower(normalized_registration)
      and vehicle_id <> p_vehicle_id
  ) then
    raise exception using message = 'registration_already_exists';
  end if;

  update public.catalog_vehicles
  set brand = btrim(p_brand),
      model = btrim(p_model),
      trunk_capacity = coalesce(btrim(p_trunk_capacity), ''),
      top_speed = coalesce(btrim(p_top_speed), ''),
      power = coalesce(btrim(p_power), ''),
      price = p_resale_price,
      description = coalesce(p_description, ''),
      images = coalesce(p_images, '[]'::jsonb),
      published = coalesce(p_published, false),
      sort_order = greatest(coalesce(p_sort_order, 0), 0),
      catalog_type = 'used',
      used_condition = normalized_condition,
      updated_at = now()
  where id = p_vehicle_id;

  update public.used_vehicle_details
  set version = nullif(btrim(coalesce(p_version, '')), ''),
      registration = normalized_registration,
      previous_owner = nullif(btrim(coalesce(p_previous_owner, '')), ''),
      purchase_date = p_purchase_date,
      purchase_price = p_purchase_price,
      resale_price = p_resale_price,
      purchase_quantity = greatest(p_quantity, 1),
      vehicle_condition = normalized_condition,
      internal_notes = nullif(btrim(coalesce(p_internal_notes, '')), ''),
      updated_by = auth.uid(),
      updated_at = now()
  where id = detail_id;

  perform public.nostra_upsert_used_purchase_accounting_v92(detail_id);

  -- Une correction du prix de rachat recalcule aussi les marges historiques
  -- sans modifier le prix de vente ni la date des ventes.
  for detail_id in
    update public.used_vehicle_sales
    set unit_purchase_price = p_purchase_price,
        total_purchase_price = p_purchase_price * quantity,
        margin = total_sale_price - (p_purchase_price * quantity),
        updated_at = now()
    where vehicle_id = p_vehicle_id
    returning id
  loop
    perform public.nostra_upsert_used_sale_accounting_v92(detail_id);
  end loop;
end;
$$;

create or replace function public.delete_used_vehicle_v92(p_vehicle_id bigint)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  detail_id bigint;
begin
  if not public.nostra_can_manage_used_vehicles_v92() then
    raise exception using message = 'forbidden';
  end if;

  select id into detail_id
  from public.used_vehicle_details
  where vehicle_id = p_vehicle_id;

  if not found then
    raise exception using message = 'vehicle_not_found';
  end if;

  if exists (
    select 1
    from public.orders order_row
    cross join lateral jsonb_array_elements(coalesce(order_row.items, '[]'::jsonb)) item
    where item ->> 'item_type' = 'vehicle'
      and nullif(item ->> 'vehicle_id', '')::bigint = p_vehicle_id
      and order_row.status in ('pending', 'confirmed', 'preparing', 'ready')
  ) then
    raise exception using message = 'vehicle_has_active_order';
  end if;

  if exists (
    select 1 from public.used_vehicle_sales where vehicle_id = p_vehicle_id
  ) or exists (
    select 1
    from public.orders order_row
    cross join lateral jsonb_array_elements(coalesce(order_row.items, '[]'::jsonb)) item
    where item ->> 'item_type' = 'vehicle'
      and nullif(item ->> 'vehicle_id', '')::bigint = p_vehicle_id
      and order_row.status = 'completed'
  ) then
    raise exception using message = 'vehicle_has_sales';
  end if;

  delete from public.accounting_entries
  where nostra_source_type = 'used_purchase'
    and nostra_source_id = detail_id::text;

  delete from public.cart_items where vehicle_id = p_vehicle_id;
  delete from public.cart_items where related_vehicle_id = p_vehicle_id;
  delete from public.catalog_vehicles where id = p_vehicle_id;
end;
$$;

create or replace function public.update_used_vehicle_stock_v92(
  p_vehicle_id bigint,
  p_stock_quantity integer,
  p_sale_status text default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  next_status text := lower(btrim(coalesce(p_sale_status, '')));
begin
  if not public.nostra_can_manage_used_vehicles_v92() then
    raise exception using message = 'forbidden';
  end if;

  if not exists (
    select 1 from public.catalog_vehicles
    where id = p_vehicle_id and catalog_type = 'used'
  ) then
    raise exception using message = 'vehicle_not_found';
  end if;

  if next_status not in ('available', 'reserved', 'sold') then
    next_status := case when greatest(p_stock_quantity, 0) > 0 then 'available' else 'sold' end;
  end if;

  if next_status = 'available' and greatest(p_stock_quantity, 0) <= 0 then
    raise exception using message = 'available_requires_stock';
  end if;

  if next_status = 'sold' then
    p_stock_quantity := 0;
  end if;

  if next_status = 'available' and exists (
    select 1
    from public.orders order_row
    cross join lateral jsonb_array_elements(coalesce(order_row.items, '[]'::jsonb)) item
    where order_row.status in ('pending', 'confirmed', 'preparing', 'ready')
      and item ->> 'item_type' = 'vehicle'
      and nullif(item ->> 'vehicle_id', '')::bigint = p_vehicle_id
  ) then
    raise exception using message = 'vehicle_has_active_order';
  end if;

  update public.catalog_vehicles
  set stock_quantity = greatest(p_stock_quantity, 0),
      used_vehicle_status = next_status,
      updated_at = now()
  where id = p_vehicle_id;

  update public.used_vehicle_details
  set sale_status = next_status,
      updated_by = auth.uid(),
      updated_at = now()
  where vehicle_id = p_vehicle_id;
end;
$$;

create or replace function public.publish_used_vehicle_v92(
  p_vehicle_id bigint,
  p_published boolean
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.nostra_can_manage_used_vehicles_v92() then
    raise exception using message = 'forbidden';
  end if;

  update public.catalog_vehicles
  set published = coalesce(p_published, false),
      updated_at = now()
  where id = p_vehicle_id
    and catalog_type = 'used';

  if not found then
    raise exception using message = 'vehicle_not_found';
  end if;
end;
$$;

-- ---------------------------------------------------------------------------
-- 7. Synchronisation commandes -> réservation / vente / comptabilité / docs
-- ---------------------------------------------------------------------------

create or replace function public.nostra_upsert_used_sale_accounting_v92(
  p_sale_id bigint
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  sale_row public.used_vehicle_sales%rowtype;
  accounting_id bigint;
begin
  select * into sale_row
  from public.used_vehicle_sales
  where id = p_sale_id;

  if not found then
    raise exception using message = 'used_vehicle_sale_not_found';
  end if;

  insert into public.accounting_entries (
    entry_date,
    entry_type,
    category,
    label,
    amount,
    notes,
    nostra_source_type,
    nostra_source_id
  ) values (
    sale_row.sold_at::date,
    'income',
    'Véhicules d’occasion — Ventes',
    'Vente ' || sale_row.vehicle_name,
    sale_row.total_sale_price,
    'Commande ' || sale_row.order_number || ' · Client : ' || sale_row.customer_name,
    'used_sale',
    sale_row.id::text
  )
  on conflict (nostra_source_type, nostra_source_id)
  do update set
    entry_date = excluded.entry_date,
    entry_type = excluded.entry_type,
    category = excluded.category,
    label = excluded.label,
    amount = excluded.amount,
    notes = excluded.notes
  returning id into accounting_id;

  update public.used_vehicle_sales
  set sale_accounting_entry_id = accounting_id,
      updated_at = now()
  where id = sale_row.id;

  return accounting_id;
end;
$$;

create or replace function public.nostra_upsert_used_order_document_v92(
  p_order_id bigint,
  p_document_type text
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  order_row public.orders%rowtype;
  invoice_id bigint;
  invoice_number text;
  title text;
  payload jsonb;
  used_items jsonb := '[]'::jsonb;
  used_total numeric(14,2) := 0;
begin
  select * into order_row
  from public.orders
  where id = p_order_id;

  if not found then
    return null;
  end if;

  select
    coalesce(jsonb_agg(line.item order by line.ordinality), '[]'::jsonb),
    coalesce(sum(
      greatest(1, coalesce(nullif(line.item ->> 'quantity', '')::numeric, 1))
      * greatest(0, coalesce(nullif(line.item ->> 'unit_price', '')::numeric, 0))
    ), 0)
  into used_items, used_total
  from jsonb_array_elements(coalesce(order_row.items, '[]'::jsonb))
    with ordinality as line(item, ordinality)
  where (
    coalesce(line.item ->> 'item_type', 'vehicle') = 'vehicle'
    and exists (
      select 1
      from public.catalog_vehicles vehicle
      where vehicle.id = nullif(line.item ->> 'vehicle_id', '')::bigint
        and vehicle.catalog_type = 'used'
    )
  ) or (
    line.item ->> 'item_type' = 'delivery'
    and exists (
      select 1
      from public.catalog_vehicles vehicle
      where vehicle.id = nullif(line.item ->> 'related_vehicle_id', '')::bigint
        and vehicle.catalog_type = 'used'
    )
  );

  if jsonb_array_length(used_items) = 0 then
    return null;
  end if;

  if p_document_type = 'order_form' then
    invoice_number := 'VO-BC-' || order_row.order_number;
    title := 'Bon de commande — véhicule d’occasion';
  else
    invoice_number := 'VO-FA-' || order_row.order_number;
    title := 'Facture — véhicule d’occasion';
    p_document_type := 'invoice';
  end if;

  payload := jsonb_build_object(
    'order_number', order_row.order_number,
    'customer_name', order_row.customer_name,
    'customer_note', order_row.customer_note,
    'admin_note', order_row.admin_note,
    'total', used_total,
    'items', used_items,
    'confirmed_at', case when p_document_type = 'order_form' then now() else null end,
    'delivered_at', case when p_document_type = 'invoice' then now() else null end,
    'catalogue', 'Véhicules d’occasion'
  );

  insert into public.invoices (
    user_id,
    invoice_number,
    status,
    amount,
    issued_at,
    download_url,
    order_id,
    document_type,
    document_title,
    document_payload
  ) values (
    order_row.user_id,
    invoice_number,
    'issued',
    used_total,
    now(),
    null,
    order_row.id,
    p_document_type,
    title,
    payload
  )
  on conflict (invoice_number)
  do update set
    status = excluded.status,
    amount = excluded.amount,
    order_id = excluded.order_id,
    document_type = excluded.document_type,
    document_title = excluded.document_title,
    document_payload = excluded.document_payload
  returning id into invoice_id;

  return invoice_id;
end;
$$;

create or replace function public.nostra_validate_used_order_v92()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  item jsonb;
  v_vehicle_id bigint;
  vehicle_row public.catalog_vehicles%rowtype;
begin
  -- Une simple évolution de statut d'une commande active (confirmée, prête,
  -- terminée...) ne doit pas être bloquée par le statut « réservé » posé après
  -- sa création. La vérification concerne la création et la réactivation d'une
  -- commande précédemment annulée.
  if tg_op = 'UPDATE' and not (old.status = 'cancelled' and new.status <> 'cancelled') then
    return new;
  end if;

  for item in
    select value
    from jsonb_array_elements(coalesce(new.items, '[]'::jsonb))
  loop
    if coalesce(item ->> 'item_type', 'vehicle') <> 'vehicle' then
      continue;
    end if;

    v_vehicle_id := nullif(item ->> 'vehicle_id', '')::bigint;
    if v_vehicle_id is null then
      continue;
    end if;

    select * into vehicle_row
    from public.catalog_vehicles
    where id = v_vehicle_id
      and catalog_type = 'used';

    if found and vehicle_row.used_vehicle_status <> 'available' then
      raise exception using message = 'used_vehicle_unavailable';
    end if;
  end loop;

  return new;
end;
$$;

create or replace function public.nostra_sync_used_order_v92()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  source_order public.orders%rowtype;
  item jsonb;
  v_vehicle_id bigint;
  quantity integer;
  unit_sale_price numeric(14,2);
  detail_row public.used_vehicle_details%rowtype;
  vehicle_row public.catalog_vehicles%rowtype;
  sale_id bigint;
  has_used_vehicle boolean := false;
begin
  if tg_op = 'DELETE' then
    source_order := old;
  else
    source_order := new;
  end if;

  for item in
    select value
    from jsonb_array_elements(coalesce(source_order.items, '[]'::jsonb))
  loop
    if item ->> 'item_type' <> 'vehicle' then
      continue;
    end if;

    v_vehicle_id := nullif(item ->> 'vehicle_id', '')::bigint;
    if v_vehicle_id is null then
      continue;
    end if;

    select * into vehicle_row
    from public.catalog_vehicles
    where id = v_vehicle_id
      and catalog_type = 'used';

    if not found then
      continue;
    end if;

    has_used_vehicle := true;
    quantity := greatest(1, coalesce((item ->> 'quantity')::integer, 1));
    unit_sale_price := greatest(0, coalesce((item ->> 'unit_price')::numeric, vehicle_row.price));

    select detail.* into detail_row
    from public.used_vehicle_details detail
    where detail.vehicle_id = vehicle_row.id;

    if tg_op = 'DELETE' or source_order.status = 'cancelled' then
      for sale_id in
        select sale.id
        from public.used_vehicle_sales sale
        where sale.order_id = source_order.id
          and sale.vehicle_id = vehicle_row.id
      loop
        delete from public.accounting_entries
        where nostra_source_type = 'used_sale'
          and nostra_source_id = sale_id::text;
      end loop;

      delete from public.used_vehicle_sales
      where order_id = source_order.id
        and vehicle_id = vehicle_row.id;

      update public.used_vehicle_details
      set actual_sale_price = null,
          actual_margin = null,
          sold_at = null,
          sold_order_id = null,
          updated_at = now()
      where vehicle_id = vehicle_row.id
        and sold_order_id = source_order.id;

      perform public.nostra_refresh_used_vehicle_status_v92(vehicle_row.id);

    elsif source_order.status = 'completed' then
      insert into public.used_vehicle_sales (
        vehicle_id,
        order_id,
        order_number,
        user_id,
        customer_name,
        vehicle_name,
        quantity,
        unit_purchase_price,
        unit_sale_price,
        total_purchase_price,
        total_sale_price,
        margin,
        sold_at,
        updated_at
      ) values (
        vehicle_row.id,
        source_order.id,
        source_order.order_number,
        source_order.user_id,
        coalesce(source_order.customer_name, ''),
        btrim(vehicle_row.brand || ' ' || vehicle_row.model),
        quantity,
        coalesce(detail_row.purchase_price, 0),
        unit_sale_price,
        coalesce(detail_row.purchase_price, 0) * quantity,
        unit_sale_price * quantity,
        (unit_sale_price - coalesce(detail_row.purchase_price, 0)) * quantity,
        now(),
        now()
      )
      on conflict (order_id, vehicle_id)
      do update set
        order_number = excluded.order_number,
        user_id = excluded.user_id,
        customer_name = excluded.customer_name,
        vehicle_name = excluded.vehicle_name,
        quantity = excluded.quantity,
        unit_purchase_price = excluded.unit_purchase_price,
        unit_sale_price = excluded.unit_sale_price,
        total_purchase_price = excluded.total_purchase_price,
        total_sale_price = excluded.total_sale_price,
        margin = excluded.margin,
        sold_at = excluded.sold_at,
        updated_at = now()
      returning id into sale_id;

      perform public.nostra_upsert_used_sale_accounting_v92(sale_id);

      update public.used_vehicle_details
      set actual_sale_price = unit_sale_price,
          actual_margin = (unit_sale_price - coalesce(purchase_price, 0)) * quantity,
          sold_at = now(),
          sold_order_id = source_order.id,
          updated_at = now()
      where vehicle_id = vehicle_row.id;

      perform public.nostra_refresh_used_vehicle_status_v92(vehicle_row.id);

    else
      -- Une commande peut être repassée de « terminée » à un statut actif pendant
      -- les tests. Dans ce cas, retire uniquement la vente comptable liée à cette
      -- commande, sans toucher à la commande ni au stock déjà géré par le moteur
      -- de commandes existant.
      for sale_id in
        select sale.id
        from public.used_vehicle_sales sale
        where sale.order_id = source_order.id
          and sale.vehicle_id = vehicle_row.id
      loop
        delete from public.accounting_entries
        where nostra_source_type = 'used_sale'
          and nostra_source_id = sale_id::text;
      end loop;

      delete from public.used_vehicle_sales
      where order_id = source_order.id
        and vehicle_id = vehicle_row.id;

      update public.used_vehicle_details
      set actual_sale_price = null,
          actual_margin = null,
          sold_at = null,
          sold_order_id = null,
          updated_at = now()
      where vehicle_id = vehicle_row.id
        and sold_order_id = source_order.id;

      perform public.nostra_refresh_used_vehicle_status_v92(vehicle_row.id);
    end if;
  end loop;

  if has_used_vehicle then
    if tg_op = 'DELETE' or source_order.status = 'cancelled' then
      delete from public.invoices
      where order_id = source_order.id
        and invoice_number in (
          'VO-BC-' || source_order.order_number,
          'VO-FA-' || source_order.order_number
        );
    elsif source_order.status in ('confirmed', 'preparing', 'ready', 'completed') then
      perform public.nostra_upsert_used_order_document_v92(source_order.id, 'order_form');
      if source_order.status = 'completed' then
        perform public.nostra_upsert_used_order_document_v92(source_order.id, 'invoice');
      else
        delete from public.invoices
        where order_id = source_order.id
          and invoice_number = 'VO-FA-' || source_order.order_number;
      end if;
    else
      -- Une commande encore en attente ne doit pas conserver une facture créée
      -- lors d'un ancien passage au statut « terminée ».
      delete from public.invoices
      where order_id = source_order.id
        and invoice_number = 'VO-FA-' || source_order.order_number;
    end if;
  end if;

  if tg_op = 'DELETE' then
    return old;
  end if;
  return new;
end;
$$;

drop trigger if exists validate_used_order_v92 on public.orders;
drop trigger if exists sync_used_order_v92 on public.orders;
drop trigger if exists sync_used_order_delete_v92 on public.orders;

create trigger validate_used_order_v92
  before insert or update of status, items
  on public.orders
  for each row
  execute function public.nostra_validate_used_order_v92();

create trigger sync_used_order_v92
  after insert or update of status, items, total, admin_note
  on public.orders
  for each row
  execute function public.nostra_sync_used_order_v92();

-- Le nettoyage doit avoir lieu avant la suppression de la commande : la clé
-- étrangère des ventes supprime sinon l'historique avant que le trigger puisse
-- retirer la recette comptable correspondante.
create trigger sync_used_order_delete_v92
  before delete
  on public.orders
  for each row
  execute function public.nostra_sync_used_order_v92();

-- Répare / aligne les anciennes fiches occasion déjà éventuelles.
update public.catalog_vehicles
set used_vehicle_status = case when stock_quantity > 0 then 'available' else used_vehicle_status end,
    updated_at = now()
where catalog_type = 'used';

-- ---------------------------------------------------------------------------
-- 8. Droits d'exécution
-- ---------------------------------------------------------------------------

-- Les helpers SECURITY DEFINER ne doivent jamais être appelés directement
-- depuis le navigateur. Ils restent utilisables par les RPC et le trigger.
revoke all on function public.nostra_upsert_used_purchase_accounting_v92(bigint) from public, anon, authenticated;
revoke all on function public.nostra_refresh_used_vehicle_status_v92(bigint) from public, anon, authenticated;
revoke all on function public.nostra_upsert_used_sale_accounting_v92(bigint) from public, anon, authenticated;
revoke all on function public.nostra_upsert_used_order_document_v92(bigint,text) from public, anon, authenticated;
revoke all on function public.nostra_validate_used_order_v92() from public, anon, authenticated;
revoke all on function public.nostra_sync_used_order_v92() from public, anon, authenticated;

revoke all on function public.create_used_vehicle_v92(text,text,text,text,text,date,numeric,numeric,integer,jsonb,text,text,text,text,text,text,integer,boolean) from public, anon;
revoke all on function public.update_used_vehicle_v92(bigint,text,text,text,text,text,date,numeric,numeric,integer,jsonb,text,text,text,text,text,text,integer,boolean) from public, anon;
revoke all on function public.delete_used_vehicle_v92(bigint) from public, anon;
revoke all on function public.update_used_vehicle_stock_v92(bigint,integer,text) from public, anon;
revoke all on function public.publish_used_vehicle_v92(bigint,boolean) from public, anon;

grant execute on function public.create_used_vehicle_v92(text,text,text,text,text,date,numeric,numeric,integer,jsonb,text,text,text,text,text,text,integer,boolean) to authenticated;
grant execute on function public.update_used_vehicle_v92(bigint,text,text,text,text,text,date,numeric,numeric,integer,jsonb,text,text,text,text,text,text,integer,boolean) to authenticated;
grant execute on function public.delete_used_vehicle_v92(bigint) to authenticated;
grant execute on function public.update_used_vehicle_stock_v92(bigint,integer,text) to authenticated;
grant execute on function public.publish_used_vehicle_v92(bigint,boolean) to authenticated;

grant select on public.used_vehicle_details to authenticated;
grant select on public.used_vehicle_sales to authenticated;

notify pgrst, 'reload schema';

commit;

select
  to_regclass('public.used_vehicle_details') is not null as details_installes,
  to_regclass('public.used_vehicle_sales') is not null as ventes_installees,
  exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'catalog_vehicles'
      and column_name = 'used_vehicle_status'
  ) as statut_public_installe,
  to_regprocedure('public.create_used_vehicle_v92(text,text,text,text,text,date,numeric,numeric,integer,jsonb,text,text,text,text,text,text,integer,boolean)') is not null as rpc_rachats_installee,
  exists (
    select 1
    from pg_trigger
    where tgrelid = 'public.orders'::regclass
      and tgname = 'sync_used_order_v92'
      and not tgisinternal
  ) as synchronisation_commandes_installee,
  'V92_OK' as resultat;
