-- NOSTRA GROUP — V93
-- Réservation / commande des véhicules avec acompte de 15 %.
-- Réexécutable : ne supprime aucune commande, réservation ou donnée existante.

begin;

-- ---------------------------------------------------------------------------
-- 1. Réservations véhicules
-- ---------------------------------------------------------------------------

create table if not exists public.vehicle_reservations (
  id bigint generated by default as identity primary key,
  reservation_number text not null unique,
  user_id uuid not null references auth.users(id) on delete cascade,
  vehicle_id bigint not null references public.catalog_vehicles(id) on delete restrict,
  customer_name text not null default '',
  vehicle_name text not null,
  catalog_type text not null default 'standard',
  quantity integer not null default 1 check (quantity > 0),
  vehicle_price numeric(14,2) not null check (vehicle_price >= 0),
  deposit_percent numeric(5,2) not null default 15 check (deposit_percent > 0 and deposit_percent < 100),
  deposit_amount numeric(14,2) not null check (deposit_amount >= 0),
  balance_amount numeric(14,2) not null check (balance_amount >= 0),
  delivery_mode text not null default 'showroom' check (delivery_mode in ('showroom', 'home')),
  delivery_fee numeric(14,2) not null default 0 check (delivery_fee >= 0),
  delivery_address text,
  delivery_phone text,
  status text not null default 'pending_validation'
    check (status in ('pending_validation', 'balance_due', 'paid_full', 'rejected', 'cancelled', 'completed')),
  admin_note text,
  stock_reserved boolean not null default true,
  deposit_paid_at timestamptz not null default now(),
  validated_at timestamptz,
  balance_added_at timestamptz,
  balance_paid_at timestamptz,
  rejected_at timestamptz,
  final_order_id bigint references public.orders(id) on delete set null,
  final_order_number text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists vehicle_reservations_user_v93_idx
  on public.vehicle_reservations (user_id, created_at desc);
create index if not exists vehicle_reservations_status_v93_idx
  on public.vehicle_reservations (status, created_at desc);
create index if not exists vehicle_reservations_vehicle_v93_idx
  on public.vehicle_reservations (vehicle_id, status);
create unique index if not exists vehicle_reservations_active_user_vehicle_v93_uq
  on public.vehicle_reservations (user_id, vehicle_id)
  where status in ('pending_validation', 'balance_due', 'paid_full');

-- ---------------------------------------------------------------------------
-- 2. Extension du panier
-- ---------------------------------------------------------------------------

alter table public.cart_items add column if not exists reservation_id bigint;
alter table public.cart_items add column if not exists delivery_address text;
alter table public.cart_items add column if not exists delivery_phone text;
alter table public.cart_items add column if not exists locked boolean not null default false;
alter table public.cart_items add column if not exists original_unit_price numeric(14,2);

-- Remplace toute ancienne contrainte portant sur item_type.
do $$
declare
  constraint_row record;
begin
  for constraint_row in
    select conname
    from pg_constraint
    where conrelid = 'public.cart_items'::regclass
      and contype = 'c'
      and pg_get_constraintdef(oid) ilike '%item_type%'
  loop
    execute format(
      'alter table public.cart_items drop constraint if exists %I',
      constraint_row.conname
    );
  end loop;
end;
$$;

alter table public.cart_items
  add constraint cart_items_item_type_v93_check
  check (item_type in ('vehicle', 'delivery', 'reservation_deposit', 'reservation_balance')) not valid;
alter table public.cart_items validate constraint cart_items_item_type_v93_check;

-- Clé étrangère ajoutée après la création de la table.
do $$
begin
  if exists (
    select 1 from pg_constraint
    where conname = 'cart_items_reservation_id_fkey'
      and conrelid = 'public.cart_items'::regclass
  ) then
    alter table public.cart_items drop constraint cart_items_reservation_id_fkey;
  end if;

  alter table public.cart_items
    add constraint cart_items_reservation_id_fkey
    foreign key (reservation_id)
    references public.vehicle_reservations(id)
    on delete cascade;
end;
$$;

create index if not exists cart_items_reservation_v93_idx
  on public.cart_items (user_id, reservation_id, item_type);

-- ---------------------------------------------------------------------------
-- 3. Permissions
-- ---------------------------------------------------------------------------

create or replace function public.nostra_can_manage_vehicle_reservations_v93()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select auth.uid() is not null
    and (
      coalesce(
        auth.jwt() -> 'user_metadata' ->> 'provider_id',
        auth.jwt() -> 'user_metadata' ->> 'discord_id',
        auth.jwt() -> 'user_metadata' ->> 'sub'
      ) = '331843410962939908'
      or exists (
        select 1
        from public.member_profiles profile
        where profile.user_id = auth.uid()
          and (
            lower(coalesce(to_jsonb(profile) ->> 'role', ''))
              in ('manager', 'gerant', 'direction', 'administrator', 'admin', 'employee', 'employe', 'commercial', 'vendeur')
            or lower(coalesce((to_jsonb(profile) -> 'roles')::text, ''))
              ~ '(manager|gerant|direction|administrator|admin|employee|employe|commercial|vendeur)'
          )
      )
    );
$$;

grant execute on function public.nostra_can_manage_vehicle_reservations_v93() to authenticated;

alter table public.vehicle_reservations enable row level security;

drop policy if exists "vehicle reservation owner reads v93" on public.vehicle_reservations;
create policy "vehicle reservation owner reads v93"
  on public.vehicle_reservations
  for select to authenticated
  using (user_id = auth.uid());

drop policy if exists "vehicle reservation staff manages v93" on public.vehicle_reservations;
create policy "vehicle reservation staff manages v93"
  on public.vehicle_reservations
  for all to authenticated
  using (public.nostra_can_manage_vehicle_reservations_v93())
  with check (public.nostra_can_manage_vehicle_reservations_v93());

grant select on public.vehicle_reservations to authenticated;

-- ---------------------------------------------------------------------------
-- 4. Ajouter une commande ou un acompte au panier
-- ---------------------------------------------------------------------------

create or replace function public.add_vehicle_purchase_to_cart_v93(
  p_vehicle_id bigint,
  p_delivery_mode text,
  p_delivery_address text default null,
  p_delivery_phone text default null,
  p_purchase_mode text default 'order'
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_vehicle public.catalog_vehicles%rowtype;
  v_vehicle_line public.cart_items%rowtype;
  v_delivery_line public.cart_items%rowtype;
  v_next_quantity integer;
  v_image_url text;
  v_item_name text;
  v_deposit numeric(14,2);
begin
  if v_user_id is null then
    raise exception using message = 'not_authenticated';
  end if;

  if coalesce(p_delivery_mode, '') not in ('showroom', 'home') then
    raise exception using message = 'invalid_delivery_mode';
  end if;

  if coalesce(p_purchase_mode, '') not in ('order', 'reservation') then
    raise exception using message = 'invalid_purchase_mode';
  end if;

  select * into v_vehicle
  from public.catalog_vehicles
  where id = p_vehicle_id
    and published = true
  for share;

  if not found then
    raise exception using message = 'vehicle_unavailable';
  end if;

  if greatest(coalesce(v_vehicle.stock_quantity, 0), 0) <= 0 then
    raise exception using message = 'insufficient_stock';
  end if;

  if coalesce(to_jsonb(v_vehicle) ->> 'catalog_type', 'standard') = 'heavy'
     and p_delivery_mode = 'home' then
    raise exception using message = 'heavy_home_delivery_disabled';
  end if;

  if coalesce(to_jsonb(v_vehicle) ->> 'catalog_type', 'standard') = 'used'
     and coalesce(to_jsonb(v_vehicle) ->> 'used_vehicle_status', 'available') <> 'available' then
    raise exception using message = 'used_vehicle_unavailable';
  end if;

  if p_delivery_mode = 'home' and length(btrim(coalesce(p_delivery_address, ''))) < 5 then
    raise exception using message = 'invalid_delivery_address';
  end if;

  if p_delivery_mode = 'home' and length(btrim(coalesce(p_delivery_phone, ''))) < 3 then
    raise exception using message = 'invalid_delivery_phone';
  end if;

  v_item_name := btrim(v_vehicle.brand || ' ' || v_vehicle.model);
  v_image_url := case
    when jsonb_typeof(v_vehicle.images) = 'array'
      and jsonb_array_length(v_vehicle.images) > 0
    then v_vehicle.images -> 0 ->> 'url'
    else null
  end;

  if p_purchase_mode = 'reservation' then
    if exists (
      select 1 from public.vehicle_reservations
      where user_id = v_user_id
        and vehicle_id = p_vehicle_id
        and status in ('pending_validation', 'balance_due', 'paid_full')
    ) then
      raise exception using message = 'reservation_already_exists';
    end if;

    delete from public.cart_items
    where user_id = v_user_id
      and (
        (item_type = 'vehicle' and vehicle_id = p_vehicle_id)
        or (item_type = 'delivery' and related_vehicle_id = p_vehicle_id)
      );

    v_deposit := round(greatest(coalesce(v_vehicle.price, 0), 0) * 0.15, 2);

    -- Remplace un éventuel acompte non payé du même véhicule afin que le
    -- mode de livraison et les coordonnées restent toujours à jour.
    delete from public.cart_items
    where user_id = v_user_id
      and item_type = 'reservation_deposit'
      and vehicle_id = p_vehicle_id;

    insert into public.cart_items (
      user_id,
      vehicle_id,
      related_vehicle_id,
      reservation_id,
      item_type,
      delivery_mode,
      delivery_address,
      delivery_phone,
      item_name,
      quantity,
      unit_price,
      original_unit_price,
      image_url,
      locked
    ) values (
      v_user_id,
      p_vehicle_id,
      p_vehicle_id,
      null,
      'reservation_deposit',
      p_delivery_mode,
      case when p_delivery_mode = 'home' then btrim(p_delivery_address) else null end,
      case when p_delivery_mode = 'home' then btrim(p_delivery_phone) else null end,
      'Acompte 15 % — ' || v_item_name,
      1,
      v_deposit,
      v_vehicle.price,
      v_image_url,
      false
    );

    return jsonb_build_object(
      'purchase_mode', 'reservation',
      'vehicle_id', p_vehicle_id,
      'deposit_amount', v_deposit,
      'balance_amount', round(greatest(coalesce(v_vehicle.price, 0), 0) - v_deposit, 2)
    );
  end if;

  -- Commander au prix total : retire l'éventuel acompte non payé du même véhicule.
  delete from public.cart_items
  where user_id = v_user_id
    and item_type = 'reservation_deposit'
    and vehicle_id = p_vehicle_id;

  select * into v_vehicle_line
  from public.cart_items
  where user_id = v_user_id
    and item_type = 'vehicle'
    and vehicle_id = p_vehicle_id
  order by id
  limit 1
  for update;

  v_next_quantity := coalesce(v_vehicle_line.quantity, 0) + 1;
  if v_next_quantity > v_vehicle.stock_quantity then
    raise exception using message = 'insufficient_stock';
  end if;

  if v_vehicle_line.id is null then
    insert into public.cart_items (
      user_id, vehicle_id, related_vehicle_id, reservation_id, item_type,
      delivery_mode, delivery_address, delivery_phone, item_name, quantity,
      unit_price, original_unit_price, image_url, locked
    ) values (
      v_user_id, p_vehicle_id, null, null, 'vehicle', p_delivery_mode,
      case when p_delivery_mode = 'home' then btrim(p_delivery_address) else null end,
      case when p_delivery_mode = 'home' then btrim(p_delivery_phone) else null end,
      v_item_name, 1, v_vehicle.price, v_vehicle.price, v_image_url, false
    );
  else
    update public.cart_items
    set quantity = v_next_quantity,
        item_name = v_item_name,
        unit_price = v_vehicle.price,
        original_unit_price = v_vehicle.price,
        image_url = v_image_url,
        delivery_mode = p_delivery_mode,
        delivery_address = case when p_delivery_mode = 'home' then btrim(p_delivery_address) else null end,
        delivery_phone = case when p_delivery_mode = 'home' then btrim(p_delivery_phone) else null end
    where id = v_vehicle_line.id;
  end if;

  if p_delivery_mode = 'home' then
    select * into v_delivery_line
    from public.cart_items
    where user_id = v_user_id
      and item_type = 'delivery'
      and related_vehicle_id = p_vehicle_id
    order by id
    limit 1
    for update;

    if v_delivery_line.id is null then
      insert into public.cart_items (
        user_id, vehicle_id, related_vehicle_id, reservation_id, item_type,
        delivery_mode, delivery_address, delivery_phone, item_name, quantity,
        unit_price, original_unit_price, image_url, locked
      ) values (
        v_user_id, null, p_vehicle_id, null, 'delivery', 'home',
        btrim(p_delivery_address), btrim(p_delivery_phone),
        'Livraison à domicile — ' || v_item_name,
        1, 75000, 75000, null, false
      );
    else
      update public.cart_items
      set quantity = v_next_quantity,
          delivery_address = btrim(p_delivery_address),
          delivery_phone = btrim(p_delivery_phone),
          item_name = 'Livraison à domicile — ' || v_item_name,
          unit_price = 75000,
          original_unit_price = 75000
      where id = v_delivery_line.id;
    end if;
  else
    delete from public.cart_items
    where user_id = v_user_id
      and item_type = 'delivery'
      and related_vehicle_id = p_vehicle_id;
  end if;

  return jsonb_build_object(
    'purchase_mode', 'order',
    'vehicle_id', p_vehicle_id,
    'delivery_mode', p_delivery_mode,
    'delivery_price', case when p_delivery_mode = 'home' then 75000 else 0 end
  );
end;
$$;

-- ---------------------------------------------------------------------------
-- 5. Commander les lignes normales sans supprimer les réservations du panier
-- ---------------------------------------------------------------------------

create or replace function public.place_nostra_order_v93(
  p_order_number text,
  p_customer_name text,
  p_customer_note text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_order_id bigint;
  v_total numeric(14,2) := 0;
  v_items jsonb := '[]'::jsonb;
  v_line record;
  v_vehicle record;
  v_delivery record;
  v_vehicle_quantity integer;
begin
  if v_user_id is null then
    raise exception using message = 'not_authenticated';
  end if;

  if not exists (
    select 1 from public.cart_items
    where user_id = v_user_id and item_type = 'vehicle'
  ) then
    raise exception using message = 'empty_cart';
  end if;

  if exists (
    select 1 from public.cart_items
    where user_id = v_user_id and item_type = 'vehicle' and vehicle_id is null
  ) then
    raise exception using message = 'cart_needs_refresh';
  end if;

  for v_line in
    select vehicle_id, sum(quantity)::integer as quantity, max(image_url) as image_url
    from public.cart_items
    where user_id = v_user_id and item_type = 'vehicle'
    group by vehicle_id
    order by vehicle_id
  loop
    select id, brand, model, price, images, published, stock_quantity
    into v_vehicle
    from public.catalog_vehicles
    where id = v_line.vehicle_id
    for update;

    if not found or not v_vehicle.published then
      raise exception using message = 'vehicle_unavailable';
    end if;
    if v_vehicle.stock_quantity < v_line.quantity then
      raise exception using message = 'insufficient_stock';
    end if;

    update public.catalog_vehicles
    set stock_quantity = stock_quantity - v_line.quantity, updated_at = now()
    where id = v_vehicle.id;

    v_items := v_items || jsonb_build_array(jsonb_build_object(
      'item_type', 'vehicle',
      'vehicle_id', v_vehicle.id,
      'name', btrim(v_vehicle.brand || ' ' || v_vehicle.model),
      'quantity', v_line.quantity,
      'unit_price', v_vehicle.price,
      'image_url', coalesce(v_line.image_url, v_vehicle.images -> 0 ->> 'url')
    ));
    v_total := v_total + (v_vehicle.price * v_line.quantity);
  end loop;

  for v_delivery in
    select related_vehicle_id, sum(quantity)::integer as quantity,
           max(delivery_address) as delivery_address,
           max(delivery_phone) as delivery_phone
    from public.cart_items
    where user_id = v_user_id and item_type = 'delivery'
    group by related_vehicle_id
    order by related_vehicle_id
  loop
    if v_delivery.related_vehicle_id is null then
      raise exception using message = 'invalid_delivery_cart';
    end if;

    select coalesce(sum(quantity), 0)::integer into v_vehicle_quantity
    from public.cart_items
    where user_id = v_user_id
      and item_type = 'vehicle'
      and vehicle_id = v_delivery.related_vehicle_id;

    if v_vehicle_quantity <= 0 or v_delivery.quantity > v_vehicle_quantity then
      raise exception using message = 'invalid_delivery_cart';
    end if;

    select * into v_vehicle
    from public.catalog_vehicles
    where id = v_delivery.related_vehicle_id;
    if not found then raise exception using message = 'vehicle_unavailable'; end if;
    if coalesce(to_jsonb(v_vehicle) ->> 'catalog_type', 'standard') = 'heavy' then
      raise exception using message = 'heavy_home_delivery_disabled';
    end if;
    if length(btrim(coalesce(v_delivery.delivery_address, ''))) < 5 then
      raise exception using message = 'invalid_delivery_address';
    end if;
    if length(btrim(coalesce(v_delivery.delivery_phone, ''))) < 3 then
      raise exception using message = 'invalid_delivery_phone';
    end if;

    v_items := v_items || jsonb_build_array(jsonb_build_object(
      'item_type', 'delivery',
      'vehicle_id', null,
      'related_vehicle_id', v_vehicle.id,
      'name', 'Livraison à domicile — ' || btrim(v_vehicle.brand || ' ' || v_vehicle.model),
      'delivery_address', v_delivery.delivery_address,
      'delivery_phone', v_delivery.delivery_phone,
      'quantity', v_delivery.quantity,
      'unit_price', 75000,
      'image_url', null
    ));
    v_total := v_total + (75000 * v_delivery.quantity);
  end loop;

  insert into public.orders (
    user_id, order_number, customer_name, status, total, items,
    customer_note, stock_deducted, updated_at
  ) values (
    v_user_id, p_order_number,
    coalesce(nullif(btrim(p_customer_name), ''), 'Client Nostra Motors'),
    'pending', v_total, v_items,
    nullif(btrim(coalesce(p_customer_note, '')), ''), true, now()
  ) returning id into v_order_id;

  delete from public.cart_items
  where user_id = v_user_id and item_type in ('vehicle', 'delivery');

  return jsonb_build_object(
    'id', v_order_id,
    'order_number', p_order_number,
    'total', v_total
  );
end;
$$;

-- ---------------------------------------------------------------------------
-- 6. Paiement des acomptes
-- ---------------------------------------------------------------------------

create or replace function public.checkout_vehicle_reservation_deposits_v93(
  p_customer_name text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_line record;
  v_vehicle public.catalog_vehicles%rowtype;
  v_reservation_id bigint;
  v_reservation_number text;
  v_count integer := 0;
  v_deposit numeric(14,2);
  v_balance numeric(14,2);
  v_catalog_type text;
begin
  if v_user_id is null then raise exception using message = 'not_authenticated'; end if;
  if not exists (
    select 1 from public.cart_items
    where user_id = v_user_id and item_type = 'reservation_deposit'
  ) then raise exception using message = 'empty_reservation_cart'; end if;

  for v_line in
    select * from public.cart_items
    where user_id = v_user_id and item_type = 'reservation_deposit'
    order by id
    for update
  loop
    select * into v_vehicle
    from public.catalog_vehicles
    where id = v_line.vehicle_id and published = true
    for update;

    if not found then raise exception using message = 'vehicle_unavailable'; end if;
    if v_vehicle.stock_quantity < 1 then raise exception using message = 'insufficient_stock'; end if;
    if exists (
      select 1 from public.vehicle_reservations
      where user_id = v_user_id
        and vehicle_id = v_vehicle.id
        and status in ('pending_validation', 'balance_due', 'paid_full')
    ) then raise exception using message = 'reservation_already_exists'; end if;

    v_catalog_type := coalesce(to_jsonb(v_vehicle) ->> 'catalog_type', 'standard');
    if coalesce(v_line.delivery_mode, '') not in ('showroom', 'home') then
      raise exception using message = 'invalid_delivery_mode';
    end if;
    if v_catalog_type = 'heavy' and v_line.delivery_mode = 'home' then
      raise exception using message = 'heavy_home_delivery_disabled';
    end if;
    if v_line.delivery_mode = 'home'
       and length(btrim(coalesce(v_line.delivery_address, ''))) < 5 then
      raise exception using message = 'invalid_delivery_address';
    end if;
    if v_line.delivery_mode = 'home'
       and length(btrim(coalesce(v_line.delivery_phone, ''))) < 3 then
      raise exception using message = 'invalid_delivery_phone';
    end if;
    if v_catalog_type = 'used'
       and coalesce(to_jsonb(v_vehicle) ->> 'used_vehicle_status', 'available') <> 'available' then
      raise exception using message = 'used_vehicle_unavailable';
    end if;

    v_deposit := round(v_vehicle.price * 0.15, 2);
    v_balance := round(v_vehicle.price - v_deposit, 2);
    v_reservation_number := 'RES-' || to_char(clock_timestamp(), 'YYYYMMDD') || '-' || upper(substr(md5(random()::text || clock_timestamp()::text || v_line.id::text), 1, 7));

    update public.catalog_vehicles
    set stock_quantity = stock_quantity - 1, updated_at = now()
    where id = v_vehicle.id;

    insert into public.vehicle_reservations (
      reservation_number, user_id, vehicle_id, customer_name, vehicle_name,
      catalog_type, quantity, vehicle_price, deposit_percent, deposit_amount,
      balance_amount, delivery_mode, delivery_fee, delivery_address,
      delivery_phone, status, stock_reserved, deposit_paid_at, created_at,
      updated_at
    ) values (
      v_reservation_number, v_user_id, v_vehicle.id,
      coalesce(nullif(btrim(p_customer_name), ''), 'Client Nostra Motors'),
      btrim(v_vehicle.brand || ' ' || v_vehicle.model), v_catalog_type, 1,
      v_vehicle.price, 15, v_deposit, v_balance,
      coalesce(v_line.delivery_mode, 'showroom'),
      case when v_line.delivery_mode = 'home' then 75000 else 0 end,
      case when v_line.delivery_mode = 'home' then v_line.delivery_address else null end,
      case when v_line.delivery_mode = 'home' then v_line.delivery_phone else null end,
      'pending_validation', true, now(), now(), now()
    ) returning id into v_reservation_id;

    if v_catalog_type = 'used' and v_vehicle.stock_quantity - 1 <= 0 then
      update public.catalog_vehicles
      set used_vehicle_status = 'reserved', updated_at = now()
      where id = v_vehicle.id;
      if to_regclass('public.used_vehicle_details') is not null then
        execute 'update public.used_vehicle_details set sale_status = ''reserved'', updated_at = now() where vehicle_id = $1'
        using v_vehicle.id;
      end if;
    end if;

    delete from public.cart_items where id = v_line.id;
    v_count := v_count + 1;
  end loop;

  return jsonb_build_object('reservations_created', v_count);
end;
$$;

-- ---------------------------------------------------------------------------
-- 7. Validation / refus par la concession
-- ---------------------------------------------------------------------------

create or replace function public.review_vehicle_reservation_v93(
  p_reservation_id bigint,
  p_decision text,
  p_admin_note text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_reservation public.vehicle_reservations%rowtype;
  v_vehicle public.catalog_vehicles%rowtype;
  v_balance_total numeric(14,2);
  v_image_url text;
begin
  if not public.nostra_can_manage_vehicle_reservations_v93() then
    raise exception using message = 'forbidden';
  end if;
  if coalesce(p_decision, '') not in ('approve', 'reject') then
    raise exception using message = 'invalid_decision';
  end if;

  select * into v_reservation
  from public.vehicle_reservations
  where id = p_reservation_id
  for update;
  if not found then raise exception using message = 'reservation_not_found'; end if;

  select * into v_vehicle
  from public.catalog_vehicles
  where id = v_reservation.vehicle_id;
  if not found then raise exception using message = 'vehicle_unavailable'; end if;

  if p_decision = 'reject' then
    if v_reservation.status not in ('pending_validation', 'balance_due') then
      raise exception using message = 'reservation_not_reviewable';
    end if;

    delete from public.cart_items
    where reservation_id = v_reservation.id
      and item_type = 'reservation_balance';

    if v_reservation.stock_reserved then
      update public.catalog_vehicles
      set stock_quantity = stock_quantity + v_reservation.quantity,
          updated_at = now()
      where id = v_reservation.vehicle_id;
    end if;

    update public.vehicle_reservations
    set status = 'rejected',
        stock_reserved = false,
        admin_note = nullif(btrim(coalesce(p_admin_note, '')), ''),
        rejected_at = now(),
        updated_at = now()
    where id = v_reservation.id;

    if v_reservation.catalog_type = 'used' then
      update public.catalog_vehicles
      set used_vehicle_status = case when stock_quantity > 0 then 'available' else 'sold' end,
          updated_at = now()
      where id = v_reservation.vehicle_id;
      if to_regclass('public.used_vehicle_details') is not null then
        execute 'update public.used_vehicle_details set sale_status = case when (select stock_quantity from public.catalog_vehicles where id = $1) > 0 then ''available'' else ''sold'' end, updated_at = now() where vehicle_id = $1'
        using v_reservation.vehicle_id;
      end if;
    end if;

    return jsonb_build_object('status', 'rejected');
  end if;

  if v_reservation.status not in ('pending_validation', 'balance_due') then
    raise exception using message = 'reservation_not_reviewable';
  end if;

  v_balance_total := v_reservation.balance_amount + v_reservation.delivery_fee;
  v_image_url := case
    when jsonb_typeof(v_vehicle.images) = 'array' and jsonb_array_length(v_vehicle.images) > 0
    then v_vehicle.images -> 0 ->> 'url'
    else null
  end;

  -- Une validation répétée remet proprement le même solde dans le panier,
  -- sans créer plusieurs lignes pour une seule réservation.
  delete from public.cart_items
  where user_id = v_reservation.user_id
    and reservation_id = v_reservation.id
    and item_type = 'reservation_balance';

  insert into public.cart_items (
    user_id, vehicle_id, related_vehicle_id, reservation_id, item_type,
    delivery_mode, delivery_address, delivery_phone, item_name, quantity,
    unit_price, original_unit_price, image_url, locked
  ) values (
    v_reservation.user_id, v_reservation.vehicle_id, v_reservation.vehicle_id,
    v_reservation.id, 'reservation_balance', v_reservation.delivery_mode,
    v_reservation.delivery_address, v_reservation.delivery_phone,
    'Solde réservation — ' || v_reservation.vehicle_name,
    1, v_balance_total, v_reservation.vehicle_price, v_image_url, true
  );

  update public.vehicle_reservations
  set status = 'balance_due',
      admin_note = nullif(btrim(coalesce(p_admin_note, '')), ''),
      validated_at = coalesce(validated_at, now()),
      balance_added_at = now(),
      updated_at = now()
  where id = v_reservation.id;

  return jsonb_build_object('status', 'balance_due', 'balance_added', v_balance_total);
end;
$$;

-- ---------------------------------------------------------------------------
-- 8. Paiement des soldes et création de la commande finale
-- ---------------------------------------------------------------------------

create or replace function public.checkout_vehicle_reservation_balances_v93()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_line record;
  v_reservation public.vehicle_reservations%rowtype;
  v_vehicle public.catalog_vehicles%rowtype;
  v_order_id bigint;
  v_order_number text;
  v_items jsonb;
  v_total numeric(14,2);
  v_count integer := 0;
begin
  if v_user_id is null then raise exception using message = 'not_authenticated'; end if;
  if not exists (
    select 1 from public.cart_items
    where user_id = v_user_id and item_type = 'reservation_balance'
  ) then raise exception using message = 'empty_balance_cart'; end if;

  for v_line in
    select * from public.cart_items
    where user_id = v_user_id and item_type = 'reservation_balance'
    order by id
    for update
  loop
    select * into v_reservation
    from public.vehicle_reservations
    where id = v_line.reservation_id
      and user_id = v_user_id
    for update;

    if not found or v_reservation.status <> 'balance_due' then
      raise exception using message = 'reservation_balance_unavailable';
    end if;

    select * into v_vehicle
    from public.catalog_vehicles
    where id = v_reservation.vehicle_id;
    if not found then raise exception using message = 'vehicle_unavailable'; end if;

    v_order_number := 'NR-' || to_char(clock_timestamp(), 'YYYYMMDD') || '-' || upper(substr(md5(random()::text || clock_timestamp()::text || v_reservation.id::text), 1, 7));
    v_total := v_reservation.vehicle_price + v_reservation.delivery_fee;
    v_items := jsonb_build_array(jsonb_build_object(
      'item_type', 'vehicle',
      'vehicle_id', v_reservation.vehicle_id,
      'reservation_id', v_reservation.id,
      'name', v_reservation.vehicle_name,
      'quantity', v_reservation.quantity,
      'unit_price', v_reservation.vehicle_price,
      'deposit_paid', v_reservation.deposit_amount,
      'balance_paid', v_reservation.balance_amount,
      'image_url', case when jsonb_typeof(v_vehicle.images) = 'array' and jsonb_array_length(v_vehicle.images) > 0 then v_vehicle.images -> 0 ->> 'url' else null end
    ));

    if v_reservation.delivery_mode = 'home' then
      v_items := v_items || jsonb_build_array(jsonb_build_object(
        'item_type', 'delivery',
        'vehicle_id', null,
        'related_vehicle_id', v_reservation.vehicle_id,
        'reservation_id', v_reservation.id,
        'name', 'Livraison à domicile — ' || v_reservation.vehicle_name,
        'delivery_address', v_reservation.delivery_address,
        'delivery_phone', v_reservation.delivery_phone,
        'quantity', v_reservation.quantity,
        'unit_price', v_reservation.delivery_fee,
        'image_url', null
      ));
    end if;

    insert into public.orders (
      user_id, order_number, customer_name, status, total, items,
      customer_note, stock_deducted, updated_at
    ) values (
      v_user_id, v_order_number, v_reservation.customer_name, 'pending',
      v_total, v_items,
      'Commande issue de la réservation ' || v_reservation.reservation_number,
      true, now()
    ) returning id into v_order_id;

    update public.vehicle_reservations
    set status = 'paid_full',
        balance_paid_at = now(),
        final_order_id = v_order_id,
        final_order_number = v_order_number,
        updated_at = now()
    where id = v_reservation.id;

    delete from public.cart_items where id = v_line.id;
    v_count := v_count + 1;
  end loop;

  return jsonb_build_object('orders_created', v_count);
end;
$$;

-- ---------------------------------------------------------------------------
-- 9. Compatibilité Véhicules d'occasion V92
-- ---------------------------------------------------------------------------

create or replace function public.nostra_validate_used_order_v92()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  item jsonb;
  v_vehicle_id bigint;
  v_reservation_id bigint;
  vehicle_row public.catalog_vehicles%rowtype;
begin
  if tg_op = 'UPDATE' and not (old.status = 'cancelled' and new.status <> 'cancelled') then
    return new;
  end if;

  for item in select value from jsonb_array_elements(coalesce(new.items, '[]'::jsonb))
  loop
    if coalesce(item ->> 'item_type', 'vehicle') <> 'vehicle' then continue; end if;
    v_vehicle_id := nullif(item ->> 'vehicle_id', '')::bigint;
    if v_vehicle_id is null then continue; end if;

    select * into vehicle_row
    from public.catalog_vehicles
    where id = v_vehicle_id and catalog_type = 'used';

    if found and vehicle_row.used_vehicle_status <> 'available' then
      v_reservation_id := nullif(item ->> 'reservation_id', '')::bigint;
      if v_reservation_id is null or not exists (
        select 1 from public.vehicle_reservations reservation
        where reservation.id = v_reservation_id
          and reservation.user_id = new.user_id
          and reservation.vehicle_id = v_vehicle_id
          and reservation.status in ('balance_due', 'paid_full')
      ) then
        raise exception using message = 'used_vehicle_unavailable';
      end if;
    end if;
  end loop;
  return new;
end;
$$;

-- Synchronise l'état de la réservation avec la commande finale.
create or replace function public.nostra_sync_reservation_order_status_v93()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'DELETE' then
    update public.vehicle_reservations
    set status = 'cancelled',
        stock_reserved = false,
        final_order_id = null,
        updated_at = now()
    where final_order_id = old.id;
    return old;
  end if;

  update public.vehicle_reservations
  set status = case
        when new.status = 'completed' then 'completed'
        when new.status = 'cancelled' then 'cancelled'
        else 'paid_full'
      end,
      stock_reserved = case when new.status = 'cancelled' then false else stock_reserved end,
      updated_at = now()
  where final_order_id = new.id;
  return new;
end;
$$;

drop trigger if exists sync_reservation_order_status_v93 on public.orders;
create trigger sync_reservation_order_status_v93
  after update of status on public.orders
  for each row
  execute function public.nostra_sync_reservation_order_status_v93();

drop trigger if exists sync_reservation_order_delete_v93 on public.orders;
create trigger sync_reservation_order_delete_v93
  before delete on public.orders
  for each row
  execute function public.nostra_sync_reservation_order_status_v93();

-- ---------------------------------------------------------------------------
-- 10. Droits d'exécution
-- ---------------------------------------------------------------------------

revoke all on function public.add_vehicle_purchase_to_cart_v93(bigint,text,text,text,text) from public, anon;
revoke all on function public.place_nostra_order_v93(text,text,text) from public, anon;
revoke all on function public.checkout_vehicle_reservation_deposits_v93(text) from public, anon;
revoke all on function public.review_vehicle_reservation_v93(bigint,text,text) from public, anon;
revoke all on function public.checkout_vehicle_reservation_balances_v93() from public, anon;
revoke all on function public.nostra_sync_reservation_order_status_v93() from public, anon, authenticated;

grant execute on function public.add_vehicle_purchase_to_cart_v93(bigint,text,text,text,text) to authenticated;
grant execute on function public.place_nostra_order_v93(text,text,text) to authenticated;
grant execute on function public.checkout_vehicle_reservation_deposits_v93(text) to authenticated;
grant execute on function public.review_vehicle_reservation_v93(bigint,text,text) to authenticated;
grant execute on function public.checkout_vehicle_reservation_balances_v93() to authenticated;

notify pgrst, 'reload schema';

commit;

select
  to_regclass('public.vehicle_reservations') is not null as table_reservations,
  to_regprocedure('public.add_vehicle_purchase_to_cart_v93(bigint,text,text,text,text)') is not null as ajout_panier,
  to_regprocedure('public.checkout_vehicle_reservation_deposits_v93(text)') is not null as paiement_acompte,
  to_regprocedure('public.review_vehicle_reservation_v93(bigint,text,text)') is not null as validation_dashboard,
  to_regprocedure('public.checkout_vehicle_reservation_balances_v93()') is not null as paiement_solde,
  'V93_OK' as resultat;
