import Link from "next/link";
import { addSupplierOrderItemV163, createSupplierOrderV163, saveSupplierV163, updateSupplierOrderV163 } from "@/app/actions/v163";
import { DashboardShell } from "@/components/dashboard/dashboard-shell";
import styles from "@/components/v163/v163.module.css";
import { getSuppliersV163 } from "@/lib/v163/data";

export const dynamic="force-dynamic";
const money=(v:unknown)=>Number(v??0).toLocaleString("fr-FR",{style:"currency",currency:"EUR",maximumFractionDigits:0});
const date=(v:unknown)=>v?new Date(String(v)).toLocaleDateString("fr-FR"):"—";
const status:Record<string,string>={draft:"Brouillon",ordered:"Commandée",confirmed:"Confirmée",in_transit:"En transport",arrived:"Arrivée",received:"Réceptionnée",cancelled:"Annulée"};

export default async function SuppliersPage({searchParams}:{searchParams:Promise<Record<string,string|undefined>>}){
  const p=await searchParams; const data=await getSuppliersV163(); const selected=data.orders.find((x:any)=>String(x.id)===String(p.order))??data.orders[0]??null;
  const vehicleMap=new Map(data.vehicles.map((v:any)=>[Number(v.id),v]));
  return <DashboardShell allowedRoles={["manager","employee","commercial"]}><div className={styles.page}>
    <section className={styles.hero}><p className={styles.eyebrow}>NOSTRA MOTORS · ACHATS</p><h1>Fournisseurs & arrivages</h1><p className={styles.muted}>Pilote les fournisseurs, commandes d’achat, dates d’arrivée et coûts réels. Une réception peut alimenter automatiquement le stock catalogue et les exemplaires physiques V162.</p></section>
    {!data.configured&&<div className={styles.error}>Module non activé : exécute le SQL V163 dans Supabase.</div>}
    {p.saved&&<div className={styles.success}>Fournisseur enregistré.</div>}{p.created&&<div className={styles.success}>Commande fournisseur créée.</div>}
    <div className={styles.grid2}>
      <div className={styles.stack}>
        <section className={styles.card}><div className={styles.row}><div><p className={styles.eyebrow}>RÉSEAU</p><h2>Fournisseurs</h2></div><span className={styles.pill}>{data.suppliers.length}</span></div>
          <div className={styles.stack}>{data.suppliers.map((x:any)=><details className={styles.details} key={x.id}><summary>{x.name} · {x.active?"Actif":"Inactif"}</summary><form action={saveSupplierV163} className={styles.form}><input type="hidden" name="id" value={x.id}/><label>Nom<input name="name" defaultValue={x.name} required/></label><label>Contact<input name="contact_name" defaultValue={x.contact_name??""}/></label><label>E-mail<input name="email" defaultValue={x.email??""}/></label><label>Téléphone<input name="phone" defaultValue={x.phone??""}/></label><label>Marques<input name="brands" defaultValue={(x.brands??[]).join(", ")}/></label><label>Délai moyen (jours)<input name="lead_time_days" type="number" min="0" defaultValue={x.lead_time_days}/></label><label>Remise fournisseur %<input name="default_discount_percent" type="number" step="0.01" min="0" defaultValue={x.default_discount_percent}/></label><label>Conditions<input name="payment_terms" defaultValue={x.payment_terms??""}/></label><label className={styles.wide}>Notes<textarea name="notes" defaultValue={x.notes??""}/></label><label><span>Actif</span><input name="active" type="checkbox" defaultChecked={x.active}/></label><div><button className={styles.button}>Enregistrer</button></div></form></details>)}</div>
        </section>
        <section className={styles.card}><p className={styles.eyebrow}>NOUVEAU FOURNISSEUR</p><form action={saveSupplierV163} className={styles.form}><label>Nom<input name="name" required/></label><label>Contact<input name="contact_name"/></label><label>E-mail<input name="email"/></label><label>Téléphone<input name="phone"/></label><label>Marques<input name="brands" placeholder="Ferrari, Porsche…"/></label><label>Délai moyen (jours)<input name="lead_time_days" type="number" min="0" defaultValue="0"/></label><label>Remise %<input name="default_discount_percent" type="number" step="0.01" min="0" defaultValue="0"/></label><label>Actif<input name="active" type="checkbox" defaultChecked/></label><button className={`${styles.button} ${styles.wide}`}>Créer le fournisseur</button></form></section>
      </div>
      <div className={styles.stack}>
        <section className={`${styles.card} ${styles.highlight}`}><p className={styles.eyebrow}>NOUVEL ARRIVAGE</p><h2>Commande fournisseur</h2><form action={createSupplierOrderV163} className={styles.form}><label>Fournisseur<select name="supplier_id" required defaultValue=""><option value="" disabled>Choisir</option>{data.suppliers.filter((x:any)=>x.active).map((x:any)=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Arrivée estimée<input type="datetime-local" name="expected_at"/></label><label>Transport fournisseur<input type="number" name="inbound_transport_cost" min="0" step="1" defaultValue="0"/></label><label>Autres coûts<input type="number" name="other_cost" min="0" step="1" defaultValue="0"/></label><label className={styles.wide}>Notes<textarea name="notes"/></label><button className={`${styles.button} ${styles.wide}`}>Créer la commande</button></form></section>
        <section className={styles.card}><div className={styles.row}><h2>Commandes</h2><span className={styles.pill}>{data.orders.length}</span></div><div className={styles.stack}>{data.orders.map((o:any)=><Link key={o.id} href={`/dashboard/fournisseurs?order=${o.id}`} className={styles.buttonAlt}><span>{o.order_number} · {status[o.status]??o.status}</span><span>{date(o.expected_at)}</span></Link>)}</div></section>
      </div>
    </div>
    {selected&&<section className={styles.card}><div className={styles.row}><div><p className={styles.eyebrow}>COMMANDE FOURNISSEUR</p><h2>{selected.order_number}</h2><p className={styles.muted}>Arrivée estimée : {date(selected.expected_at)}</p></div><form action={updateSupplierOrderV163} className={styles.row}><input type="hidden" name="id" value={selected.id}/><select name="status" defaultValue={selected.status}><option value="draft">Brouillon</option><option value="ordered">Commandée</option><option value="confirmed">Confirmée</option><option value="in_transit">En transport</option><option value="arrived">Arrivée</option><option value="received">Réceptionner + stock</option><option value="cancelled">Annulée</option></select><button className={styles.button}>Mettre à jour</button></form></div>
      <div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>Véhicule</th><th>Qté</th><th>Achat/unité</th><th>Préparation</th><th>Total achat</th></tr></thead><tbody>{selected.items.map((i:any)=>{const v:any=vehicleMap.get(Number(i.catalog_vehicle_id));return <tr key={i.id}><td>{v?`${v.brand} ${v.model}`:`VL #${i.catalog_vehicle_id}`}</td><td>{i.quantity}</td><td>{money(i.unit_purchase_cost)}</td><td>{money(i.preparation_cost_per_unit)}</td><td>{money(Number(i.unit_purchase_cost)*Number(i.quantity))}</td></tr>})}</tbody></table></div>
      {selected.status!=="received"&&selected.status!=="cancelled"&&<form action={addSupplierOrderItemV163} className={styles.form}><input type="hidden" name="supplier_order_id" value={selected.id}/><label>Véhicule<select name="catalog_vehicle_id" required defaultValue=""><option value="" disabled>Choisir un véhicule</option>{data.vehicles.map((v:any)=><option value={v.id} key={v.id}>{v.brand} {v.model}</option>)}</select></label><label>Quantité<input name="quantity" type="number" min="1" defaultValue="1"/></label><label>Prix d’achat unitaire<input name="unit_purchase_cost" type="number" min="0" step="1" required/></label><label>Préparation / unité<input name="preparation_cost_per_unit" type="number" min="0" step="1" defaultValue="0"/></label><button className={`${styles.button} ${styles.wide}`}>Ajouter à la commande</button></form>}
    </section>}
  </div></DashboardShell>;
}
