"use server";
import { randomUUID } from "crypto";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { getUserRoleKeys } from "@/lib/auth/access";
import { createClient } from "@/lib/supabase/server";
const MAX=8*1024*1024, TYPES=new Set(['application/pdf','image/jpeg','image/png']);
const txt=(v:FormDataEntryValue|null,max=5000)=>typeof v==='string'?v.trim().slice(0,max):'';
const num=(v:FormDataEntryValue|null)=>Number.parseInt(txt(v,40),10)||0;
async function user(){const s=await createClient();const {data}=await s.auth.getUser();if(!data.user)redirect('/');return{s,u:data.user};}
async function manager(){const c=await user();const roles=await getUserRoleKeys(c.u);if(!roles.includes('manager'))redirect('/accueil');return c;}
async function staff(){const c=await user();const roles=await getUserRoleKeys(c.u);if(!roles.some(r=>['manager','employee','commercial'].includes(r)))redirect('/accueil');return c;}
async function upload(bucket:string,file:File|null,uid:string){if(!file||!file.size)return{path:null,name:null,error:null};if(file.size>MAX)return{path:null,name:null,error:'file-size'};if(!TYPES.has(file.type))return{path:null,name:null,error:'file-type'};const s=await createClient();const safe=file.name.normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-zA-Z0-9._-]+/g,'-').slice(0,100)||'document';const path=`${uid}/${randomUUID()}/${safe}`;const {error}=await s.storage.from(bucket).upload(path,file,{contentType:file.type});return error?{path:null,name:null,error:'upload'}:{path,name:file.name,error:null};}
export async function createRecruitment(form:FormData){const {s,u}=await user();const f=form.get('attachment');const up=await upload('recruitment-files',f instanceof File?f:null,u.id);if(up.error)redirect(`/recrutement/candidature?error=${up.error}`);const {data,error}=await (s as any).rpc('nostra_create_recruitment_application',{p_desired_position:txt(form.get('desired_position'),180),p_phone:txt(form.get('phone'),60),p_availability:txt(form.get('availability'),1000),p_experience:txt(form.get('experience')),p_motivation:txt(form.get('motivation')),p_attachment_path:up.path,p_attachment_name:up.name});if(error)redirect('/recrutement/candidature?error=save');const n=typeof data?.application_number==='string'?data.application_number:'envoyée';revalidatePath('/dashboard/recrutement');redirect(`/recrutement/candidature?success=${encodeURIComponent(n)}`);}
export async function reviewRecruitment(form:FormData){const {s}=await manager();const {error}=await (s as any).rpc('nostra_review_recruitment_application',{p_id:num(form.get('id')),p_status:txt(form.get('status'),30),p_message:txt(form.get('message'),3000)||null,p_role:txt(form.get('role'),50)||null});if(error)redirect('/dashboard/recrutement?error=1');revalidatePath('/recrutement/candidature');redirect('/dashboard/recrutement?success=1');}
export async function withdrawRecruitment(form:FormData){const {s}=await user();const {error}=await (s as any).rpc('nostra_withdraw_recruitment_application',{p_id:num(form.get('id'))});if(error)redirect('/recrutement/candidature?error=withdraw');redirect('/recrutement/candidature?withdrawn=1');}
export async function createSav(form:FormData){const {s,u}=await user();const f=form.get('attachment');const up=await upload('motors-sav-files',f instanceof File?f:null,u.id);if(up.error)redirect(`/motors/sav?error=${up.error}`);const {data,error}=await (s as any).rpc('nostra_create_sav_ticket',{p_category:txt(form.get('category'),30),p_priority:txt(form.get('priority'),30),p_subject:txt(form.get('subject'),180),p_description:txt(form.get('description')),p_reference:txt(form.get('reference'),180)||null,p_attachment_path:up.path,p_attachment_name:up.name});if(error)redirect('/motors/sav?error=save');revalidatePath('/dashboard/sav');redirect(`/motors/sav/${Number(data?.id)||''}?created=1`);}
export async function addSavMessage(form:FormData){const {s,u}=await user();const id=num(form.get('id')),back=txt(form.get('return_to'),250)||`/motors/sav/${id}`;const f=form.get('attachment');const up=await upload('motors-sav-files',f instanceof File?f:null,u.id);if(up.error)redirect(`${back}?error=${up.error}`);const {error}=await (s as any).rpc('nostra_add_sav_message',{p_ticket_id:id,p_body:txt(form.get('body')),p_attachment_path:up.path,p_attachment_name:up.name});if(error)redirect(`${back}?error=message`);revalidatePath(`/motors/sav/${id}`);revalidatePath(`/dashboard/sav/${id}`);redirect(`${back}?sent=1`);}
export async function updateSav(form:FormData){const {s}=await staff();const id=num(form.get('id'));const {error}=await (s as any).rpc('nostra_update_sav_ticket',{p_id:id,p_status:txt(form.get('status'),30),p_priority:txt(form.get('priority'),30),p_assigned_to:txt(form.get('assigned_to'),80)||null,p_note:txt(form.get('note'),3000)||null});if(error)redirect(`/dashboard/sav/${id}?error=1`);redirect(`/dashboard/sav/${id}?success=1`);}
export async function createBackup(form:FormData){const {s}=await manager();const {error}=await (s as any).rpc('nostra_create_backup_snapshot',{p_label:txt(form.get('label'),180)||null});if(error)redirect('/dashboard/securite?error=backup');revalidatePath('/dashboard/securite');redirect('/dashboard/securite?success=backup');}
export async function deleteBackup(form:FormData){const {s}=await manager();const {error}=await (s as any).rpc('nostra_delete_backup_snapshot',{p_id:num(form.get('id'))});if(error)redirect('/dashboard/securite?error=delete');revalidatePath('/dashboard/securite');redirect('/dashboard/securite?success=delete');}
