"use server";

import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";

import { getUserRoleKeys } from "@/lib/auth/access";
import { creditCitizenGameMoney } from "@/lib/game-bank/data";
import { createClient } from "@/lib/supabase/server";

const text=(v:FormDataEntryValue|null,max=4000)=>typeof v==="string"?v.trim().slice(0,max):"";
const num=(v:FormDataEntryValue|null,fallback=0)=>{const x=Number(text(v,80).replace(/\s/g,"").replace(",","."));return Number.isFinite(x)?x:fallback;};
const int=(v:FormDataEntryValue|null,fallback=0)=>{const x=Number.parseInt(text(v,40),10);return Number.isFinite(x)?x:fallback;};
const nullableDate=(v:FormDataEntryValue|null)=>{const raw=text(v,50);return raw?new Date(raw).toISOString():null;};

async function manager(){const supabase=await createClient();const {data}=await supabase.auth.getUser();if(!data.user)redirect("/");const roles=await getUserRoleKeys(data.user);if(!roles.includes("manager"))redirect("/accueil");return{supabase,user:data.user};}
async function motorsStaff(){const supabase=await createClient();const {data}=await supabase.auth.getUser();if(!data.user)redirect("/");const roles=await getUserRoleKeys(data.user);if(!roles.some(r=>["manager","employee","commercial"].includes(r)))redirect("/accueil");return{supabase,user:data.user};}
async function currentUser(){const supabase=await createClient();const {data}=await supabase.auth.getUser();if(!data.user)redirect("/");return{supabase,user:data.user};}
async function audit(supabase:any,userId:string,action:string,entity:string,id:string|null,summary:string,newData?:unknown){await supabase.from("nostra_audit_log_v155").insert({actor_user_id:userId,action,entity_type:entity,entity_id:id,summary,new_data:newData??null});}

export async function createRentalRequestV155(formData:FormData){const {supabase}=await currentUser();const vehicleId=int(formData.get("vehicle_id"));const start=text(formData.get("start_date"),20);const end=text(formData.get("end_date"),20);if(!vehicleId||!start||!end)redirect(`/motors/location/${vehicleId}?error=dates`);const {data,error}=await (supabase as any).rpc("nostra_create_rental_v155",{p_vehicle_id:vehicleId,p_start_date:start,p_end_date:end});if(error)redirect(`/motors/location/${vehicleId}?error=${encodeURIComponent(error.message)}`);revalidatePath("/profil/locations");redirect(`/profil/locations?created=${encodeURIComponent(String(data))}`);}

export async function cancelRentalV155(formData:FormData){const {supabase}=await currentUser();const id=text(formData.get("id"),80);if(!id)redirect("/profil/locations?error=invalid");const {error}=await (supabase as any).rpc("nostra_cancel_rental_v155",{p_booking_id:id});if(error)redirect(`/profil/locations?error=${encodeURIComponent(error.message)}`);revalidatePath("/profil/locations");revalidatePath("/dashboard/location-motors");redirect("/profil/locations?cancelled=1");}

export async function saveRentalSettingV155(formData:FormData){const {supabase,user}=await motorsStaff();const vehicleId=int(formData.get("vehicle_id"));if(!vehicleId)redirect("/dashboard/location-motors?error=vehicle");const payload={vehicle_id:vehicleId,daily_rate:Math.max(0,num(formData.get("daily_rate"))),deposit_amount:Math.max(0,num(formData.get("deposit_amount"))),min_days:Math.max(1,int(formData.get("min_days"),1)),max_days:Math.max(1,int(formData.get("max_days"),30)),mileage_included_per_day:Math.max(0,int(formData.get("mileage_included_per_day"),200)),extra_km_price:Math.max(0,num(formData.get("extra_km_price"))),active:formData.get("active")==="on",updated_at:new Date().toISOString(),updated_by:user.id};const {error}=await (supabase as any).from("motors_rental_settings_v155").upsert(payload,{onConflict:"vehicle_id"});if(error)redirect("/dashboard/location-motors?error=save");revalidatePath("/motors/catalogue/location");revalidatePath("/dashboard/location-motors");redirect("/dashboard/location-motors?saved=1");}

export async function updateRentalBookingV155(formData:FormData){const {supabase,user}=await motorsStaff();const id=text(formData.get("id"),80);const status=text(formData.get("status"),30);if(!id||!["pending","confirmed","ready","active","returned","cancelled","rejected"].includes(status))redirect("/dashboard/location-motors?error=booking");const payload:any={status,staff_notes:text(formData.get("staff_notes"),2000)||null,damage_notes:text(formData.get("damage_notes"),2000)||null,condition_out:text(formData.get("condition_out"),1000)||null,condition_in:text(formData.get("condition_in"),1000)||null,updated_at:new Date().toISOString(),updated_by:user.id};const mo=int(formData.get("mileage_out"),-1);const mi=int(formData.get("mileage_in"),-1);if(mo>=0)payload.mileage_out=mo;if(mi>=0)payload.mileage_in=mi;if(status==="active")payload.picked_up_at=new Date().toISOString();if(status==="returned")payload.returned_at=new Date().toISOString();const {error}=await (supabase as any).from("motors_rental_bookings_v155").update(payload).eq("id",id);if(error)redirect("/dashboard/location-motors?error=booking");revalidatePath("/dashboard/location-motors");revalidatePath("/profil/locations");redirect("/dashboard/location-motors?booking_saved=1");}

export async function saveStockStateV155(formData:FormData){const {supabase,user}=await motorsStaff();const vehicleId=int(formData.get("vehicle_id"));if(!vehicleId)redirect("/dashboard/stock-reel?error=vehicle");const status=text(formData.get("operational_status"),30);if(!["available","reserved","rented","workshop","unavailable"].includes(status))redirect("/dashboard/stock-reel?error=status");await (supabase as any).from("motors_vehicle_stock_v155").upsert({vehicle_id:vehicleId,operational_status:status,physical_location:text(formData.get("physical_location"),160)||"Concession Nostra Motors",minimum_stock:Math.max(0,int(formData.get("minimum_stock"),1)),notes:text(formData.get("notes"),1200)||null,updated_at:new Date().toISOString(),updated_by:user.id},{onConflict:"vehicle_id"});revalidatePath("/dashboard/stock-reel");redirect("/dashboard/stock-reel?saved=1");}

export async function updateLoyaltyTierV155(formData:FormData){const {supabase,user}=await manager();const code=text(formData.get("code"),80);if(!code)redirect("/dashboard/fidelite?error=tier");const benefits=text(formData.get("benefits"),4000).split("\n").map(x=>x.trim()).filter(Boolean).slice(0,20);const payload:any={label:text(formData.get("label"),120),catalog_discount_percent:Math.max(0,num(formData.get("catalog_discount_percent"))),plate_discount_percent:Math.max(0,num(formData.get("plate_discount_percent"))),min_points:Math.max(0,int(formData.get("min_points"))),public_description:text(formData.get("public_description"),1000)||null,benefits,active:formData.get("active")==="on"};const {error}=await (supabase as any).from("loyalty_tiers").update(payload).eq("code",code);if(error)redirect(`/dashboard/fidelite?error=${encodeURIComponent(error.message)}`);await audit(supabase,user.id,"update","loyalty_tiers",code,`Avantages fidélité ${code} modifiés`,payload);revalidatePath("/dashboard/fidelite");revalidatePath("/profil/fidelite");revalidatePath("/motors/fidelite");redirect("/dashboard/fidelite?tier_saved=1");}

export async function applyReferralV155(formData:FormData){const {supabase}=await currentUser();const code=text(formData.get("code"),40);const {error}=await (supabase as any).rpc("nostra_apply_referral_v155",{p_code:code});if(error)redirect(`/profil/parrainage?error=${encodeURIComponent(error.message)}`);revalidatePath("/profil/parrainage");revalidatePath("/profil/wallet");redirect("/profil/parrainage?success=1");}

export async function savePrivateSaleV155(formData:FormData){const {supabase,user}=await manager();const id=text(formData.get("id"),80);const payload={vehicle_id:int(formData.get("vehicle_id")),title:text(formData.get("title"),180),description:text(formData.get("description"),2500),min_loyalty_points:Math.max(0,int(formData.get("min_loyalty_points"))),starts_at:nullableDate(formData.get("starts_at")),ends_at:nullableDate(formData.get("ends_at")),enabled:formData.get("enabled")==="on",stock_limit:int(formData.get("stock_limit"))>0?int(formData.get("stock_limit")):null,updated_at:new Date().toISOString()};if(!payload.vehicle_id||!payload.title)redirect("/dashboard/ventes-privees?error=invalid");let error;if(id){({error}=await (supabase as any).from("nostra_private_sales_v155").update(payload).eq("id",id));}else{({error}=await (supabase as any).from("nostra_private_sales_v155").insert({...payload,created_by:user.id}));}if(error)redirect("/dashboard/ventes-privees?error=save");revalidatePath("/ventes-privees");revalidatePath("/dashboard/ventes-privees");redirect("/dashboard/ventes-privees?saved=1");}

export async function joinVehicleWaitlistV155(formData:FormData){const {supabase,user}=await currentUser();const vehicleId=int(formData.get("vehicle_id"));const reason=text(formData.get("reason"),30)||"stock";if(!vehicleId||!["stock","rental","private_sale"].includes(reason))redirect("/profil/liste-attente?error=invalid");await (supabase as any).from("nostra_vehicle_waitlist_v155").upsert({user_id:user.id,vehicle_id:vehicleId,reason},{onConflict:"user_id,vehicle_id,reason"});revalidatePath("/profil/liste-attente");redirect("/profil/liste-attente?added=1");}
export async function leaveVehicleWaitlistV155(formData:FormData){const {supabase,user}=await currentUser();const id=int(formData.get("id"));if(id)await (supabase as any).from("nostra_vehicle_waitlist_v155").delete().eq("id",id).eq("user_id",user.id);revalidatePath("/profil/liste-attente");redirect("/profil/liste-attente?removed=1");}

export async function createRefundV155(formData:FormData){const {supabase,user}=await manager();const userId=text(formData.get("user_id"),80);const amount=Math.max(0,num(formData.get("amount")));const reason=text(formData.get("reason"),2000);if(!userId||amount<=0||!reason)redirect("/dashboard/remboursements?error=invalid");const {error}=await (supabase as any).from("nostra_refunds_v155").insert({user_id:userId,source_type:text(formData.get("source_type"),40)||"manual",source_id:text(formData.get("source_id"),120)||null,refund_kind:text(formData.get("refund_kind"),20)==="total"?"total":"partial",amount,reason,status:"pending",created_by:user.id});if(error)redirect("/dashboard/remboursements?error=save");revalidatePath("/dashboard/remboursements");redirect("/dashboard/remboursements?created=1");}

export async function processRefundV155(formData:FormData){const {supabase,user}=await manager();const id=text(formData.get("id"),80);const decision=text(formData.get("decision"),20);if(!id||!["approve","pay","reject"].includes(decision))redirect("/dashboard/remboursements?error=invalid");const {data:refund}=await (supabase as any).from("nostra_refunds_v155").select("*").eq("id",id).maybeSingle();if(!refund)redirect("/dashboard/remboursements?error=missing");if(decision==="reject"){if(refund.status!=="pending")redirect("/dashboard/remboursements?error=status");await (supabase as any).from("nostra_refunds_v155").update({status:"rejected",approved_by:user.id,approved_at:new Date().toISOString()}).eq("id",id);revalidatePath("/dashboard/remboursements");redirect("/dashboard/remboursements?rejected=1");}if(decision==="approve"){if(refund.status!=="pending")redirect("/dashboard/remboursements?error=status");await (supabase as any).from("nostra_refunds_v155").update({status:"approved",approved_by:user.id,approved_at:new Date().toISOString()}).eq("id",id);revalidatePath("/dashboard/remboursements");redirect("/dashboard/remboursements?approved=1");}if(refund.status!=="approved")redirect("/dashboard/remboursements?error=status");if(!refund.user_id)redirect("/dashboard/remboursements?error=user");const {data:profile}=await (supabase as any).from("member_profiles").select("steam_id").eq("user_id",refund.user_id).maybeSingle();const steamId=typeof profile?.steam_id==="string"?profile.steam_id:null;if(!steamId)redirect("/dashboard/remboursements?error=steam");const result=await creditCitizenGameMoney(steamId,Math.trunc(Number(refund.amount)));if(result.status!=="credited")redirect(`/dashboard/remboursements?error=${result.status}`);await (supabase as any).from("nostra_refunds_v155").update({status:"paid",paid_at:new Date().toISOString(),payment_reference:`GAME-${Date.now()}`}).eq("id",id);await (supabase as any).from("nostra_wallet_ledger_v155").insert({user_id:refund.user_id,entry_type:"refund",label:`Remboursement Nostra · ${refund.reason}`,amount_rp:Number(refund.amount),source_type:"refund",source_id:id});await (supabase as any).from("user_notifications").insert({user_id:refund.user_id,notification_type:"refund",title:"Remboursement effectué",message:`Un remboursement de ${Number(refund.amount).toLocaleString("fr-FR")} $RP a été crédité.`,target_url:"/profil/wallet",source_type:"refund",source_id:id,priority:"important",category:"general"});revalidatePath("/dashboard/remboursements");redirect("/dashboard/remboursements?paid=1");}

async function trashEntity(supabase:any,userId:string,table:string,id:string,title:string){const {data,error}=await supabase.from(table).select("*").eq("id",id).maybeSingle();if(error||!data)throw new Error("missing");await supabase.from("nostra_trash_v155").insert({entity_type:table,entity_id:id,title,payload:data,deleted_by:userId});await supabase.from(table).delete().eq("id",id);}
export async function trashContentV155(formData:FormData){const {supabase,user}=await manager();const table=text(formData.get("entity_type"),80);const id=text(formData.get("id"),80);const title=text(formData.get("title"),200)||"Élément supprimé";if(!["nostra_news_v155","nostra_banners_v155","nostra_announcements_v155","nostra_private_sales_v155"].includes(table)||!id)redirect("/dashboard/corbeille?error=invalid");try{await trashEntity(supabase,user.id,table,id,title);}catch{redirect("/dashboard/corbeille?error=delete");}revalidatePath("/dashboard/corbeille");revalidatePath("/actualites");redirect("/dashboard/corbeille?trashed=1");}
export async function restoreTrashV155(formData:FormData){const {supabase,user}=await manager();const trashId=text(formData.get("id"),80);const {data:item}=await (supabase as any).from("nostra_trash_v155").select("*").eq("id",trashId).is("restored_at",null).maybeSingle();if(!item)redirect("/dashboard/corbeille?error=missing");const allowed=["nostra_news_v155","nostra_banners_v155","nostra_announcements_v155","nostra_private_sales_v155"];if(!allowed.includes(item.entity_type))redirect("/dashboard/corbeille?error=unsupported");const {error}=await (supabase as any).from(item.entity_type).insert(item.payload);if(error)redirect("/dashboard/corbeille?error=restore");await (supabase as any).from("nostra_trash_v155").update({restored_at:new Date().toISOString()}).eq("id",trashId);await audit(supabase,user.id,"restore",item.entity_type,item.entity_id,`Restauration depuis la corbeille : ${item.title}`);revalidatePath("/dashboard/corbeille");redirect("/dashboard/corbeille?restored=1");}

export async function saveNewsV155(formData:FormData){const {supabase,user}=await manager();const id=text(formData.get("id"),80);const payload={pole:text(formData.get("pole"),30)||"group",title:text(formData.get("title"),200),excerpt:text(formData.get("excerpt"),600),content:text(formData.get("content"),6000),image_url:text(formData.get("image_url"),1000)||null,published:formData.get("published")==="on",featured:formData.get("featured")==="on",starts_at:nullableDate(formData.get("starts_at")),ends_at:nullableDate(formData.get("ends_at")),updated_at:new Date().toISOString()};if(!payload.title)redirect("/dashboard/communication?error=news");let error;if(id){({error}=await (supabase as any).from("nostra_news_v155").update(payload).eq("id",id));}else{({error}=await (supabase as any).from("nostra_news_v155").insert({...payload,created_by:user.id}));}if(error)redirect("/dashboard/communication?error=news-save");revalidatePath("/actualites");revalidatePath("/aujourdhui");redirect("/dashboard/communication?saved=news");}
export async function saveBannerV155(formData:FormData){const {supabase,user}=await manager();const id=text(formData.get("id"),80);const payload={pole:text(formData.get("pole"),30)||"group",title:text(formData.get("title"),200),message:text(formData.get("message"),1500),cta_label:text(formData.get("cta_label"),80)||null,cta_url:text(formData.get("cta_url"),500)||null,starts_at:nullableDate(formData.get("starts_at")),ends_at:nullableDate(formData.get("ends_at")),active:formData.get("active")==="on",priority:int(formData.get("priority")),updated_at:new Date().toISOString()};if(!payload.title)redirect("/dashboard/communication?error=banner");let error;if(id){({error}=await (supabase as any).from("nostra_banners_v155").update(payload).eq("id",id));}else{({error}=await (supabase as any).from("nostra_banners_v155").insert({...payload,created_by:user.id}));}if(error)redirect("/dashboard/communication?error=banner-save");revalidatePath("/accueil");redirect("/dashboard/communication?saved=banner");}
export async function saveAnnouncementV155(formData:FormData){const {supabase,user}=await manager();const id=text(formData.get("id"),80);const payload={title:text(formData.get("title"),200),message:text(formData.get("message"),2000),severity:text(formData.get("severity"),20)||"important",active:formData.get("active")==="on",dismissible:formData.get("dismissible")==="on",starts_at:nullableDate(formData.get("starts_at")),ends_at:nullableDate(formData.get("ends_at")),updated_at:new Date().toISOString()};if(!payload.title||!payload.message)redirect("/dashboard/communication?error=announcement");let error;if(id){({error}=await (supabase as any).from("nostra_announcements_v155").update(payload).eq("id",id));}else{({error}=await (supabase as any).from("nostra_announcements_v155").insert({...payload,created_by:user.id}));}if(error)redirect("/dashboard/communication?error=announcement-save");revalidatePath("/accueil");redirect("/dashboard/communication?saved=announcement");}

export async function purgeTrashV155(formData:FormData){const {supabase,user}=await manager();const id=text(formData.get("id"),80);if(!id)redirect("/dashboard/corbeille?error=invalid");const {data:item}=await (supabase as any).from("nostra_trash_v155").select("*").eq("id",id).maybeSingle();if(!item)redirect("/dashboard/corbeille?error=missing");await (supabase as any).from("nostra_trash_v155").delete().eq("id",id);await audit(supabase,user.id,"purge","nostra_trash_v155",id,`Suppression définitive : ${item.title}`);revalidatePath("/dashboard/corbeille");redirect("/dashboard/corbeille?purged=1");}
