"use server";

import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { getUserRoleKeys } from "@/lib/auth/access";
import { createClient } from "@/lib/supabase/server";
import { chargeNostraMotors, refundNostraMotors } from "@/lib/nostra-motors/game-payment";

const text=(v:FormDataEntryValue|null,max=5000)=>typeof v==="string"?v.trim().slice(0,max):"";
const int=(v:FormDataEntryValue|null)=>{const x=Number.parseInt(text(v,40),10);return Number.isFinite(x)?x:0};
const num=(v:FormDataEntryValue|null)=>{const x=Number(String(v??"").replace(",","."));return Number.isFinite(x)?Math.max(0,x):0};
async function current(){const s=await createClient();const {data}=await s.auth.getUser();if(!data.user)redirect("/");return{s,user:data.user};}
async function staff(required?:string){const c=await current();const roles=await getUserRoleKeys(c.user);if(roles.includes("manager"))return c;if(!roles.some(r=>["employee","commercial"].includes(r)))redirect("/accueil");if(required){const check=await (c.s as any).rpc("nostra_v164_has_permission",{p_permission:required});if(!check.error){if(check.data===true)return c;redirect("/dashboard");}}return c;}
function revalidateV163(){["/dashboard/fournisseurs","/dashboard/marges","/dashboard/garanties","/dashboard/crm-motors","/profil/garanties","/profil/garage","/dashboard/stocks","/dashboard/stock-reel"].forEach(p=>revalidatePath(p));revalidatePath("/profil/garage","layout");}
function code(prefix:string){return `${prefix}-${new Date().toISOString().slice(2,10).replaceAll("-","")}-${crypto.randomUUID().replaceAll("-","").slice(0,6).toUpperCase()}`;}

export async function saveSupplierV163(form:FormData){const {s,user}=await staff("suppliers_manage");const id=int(form.get("id"));const brands=text(form.get("brands"),1000).split(",").map(x=>x.trim()).filter(Boolean);const payload={name:text(form.get("name"),180),contact_name:text(form.get("contact_name"),180)||null,email:text(form.get("email"),220)||null,phone:text(form.get("phone"),80)||null,brands,lead_time_days:int(form.get("lead_time_days")),default_discount_percent:num(form.get("default_discount_percent")),payment_terms:text(form.get("payment_terms"),1000)||null,notes:text(form.get("notes"),3000)||null,active:form.get("active")==="on",updated_at:new Date().toISOString()};if(!payload.name)redirect("/dashboard/fournisseurs?error=invalid");const q=id>0?(s as any).from("motors_suppliers_v163").update(payload).eq("id",id):(s as any).from("motors_suppliers_v163").insert({...payload,created_by:user.id});const {error}=await q;if(error)redirect("/dashboard/fournisseurs?error=save");revalidateV163();redirect("/dashboard/fournisseurs?saved=1");}

export async function createSupplierOrderV163(form:FormData){const {s,user}=await staff("suppliers_manage");const supplierId=int(form.get("supplier_id"));if(!supplierId)redirect("/dashboard/fournisseurs?error=invalid");const expected=text(form.get("expected_at"),80);const {data,error}=await (s as any).from("motors_supplier_orders_v163").insert({order_number:code("FOU"),supplier_id:supplierId,status:"draft",expected_at:expected?new Date(expected).toISOString():null,inbound_transport_cost:num(form.get("inbound_transport_cost")),other_cost:num(form.get("other_cost")),notes:text(form.get("notes"),3000)||null,created_by:user.id}).select("id").single();if(error||!data)redirect("/dashboard/fournisseurs?error=order");revalidateV163();redirect(`/dashboard/fournisseurs?order=${data.id}&created=1`);}

export async function addSupplierOrderItemV163(form:FormData){const {s}=await staff("suppliers_manage");const orderId=int(form.get("supplier_order_id"));const vehicleId=int(form.get("catalog_vehicle_id"));if(!orderId||!vehicleId)redirect("/dashboard/fournisseurs?error=item");const {error}=await (s as any).from("motors_supplier_order_items_v163").insert({supplier_order_id:orderId,catalog_vehicle_id:vehicleId,quantity:Math.max(1,int(form.get("quantity"))),unit_purchase_cost:num(form.get("unit_purchase_cost")),preparation_cost_per_unit:num(form.get("preparation_cost_per_unit"))});if(error)redirect(`/dashboard/fournisseurs?order=${orderId}&error=item`);revalidateV163();redirect(`/dashboard/fournisseurs?order=${orderId}&item=1`);}

export async function updateSupplierOrderV163(form:FormData){const {s}=await staff("suppliers_manage");const id=int(form.get("id"));const status=text(form.get("status"),40);if(!id)redirect("/dashboard/fournisseurs?error=invalid");if(status==="received"){const {error}=await (s as any).rpc("nostra_receive_supplier_order_v163",{p_order_id:id});if(error)redirect(`/dashboard/fournisseurs?order=${id}&error=receive`);}else{const payload:any={status,updated_at:new Date().toISOString()};if(status==="ordered")payload.ordered_at=new Date().toISOString();const {error}=await (s as any).from("motors_supplier_orders_v163").update(payload).eq("id",id);if(error)redirect(`/dashboard/fournisseurs?order=${id}&error=status`);}revalidateV163();redirect(`/dashboard/fournisseurs?order=${id}&updated=1`);}

export async function saveVehicleCostV163(form:FormData){const {s,user}=await staff("suppliers_manage");const vehicleId=int(form.get("catalog_vehicle_id"));if(!vehicleId)redirect("/dashboard/marges?error=invalid");const payload={catalog_vehicle_id:vehicleId,supplier_id:int(form.get("supplier_id"))||null,purchase_cost:num(form.get("purchase_cost")),inbound_transport_per_unit:num(form.get("inbound_transport_per_unit")),preparation_cost:num(form.get("preparation_cost")),other_cost:num(form.get("other_cost")),updated_at:new Date().toISOString(),updated_by:user.id};const {error}=await (s as any).from("motors_vehicle_costs_v163").upsert(payload,{onConflict:"catalog_vehicle_id"});if(error)redirect("/dashboard/marges?error=save");revalidateV163();redirect("/dashboard/marges?saved=1");}

export async function saveWarrantyPlanV163(form:FormData){const {s,user}=await staff("warranty_manage");const id=int(form.get("id"));const payload={name:text(form.get("name"),140),description:text(form.get("description"),1500)||null,duration_days:Math.max(1,int(form.get("duration_days"))),price:0,rate_percent:Math.min(100,Math.max(0.01,num(form.get("rate_percent")))),deductible:num(form.get("deductible")),engine:form.get("engine")==="on",gearbox:form.get("gearbox")==="on",electronics:form.get("electronics")==="on",suspension:form.get("suspension")==="on",bodywork:form.get("bodywork")==="on",tyres:form.get("tyres")==="on",active:form.get("active")==="on",updated_at:new Date().toISOString()};if(!payload.name)redirect("/dashboard/garanties?error=invalid");const q=id>0?(s as any).from("motors_warranty_plans_v163").update(payload).eq("id",id).select("id").maybeSingle():(s as any).from("motors_warranty_plans_v163").insert({...payload,created_by:user.id}).select("id").single();const result=await q;if(result.error)redirect("/dashboard/garanties?error=plan");try{await (s as any).from("motors_employee_audit_v164").insert({actor_user_id:user.id,action_key:id>0?"warranty_plan_updated":"warranty_plan_created",entity_type:"warranty_plan",entity_id:String(result.data?.id??id),title:id>0?"Formule Nostra Care modifiée":"Formule Nostra Care créée",details:{name:payload.name,duration_days:payload.duration_days,rate_percent:payload.rate_percent,active:payload.active}});}catch{}revalidateV163();redirect("/dashboard/garanties?saved=1");}

export async function deleteWarrantyPlanV163(form:FormData){const {s,user}=await staff("warranty_manage");const id=int(form.get("id"));if(!id)redirect("/dashboard/garanties?error=plan");const before=await (s as any).from("motors_warranty_plans_v163").select("name,duration_days,rate_percent").eq("id",id).maybeSingle();const {error}=await (s as any).from("motors_warranty_plans_v163").delete().eq("id",id);if(error)redirect("/dashboard/garanties?error=plan_delete");try{await (s as any).from("motors_employee_audit_v164").insert({actor_user_id:user.id,action_key:"warranty_plan_deleted",entity_type:"warranty_plan",entity_id:String(id),title:"Formule Nostra Care supprimée",details:before.data??{}});}catch{}revalidateV163();redirect("/dashboard/garanties?deleted=1");}

export async function subscribeWarrantyV163(form:FormData){const {s}=await current();const vehicleId=int(form.get("customer_vehicle_id"));const planId=int(form.get("plan_id"));const {data,error}=await (s as any).rpc("nostra_subscribe_warranty_v163",{p_customer_vehicle_id:vehicleId,p_plan_id:planId,p_start_at:new Date().toISOString()});if(error)redirect(`/profil/garanties?vehicle=${vehicleId}&error=${encodeURIComponent(String(error.message||"save"))}`);revalidateV163();revalidatePath("/profil");redirect(`/profil?warranty_added=${encodeURIComponent(String(data?.contract_number||"1"))}`);}

export async function removeWarrantyFromCartV1631(form:FormData){const {s}=await current();const id=int(form.get("id"));if(!id)redirect("/profil?warranty_error=invalid");const {error}=await (s as any).rpc("nostra_cancel_pending_warranty_v1631",{p_contract_id:id});if(error)redirect(`/profil?warranty_error=${encodeURIComponent(String(error.message||"remove"))}`);revalidateV163();revalidatePath("/profil");redirect("/profil?warranty_removed=1");}

export async function checkoutWarrantyCartV1631(form?:FormData){const {s,user}=await current();const rows=await (s as any).from("motors_warranty_contracts_v163").select("id,amount").eq("user_id",user.id).eq("status","pending_payment");const amount=Math.max(0,Math.round((rows.data??[]).reduce((sum:number,row:any)=>sum+Math.max(0,Number(row.amount)||0),0)));if(amount<=0)redirect("/profil?warranty_error=empty_warranty_cart");const token=text(form?.get("checkout_token")??null,120)||crypto.randomUUID();const payment=await chargeNostraMotors({supabase:s as any,user,amount,idempotencyKey:`motors-warranty:${user.id}:${token}`,description:"Garantie Nostra Care"});if(!payment.ok){const reason=payment.reason==="funds"?"payment-funds":payment.reason==="steam"?"payment-steam":payment.reason==="duplicate"?"payment-processing":"payment-bank";redirect(`/profil?warranty_error=${encodeURIComponent(reason)}`);}const {data,error}=await (s as any).rpc("nostra_checkout_warranty_cart_v1631");if(error){await refundNostraMotors({payerPid:payment.payerPid,receiverPid:payment.receiverPid,amount:payment.amount,paymentId:payment.paymentId,reason:`warranty:${String(error.message||"checkout")}`});redirect(`/profil?warranty_error=${encodeURIComponent(String(error.message||"checkout"))}`);}const count=Math.max(1,Number(data?.count)||1);revalidateV163();revalidatePath("/profil");redirect(`/profil?warranty_paid=${count}`);}

export async function updateWarrantyStatusV163(form:FormData){const {s,user}=await staff("warranty_manage");const id=int(form.get("id"));const status=text(form.get("status"),30);const endRaw=text(form.get("ends_at"),40);if(!id||!["pending_payment","active","expired","cancelled"].includes(status))redirect("/dashboard/garanties?error=contract");const before=await (s as any).from("motors_warranty_contracts_v163").select("status,duration_days,starts_at,ends_at,contract_number,customer_vehicle_id").eq("id",id).maybeSingle();if(!before.data)redirect("/dashboard/garanties?error=contract");const payload:any={status,updated_at:new Date().toISOString()};if(endRaw){const parsed=new Date(`${endRaw}T23:59:59`);if(Number.isNaN(parsed.getTime()))redirect("/dashboard/garanties?error=date");payload.ends_at=parsed.toISOString();}if(status==="active"&&before.data.status!=="active"){const starts=new Date();payload.starts_at=starts.toISOString();payload.paid_at=starts.toISOString();if(!payload.ends_at)payload.ends_at=new Date(starts.getTime()+Math.max(1,Number(before.data.duration_days)||1)*86400000).toISOString();}const {error}=await (s as any).from("motors_warranty_contracts_v163").update(payload).eq("id",id);if(error)redirect("/dashboard/garanties?error=contract");try{await (s as any).from("motors_employee_audit_v164").insert({actor_user_id:user.id,action_key:"warranty_contract_updated",entity_type:"warranty_contract",entity_id:String(id),title:"Contrat Nostra Care modifié",details:{contract_number:before.data.contract_number,customer_vehicle_id:before.data.customer_vehicle_id,old_status:before.data.status,new_status:status,old_ends_at:before.data.ends_at,new_ends_at:payload.ends_at??before.data.ends_at}});}catch{}revalidateV163();redirect("/dashboard/garanties?contract_saved=1");}
