import { saveVehicleCostV163 } from "@/app/actions/v163";
import { DashboardShell } from "@/components/dashboard/dashboard-shell";
import styles from "@/components/v163/v163.module.css";
import { getMarginsV163, getSuppliersV163 } from "@/lib/v163/data";

export const dynamic="force-dynamic";
const money=(v:number)=>Number(v||0).toLocaleString("fr-FR",{style:"currency",currency:"EUR",maximumFractionDigits:0});
export default async function MarginsPage({searchParams}:{searchParams:Promise<Record<string,string|undefined>>}){
 const p=await searchParams; const [data,suppliers]=await Promise.all([getMarginsV163(),getSuppliersV163()]); const costMap=new Map(data.costs.map((c:any)=>[Number(c.catalog_vehicle_id),c]));
 return <DashboardShell allowedRoles={["manager","employee","commercial"]}><div className={styles.page}>
  <section className={styles.hero}><p className={styles.eyebrow}>NOSTRA MOTORS · RENTABILITÉ</p><h1>Marge réelle par véhicule</h1><p className={styles.muted}>Le coût réel additionne achat fournisseur, transport entrant, préparation et autres frais. La marge est calculée sur le prix réellement enregistré dans chaque commande.</p></section>
  {!data.configured&&<div className={styles.error}>Exécute le SQL V163 pour activer les coûts réels.</div>}{p.saved&&<div className={styles.success}>Coût véhicule enregistré.</div>}
  <section className={styles.kpis}><div className={styles.kpi}><span>CA véhicules analysé</span><strong>{money(data.totalRevenue)}</strong></div><div className={styles.kpi}><span>Coûts réels</span><strong>{money(data.totalCost)}</strong></div><div className={styles.kpi}><span>Marge brute</span><strong className={data.totalMargin>=0?styles.good:styles.bad}>{money(data.totalMargin)}</strong></div><div className={styles.kpi}><span>Taux de marge</span><strong>{data.marginPercent.toFixed(1)} %</strong></div></section>
  <section className={styles.card}><p className={styles.eyebrow}>COÛT DE REVIENT</p><h2>Configurer un véhicule</h2><form action={saveVehicleCostV163} className={styles.form}><label>Véhicule<select name="catalog_vehicle_id" required defaultValue=""><option value="" disabled>Choisir</option>{data.vehicles.map((v:any)=><option key={v.id} value={v.id}>{v.brand} {v.model} · vente {money(Number(v.price))}</option>)}</select></label><label>Fournisseur<select name="supplier_id" defaultValue=""><option value="">Non renseigné</option>{suppliers.suppliers.map((s:any)=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Prix d’achat<input name="purchase_cost" type="number" min="0" step="1" required/></label><label>Transport entrant / VL<input name="inbound_transport_per_unit" type="number" min="0" step="1" defaultValue="0"/></label><label>Préparation<input name="preparation_cost" type="number" min="0" step="1" defaultValue="0"/></label><label>Autres coûts<input name="other_cost" type="number" min="0" step="1" defaultValue="0"/></label><button className={`${styles.button} ${styles.wide}`}>Enregistrer le coût réel</button></form></section>
  <section className={styles.card}><div className={styles.row}><div><p className={styles.eyebrow}>RÉFÉRENTIEL</p><h2>Coûts configurés</h2></div><span className={styles.pill}>{data.costs.length}</span></div><div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>Véhicule</th><th>Achat</th><th>Transport</th><th>Prépa</th><th>Autres</th><th>Coût total</th></tr></thead><tbody>{data.vehicles.filter((v:any)=>costMap.has(Number(v.id))).map((v:any)=>{const c:any=costMap.get(Number(v.id));const total=Number(c.purchase_cost)+Number(c.inbound_transport_per_unit)+Number(c.preparation_cost)+Number(c.other_cost);return <tr key={v.id}><td><strong>{v.brand} {v.model}</strong><div className={styles.mini}>Vente catalogue {money(Number(v.price))}</div></td><td>{money(Number(c.purchase_cost))}</td><td>{money(Number(c.inbound_transport_per_unit))}</td><td>{money(Number(c.preparation_cost))}</td><td>{money(Number(c.other_cost))}</td><td><strong>{money(total)}</strong></td></tr>})}</tbody></table></div></section>
  <section className={styles.card}><div className={styles.row}><div><p className={styles.eyebrow}>VENTES</p><h2>Marge réellement réalisée</h2></div><span className={styles.pill}>{data.lines.length} ligne(s)</span></div><div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>Commande</th><th>Véhicule</th><th>Vente</th><th>Coût</th><th>Marge</th><th>%</th></tr></thead><tbody>{data.lines.slice(0,500).map((x:any,index:number)=><tr key={`${x.orderId}-${x.vehicleId}-${index}`}><td><strong>{x.orderNumber}</strong><div className={styles.mini}>{x.customerName}</div></td><td>{x.vehicle?`${x.vehicle.brand} ${x.vehicle.model}`:`VL #${x.vehicleId}`} × {x.quantity}{!x.configuredCost&&<div className={styles.warn}>Coût non configuré</div>}</td><td>{money(x.revenue)}</td><td>{money(x.totalCost)}</td><td className={x.margin>=0?styles.good:styles.bad}><strong>{money(x.margin)}</strong></td><td>{x.marginPercent.toFixed(1)} %</td></tr>)}</tbody></table></div></section>
 </div></DashboardShell>;
}
