import Link from "next/link";
import { redirect } from "next/navigation";

import styles from "@/components/v164/v164.module.css";
import { getUserRoleKeys } from "@/lib/auth/access";
import { createClient } from "@/lib/supabase/server";
import { getMotorsDirectionStatsV164, getMotorsEmployeeAccessV164 } from "@/lib/v164/data";

export const dynamic = "force-dynamic";
export const revalidate = 0;

const money=(v:unknown)=>Number(v??0).toLocaleString("fr-FR",{style:"currency",currency:"EUR",maximumFractionDigits:0});

export default async function MotorsStatsV164({searchParams}:{searchParams:Promise<{days?:string}>}){
  const supabase=await createClient(); const {data}=await supabase.auth.getUser(); if(!data.user)redirect("/");
  const roles=await getUserRoleKeys(data.user); const manager=roles.includes("manager"); const access=await getMotorsEmployeeAccessV164(data.user.id,manager);
  if(!manager&&!access.permissions.has("stats_read"))redirect("/dashboard");
  const q=await searchParams; const days=[30,90,365,0].includes(Number(q.days))?Number(q.days):30; const s=await getMotorsDirectionStatsV164(days);
  const maxBrand=Math.max(1,...s.brands.map(x=>x.units));
  return <main className={styles.page}>
    <section className={styles.hero}><div><span className={styles.eyebrow}>DIRECTION · NOSTRA MOTORS</span><h1>Statistiques avancées Motors</h1><p>Ventes, marges, stock, garanties, atelier et activité clients.</p></div><Link className={styles.back} href="/dashboard">← Dashboard</Link></section>
    <section className={styles.row}><nav className={styles.row}>{[[30,"30 jours"],[90,"90 jours"],[365,"1 an"],[0,"Tout"]].map(([value,label])=><Link className={styles.buttonAlt} key={value} href={`/dashboard/statistiques-motors?days=${value}`}>{label}</Link>)}</nav><span className={styles.pill}>{days===0?"Toutes périodes":`${days} derniers jours`}</span></section>
    {!s.configured&&<div className={styles.error}>Certaines tables nécessaires aux statistiques ne sont pas encore disponibles.</div>}
    <section className={styles.stats}><article className={styles.stat}><span>CA véhicules</span><strong>{money(s.motorsRevenue)}</strong></article><article className={styles.stat}><span>Véhicules vendus</span><strong>{s.soldUnits}</strong></article><article className={styles.stat}><span>Marge estimée</span><strong>{money(s.estimatedMargin)}</strong></article><article className={styles.stat}><span>Panier moyen</span><strong>{money(s.averageBasket)}</strong></article></section>
    <section className={styles.grid3}><article className={styles.card}><span className={styles.eyebrow}>VENTES</span><h2>Performance commerciale</h2><div className={styles.list}><div className={styles.item}><strong>Meilleure marque</strong><p>{s.topBrand?.name??"—"} {s.topBrand?`· ${s.topBrand.units} vente(s)`:""}</p></div><div className={styles.item}><strong>Meilleur modèle</strong><p>{s.topModel?.name??"—"} {s.topModel?`· ${s.topModel.units} vente(s)`:""}</p></div><div className={styles.item}><strong>Clients acheteurs</strong><p>{s.uniqueCustomers}</p></div><div className={styles.item}><strong>Nouveaux citoyens</strong><p>{s.newCitizens}</p></div></div></article><article className={styles.card}><span className={styles.eyebrow}>STOCK</span><h2>État du catalogue</h2><div className={styles.list}><div className={styles.item}><strong>Fiches catalogue</strong><p>{s.stock.total}</p></div><div className={styles.item}><strong>Stock faible ≤ 2</strong><p>{s.stock.low}</p></div><div className={styles.item}><strong>Ruptures</strong><p>{s.stock.out}</p></div><div className={styles.item}><strong>Véhicules de démonstration</strong><p>{s.stock.demos}</p></div></div></article><article className={styles.card}><span className={styles.eyebrow}>MARGES</span><h2>Rentabilité estimée</h2><div className={styles.list}><div className={styles.item}><strong>Coûts fournisseurs estimés</strong><p>{money(s.estimatedCost)}</p></div><div className={styles.item}><strong>Marge estimée</strong><p>{money(s.estimatedMargin)}</p></div><div className={styles.item}><strong>Taux de marge</strong><p>{s.estimatedMarginPercent.toFixed(1)} %</p></div></div></article></section>
    <section className={styles.grid2}><article className={styles.card}><span className={styles.eyebrow}>NOSTRA CARE</span><h2>Garanties</h2><div className={styles.stats} style={{gridTemplateColumns:"repeat(2,minmax(0,1fr))"}}><div className={styles.stat}><span>CA garanties</span><strong>{money(s.warranty.revenue)}</strong></div><div className={styles.stat}><span>Actives</span><strong>{s.warranty.active}</strong></div><div className={styles.stat}><span>Care</span><strong>{s.warranty.care}</strong></div><div className={styles.stat}><span>Care+</span><strong>{s.warranty.carePlus}</strong></div></div></article><article className={styles.card}><span className={styles.eyebrow}>ATELIER</span><h2>Après-vente & entretien</h2><div className={styles.list}><div className={styles.item}><strong>Dossiers atelier</strong><p>{s.workshop.cases} · {s.workshop.active} actif(s)</p></div><div className={styles.item}><strong>CA devis atelier</strong><p>{money(s.workshop.revenue)}</p></div><div className={styles.item}><strong>Entrées carnet</strong><p>{s.workshop.maintenanceRecords} · {money(s.workshop.maintenanceRevenue)}</p></div><div className={styles.item}><strong>Prises en charge Nostra Care</strong><p>{s.workshop.warrantyCovered}</p></div></div></article></section>
    <section className={styles.card}><span className={styles.eyebrow}>TOP MARQUES</span><h2>Ventes par marque</h2><div className={styles.list}>{s.brands.map(row=><div className={styles.metricBar} key={row.name}><strong>{row.name}</strong><div className={styles.metricTrack}><div className={styles.metricFill} style={{width:`${Math.max(3,row.units/maxBrand*100)}%`}}/></div><span>{row.units} · {money(row.revenue)}</span></div>)}{s.brands.length===0&&<p className={styles.muted}>Aucune vente dans cette période.</p>}</div></section>
  </main>
}
