import { addVehicleSearchProposalV134, updateVehicleSearchMandateV134 } from "@/app/actions/vehicle-search-mandates";
import { DashboardHeader } from "@/components/dashboard/dashboard-header";
import { DashboardShell } from "@/components/dashboard/dashboard-shell";
import { UsedVehicleDashboardNav } from "@/components/used-vehicles/used-dashboard-nav";
import { getSearchMandatesConfiguredV134, getSearchMandatesV134 } from "@/lib/vehicle-search-mandates/data";
import styles from "@/components/used-vehicles/used-vehicles.module.css";

const money=(value:number)=>value.toLocaleString("fr-FR",{style:"currency",currency:"EUR",maximumFractionDigits:0});
export default async function SearchMandatesDashboard({searchParams}:{searchParams:Promise<Record<string,string|undefined>>}){
 const [params,configured,rows]=await Promise.all([searchParams,getSearchMandatesConfiguredV134(),getSearchMandatesV134()]);
 return <DashboardShell allowedRoles={["manager","employee","commercial"]}><DashboardHeader title="Mandats de recherche" description="Analyse les critères des citoyens et envoie plusieurs propositions de véhicules."/><UsedVehicleDashboardNav current="/dashboard/occasion/mandats-recherche"/>
 {!configured?<section className="dashboard-setup"><span className="module-status">Activation nécessaire</span><h2>Exécute le SQL V134</h2></section>:<>
 {params.saved&&<div className="dashboard-feedback dashboard-feedback-success">Mandat mis à jour.</div>}{params.proposal&&<div className="dashboard-feedback dashboard-feedback-success">Proposition envoyée au citoyen.</div>}{params.error&&<div className="dashboard-feedback dashboard-feedback-error">Impossible d’enregistrer la modification.</div>}
 <section className={styles.kpis}><article className={styles.kpi}><span>Total</span><strong>{rows.length}</strong></article><article className={styles.kpi}><span>Nouveaux</span><strong>{rows.filter(r=>r.status==="new").length}</strong></article><article className={styles.kpi}><span>Recherches actives</span><strong>{rows.filter(r=>["searching","proposed"].includes(r.status)).length}</strong></article><article className={styles.kpi}><span>Choix clients</span><strong>{rows.filter(r=>r.status==="selected").length}</strong></article></section>
 <div className={styles.stack}>{rows.length===0&&<section className={styles.panel}><p className={styles.empty}>Aucun mandat reçu.</p></section>}{rows.map(row=><article className={styles.panel} key={row.id}><div className={styles.caseHead}><div><span className={styles.badge}>{row.status}</span><h2>{row.mandate_number} · {row.customer_name}</h2><p>{[row.brand,row.model,row.vehicle_type].filter(Boolean).join(" · ")}</p></div><strong>{money(row.budget_max)}</strong></div>
 <div className={styles.detailsGrid}><div><span>Budget</span><strong>{money(row.budget_min)} – {money(row.budget_max)}</strong></div><div><span>Année min.</span><strong>{row.year_min??"Libre"}</strong></div><div><span>Kilométrage max.</span><strong>{row.max_mileage?`${row.max_mileage.toLocaleString("fr-FR")} km`:"Libre"}</strong></div><div><span>Contact</span><strong>{row.customer_phone||row.customer_email||"Non renseigné"}</strong></div></div>{row.required_features&&<p className={styles.notice}><strong>Critères :</strong> {row.required_features}</p>}
 <form action={updateVehicleSearchMandateV134} className={styles.form}><input type="hidden" name="mandate_id" value={row.id}/><label>Statut<select name="status" defaultValue={row.status}><option value="new">Nouveau</option><option value="searching">Recherche en cours</option><option value="proposed">Propositions envoyées</option><option value="closed">Terminé</option><option value="refused">Refusé</option></select></label><label>Commercial<input name="assigned_staff" defaultValue={row.assigned_staff??""}/></label><label className={styles.span2}>Message client<textarea name="staff_note" rows={2} defaultValue={row.staff_note??""}/></label><button className={styles.secondary}>Enregistrer le suivi</button></form>
 <div className={styles.proposalGrid}>{row.proposals.map(p=><article className={styles.proposal} key={p.id}><span className={styles.badge}>{p.status}</span><h3>{p.vehicle_name}</h3><strong>{money(p.price)}</strong><p>{p.year||"—"} · {p.mileage==null?"—":`${p.mileage.toLocaleString("fr-FR")} km`}</p></article>)}</div>
 {!['selected','closed','refused','cancelled'].includes(row.status)&&<form action={addVehicleSearchProposalV134} className={styles.form}><input type="hidden" name="mandate_id" value={row.id}/><label>Véhicule<input name="vehicle_name" required/></label><label>Prix<input name="price" inputMode="decimal" required/></label><label>Année<input name="year" type="number"/></label><label>Kilométrage<input name="mileage" type="number" min="0"/></label><label className={styles.span2}>Lien source<input name="source_url" type="url"/></label><label className={styles.span2}>Détails<textarea name="details" rows={2}/></label><button className={styles.primary}>Ajouter la proposition</button></form>}
 </article>)}</div></>}
 </DashboardShell>;
}
