export const GAMES_SETUP_SQL = String.raw`-- Nostra Group V29 — Roue de la chance

create table if not exists public.game_wheel_spins (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  player_name text not null,
  slot_index integer not null check (slot_index between 0 and 22),
  prize_key text not null,
  prize_label text not null,
  prize_type text not null check (prize_type in ('bonus', 'loss')),
  redemption_status text not null default 'unused' check (redemption_status in ('unused', 'used', 'lost')),
  awarded_at timestamptz not null default now(),
  used_at timestamptz,
  used_by uuid references auth.users(id) on delete set null,
  updated_at timestamptz not null default now()
);

create index if not exists game_wheel_spins_user_id_idx on public.game_wheel_spins(user_id, awarded_at desc);
create index if not exists game_wheel_spins_status_idx on public.game_wheel_spins(redemption_status, awarded_at desc);

create or replace function public.nostra_games_is_manager()
returns boolean language sql stable security definer set search_path = public
as $$
  select exists (
    select 1 from public.member_profiles profile
    where profile.user_id = auth.uid()
      and (lower(coalesce(profile.role, '')) = 'manager' or 'manager' = any(coalesce(profile.roles, array[]::text[])))
  );
$$;
grant execute on function public.nostra_games_is_manager() to authenticated;

alter table public.game_wheel_spins enable row level security;
drop policy if exists "wheel citizens read own" on public.game_wheel_spins;
create policy "wheel citizens read own" on public.game_wheel_spins for select to authenticated using (auth.uid() = user_id);
drop policy if exists "wheel managers read all" on public.game_wheel_spins;
create policy "wheel managers read all" on public.game_wheel_spins for select to authenticated using (public.nostra_games_is_manager());
drop policy if exists "wheel managers update all" on public.game_wheel_spins;
create policy "wheel managers update all" on public.game_wheel_spins for update to authenticated using (public.nostra_games_is_manager()) with check (public.nostra_games_is_manager());
drop policy if exists "wheel managers delete all" on public.game_wheel_spins;
create policy "wheel managers delete all" on public.game_wheel_spins for delete to authenticated using (public.nostra_games_is_manager());

create or replace function public.spin_nostra_wheel()
returns jsonb language plpgsql security definer set search_path = public
as $$
declare
  v_user_id uuid := auth.uid(); v_player_name text; v_slot integer;
  v_prize_key text; v_prize_label text; v_prize_type text; v_status text; v_spin_id bigint;
begin
  if v_user_id is null then raise exception 'not_authenticated'; end if;
  select nullif(trim(concat_ws(' ', rp_first_name, rp_last_name)), '') into v_player_name from public.member_profiles where user_id = v_user_id;
  if v_player_name is null then select nullif(trim(coalesce(discord_name, '')), '') into v_player_name from public.member_profiles where user_id = v_user_id; end if;
  v_player_name := coalesce(v_player_name, 'Citoyen Nostra Group');
  v_slot := floor(random() * 23)::integer;
  case v_slot
    when 0 then v_prize_key := 'lost'; v_prize_label := 'Perdu'; v_prize_type := 'loss';
    when 1 then v_prize_key := 'paint'; v_prize_label := 'Peinture offerte'; v_prize_type := 'bonus';
    when 2 then v_prize_key := 'lost'; v_prize_label := 'Perdu'; v_prize_type := 'loss';
    when 3 then v_prize_key := 'discount_5'; v_prize_label := '-5 % sur la prochaine commande'; v_prize_type := 'bonus';
    when 4 then v_prize_key := 'coffee'; v_prize_label := '1 café offert'; v_prize_type := 'bonus';
    when 5 then v_prize_key := 'lost'; v_prize_label := 'Perdu'; v_prize_type := 'loss';
    when 6 then v_prize_key := 'circuit_lap'; v_prize_label := '1 tour de circuit offert'; v_prize_type := 'bonus';
    when 7 then v_prize_key := 'paint'; v_prize_label := 'Peinture offerte'; v_prize_type := 'bonus';
    when 8 then v_prize_key := 'lost'; v_prize_label := 'Perdu'; v_prize_type := 'loss';
    when 9 then v_prize_key := 'circuit_10_laps'; v_prize_label := '10 tours de circuit offerts'; v_prize_type := 'bonus';
    when 10 then v_prize_key := 'discount_5'; v_prize_label := '-5 % sur la prochaine commande'; v_prize_type := 'bonus';
    when 11 then v_prize_key := 'circuit_5_laps'; v_prize_label := '5 tours de circuit offerts'; v_prize_type := 'bonus';
    when 12 then v_prize_key := 'lost'; v_prize_label := 'Perdu'; v_prize_type := 'loss';
    when 13 then v_prize_key := 'silver_card'; v_prize_label := 'Carte fidélité Silver'; v_prize_type := 'bonus';
    when 14 then v_prize_key := 'coffee'; v_prize_label := '1 café offert'; v_prize_type := 'bonus';
    when 15 then v_prize_key := 'discount_5'; v_prize_label := '-5 % sur la prochaine commande'; v_prize_type := 'bonus';
    when 16 then v_prize_key := 'circuit_lap'; v_prize_label := '1 tour de circuit offert'; v_prize_type := 'bonus';
    when 17 then v_prize_key := 'lost'; v_prize_label := 'Perdu'; v_prize_type := 'loss';
    when 18 then v_prize_key := 'vehicle_test'; v_prize_label := 'Essai d’un véhicule de la concession'; v_prize_type := 'bonus';
    when 19 then v_prize_key := 'paint'; v_prize_label := 'Peinture offerte'; v_prize_type := 'bonus';
    when 20 then v_prize_key := 'circuit_5_laps'; v_prize_label := '5 tours de circuit offerts'; v_prize_type := 'bonus';
    when 21 then v_prize_key := 'discount_10k'; v_prize_label := '-10 000 € sur la prochaine commande'; v_prize_type := 'bonus';
    else v_prize_key := 'discount_10k'; v_prize_label := '-10 000 € sur la prochaine commande'; v_prize_type := 'bonus';
  end case;
  v_status := case when v_prize_type = 'loss' then 'lost' else 'unused' end;
  insert into public.game_wheel_spins (user_id, player_name, slot_index, prize_key, prize_label, prize_type, redemption_status)
  values (v_user_id, v_player_name, v_slot, v_prize_key, v_prize_label, v_prize_type, v_status)
  returning id into v_spin_id;
  return jsonb_build_object('id', v_spin_id, 'slot_index', v_slot, 'prize_key', v_prize_key, 'prize_label', v_prize_label, 'prize_type', v_prize_type, 'redemption_status', v_status);
end;
$$;
revoke all on function public.spin_nostra_wheel() from public;
grant execute on function public.spin_nostra_wheel() to authenticated;
grant select, update, delete on public.game_wheel_spins to authenticated;
grant usage, select on sequence public.game_wheel_spins_id_seq to authenticated;
notify pgrst, 'reload schema';`;
