export const BACKOFFICE_SETUP_SQL = String.raw`-- NOSTRA GROUP — Dashboard V18
-- Script réexécutable : il conserve les données déjà présentes.

create table if not exists public.member_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  discord_id text,
  discord_name text,
  email text,
  avatar_url text,
  rp_first_name text,
  rp_last_name text,
  role text not null default 'member' check (role in ('member','staff','administrator','manager')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function public.nostra_jwt_discord_id()
returns text
language sql
stable
as $$
  select coalesce(
    auth.jwt() -> 'user_metadata' ->> 'provider_id',
    auth.jwt() -> 'user_metadata' ->> 'discord_id',
    auth.jwt() -> 'user_metadata' ->> 'sub'
  );
$$;

create or replace function public.nostra_role()
returns text
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  stored_role text;
begin
  if public.nostra_jwt_discord_id() = '331843410962939908' then
    return 'manager';
  end if;
  select role into stored_role from public.member_profiles where user_id = auth.uid();
  return coalesce(stored_role, 'member');
end;
$$;

create or replace function public.has_nostra_dashboard_access()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select public.nostra_role() in ('administrator','manager');
$$;

create or replace function public.is_nostra_manager()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select public.has_nostra_dashboard_access();
$$;

grant execute on function public.nostra_jwt_discord_id() to authenticated;
grant execute on function public.nostra_role() to authenticated;
grant execute on function public.has_nostra_dashboard_access() to authenticated;
grant execute on function public.is_nostra_manager() to authenticated;

create table if not exists public.site_pages (
  slug text primary key,
  title text not null,
  content text not null,
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id) on delete set null
);

create table if not exists public.custom_circuit_pages (
  id bigint generated by default as identity primary key,
  category_key text not null,
  category_label text not null,
  slug text not null unique,
  label text not null,
  title text not null,
  content text not null,
  sort_order integer not null default 100,
  visible boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references auth.users(id) on delete set null,
  updated_by uuid references auth.users(id) on delete set null
);

create table if not exists public.hidden_circuit_pages (
  page_key text primary key,
  hidden_at timestamptz not null default now(),
  hidden_by uuid references auth.users(id) on delete set null
);

create table if not exists public.circuit_settings (
  id integer primary key default 1 check (id = 1),
  status text not null default 'open',
  label text not null default 'Circuit ouvert',
  message text not null default 'Le Nostra Circuit est actuellement ouvert.',
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id) on delete set null
);
insert into public.circuit_settings (id) values (1) on conflict (id) do nothing;


create table if not exists public.motors_settings (
  id integer primary key default 1 check (id = 1),
  status text not null default 'open',
  label text not null default 'Concession ouverte',
  message text not null default 'Nostra Motors accueille actuellement ses clients.',
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id) on delete set null
);
insert into public.motors_settings (id) values (1) on conflict (id) do nothing;

create table if not exists public.inventory_items (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null default 'Général',
  sku text,
  quantity integer not null default 0 check (quantity >= 0),
  minimum_quantity integer not null default 0 check (minimum_quantity >= 0),
  unit_price numeric(12,2) not null default 0 check (unit_price >= 0),
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id) on delete set null
);

create table if not exists public.accounting_entries (
  id bigint generated by default as identity primary key,
  entry_date date not null default current_date,
  entry_type text not null check (entry_type in ('income', 'expense')),
  category text not null default 'Général',
  label text not null,
  amount numeric(12,2) not null check (amount >= 0),
  notes text,
  created_at timestamptz not null default now(),
  created_by uuid references auth.users(id) on delete set null
);

create table if not exists public.events (
  id bigint generated by default as identity primary key,
  title text not null,
  description text not null default '',
  location text not null default '',
  starts_at timestamptz not null,
  ends_at timestamptz,
  status text not null default 'draft' check (status in ('draft', 'published', 'cancelled', 'completed')),
  registration_open boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references auth.users(id) on delete set null
);

create table if not exists public.homologation_requests (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  request_type text not null check (request_type in ('vehicle', 'team')),
  applicant_name text not null,
  status text not null default 'pending' check (status in ('pending', 'reviewing', 'approved', 'rejected')),
  payload jsonb not null default '{}'::jsonb,
  admin_note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  order_number text not null unique,
  status text not null default 'pending',
  total numeric(12,2) not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.invoices (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  invoice_number text not null unique,
  status text not null default 'issued',
  amount numeric(12,2) not null default 0,
  issued_at timestamptz not null default now(),
  download_url text
);

create table if not exists public.loyalty_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  tier text not null default 'Aucun statut',
  purchases_count integer not null default 0,
  discount_percent numeric(5,2) not null default 0,
  updated_at timestamptz not null default now()
);

create table if not exists public.cart_items (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  item_name text not null,
  quantity integer not null default 1 check (quantity > 0),
  unit_price numeric(12,2) not null default 0,
  image_url text,
  created_at timestamptz not null default now()
);

alter table public.member_profiles enable row level security;
alter table public.site_pages enable row level security;
alter table public.custom_circuit_pages enable row level security;
alter table public.hidden_circuit_pages enable row level security;
alter table public.circuit_settings enable row level security;
alter table public.motors_settings enable row level security;
alter table public.inventory_items enable row level security;
alter table public.accounting_entries enable row level security;
alter table public.events enable row level security;
alter table public.homologation_requests enable row level security;
alter table public.orders enable row level security;
alter table public.invoices enable row level security;
alter table public.loyalty_profiles enable row level security;
alter table public.cart_items enable row level security;

-- Profils et rôles
drop policy if exists "members read profiles" on public.member_profiles;
create policy "members read profiles" on public.member_profiles for select to authenticated
using (user_id = auth.uid() or public.has_nostra_dashboard_access());
drop policy if exists "members insert own profile" on public.member_profiles;
create policy "members insert own profile" on public.member_profiles for insert to authenticated
with check (user_id = auth.uid());
drop policy if exists "members update own profile" on public.member_profiles;
create policy "members update own profile" on public.member_profiles for update to authenticated
using (user_id = auth.uid() or public.has_nostra_dashboard_access())
with check (user_id = auth.uid() or public.has_nostra_dashboard_access());
drop policy if exists "dashboard deletes profiles" on public.member_profiles;
create policy "dashboard deletes profiles" on public.member_profiles for delete to authenticated
using (public.has_nostra_dashboard_access());

-- Pages du site
drop policy if exists "manager can insert site pages" on public.site_pages;
drop policy if exists "manager can update site pages" on public.site_pages;
drop policy if exists "manager can delete site pages" on public.site_pages;
drop policy if exists "site pages readable by authenticated users" on public.site_pages;
create policy "site pages readable by authenticated users" on public.site_pages for select to authenticated using (true);
drop policy if exists "dashboard manages site pages" on public.site_pages;
create policy "dashboard manages site pages" on public.site_pages for all to authenticated
using (public.has_nostra_dashboard_access()) with check (public.has_nostra_dashboard_access());

drop policy if exists "custom pages readable" on public.custom_circuit_pages;
create policy "custom pages readable" on public.custom_circuit_pages for select to authenticated using (visible or public.has_nostra_dashboard_access());
drop policy if exists "dashboard manages custom pages" on public.custom_circuit_pages;
create policy "dashboard manages custom pages" on public.custom_circuit_pages for all to authenticated
using (public.has_nostra_dashboard_access()) with check (public.has_nostra_dashboard_access());

drop policy if exists "hidden pages readable" on public.hidden_circuit_pages;
create policy "hidden pages readable" on public.hidden_circuit_pages for select to authenticated using (true);
drop policy if exists "dashboard manages hidden pages" on public.hidden_circuit_pages;
create policy "dashboard manages hidden pages" on public.hidden_circuit_pages for all to authenticated
using (public.has_nostra_dashboard_access()) with check (public.has_nostra_dashboard_access());

-- Informations publiques du circuit
drop policy if exists "circuit settings readable" on public.circuit_settings;
create policy "circuit settings readable" on public.circuit_settings for select to authenticated using (true);
drop policy if exists "events readable" on public.events;
create policy "events readable" on public.events for select to authenticated using (status <> 'draft' or public.has_nostra_dashboard_access());

-- Modules du dashboard
drop policy if exists "manager manages circuit settings" on public.circuit_settings;
create policy "manager manages circuit settings" on public.circuit_settings for all to authenticated
using (public.has_nostra_dashboard_access()) with check (public.has_nostra_dashboard_access());
drop policy if exists "motors settings readable" on public.motors_settings;
create policy "motors settings readable" on public.motors_settings for select to authenticated using (true);
drop policy if exists "manager manages motors settings" on public.motors_settings;
create policy "manager manages motors settings" on public.motors_settings for all to authenticated
using (public.has_nostra_dashboard_access()) with check (public.has_nostra_dashboard_access());
drop policy if exists "manager manages inventory" on public.inventory_items;
create policy "manager manages inventory" on public.inventory_items for all to authenticated
using (public.has_nostra_dashboard_access()) with check (public.has_nostra_dashboard_access());
drop policy if exists "manager manages accounting" on public.accounting_entries;
create policy "manager manages accounting" on public.accounting_entries for all to authenticated
using (public.has_nostra_dashboard_access()) with check (public.has_nostra_dashboard_access());
drop policy if exists "manager manages events" on public.events;
create policy "manager manages events" on public.events for all to authenticated
using (public.has_nostra_dashboard_access()) with check (public.has_nostra_dashboard_access());

-- Homologations
drop policy if exists "users create homologation requests" on public.homologation_requests;
create policy "users create homologation requests" on public.homologation_requests for insert to authenticated
with check (user_id = auth.uid());
drop policy if exists "users read homologation requests" on public.homologation_requests;
create policy "users read homologation requests" on public.homologation_requests for select to authenticated
using (user_id = auth.uid() or public.has_nostra_dashboard_access());
drop policy if exists "manager updates homologation requests" on public.homologation_requests;
create policy "manager updates homologation requests" on public.homologation_requests for update to authenticated
using (public.has_nostra_dashboard_access()) with check (public.has_nostra_dashboard_access());
drop policy if exists "manager deletes homologation requests" on public.homologation_requests;
create policy "manager deletes homologation requests" on public.homologation_requests for delete to authenticated
using (public.has_nostra_dashboard_access());

-- Espace client
drop policy if exists "users read own orders" on public.orders;
create policy "users read own orders" on public.orders for select to authenticated
using (user_id = auth.uid() or public.has_nostra_dashboard_access());
drop policy if exists "manager manages orders" on public.orders;
create policy "manager manages orders" on public.orders for all to authenticated
using (public.has_nostra_dashboard_access()) with check (public.has_nostra_dashboard_access());
drop policy if exists "users read own invoices" on public.invoices;
create policy "users read own invoices" on public.invoices for select to authenticated
using (user_id = auth.uid() or public.has_nostra_dashboard_access());
drop policy if exists "manager manages invoices" on public.invoices;
create policy "manager manages invoices" on public.invoices for all to authenticated
using (public.has_nostra_dashboard_access()) with check (public.has_nostra_dashboard_access());
drop policy if exists "users read own loyalty" on public.loyalty_profiles;
create policy "users read own loyalty" on public.loyalty_profiles for select to authenticated
using (user_id = auth.uid() or public.has_nostra_dashboard_access());
drop policy if exists "manager manages loyalty" on public.loyalty_profiles;
create policy "manager manages loyalty" on public.loyalty_profiles for all to authenticated
using (public.has_nostra_dashboard_access()) with check (public.has_nostra_dashboard_access());
drop policy if exists "users manage own cart" on public.cart_items;
create policy "users manage own cart" on public.cart_items for all to authenticated
using (user_id = auth.uid() or public.has_nostra_dashboard_access())
with check (user_id = auth.uid() or public.has_nostra_dashboard_access());

-- Empêche un membre de s’attribuer lui-même un rôle supérieur via une requête directe.
create or replace function public.protect_nostra_member_role()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.has_nostra_dashboard_access() then
    new.role := old.role;
  end if;
  if new.discord_id = '331843410962939908' then
    new.role := 'manager';
  end if;
  return new;
end;
$$;

drop trigger if exists protect_nostra_member_role_trigger on public.member_profiles;
create trigger protect_nostra_member_role_trigger
before update on public.member_profiles
for each row execute function public.protect_nostra_member_role();


-- V11 — Réservations du circuit et calendriers des championnats
alter table public.events add column if not exists championship text not null default 'general';
update public.events set championship = 'general' where championship is null or championship = '';

create table if not exists public.circuit_reservation_requests (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  first_name text not null,
  last_name text not null,
  reservation_date date not null,
  reservation_time time not null,
  reason text not null,
  status text not null default 'pending' check (status in ('pending','approved','rejected','cancelled')),
  admin_note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists one_approved_reservation_per_slot
on public.circuit_reservation_requests (reservation_date, reservation_time)
where status = 'approved';

alter table public.circuit_reservation_requests enable row level security;

drop policy if exists "members create circuit reservations" on public.circuit_reservation_requests;
create policy "members create circuit reservations" on public.circuit_reservation_requests
for insert to authenticated with check (user_id = auth.uid());

drop policy if exists "members read circuit reservations" on public.circuit_reservation_requests;
create policy "members read circuit reservations" on public.circuit_reservation_requests
for select to authenticated using (
  user_id = auth.uid()
  or status = 'approved'
  or public.has_nostra_dashboard_access()
);

drop policy if exists "dashboard manages circuit reservations" on public.circuit_reservation_requests;
create policy "dashboard manages circuit reservations" on public.circuit_reservation_requests
for update to authenticated
using (public.has_nostra_dashboard_access())
with check (public.has_nostra_dashboard_access());

drop policy if exists "dashboard deletes circuit reservations" on public.circuit_reservation_requests;
create policy "dashboard deletes circuit reservations" on public.circuit_reservation_requests
for delete to authenticated using (public.has_nostra_dashboard_access());


-- V15 — Catalogue Nostra Motors avec photos
create table if not exists public.catalog_vehicles (
  id bigint generated by default as identity primary key,
  brand text not null,
  model text not null,
  trunk_capacity text not null default '',
  top_speed text not null default '',
  power text not null default '',
  price numeric(14,2) not null default 0,
  description text not null default '',
  images jsonb not null default '[]'::jsonb,
  published boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id) on delete set null
);

create index if not exists catalog_vehicles_brand_index
on public.catalog_vehicles (brand, sort_order, model);

alter table public.catalog_vehicles enable row level security;

drop policy if exists "members read published catalog vehicles" on public.catalog_vehicles;
create policy "members read published catalog vehicles" on public.catalog_vehicles
for select to authenticated
using (published or public.has_nostra_dashboard_access());

drop policy if exists "dashboard manages catalog vehicles" on public.catalog_vehicles;
create policy "dashboard manages catalog vehicles" on public.catalog_vehicles
for all to authenticated
using (public.has_nostra_dashboard_access())
with check (public.has_nostra_dashboard_access());

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'vehicle-images',
  'vehicle-images',
  true,
  5242880,
  array['image/jpeg','image/png','image/webp']::text[]
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "public reads vehicle images" on storage.objects;
create policy "public reads vehicle images" on storage.objects
for select to public
using (bucket_id = 'vehicle-images');

drop policy if exists "dashboard uploads vehicle images" on storage.objects;
create policy "dashboard uploads vehicle images" on storage.objects
for insert to authenticated
with check (bucket_id = 'vehicle-images' and public.has_nostra_dashboard_access());

drop policy if exists "dashboard updates vehicle images" on storage.objects;
create policy "dashboard updates vehicle images" on storage.objects
for update to authenticated
using (bucket_id = 'vehicle-images' and public.has_nostra_dashboard_access())
with check (bucket_id = 'vehicle-images' and public.has_nostra_dashboard_access());

drop policy if exists "dashboard deletes vehicle images" on storage.objects;
create policy "dashboard deletes vehicle images" on storage.objects
for delete to authenticated
using (bucket_id = 'vehicle-images' and public.has_nostra_dashboard_access());
`;
