export const TEAM_REGISTRATIONS_SETUP_SQL = String.raw`-- NOSTRA GROUP — Inscriptions des écuries aux championnats V23
-- Script réexécutable : il conserve toutes les demandes déjà enregistrées.

create table if not exists public.team_registration_requests (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  registration_type text not null check (registration_type in ('f1','gt3rs','both')),
  applicant_name text not null,
  team_name text not null,
  team_director text not null,
  requested_number_f1 text,
  requested_number_gt3rs text,
  has_f1_license boolean not null default false,
  has_gt3rs_license boolean not null default false,
  notes text,
  status text not null default 'pending' check (status in ('pending','reviewing','approved','rejected')),
  admin_note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists team_registration_requests_user_id_index
on public.team_registration_requests (user_id);

create index if not exists team_registration_requests_status_index
on public.team_registration_requests (status, created_at desc);

alter table public.team_registration_requests enable row level security;

drop policy if exists "members create team registrations" on public.team_registration_requests;
create policy "members create team registrations"
on public.team_registration_requests
for insert to authenticated
with check (user_id = auth.uid());

drop policy if exists "members read team registrations" on public.team_registration_requests;
create policy "members read team registrations"
on public.team_registration_requests
for select to authenticated
using (user_id = auth.uid() or public.has_nostra_dashboard_access());

drop policy if exists "dashboard updates team registrations" on public.team_registration_requests;
create policy "dashboard updates team registrations"
on public.team_registration_requests
for update to authenticated
using (public.has_nostra_dashboard_access())
with check (public.has_nostra_dashboard_access());

drop policy if exists "dashboard deletes team registrations" on public.team_registration_requests;
create policy "dashboard deletes team registrations"
on public.team_registration_requests
for delete to authenticated
using (public.has_nostra_dashboard_access());


-- V146 — vérification réelle des licences F1 / GT3 RS pour créer une écurie.
create or replace function public.nostra_v146_has_valid_team_licence(
  p_user uuid,
  p_championship text
)
returns boolean
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_target text := lower(trim(coalesce(p_championship, '')));
  v_found boolean := false;
begin
  if p_user is null or v_target not in ('f1', 'gt3rs') then return false; end if;

  select exists (
    select 1
    from public.nostra_licences l
    where l.holder_user_id = p_user
      and l.valid_from <= current_date
      and (l.valid_until is null or l.valid_until >= current_date)
      and lower(coalesce(l.status, '')) not like '%retir%'
      and lower(coalesce(l.status, '')) not like '%revok%'
      and lower(coalesce(l.status, '')) not like '%suspend%'
      and not public.nostra_v140_licence_is_blocked(l.id::text)
      and (
        (v_target = 'f1' and public.nostra_v140_normalize(public.nostra_v142_official_licence_code(l.id::text, l.licence_name)) = 'F1')
        or
        (v_target = 'gt3rs' and public.nostra_v140_normalize(public.nostra_v142_official_licence_code(l.id::text, l.licence_name)) like '%GT3%')
      )
  ) into v_found;

  return coalesce(v_found, false);
end;
$$;

revoke all on function public.nostra_v146_has_valid_team_licence(uuid,text) from public;
revoke all on function public.nostra_v146_has_valid_team_licence(uuid,text) from authenticated;

create or replace function public.nostra_v146_guard_team_registration()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_has_f1 boolean := false;
  v_has_gt3rs boolean := false;
begin
  if new.registration_type in ('f1','both') then
    v_has_f1 := public.nostra_v146_has_valid_team_licence(new.user_id, 'f1');
    if not v_has_f1 then
      raise exception using errcode = 'P0001', message = 'team_license_f1_required';
    end if;
  end if;

  if new.registration_type in ('gt3rs','both') then
    v_has_gt3rs := public.nostra_v146_has_valid_team_licence(new.user_id, 'gt3rs');
    if not v_has_gt3rs then
      raise exception using errcode = 'P0001', message = 'team_license_gt3rs_required';
    end if;
  end if;

  new.has_f1_license := case when new.registration_type in ('f1','both') then v_has_f1 else false end;
  new.has_gt3rs_license := case when new.registration_type in ('gt3rs','both') then v_has_gt3rs else false end;
  return new;
end;
$$;

drop trigger if exists nostra_v146_team_registration_license_guard on public.team_registration_requests;
create trigger nostra_v146_team_registration_license_guard
before insert on public.team_registration_requests
for each row execute function public.nostra_v146_guard_team_registration();
`;
