export const TEAM_REGISTRATIONS_SETUP_SQL = String.raw`-- NOSTRA GROUP — Inscriptions des écuries aux championnats V23
-- Script réexécutable : il conserve toutes les demandes déjà enregistrées.

create table if not exists public.team_registration_requests (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  registration_type text not null check (registration_type in ('f1','gt3rs','both')),
  applicant_name text not null,
  team_name text not null,
  team_director text not null,
  requested_number_f1 text,
  requested_number_gt3rs text,
  has_f1_license boolean not null default false,
  has_gt3rs_license boolean not null default false,
  notes text,
  status text not null default 'pending' check (status in ('pending','reviewing','approved','rejected')),
  admin_note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists team_registration_requests_user_id_index
on public.team_registration_requests (user_id);

create index if not exists team_registration_requests_status_index
on public.team_registration_requests (status, created_at desc);

alter table public.team_registration_requests enable row level security;

drop policy if exists "members create team registrations" on public.team_registration_requests;
create policy "members create team registrations"
on public.team_registration_requests
for insert to authenticated
with check (user_id = auth.uid());

drop policy if exists "members read team registrations" on public.team_registration_requests;
create policy "members read team registrations"
on public.team_registration_requests
for select to authenticated
using (user_id = auth.uid() or public.has_nostra_dashboard_access());

drop policy if exists "dashboard updates team registrations" on public.team_registration_requests;
create policy "dashboard updates team registrations"
on public.team_registration_requests
for update to authenticated
using (public.has_nostra_dashboard_access())
with check (public.has_nostra_dashboard_access());

drop policy if exists "dashboard deletes team registrations" on public.team_registration_requests;
create policy "dashboard deletes team registrations"
on public.team_registration_requests
for delete to authenticated
using (public.has_nostra_dashboard_access());
`;
