export const TOMBOLA_SETUP_SQL = String.raw`-- NOSTRA GROUP V31 — TOMBOLA COMPLÈTE
-- Inscription, panier, commandes de tickets, numéros aléatoires uniques,
-- podium, tirage avec nombre de gagnants configurable et réinitialisation.
-- Script réexécutable : les données existantes sont conservées.

create or replace function public.nostra_tombola_is_manager()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select
    coalesce(public.nostra_has_role('manager'), false)
    or coalesce(public.nostra_jwt_discord_id(), '') = '331843410962939908'
    or exists (
      select 1
      from public.member_profiles profile
      where profile.user_id = auth.uid()
        and (
          lower(coalesce(profile.role, '')) = 'manager'
          or 'manager' = any(coalesce(profile.roles, array[]::text[]))
          or profile.discord_id = '331843410962939908'
        )
    );
$$;

revoke all on function public.nostra_tombola_is_manager() from public;
grant execute on function public.nostra_tombola_is_manager() to authenticated;

create table if not exists public.tombola_rounds (
  id bigint generated by default as identity primary key,
  title text not null default 'Tombola Nostra Group',
  ticket_price numeric(12,2) not null default 5000,
  status text not null default 'open',
  archived_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint tombola_rounds_ticket_price_check check (ticket_price >= 0),
  constraint tombola_rounds_status_check check (status in ('open','closed','drawn','archived'))
);

create unique index if not exists tombola_rounds_single_current_idx
  on public.tombola_rounds ((archived_at is null))
  where archived_at is null;

insert into public.tombola_rounds (title, ticket_price, status)
select 'Tombola Nostra Group', 5000, 'open'
where not exists (
  select 1 from public.tombola_rounds where archived_at is null
);

create table if not exists public.tombola_cart_items (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  round_id bigint not null references public.tombola_rounds(id) on delete cascade,
  customer_name text not null,
  quantity integer not null,
  unit_price numeric(12,2) not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint tombola_cart_quantity_check check (quantity between 1 and 100),
  constraint tombola_cart_price_check check (unit_price >= 0),
  unique (user_id, round_id)
);

create table if not exists public.tombola_purchases (
  id bigint generated by default as identity primary key,
  round_id bigint not null references public.tombola_rounds(id) on delete restrict,
  user_id uuid not null references auth.users(id) on delete cascade,
  order_number text not null unique,
  customer_name text not null,
  quantity integer not null,
  unit_price numeric(12,2) not null,
  total numeric(14,2) not null,
  created_at timestamptz not null default now(),
  constraint tombola_purchase_quantity_check check (quantity > 0),
  constraint tombola_purchase_total_check check (total >= 0)
);

create table if not exists public.tombola_tickets (
  id bigint generated by default as identity primary key,
  round_id bigint not null references public.tombola_rounds(id) on delete cascade,
  purchase_id bigint not null references public.tombola_purchases(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  customer_name text not null,
  ticket_number integer not null,
  created_at timestamptz not null default now(),
  constraint tombola_ticket_number_check check (ticket_number between 1 and 99999),
  unique (round_id, ticket_number)
);

create table if not exists public.tombola_winners (
  id bigint generated by default as identity primary key,
  round_id bigint not null references public.tombola_rounds(id) on delete cascade,
  ticket_id bigint not null references public.tombola_tickets(id) on delete cascade,
  position integer not null,
  ticket_number integer not null,
  customer_name text not null,
  drawn_at timestamptz not null default now(),
  constraint tombola_winner_position_check check (position > 0),
  unique (round_id, position),
  unique (round_id, ticket_id)
);

create index if not exists tombola_cart_user_idx on public.tombola_cart_items(user_id);
create index if not exists tombola_purchases_user_idx on public.tombola_purchases(user_id, created_at desc);
create index if not exists tombola_tickets_user_idx on public.tombola_tickets(user_id, created_at desc);
create index if not exists tombola_tickets_round_idx on public.tombola_tickets(round_id, ticket_number);
create index if not exists tombola_winners_round_idx on public.tombola_winners(round_id, position);

alter table public.tombola_rounds enable row level security;
alter table public.tombola_cart_items enable row level security;
alter table public.tombola_purchases enable row level security;
alter table public.tombola_tickets enable row level security;
alter table public.tombola_winners enable row level security;

drop policy if exists "tombola citizens read rounds" on public.tombola_rounds;
create policy "tombola citizens read rounds"
on public.tombola_rounds for select to authenticated using (true);

drop policy if exists "tombola managers manage rounds" on public.tombola_rounds;
create policy "tombola managers manage rounds"
on public.tombola_rounds for all to authenticated
using (public.nostra_tombola_is_manager())
with check (public.nostra_tombola_is_manager());

drop policy if exists "tombola citizens manage own cart" on public.tombola_cart_items;
create policy "tombola citizens manage own cart"
on public.tombola_cart_items for all to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "tombola managers read all carts" on public.tombola_cart_items;
create policy "tombola managers read all carts"
on public.tombola_cart_items for select to authenticated
using (public.nostra_tombola_is_manager());

drop policy if exists "tombola citizens read own purchases" on public.tombola_purchases;
create policy "tombola citizens read own purchases"
on public.tombola_purchases for select to authenticated
using (auth.uid() = user_id);

drop policy if exists "tombola managers read purchases" on public.tombola_purchases;
create policy "tombola managers read purchases"
on public.tombola_purchases for select to authenticated
using (public.nostra_tombola_is_manager());

drop policy if exists "tombola citizens read own tickets" on public.tombola_tickets;
create policy "tombola citizens read own tickets"
on public.tombola_tickets for select to authenticated
using (auth.uid() = user_id);

drop policy if exists "tombola managers read tickets" on public.tombola_tickets;
create policy "tombola managers read tickets"
on public.tombola_tickets for select to authenticated
using (public.nostra_tombola_is_manager());

drop policy if exists "tombola citizens read winners" on public.tombola_winners;
create policy "tombola citizens read winners"
on public.tombola_winners for select to authenticated using (true);

drop policy if exists "tombola managers manage winners" on public.tombola_winners;
create policy "tombola managers manage winners"
on public.tombola_winners for all to authenticated
using (public.nostra_tombola_is_manager())
with check (public.nostra_tombola_is_manager());

grant select on public.tombola_rounds to authenticated;
grant select, insert, update, delete on public.tombola_cart_items to authenticated;
grant select on public.tombola_purchases to authenticated;
grant select on public.tombola_tickets to authenticated;
grant select on public.tombola_winners to authenticated;

create or replace function public.add_tombola_to_cart(
  p_customer_name text,
  p_quantity integer
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_round public.tombola_rounds%rowtype;
  v_quantity integer := greatest(1, least(100, coalesce(p_quantity, 1)));
  v_cart public.tombola_cart_items%rowtype;
begin
  if v_user_id is null then
    raise exception using message = 'not_authenticated';
  end if;

  if length(trim(coalesce(p_customer_name, ''))) < 3 then
    raise exception using message = 'invalid_name';
  end if;

  select * into v_round
  from public.tombola_rounds
  where archived_at is null
  limit 1;

  if not found then
    raise exception using message = 'round_not_found';
  end if;

  if v_round.status <> 'open' then
    raise exception using message = 'round_closed';
  end if;

  insert into public.tombola_cart_items (
    user_id,
    round_id,
    customer_name,
    quantity,
    unit_price,
    updated_at
  ) values (
    v_user_id,
    v_round.id,
    trim(p_customer_name),
    v_quantity,
    v_round.ticket_price,
    now()
  )
  on conflict (user_id, round_id) do update
  set customer_name = excluded.customer_name,
      quantity = least(100, public.tombola_cart_items.quantity + excluded.quantity),
      unit_price = excluded.unit_price,
      updated_at = now()
  returning * into v_cart;

  return jsonb_build_object(
    'id', v_cart.id,
    'quantity', v_cart.quantity,
    'unit_price', v_cart.unit_price,
    'total', v_cart.quantity * v_cart.unit_price
  );
end;
$$;

create or replace function public.checkout_tombola_cart()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_cart public.tombola_cart_items%rowtype;
  v_round public.tombola_rounds%rowtype;
  v_purchase_id bigint;
  v_order_number text;
  v_total numeric(14,2);
  v_ticket_number integer;
  v_attempts integer;
  v_ticket_numbers jsonb := '[]'::jsonb;
  v_index integer;
begin
  if v_user_id is null then
    raise exception using message = 'not_authenticated';
  end if;

  select * into v_cart
  from public.tombola_cart_items
  where user_id = v_user_id
  order by updated_at desc
  limit 1
  for update;

  if not found then
    raise exception using message = 'empty_cart';
  end if;

  select * into v_round
  from public.tombola_rounds
  where id = v_cart.round_id
    and archived_at is null
  for update;

  if not found or v_round.status <> 'open' then
    raise exception using message = 'round_closed';
  end if;

  v_total := v_round.ticket_price * v_cart.quantity;
  v_order_number := 'TMB-' || to_char(clock_timestamp(), 'YYYYMMDD') || '-' || upper(substr(md5(random()::text || clock_timestamp()::text || v_user_id::text), 1, 6));

  insert into public.tombola_purchases (
    round_id,
    user_id,
    order_number,
    customer_name,
    quantity,
    unit_price,
    total
  ) values (
    v_round.id,
    v_user_id,
    v_order_number,
    v_cart.customer_name,
    v_cart.quantity,
    v_round.ticket_price,
    v_total
  ) returning id into v_purchase_id;

  for v_index in 1..v_cart.quantity loop
    v_attempts := 0;
    loop
      v_attempts := v_attempts + 1;
      if v_attempts > 2000 then
        raise exception using message = 'ticket_pool_exhausted';
      end if;

      v_ticket_number := 1 + floor(random() * 99999)::integer;

      begin
        insert into public.tombola_tickets (
          round_id,
          purchase_id,
          user_id,
          customer_name,
          ticket_number
        ) values (
          v_round.id,
          v_purchase_id,
          v_user_id,
          v_cart.customer_name,
          v_ticket_number
        );
        exit;
      exception when unique_violation then
        null;
      end;
    end loop;

    v_ticket_numbers := v_ticket_numbers || jsonb_build_array(v_ticket_number);
  end loop;

  delete from public.tombola_cart_items where id = v_cart.id;

  return jsonb_build_object(
    'purchase_id', v_purchase_id,
    'order_number', v_order_number,
    'quantity', v_cart.quantity,
    'unit_price', v_round.ticket_price,
    'total', v_total,
    'ticket_numbers', v_ticket_numbers
  );
end;
$$;

create or replace function public.update_tombola_settings(
  p_title text,
  p_ticket_price numeric,
  p_status text
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.nostra_tombola_is_manager() then
    raise exception using message = 'forbidden';
  end if;

  if p_status not in ('open', 'closed') then
    raise exception using message = 'invalid_status';
  end if;

  if coalesce(p_ticket_price, -1) < 0 then
    raise exception using message = 'invalid_price';
  end if;

  update public.tombola_rounds
  set title = coalesce(nullif(trim(p_title), ''), 'Tombola Nostra Group'),
      ticket_price = p_ticket_price,
      status = p_status,
      updated_at = now()
  where archived_at is null;
end;
$$;

create or replace function public.draw_tombola(p_winner_count integer)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_round_id bigint;
  v_ticket_count integer;
  v_winner_count integer := greatest(1, least(20, coalesce(p_winner_count, 1)));
  v_result jsonb;
begin
  if not public.nostra_tombola_is_manager() then
    raise exception using message = 'forbidden';
  end if;

  select id into v_round_id
  from public.tombola_rounds
  where archived_at is null
  limit 1
  for update;

  if v_round_id is null then
    raise exception using message = 'round_not_found';
  end if;

  if exists (select 1 from public.tombola_winners where round_id = v_round_id) then
    raise exception using message = 'draw_already_done';
  end if;

  select count(*) into v_ticket_count
  from public.tombola_tickets
  where round_id = v_round_id;

  if v_ticket_count = 0 then
    raise exception using message = 'no_tickets';
  end if;

  if v_winner_count > v_ticket_count then
    raise exception using message = 'too_many_winners';
  end if;

  with randomized as (
    select ticket.id, random() as random_value
    from public.tombola_tickets ticket
    where ticket.round_id = v_round_id
  ),
  chosen as (
    select id, row_number() over (order by random_value)::integer as position
    from randomized
    order by random_value
    limit v_winner_count
  )
  insert into public.tombola_winners (
    round_id,
    ticket_id,
    position,
    ticket_number,
    customer_name
  )
  select
    v_round_id,
    ticket.id,
    chosen.position,
    ticket.ticket_number,
    ticket.customer_name
  from chosen
  join public.tombola_tickets ticket on ticket.id = chosen.id;

  update public.tombola_rounds
  set status = 'drawn', updated_at = now()
  where id = v_round_id;

  select jsonb_agg(jsonb_build_object(
    'position', winner.position,
    'ticket_number', winner.ticket_number,
    'customer_name', winner.customer_name
  ) order by winner.position)
  into v_result
  from public.tombola_winners winner
  where winner.round_id = v_round_id;

  return coalesce(v_result, '[]'::jsonb);
end;
$$;

create or replace function public.reset_tombola()
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_current public.tombola_rounds%rowtype;
  v_new_id bigint;
begin
  if not public.nostra_tombola_is_manager() then
    raise exception using message = 'forbidden';
  end if;

  select * into v_current
  from public.tombola_rounds
  where archived_at is null
  limit 1
  for update;

  if found then
    delete from public.tombola_cart_items where round_id = v_current.id;

    update public.tombola_rounds
    set status = 'archived',
        archived_at = now(),
        updated_at = now()
    where id = v_current.id;
  end if;

  insert into public.tombola_rounds (
    title,
    ticket_price,
    status
  ) values (
    coalesce(v_current.title, 'Tombola Nostra Group'),
    coalesce(v_current.ticket_price, 5000),
    'open'
  ) returning id into v_new_id;

  return v_new_id;
end;
$$;

revoke all on function public.add_tombola_to_cart(text,integer) from public;
revoke all on function public.checkout_tombola_cart() from public;
revoke all on function public.update_tombola_settings(text,numeric,text) from public;
revoke all on function public.draw_tombola(integer) from public;
revoke all on function public.reset_tombola() from public;

grant execute on function public.add_tombola_to_cart(text,integer) to authenticated;
grant execute on function public.checkout_tombola_cart() to authenticated;
grant execute on function public.update_tombola_settings(text,numeric,text) to authenticated;
grant execute on function public.draw_tombola(integer) to authenticated;
grant execute on function public.reset_tombola() to authenticated;

notify pgrst, 'reload schema';
`;
