export const MAIL_SETUP_SQL = String.raw`
-- NOSTRA GROUP V35 — MESSAGERIE INTERNE
-- Réexécutable : conserve les boîtes et les conversations existantes.
--
-- IMPORTANT :
-- Les adresses @nostra.group créées ici sont internes au site.
-- Elles ne communiquent pas directement avec Gmail ou Outlook.

create extension if not exists pgcrypto;

create table if not exists public.nostra_mailboxes (
  id bigint generated by default as identity primary key,
  user_id uuid unique references auth.users(id) on delete cascade,
  address text not null unique,
  display_name text not null,
  mailbox_type text not null default 'citizen',
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint nostra_mailboxes_type_check
    check (mailbox_type in ('citizen', 'team')),
  constraint nostra_mailboxes_address_check
    check (
      address = lower(address)
      and address ~ '^[a-z0-9][a-z0-9._-]*@nostra\.group$'
    )
);

create unique index if not exists nostra_mailboxes_team_unique_idx
  on public.nostra_mailboxes(mailbox_type)
  where mailbox_type = 'team';

create table if not exists public.nostra_mail_messages (
  id bigint generated by default as identity primary key,
  thread_id uuid not null default gen_random_uuid(),
  sender_mailbox_id bigint not null
    references public.nostra_mailboxes(id) on delete restrict,
  recipient_mailbox_id bigint not null
    references public.nostra_mailboxes(id) on delete restrict,
  subject text not null,
  body text not null,
  read_at timestamptz,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  constraint nostra_mail_messages_subject_check
    check (char_length(trim(subject)) between 3 and 180),
  constraint nostra_mail_messages_body_check
    check (char_length(trim(body)) between 2 and 5000),
  constraint nostra_mail_messages_sender_recipient_check
    check (sender_mailbox_id <> recipient_mailbox_id)
);

create index if not exists nostra_mail_messages_thread_idx
  on public.nostra_mail_messages(thread_id, created_at);

create index if not exists nostra_mail_messages_recipient_idx
  on public.nostra_mail_messages(recipient_mailbox_id, read_at, created_at desc);

create index if not exists nostra_mail_messages_sender_idx
  on public.nostra_mail_messages(sender_mailbox_id, created_at desc);

create or replace function public.nostra_mail_is_staff()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select
    coalesce(public.nostra_has_role('manager'), false)
    or coalesce(public.nostra_has_role('employee'), false)
    or coalesce(public.nostra_has_role('commercial'), false);
$$;

revoke all on function public.nostra_mail_is_staff() from public;
grant execute on function public.nostra_mail_is_staff() to authenticated;

create or replace function public.nostra_mail_slug(p_value text)
returns text
language sql
immutable
as $$
  select trim(
    both '.'
    from regexp_replace(
      regexp_replace(
        translate(
          lower(trim(coalesce(p_value, ''))),
          'àáâãäåæçèéêëìíîïñòóôõöœùúûüýÿ',
          'aaaaaaaceeeeiiiinoooooouuuuyy'
        ),
        '[^a-z0-9]+',
        '.',
        'g'
      ),
      '\.{2,}',
      '.',
      'g'
    )
  );
$$;

create or replace function public.nostra_create_mailbox_for_user(
  p_user_id uuid
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_existing_id bigint;
  v_first_name text;
  v_last_name text;
  v_display_name text;
  v_base text;
  v_candidate text;
  v_suffix integer := 1;
  v_id bigint;
begin
  if p_user_id is null then
    return null;
  end if;

  select mailbox.id
    into v_existing_id
  from public.nostra_mailboxes mailbox
  where mailbox.user_id = p_user_id
    and mailbox.mailbox_type = 'citizen'
  limit 1;

  select
    nullif(trim(profile.rp_first_name), ''),
    nullif(trim(profile.rp_last_name), '')
  into
    v_first_name,
    v_last_name
  from public.member_profiles profile
  where profile.user_id = p_user_id
  limit 1;

  v_display_name := nullif(
    trim(concat_ws(' ', v_first_name, v_last_name)),
    ''
  );

  if v_existing_id is not null then
    if v_display_name is not null then
      update public.nostra_mailboxes
      set
        display_name = v_display_name,
        updated_at = now()
      where id = v_existing_id;
    end if;

    return v_existing_id;
  end if;

  if v_display_name is null then
    v_display_name := 'Citoyen Nostra Group';
  end if;

  v_base := trim(
    both '.'
    from concat_ws(
      '.',
      nullif(public.nostra_mail_slug(v_first_name), ''),
      nullif(public.nostra_mail_slug(v_last_name), '')
    )
  );

  if v_base = '' then
    v_base := 'citoyen.' || left(replace(p_user_id::text, '-', ''), 8);
  end if;

  v_candidate := v_base || '@nostra.group';

  while exists (
    select 1
    from public.nostra_mailboxes mailbox
    where mailbox.address = v_candidate
  ) loop
    v_suffix := v_suffix + 1;
    v_candidate := v_base || v_suffix::text || '@nostra.group';
  end loop;

  insert into public.nostra_mailboxes (
    user_id,
    address,
    display_name,
    mailbox_type
  )
  values (
    p_user_id,
    v_candidate,
    v_display_name,
    'citizen'
  )
  returning id into v_id;

  return v_id;
end;
$$;

insert into public.nostra_mailboxes (
  user_id,
  address,
  display_name,
  mailbox_type
)
values (
  null,
  'equipe@nostra.group',
  'Équipe Nostra Group',
  'team'
)
on conflict (address) do update
set
  display_name = excluded.display_name,
  mailbox_type = 'team',
  active = true,
  updated_at = now();

create or replace function public.nostra_sync_member_mailbox()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  perform public.nostra_create_mailbox_for_user(new.user_id);
  return new;
end;
$$;

do $$
begin
  if to_regclass('public.member_profiles') is not null then
    execute 'drop trigger if exists nostra_sync_member_mailbox_trigger
      on public.member_profiles';

    execute 'create trigger nostra_sync_member_mailbox_trigger
      after insert or update of rp_first_name, rp_last_name
      on public.member_profiles
      for each row
      execute function public.nostra_sync_member_mailbox()';
  end if;
end $$;

do $$
declare
  v_user_id uuid;
begin
  if to_regclass('public.member_profiles') is not null then
    for v_user_id in
      select profile.user_id
      from public.member_profiles profile
      where profile.user_id is not null
    loop
      perform public.nostra_create_mailbox_for_user(v_user_id);
    end loop;
  end if;
end $$;

alter table public.nostra_mailboxes enable row level security;
alter table public.nostra_mail_messages enable row level security;

drop policy if exists "mail users read own mailbox"
on public.nostra_mailboxes;

create policy "mail users read own mailbox"
on public.nostra_mailboxes
for select
to authenticated
using (
  user_id = auth.uid()
  or (
    public.nostra_mail_is_staff()
    and mailbox_type in ('citizen', 'team')
  )
);

drop policy if exists "mail users read own messages"
on public.nostra_mail_messages;

create policy "mail users read own messages"
on public.nostra_mail_messages
for select
to authenticated
using (
  exists (
    select 1
    from public.nostra_mailboxes mailbox
    where mailbox.id in (
      nostra_mail_messages.sender_mailbox_id,
      nostra_mail_messages.recipient_mailbox_id
    )
      and mailbox.user_id = auth.uid()
  )
  or (
    public.nostra_mail_is_staff()
    and exists (
      select 1
      from public.nostra_mailboxes mailbox
      where mailbox.id in (
        nostra_mail_messages.sender_mailbox_id,
        nostra_mail_messages.recipient_mailbox_id
      )
        and mailbox.mailbox_type = 'team'
    )
  )
);

drop policy if exists "mail recipients update read state"
on public.nostra_mail_messages;

create policy "mail recipients update read state"
on public.nostra_mail_messages
for update
to authenticated
using (
  exists (
    select 1
    from public.nostra_mailboxes mailbox
    where mailbox.id = nostra_mail_messages.recipient_mailbox_id
      and (
        mailbox.user_id = auth.uid()
        or (
          mailbox.mailbox_type = 'team'
          and public.nostra_mail_is_staff()
        )
      )
  )
)
with check (
  exists (
    select 1
    from public.nostra_mailboxes mailbox
    where mailbox.id = nostra_mail_messages.recipient_mailbox_id
      and (
        mailbox.user_id = auth.uid()
        or (
          mailbox.mailbox_type = 'team'
          and public.nostra_mail_is_staff()
        )
      )
  )
);

revoke insert, delete on public.nostra_mail_messages from authenticated;
grant select, update on public.nostra_mail_messages to authenticated;
grant select on public.nostra_mailboxes to authenticated;

create or replace function public.nostra_get_or_create_my_mailbox()
returns table (
  id bigint,
  address text,
  display_name text,
  mailbox_type text
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_mailbox_id bigint;
begin
  if v_user_id is null then
    raise exception 'not_authenticated';
  end if;

  v_mailbox_id := public.nostra_create_mailbox_for_user(v_user_id);

  return query
  select
    mailbox.id,
    mailbox.address,
    mailbox.display_name,
    mailbox.mailbox_type
  from public.nostra_mailboxes mailbox
  where mailbox.id = v_mailbox_id;
end;
$$;

create or replace function public.nostra_get_unread_mail_count()
returns integer
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_mailbox_id bigint;
  v_count integer;
begin
  if v_user_id is null then
    return 0;
  end if;

  select mailbox.id
    into v_mailbox_id
  from public.nostra_mailboxes mailbox
  where mailbox.user_id = v_user_id
    and mailbox.mailbox_type = 'citizen'
  limit 1;

  if v_mailbox_id is null then
    return 0;
  end if;

  select count(*)::integer
    into v_count
  from public.nostra_mail_messages message
  where message.recipient_mailbox_id = v_mailbox_id
    and message.read_at is null;

  return coalesce(v_count, 0);
end;
$$;

create or replace function public.nostra_get_unread_team_mail_count()
returns integer
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_team_id bigint;
  v_count integer;
begin
  if not public.nostra_mail_is_staff() then
    raise exception 'staff_required';
  end if;

  select mailbox.id
    into v_team_id
  from public.nostra_mailboxes mailbox
  where mailbox.mailbox_type = 'team'
  limit 1;

  select count(*)::integer
    into v_count
  from public.nostra_mail_messages message
  where message.recipient_mailbox_id = v_team_id
    and message.read_at is null;

  return coalesce(v_count, 0);
end;
$$;

create or replace function public.nostra_send_mail_to_team(
  p_subject text,
  p_body text
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_sender_id bigint;
  v_team_id bigint;
  v_thread_id uuid := gen_random_uuid();
begin
  if v_user_id is null then
    raise exception 'not_authenticated';
  end if;

  if char_length(trim(coalesce(p_subject, ''))) not between 3 and 180
    or char_length(trim(coalesce(p_body, ''))) not between 3 and 5000
  then
    raise exception 'invalid_message';
  end if;

  v_sender_id := public.nostra_create_mailbox_for_user(v_user_id);

  select mailbox.id
    into v_team_id
  from public.nostra_mailboxes mailbox
  where mailbox.mailbox_type = 'team'
  limit 1;

  insert into public.nostra_mail_messages (
    thread_id,
    sender_mailbox_id,
    recipient_mailbox_id,
    subject,
    body,
    created_by
  )
  values (
    v_thread_id,
    v_sender_id,
    v_team_id,
    trim(p_subject),
    trim(p_body),
    v_user_id
  );

  return v_thread_id;
end;
$$;

create or replace function public.nostra_send_mail_to_user(
  p_recipient_mailbox_id bigint,
  p_subject text,
  p_body text
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_team_id bigint;
  v_thread_id uuid := gen_random_uuid();
begin
  if not public.nostra_mail_is_staff() then
    raise exception 'staff_required';
  end if;

  if char_length(trim(coalesce(p_subject, ''))) not between 3 and 180
    or char_length(trim(coalesce(p_body, ''))) not between 3 and 5000
  then
    raise exception 'invalid_message';
  end if;

  if not exists (
    select 1
    from public.nostra_mailboxes mailbox
    where mailbox.id = p_recipient_mailbox_id
      and mailbox.mailbox_type = 'citizen'
      and mailbox.active
  ) then
    raise exception 'invalid_recipient';
  end if;

  select mailbox.id
    into v_team_id
  from public.nostra_mailboxes mailbox
  where mailbox.mailbox_type = 'team'
  limit 1;

  insert into public.nostra_mail_messages (
    thread_id,
    sender_mailbox_id,
    recipient_mailbox_id,
    subject,
    body,
    created_by
  )
  values (
    v_thread_id,
    v_team_id,
    p_recipient_mailbox_id,
    trim(p_subject),
    trim(p_body),
    v_user_id
  );

  return v_thread_id;
end;
$$;

create or replace function public.nostra_reply_to_mail(
  p_thread_id uuid,
  p_body text
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_team_id bigint;
  v_own_id bigint;
  v_citizen_id bigint;
  v_subject text;
  v_sender_id bigint;
  v_recipient_id bigint;
  v_message_id bigint;
begin
  if v_user_id is null then
    raise exception 'not_authenticated';
  end if;

  if char_length(trim(coalesce(p_body, ''))) not between 2 and 5000 then
    raise exception 'invalid_message';
  end if;

  select mailbox.id
    into v_team_id
  from public.nostra_mailboxes mailbox
  where mailbox.mailbox_type = 'team'
  limit 1;

  select message.subject
    into v_subject
  from public.nostra_mail_messages message
  where message.thread_id = p_thread_id
  order by message.created_at
  limit 1;

  if v_subject is null then
    raise exception 'thread_not_found';
  end if;

  if public.nostra_mail_is_staff() then
    select mailbox.id
      into v_citizen_id
    from public.nostra_mail_messages message
    join public.nostra_mailboxes mailbox
      on mailbox.id in (
        message.sender_mailbox_id,
        message.recipient_mailbox_id
      )
    where message.thread_id = p_thread_id
      and mailbox.mailbox_type = 'citizen'
    limit 1;

    if v_citizen_id is null then
      raise exception 'invalid_thread';
    end if;

    v_sender_id := v_team_id;
    v_recipient_id := v_citizen_id;
  else
    v_own_id := public.nostra_create_mailbox_for_user(v_user_id);

    if not exists (
      select 1
      from public.nostra_mail_messages message
      where message.thread_id = p_thread_id
        and v_own_id in (
          message.sender_mailbox_id,
          message.recipient_mailbox_id
        )
        and v_team_id in (
          message.sender_mailbox_id,
          message.recipient_mailbox_id
        )
    ) then
      raise exception 'thread_access_denied';
    end if;

    v_sender_id := v_own_id;
    v_recipient_id := v_team_id;
  end if;

  insert into public.nostra_mail_messages (
    thread_id,
    sender_mailbox_id,
    recipient_mailbox_id,
    subject,
    body,
    created_by
  )
  values (
    p_thread_id,
    v_sender_id,
    v_recipient_id,
    v_subject,
    trim(p_body),
    v_user_id
  )
  returning id into v_message_id;

  return v_message_id;
end;
$$;

create or replace function public.nostra_get_my_mail_messages(
  p_folder text default 'inbox'
)
returns table (
  message_id bigint,
  thread_id uuid,
  sender_address text,
  sender_name text,
  recipient_address text,
  recipient_name text,
  subject text,
  body text,
  read_at timestamptz,
  created_at timestamptz,
  direction text
)
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_mailbox_id bigint;
begin
  if v_user_id is null then
    raise exception 'not_authenticated';
  end if;

  select mailbox.id
    into v_mailbox_id
  from public.nostra_mailboxes mailbox
  where mailbox.user_id = v_user_id
    and mailbox.mailbox_type = 'citizen'
  limit 1;

  if v_mailbox_id is null then
    return;
  end if;

  return query
  select distinct on (message.thread_id)
    message.id,
    message.thread_id,
    sender.address,
    sender.display_name,
    recipient.address,
    recipient.display_name,
    message.subject,
    message.body,
    message.read_at,
    message.created_at,
    case
      when message.sender_mailbox_id = v_mailbox_id then 'sent'
      else 'inbox'
    end
  from public.nostra_mail_messages message
  join public.nostra_mailboxes sender
    on sender.id = message.sender_mailbox_id
  join public.nostra_mailboxes recipient
    on recipient.id = message.recipient_mailbox_id
  where (
    lower(coalesce(p_folder, 'inbox')) = 'sent'
    and message.sender_mailbox_id = v_mailbox_id
  )
  or (
    lower(coalesce(p_folder, 'inbox')) <> 'sent'
    and message.recipient_mailbox_id = v_mailbox_id
  )
  order by message.thread_id, message.created_at desc;
end;
$$;

create or replace function public.nostra_get_my_mail_thread(
  p_thread_id uuid
)
returns table (
  message_id bigint,
  thread_id uuid,
  sender_address text,
  sender_name text,
  recipient_address text,
  recipient_name text,
  subject text,
  body text,
  read_at timestamptz,
  created_at timestamptz,
  direction text
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_mailbox_id bigint;
begin
  if v_user_id is null then
    raise exception 'not_authenticated';
  end if;

  select mailbox.id
    into v_mailbox_id
  from public.nostra_mailboxes mailbox
  where mailbox.user_id = v_user_id
    and mailbox.mailbox_type = 'citizen'
  limit 1;

  if not exists (
    select 1
    from public.nostra_mail_messages message
    where message.thread_id = p_thread_id
      and v_mailbox_id in (
        message.sender_mailbox_id,
        message.recipient_mailbox_id
      )
  ) then
    raise exception 'thread_access_denied';
  end if;

  return query
  select
    message.id,
    message.thread_id,
    sender.address,
    sender.display_name,
    recipient.address,
    recipient.display_name,
    message.subject,
    message.body,
    message.read_at,
    message.created_at,
    case
      when message.sender_mailbox_id = v_mailbox_id then 'sent'
      else 'inbox'
    end
  from public.nostra_mail_messages message
  join public.nostra_mailboxes sender
    on sender.id = message.sender_mailbox_id
  join public.nostra_mailboxes recipient
    on recipient.id = message.recipient_mailbox_id
  where message.thread_id = p_thread_id
  order by message.created_at;
end;
$$;

create or replace function public.nostra_get_team_mail_messages(
  p_folder text default 'inbox'
)
returns table (
  message_id bigint,
  thread_id uuid,
  sender_address text,
  sender_name text,
  recipient_address text,
  recipient_name text,
  subject text,
  body text,
  read_at timestamptz,
  created_at timestamptz,
  direction text
)
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_team_id bigint;
begin
  if not public.nostra_mail_is_staff() then
    raise exception 'staff_required';
  end if;

  select mailbox.id
    into v_team_id
  from public.nostra_mailboxes mailbox
  where mailbox.mailbox_type = 'team'
  limit 1;

  return query
  select distinct on (message.thread_id)
    message.id,
    message.thread_id,
    sender.address,
    sender.display_name,
    recipient.address,
    recipient.display_name,
    message.subject,
    message.body,
    message.read_at,
    message.created_at,
    case
      when message.sender_mailbox_id = v_team_id then 'sent'
      else 'inbox'
    end
  from public.nostra_mail_messages message
  join public.nostra_mailboxes sender
    on sender.id = message.sender_mailbox_id
  join public.nostra_mailboxes recipient
    on recipient.id = message.recipient_mailbox_id
  where (
    lower(coalesce(p_folder, 'inbox')) = 'sent'
    and message.sender_mailbox_id = v_team_id
  )
  or (
    lower(coalesce(p_folder, 'inbox')) <> 'sent'
    and message.recipient_mailbox_id = v_team_id
  )
  order by message.thread_id, message.created_at desc;
end;
$$;

create or replace function public.nostra_get_team_mail_thread(
  p_thread_id uuid
)
returns table (
  message_id bigint,
  thread_id uuid,
  sender_address text,
  sender_name text,
  recipient_address text,
  recipient_name text,
  subject text,
  body text,
  read_at timestamptz,
  created_at timestamptz,
  direction text
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_team_id bigint;
begin
  if not public.nostra_mail_is_staff() then
    raise exception 'staff_required';
  end if;

  select mailbox.id
    into v_team_id
  from public.nostra_mailboxes mailbox
  where mailbox.mailbox_type = 'team'
  limit 1;

  if not exists (
    select 1
    from public.nostra_mail_messages message
    where message.thread_id = p_thread_id
      and v_team_id in (
        message.sender_mailbox_id,
        message.recipient_mailbox_id
      )
  ) then
    raise exception 'thread_access_denied';
  end if;

  return query
  select
    message.id,
    message.thread_id,
    sender.address,
    sender.display_name,
    recipient.address,
    recipient.display_name,
    message.subject,
    message.body,
    message.read_at,
    message.created_at,
    case
      when message.sender_mailbox_id = v_team_id then 'sent'
      else 'inbox'
    end
  from public.nostra_mail_messages message
  join public.nostra_mailboxes sender
    on sender.id = message.sender_mailbox_id
  join public.nostra_mailboxes recipient
    on recipient.id = message.recipient_mailbox_id
  where message.thread_id = p_thread_id
  order by message.created_at;
end;
$$;

create or replace function public.nostra_get_citizen_mailboxes_for_team()
returns table (
  mailbox_id bigint,
  user_id uuid,
  address text,
  display_name text
)
language plpgsql
stable
security definer
set search_path = public
as $$
begin
  if not public.nostra_mail_is_staff() then
    raise exception 'staff_required';
  end if;

  return query
  select
    mailbox.id,
    mailbox.user_id,
    mailbox.address,
    mailbox.display_name
  from public.nostra_mailboxes mailbox
  where mailbox.mailbox_type = 'citizen'
    and mailbox.active
  order by mailbox.display_name, mailbox.address;
end;
$$;

create or replace function public.nostra_mark_mail_thread_read(
  p_thread_id uuid
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_mailbox_id bigint;
begin
  select mailbox.id
    into v_mailbox_id
  from public.nostra_mailboxes mailbox
  where mailbox.user_id = auth.uid()
    and mailbox.mailbox_type = 'citizen'
  limit 1;

  update public.nostra_mail_messages
  set read_at = coalesce(read_at, now())
  where thread_id = p_thread_id
    and recipient_mailbox_id = v_mailbox_id;
end;
$$;

create or replace function public.nostra_mark_team_mail_thread_read(
  p_thread_id uuid
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_team_id bigint;
begin
  if not public.nostra_mail_is_staff() then
    raise exception 'staff_required';
  end if;

  select mailbox.id
    into v_team_id
  from public.nostra_mailboxes mailbox
  where mailbox.mailbox_type = 'team'
  limit 1;

  update public.nostra_mail_messages
  set read_at = coalesce(read_at, now())
  where thread_id = p_thread_id
    and recipient_mailbox_id = v_team_id;
end;
$$;

revoke all on function public.nostra_get_or_create_my_mailbox() from public;
revoke all on function public.nostra_get_unread_mail_count() from public;
revoke all on function public.nostra_get_unread_team_mail_count() from public;
revoke all on function public.nostra_send_mail_to_team(text,text) from public;
revoke all on function public.nostra_send_mail_to_user(bigint,text,text) from public;
revoke all on function public.nostra_reply_to_mail(uuid,text) from public;
revoke all on function public.nostra_get_my_mail_messages(text) from public;
revoke all on function public.nostra_get_my_mail_thread(uuid) from public;
revoke all on function public.nostra_get_team_mail_messages(text) from public;
revoke all on function public.nostra_get_team_mail_thread(uuid) from public;
revoke all on function public.nostra_get_citizen_mailboxes_for_team() from public;
revoke all on function public.nostra_mark_mail_thread_read(uuid) from public;
revoke all on function public.nostra_mark_team_mail_thread_read(uuid) from public;

grant execute on function public.nostra_get_or_create_my_mailbox() to authenticated;
grant execute on function public.nostra_get_unread_mail_count() to authenticated;
grant execute on function public.nostra_get_unread_team_mail_count() to authenticated;
grant execute on function public.nostra_send_mail_to_team(text,text) to authenticated;
grant execute on function public.nostra_send_mail_to_user(bigint,text,text) to authenticated;
grant execute on function public.nostra_reply_to_mail(uuid,text) to authenticated;
grant execute on function public.nostra_get_my_mail_messages(text) to authenticated;
grant execute on function public.nostra_get_my_mail_thread(uuid) to authenticated;
grant execute on function public.nostra_get_team_mail_messages(text) to authenticated;
grant execute on function public.nostra_get_team_mail_thread(uuid) to authenticated;
grant execute on function public.nostra_get_citizen_mailboxes_for_team() to authenticated;
grant execute on function public.nostra_mark_mail_thread_read(uuid) to authenticated;
grant execute on function public.nostra_mark_team_mail_thread_read(uuid) to authenticated;

-- Ajout du type "mail" au centre de notifications V34, s'il est déjà installé.
do $$
begin
  if to_regclass('public.user_notifications') is not null then
    alter table public.user_notifications
      drop constraint if exists user_notifications_type_check;

    alter table public.user_notifications
      add constraint user_notifications_type_check
      check (
        notification_type in (
          'order',
          'event',
          'championship',
          'homologation',
          'team',
          'reservation',
          'invoice',
          'loyalty',
          'general',
          'mail'
        )
      );
  end if;
end $$;

create or replace function public.nostra_notify_new_internal_mail()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_recipient public.nostra_mailboxes%rowtype;
  v_sender public.nostra_mailboxes%rowtype;
  v_target text;
begin
  select * into v_recipient
  from public.nostra_mailboxes
  where id = new.recipient_mailbox_id;

  select * into v_sender
  from public.nostra_mailboxes
  where id = new.sender_mailbox_id;

  if to_regclass('public.user_notifications') is null then
    return new;
  end if;

  if v_recipient.mailbox_type = 'citizen'
    and v_recipient.user_id is not null
  then
    v_target := '/profil/messagerie?thread=' || new.thread_id::text;

    execute '
      insert into public.user_notifications (
        user_id,
        notification_type,
        title,
        message,
        target_url,
        source_type,
        source_id
      )
      values ($1, ''mail'', $2, $3, $4, ''mail'', $5)'
    using
      v_recipient.user_id,
      'Nouveau message Nostra Group',
      v_sender.display_name || ' t’a envoyé un message : « ' || new.subject || ' ».',
      v_target,
      new.id::text;
  elsif v_recipient.mailbox_type = 'team' then
    execute '
      insert into public.user_notifications (
        user_id,
        notification_type,
        title,
        message,
        target_url,
        source_type,
        source_id
      )
      select
        profile.user_id,
        ''mail'',
        ''Nouveau message citoyen'',
        $1,
        $2,
        ''mail'',
        $3
      from public.member_profiles profile
      where profile.user_id is not null
        and (
          lower(coalesce(profile.role, '''')) in (
            ''manager'',
            ''employee'',
            ''commercial''
          )
          or coalesce(profile.roles, array[]::text[])
            && array[''manager'', ''employee'', ''commercial'']::text[]
        )'
    using
      v_sender.display_name || ' a écrit à l’équipe : « ' || new.subject || ' ».',
      '/dashboard/messagerie?thread=' || new.thread_id::text,
      new.id::text;
  end if;

  return new;
end;
$$;

drop trigger if exists nostra_notify_new_internal_mail_trigger
on public.nostra_mail_messages;

create trigger nostra_notify_new_internal_mail_trigger
after insert
on public.nostra_mail_messages
for each row
execute function public.nostra_notify_new_internal_mail();

notify pgrst, 'reload schema';

`;
