export const SPECIAL_RANKINGS_SETUP_SQL = String.raw`
-- NOSTRA GROUP V38 — CLASSEMENTS SPÉCIAUX DU CIRCUIT
-- Classement événements, chrono contre la montre et records du tour.
-- Réexécutable : conserve les résultats déjà enregistrés.

create table if not exists public.circuit_event_scores (
  id bigint generated by default as identity primary key,
  event_name text not null,
  event_date date not null,
  driver_name text not null,
  team_name text not null,
  finishing_position integer not null,
  points integer not null default 0,
  note text,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  constraint circuit_event_scores_position_check
    check (finishing_position >= 1),
  constraint circuit_event_scores_points_check
    check (points >= 0)
);

create index if not exists circuit_event_scores_driver_idx
  on public.circuit_event_scores(driver_name, event_date desc);

create table if not exists public.circuit_time_trials (
  id bigint generated by default as identity primary key,
  course_name text not null,
  driver_name text not null,
  team_name text not null,
  vehicle_name text not null,
  time_ms bigint not null,
  attempt_date date not null,
  note text,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  constraint circuit_time_trials_time_check
    check (time_ms >= 500)
);

create index if not exists circuit_time_trials_course_time_idx
  on public.circuit_time_trials(course_name, time_ms);

create table if not exists public.circuit_lap_records (
  id bigint generated by default as identity primary key,
  circuit_layout text not null,
  driver_name text not null,
  team_name text not null,
  vehicle_name text not null,
  lap_time_ms bigint not null,
  record_date date not null,
  note text,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  constraint circuit_lap_records_time_check
    check (lap_time_ms >= 500)
);

create index if not exists circuit_lap_records_layout_time_idx
  on public.circuit_lap_records(circuit_layout, lap_time_ms);

create or replace function public.nostra_special_rankings_is_commissioner()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select
    coalesce(public.nostra_has_role('manager'), false)
    or coalesce(public.nostra_has_role('commissioner'), false);
$$;

revoke all on function public.nostra_special_rankings_is_commissioner()
from public;

grant execute on function public.nostra_special_rankings_is_commissioner()
to authenticated;

create or replace function public.nostra_add_event_ranking_result(
  p_event_name text,
  p_event_date date,
  p_driver_name text,
  p_team_name text,
  p_finishing_position integer,
  p_points integer,
  p_note text default null
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_id bigint;
begin
  if not public.nostra_special_rankings_is_commissioner() then
    raise exception 'commissioner_required';
  end if;

  if nullif(trim(coalesce(p_event_name, '')), '') is null
    or p_event_date is null
    or nullif(trim(coalesce(p_driver_name, '')), '') is null
    or nullif(trim(coalesce(p_team_name, '')), '') is null
    or p_finishing_position < 1
    or p_points < 0
  then
    raise exception 'invalid_result';
  end if;

  insert into public.circuit_event_scores (
    event_name,
    event_date,
    driver_name,
    team_name,
    finishing_position,
    points,
    note,
    created_by
  )
  values (
    left(trim(p_event_name), 160),
    p_event_date,
    left(trim(p_driver_name), 120),
    left(trim(p_team_name), 120),
    p_finishing_position,
    p_points,
    nullif(left(trim(coalesce(p_note, '')), 500), ''),
    auth.uid()
  )
  returning id into v_id;

  return v_id;
end;
$$;

create or replace function public.nostra_add_time_trial_result(
  p_course_name text,
  p_driver_name text,
  p_team_name text,
  p_vehicle_name text,
  p_time_ms bigint,
  p_attempt_date date,
  p_note text default null
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_id bigint;
begin
  if not public.nostra_special_rankings_is_commissioner() then
    raise exception 'commissioner_required';
  end if;

  if nullif(trim(coalesce(p_course_name, '')), '') is null
    or nullif(trim(coalesce(p_driver_name, '')), '') is null
    or nullif(trim(coalesce(p_team_name, '')), '') is null
    or nullif(trim(coalesce(p_vehicle_name, '')), '') is null
    or p_time_ms < 500
    or p_attempt_date is null
  then
    raise exception 'invalid_result';
  end if;

  insert into public.circuit_time_trials (
    course_name,
    driver_name,
    team_name,
    vehicle_name,
    time_ms,
    attempt_date,
    note,
    created_by
  )
  values (
    left(trim(p_course_name), 160),
    left(trim(p_driver_name), 120),
    left(trim(p_team_name), 120),
    left(trim(p_vehicle_name), 160),
    p_time_ms,
    p_attempt_date,
    nullif(left(trim(coalesce(p_note, '')), 500), ''),
    auth.uid()
  )
  returning id into v_id;

  return v_id;
end;
$$;

create or replace function public.nostra_add_circuit_lap_record(
  p_circuit_layout text,
  p_driver_name text,
  p_team_name text,
  p_vehicle_name text,
  p_lap_time_ms bigint,
  p_record_date date,
  p_note text default null
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_id bigint;
begin
  if not public.nostra_special_rankings_is_commissioner() then
    raise exception 'commissioner_required';
  end if;

  if nullif(trim(coalesce(p_circuit_layout, '')), '') is null
    or nullif(trim(coalesce(p_driver_name, '')), '') is null
    or nullif(trim(coalesce(p_team_name, '')), '') is null
    or nullif(trim(coalesce(p_vehicle_name, '')), '') is null
    or p_lap_time_ms < 500
    or p_record_date is null
  then
    raise exception 'invalid_result';
  end if;

  insert into public.circuit_lap_records (
    circuit_layout,
    driver_name,
    team_name,
    vehicle_name,
    lap_time_ms,
    record_date,
    note,
    created_by
  )
  values (
    left(trim(p_circuit_layout), 160),
    left(trim(p_driver_name), 120),
    left(trim(p_team_name), 120),
    left(trim(p_vehicle_name), 160),
    p_lap_time_ms,
    p_record_date,
    nullif(left(trim(coalesce(p_note, '')), 500), ''),
    auth.uid()
  )
  returning id into v_id;

  return v_id;
end;
$$;

create or replace function public.nostra_delete_special_ranking_entry(
  p_record_type text,
  p_record_id bigint
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.nostra_special_rankings_is_commissioner() then
    raise exception 'commissioner_required';
  end if;

  if p_record_type = 'event' then
    delete from public.circuit_event_scores where id = p_record_id;
  elsif p_record_type = 'time_trial' then
    delete from public.circuit_time_trials where id = p_record_id;
  elsif p_record_type = 'lap_record' then
    delete from public.circuit_lap_records where id = p_record_id;
  else
    raise exception 'invalid_record_type';
  end if;
end;
$$;

create or replace function public.nostra_reset_special_rankings(
  p_scope text
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.nostra_special_rankings_is_commissioner() then
    raise exception 'commissioner_required';
  end if;

  if p_scope in ('event', 'all') then
    delete from public.circuit_event_scores;
  end if;

  if p_scope in ('time_trial', 'all') then
    delete from public.circuit_time_trials;
  end if;

  if p_scope in ('lap_record', 'all') then
    delete from public.circuit_lap_records;
  end if;

  if p_scope not in ('event', 'time_trial', 'lap_record', 'all') then
    raise exception 'invalid_scope';
  end if;
end;
$$;

create or replace function public.nostra_get_public_event_standings()
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
begin
  if auth.uid() is null then
    raise exception 'not_authenticated';
  end if;

  return coalesce((
    select jsonb_agg(
      jsonb_build_object(
        'position', standing.position,
        'driver_name', standing.driver_name,
        'teams', standing.teams,
        'points', standing.points,
        'events', standing.events,
        'wins', standing.wins,
        'podiums', standing.podiums
      )
      order by standing.position
    )
    from (
      select
        row_number() over (
          order by
            sum(score.points) desc,
            count(*) filter (where score.finishing_position = 1) desc,
            count(*) filter (where score.finishing_position between 1 and 3) desc,
            score.driver_name
        )::integer as position,
        score.driver_name,
        string_agg(
          distinct score.team_name,
          ', '
          order by score.team_name
        ) as teams,
        sum(score.points)::integer as points,
        count(distinct score.event_name || score.event_date::text)::integer
          as events,
        count(*) filter (
          where score.finishing_position = 1
        )::integer as wins,
        count(*) filter (
          where score.finishing_position between 1 and 3
        )::integer as podiums
      from public.circuit_event_scores score
      group by score.driver_name
    ) standing
  ), '[]'::jsonb);
end;
$$;

create or replace function public.nostra_get_public_time_trial_rankings()
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
begin
  if auth.uid() is null then
    raise exception 'not_authenticated';
  end if;

  return coalesce((
    select jsonb_agg(
      jsonb_build_object(
        'id', ranked.id,
        'rank', ranked.rank,
        'course_name', ranked.course_name,
        'driver_name', ranked.driver_name,
        'team_name', ranked.team_name,
        'vehicle_name', ranked.vehicle_name,
        'time_ms', ranked.time_ms,
        'attempt_date', ranked.attempt_date,
        'note', ranked.note,
        'created_at', ranked.created_at
      )
      order by ranked.course_name, ranked.rank, ranked.attempt_date
    )
    from (
      select
        trial.*,
        dense_rank() over (
          partition by trial.course_name
          order by trial.time_ms, trial.attempt_date, trial.id
        )::integer as rank
      from public.circuit_time_trials trial
    ) ranked
  ), '[]'::jsonb);
end;
$$;

create or replace function public.nostra_get_public_circuit_lap_records()
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
begin
  if auth.uid() is null then
    raise exception 'not_authenticated';
  end if;

  return coalesce((
    select jsonb_agg(
      jsonb_build_object(
        'id', ranked.id,
        'rank', ranked.rank,
        'circuit_layout', ranked.circuit_layout,
        'driver_name', ranked.driver_name,
        'team_name', ranked.team_name,
        'vehicle_name', ranked.vehicle_name,
        'lap_time_ms', ranked.lap_time_ms,
        'record_date', ranked.record_date,
        'note', ranked.note,
        'created_at', ranked.created_at
      )
      order by ranked.circuit_layout, ranked.rank, ranked.record_date
    )
    from (
      select
        record.*,
        dense_rank() over (
          partition by record.circuit_layout
          order by record.lap_time_ms, record.record_date, record.id
        )::integer as rank
      from public.circuit_lap_records record
    ) ranked
  ), '[]'::jsonb);
end;
$$;

create or replace function public.nostra_get_special_rankings_dashboard_state()
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
begin
  if not public.nostra_special_rankings_is_commissioner() then
    raise exception 'commissioner_required';
  end if;

  return jsonb_build_object(
    'configured', true,
    'event_scores', coalesce((
      select jsonb_agg(
        to_jsonb(score)
        order by score.event_date desc, score.event_name, score.finishing_position
      )
      from (
        select
          id,
          event_name,
          event_date,
          driver_name,
          team_name,
          finishing_position,
          points,
          note,
          created_at
        from public.circuit_event_scores
        order by event_date desc, event_name, finishing_position
        limit 200
      ) score
    ), '[]'::jsonb),
    'time_trials', coalesce((
      select jsonb_agg(
        jsonb_build_object(
          'id', ranked.id,
          'rank', ranked.rank,
          'course_name', ranked.course_name,
          'driver_name', ranked.driver_name,
          'team_name', ranked.team_name,
          'vehicle_name', ranked.vehicle_name,
          'time_ms', ranked.time_ms,
          'attempt_date', ranked.attempt_date,
          'note', ranked.note,
          'created_at', ranked.created_at
        )
        order by ranked.course_name, ranked.rank
      )
      from (
        select
          trial.*,
          dense_rank() over (
            partition by trial.course_name
            order by trial.time_ms, trial.attempt_date, trial.id
          )::integer as rank
        from public.circuit_time_trials trial
        order by trial.course_name, trial.time_ms
        limit 200
      ) ranked
    ), '[]'::jsonb),
    'lap_records', coalesce((
      select jsonb_agg(
        jsonb_build_object(
          'id', ranked.id,
          'rank', ranked.rank,
          'circuit_layout', ranked.circuit_layout,
          'driver_name', ranked.driver_name,
          'team_name', ranked.team_name,
          'vehicle_name', ranked.vehicle_name,
          'lap_time_ms', ranked.lap_time_ms,
          'record_date', ranked.record_date,
          'note', ranked.note,
          'created_at', ranked.created_at
        )
        order by ranked.circuit_layout, ranked.rank
      )
      from (
        select
          record.*,
          dense_rank() over (
            partition by record.circuit_layout
            order by record.lap_time_ms, record.record_date, record.id
          )::integer as rank
        from public.circuit_lap_records record
        order by record.circuit_layout, record.lap_time_ms
        limit 200
      ) ranked
    ), '[]'::jsonb)
  );
end;
$$;

alter table public.circuit_event_scores enable row level security;
alter table public.circuit_time_trials enable row level security;
alter table public.circuit_lap_records enable row level security;

drop policy if exists "special rankings authenticated read event scores"
on public.circuit_event_scores;

create policy "special rankings authenticated read event scores"
on public.circuit_event_scores
for select
to authenticated
using (true);

drop policy if exists "special rankings authenticated read time trials"
on public.circuit_time_trials;

create policy "special rankings authenticated read time trials"
on public.circuit_time_trials
for select
to authenticated
using (true);

drop policy if exists "special rankings authenticated read lap records"
on public.circuit_lap_records;

create policy "special rankings authenticated read lap records"
on public.circuit_lap_records
for select
to authenticated
using (true);

grant select on public.circuit_event_scores to authenticated;
grant select on public.circuit_time_trials to authenticated;
grant select on public.circuit_lap_records to authenticated;

revoke all on function public.nostra_add_event_ranking_result(
  text,
  date,
  text,
  text,
  integer,
  integer,
  text
) from public;

revoke all on function public.nostra_add_time_trial_result(
  text,
  text,
  text,
  text,
  bigint,
  date,
  text
) from public;

revoke all on function public.nostra_add_circuit_lap_record(
  text,
  text,
  text,
  text,
  bigint,
  date,
  text
) from public;

revoke all on function public.nostra_delete_special_ranking_entry(
  text,
  bigint
) from public;

revoke all on function public.nostra_reset_special_rankings(text)
from public;

revoke all on function public.nostra_get_public_event_standings()
from public;

revoke all on function public.nostra_get_public_time_trial_rankings()
from public;

revoke all on function public.nostra_get_public_circuit_lap_records()
from public;

revoke all on function public.nostra_get_special_rankings_dashboard_state()
from public;

grant execute on function public.nostra_add_event_ranking_result(
  text,
  date,
  text,
  text,
  integer,
  integer,
  text
) to authenticated;

grant execute on function public.nostra_add_time_trial_result(
  text,
  text,
  text,
  text,
  bigint,
  date,
  text
) to authenticated;

grant execute on function public.nostra_add_circuit_lap_record(
  text,
  text,
  text,
  text,
  bigint,
  date,
  text
) to authenticated;

grant execute on function public.nostra_delete_special_ranking_entry(
  text,
  bigint
) to authenticated;

grant execute on function public.nostra_reset_special_rankings(text)
to authenticated;

grant execute on function public.nostra_get_public_event_standings()
to authenticated;

grant execute on function public.nostra_get_public_time_trial_rankings()
to authenticated;

grant execute on function public.nostra_get_public_circuit_lap_records()
to authenticated;

grant execute on function public.nostra_get_special_rankings_dashboard_state()
to authenticated;

notify pgrst, 'reload schema';

`;
