import { createPromoCodeV153, deletePromoCodeV153, updatePromoCodeV153 } from "@/app/actions/v153";
import { DashboardHeader } from "@/components/dashboard/dashboard-header";
import { DashboardShell } from "@/components/dashboard/dashboard-shell";
import { getPromoCodesV153 } from "@/lib/v153/data";
import styles from "@/components/v153/v153.module.css";
export const dynamic="force-dynamic";
function dt(v:string|null){return v?new Date(v).toISOString().slice(0,16):""}
export default async function PromoPage({searchParams}:{searchParams:Promise<Record<string,string|undefined>>}){const [codes,p]=await Promise.all([getPromoCodesV153(),searchParams]);return <DashboardShell><DashboardHeader title="Codes promotionnels" description="Créer des codes pour Nostra Motors, la billetterie, Nostra Cercle ou tout Nostra Group." />
{p.created&&<p className={styles.feedback}>Code créé.</p>}{p.saved&&<p className={styles.feedback}>Code mis à jour.</p>}{p.deleted&&<p className={styles.feedback}>Code supprimé.</p>}{p.error&&<p className={`${styles.feedback} ${styles.error}`}>Action impossible : {p.error}</p>}
<section className={styles.card}><h2>Nouveau code</h2><form action={createPromoCodeV153} className={styles.form}><label>Code<input name="code" required placeholder="NOSTRA10" /></label><label>Nom interne<input name="label" required placeholder="Offre lancement" /></label><label>Utilisation<select name="scope" defaultValue="global"><option value="global">Tout le groupe</option><option value="motors">Nostra Motors</option><option value="ticketing">Billetterie</option><option value="cercle">Nostra Cercle</option></select></label><label>Type<select name="discount_type" defaultValue="percent"><option value="percent">Pourcentage</option><option value="fixed">Montant fixe</option></select></label><label>Valeur<input name="discount_value" type="number" min="0.01" step="0.01" required /></label><label>Montant minimum<input name="min_amount" type="number" min="0" defaultValue="0" /></label><label>Plafond de remise<input name="max_discount" type="number" min="0" placeholder="Vide = sans plafond" /></label><label>Utilisations totales<input name="max_uses" type="number" min="1" placeholder="Vide = illimité" /></label><label>Utilisations / citoyen<input name="max_uses_per_user" type="number" min="1" defaultValue="1" /></label><label>Début<input name="starts_at" type="datetime-local" /></label><label>Fin<input name="ends_at" type="datetime-local" /></label><div className={styles.full}><button className={styles.button} type="submit">Créer le code</button></div></form></section>
<section className={styles.stack} style={{marginTop:16}}>{codes.length===0&&<article className={styles.card}>Aucun code promotionnel.</article>}{codes.map(c=><article className={styles.card} key={c.id}><div className={styles.row}><div><span className={styles.eyebrow}>{c.scope.toUpperCase()}</span><h2>{c.code} · {c.label}</h2><p>{c.discountType==="percent"?`${c.discountValue}%`:`${c.discountValue.toLocaleString("fr-FR")} €`} · {c.uses} utilisation(s)</p></div><span className={styles.pill}>{c.enabled?"ACTIF":"DÉSACTIVÉ"}</span></div><form action={updatePromoCodeV153} className={styles.form}><input type="hidden" name="id" value={c.id}/><label>Nom<input name="label" defaultValue={c.label}/></label><label>Portée<select name="scope" defaultValue={c.scope}><option value="global">Groupe</option><option value="motors">Motors</option><option value="ticketing">Billetterie</option><option value="cercle">Cercle</option></select></label><label>Type<select name="discount_type" defaultValue={c.discountType}><option value="percent">Pourcentage</option><option value="fixed">Montant fixe</option></select></label><label>Valeur<input name="discount_value" type="number" step="0.01" defaultValue={c.discountValue}/></label><label>Minimum<input name="min_amount" type="number" defaultValue={c.minAmount}/></label><label>Plafond<input name="max_discount" type="number" defaultValue={c.maxDiscount??""}/></label><label>Max total<input name="max_uses" type="number" defaultValue={c.maxUses??""}/></label><label>Max / citoyen<input name="max_uses_per_user" type="number" defaultValue={c.maxUsesPerUser}/></label><label>Début<input name="starts_at" type="datetime-local" defaultValue={dt(c.startsAt)}/></label><label>Fin<input name="ends_at" type="datetime-local" defaultValue={dt(c.endsAt)}/></label><label><span>Actif</span><input name="enabled" type="checkbox" defaultChecked={c.enabled}/></label><div className={styles.actions}><button className={styles.button} type="submit">Enregistrer</button></div></form><form action={deletePromoCodeV153} style={{marginTop:12}}><input type="hidden" name="id" value={c.id}/><button className={styles.danger} type="submit">Supprimer ce code</button></form></article>)}</section>
</DashboardShell>}
