import { DashboardHeader } from "@/components/dashboard/dashboard-header";
import { DashboardShell } from "@/components/dashboard/dashboard-shell";
import { deleteMysteryEventV156, saveMysteryEventV156 } from "@/app/actions/v156";
import { getMysteryEventsV156 } from "@/lib/v156/data";
import styles from "@/components/v156/v156.module.css";

function dateInput(value?: string) { if (!value) return ""; const d=new Date(value); if(Number.isNaN(d.getTime())) return ""; const local=new Date(d.getTime()-d.getTimezoneOffset()*60000); return local.toISOString().slice(0,16); }

export default async function MysteryDashboard() {
  const rows = await getMysteryEventsV156(true);
  return <DashboardShell allowedRoles={["manager"]}><DashboardHeader title="Événement mystère" description="Créer un teaser qui se révèle automatiquement à la date et l’heure choisies."/><main className={styles.page} style={{paddingTop:10}}><section className={styles.card}><span className={styles.eyebrow}>NOUVEAU MYSTÈRE</span><h2>Préparer la révélation</h2><form action={saveMysteryEventV156} className={styles.formGrid}><label>Titre avant révélation<input className={styles.input} name="teaser_title" required placeholder="Quelque chose arrive chez Nostra…"/></label><label>Date de révélation<input className={styles.input} name="reveal_at" type="datetime-local" required/></label><label className={styles.full}>Texte teaser<textarea className={styles.textarea} name="teaser_text"/></label><label>Titre après révélation<input className={styles.input} name="revealed_title"/></label><label>Lien après révélation<input className={styles.input} name="target_url" placeholder="/evenements/..."/></label><label className={styles.full}>Contenu révélé<textarea className={styles.textarea} name="revealed_text"/></label><label><input type="checkbox" name="enabled" defaultChecked/> Visible</label><button className={`${styles.button} ${styles.full}`}>Créer l’événement mystère</button></form></section><section className={styles.sectionTitle}><span className={styles.eyebrow}>PROGRAMMATION</span><h2>Événements mystère</h2></section><div className={styles.grid}>{rows.map(row=><article className={styles.card} key={row.id}><span className={row.revealed?styles.sale:styles.pill}>{row.revealed?"RÉVÉLÉ":"SECRET"}</span><h3>{row.teaserTitle}</h3><p>Révélation : {new Date(row.revealAt).toLocaleString("fr-FR")}</p><form action={saveMysteryEventV156} className={styles.formGrid}><input type="hidden" name="id" value={row.id}/><label>Titre teaser<input className={styles.input} name="teaser_title" defaultValue={row.teaserTitle}/></label><label>Révélation<input className={styles.input} type="datetime-local" name="reveal_at" defaultValue={dateInput(row.revealAt)}/></label><label className={styles.full}>Teaser<textarea className={styles.textarea} name="teaser_text" defaultValue={row.teaserText}/></label><label>Titre révélé<input className={styles.input} name="revealed_title" defaultValue={row.revealedTitle}/></label><label>Lien<input className={styles.input} name="target_url" defaultValue={row.targetUrl??""}/></label><label className={styles.full}>Contenu révélé<textarea className={styles.textarea} name="revealed_text" defaultValue={row.revealedText}/></label><label><input type="checkbox" name="enabled" defaultChecked={row.enabled}/> Visible</label><button className={styles.button}>Enregistrer</button></form><form action={deleteMysteryEventV156}><input type="hidden" name="id" value={row.id}/><button className={styles.danger}>Supprimer</button></form></article>)}</div></main></DashboardShell>;
}
