export const DEAL_SETUP_SQL = String.raw`
-- NOSTRA GROUP V36 — À PRENDRE OU À LAISSER
-- 24 boîtes, gains personnalisables et appels manuels du banquier.
-- Réexécutable : conserve les anciennes éditions et parties.

create extension if not exists pgcrypto;

create table if not exists public.deal_editions (
  id bigint generated by default as identity primary key,
  title text not null default 'À Prendre ou à Laisser',
  box_count integer not null default 24,
  prize_labels text[] not null,
  status text not null default 'open',
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  closed_at timestamptz,
  constraint deal_editions_box_count_check
    check (box_count = 24),
  constraint deal_editions_prizes_check
    check (cardinality(prize_labels) = 24),
  constraint deal_editions_status_check
    check (status in ('draft', 'open', 'closed', 'archived'))
);

create unique index if not exists deal_one_open_edition_idx
  on public.deal_editions((status))
  where status = 'open';

create table if not exists public.deal_sessions (
  id uuid primary key default gen_random_uuid(),
  edition_id bigint not null
    references public.deal_editions(id) on delete cascade,
  user_id uuid not null
    references auth.users(id) on delete cascade,
  player_name text not null,
  selected_box integer,
  status text not null default 'choosing',
  banker_offer text,
  final_reward text,
  selected_box_prize text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  completed_at timestamptz,
  constraint deal_sessions_selected_box_check
    check (selected_box is null or selected_box between 1 and 24),
  constraint deal_sessions_status_check
    check (
      status in (
        'choosing',
        'playing',
        'banker_call',
        'accepted',
        'final',
        'stopped'
      )
    ),
  unique (edition_id, user_id)
);

create index if not exists deal_sessions_edition_status_idx
  on public.deal_sessions(edition_id, status, updated_at desc);

create table if not exists public.deal_boxes (
  session_id uuid not null
    references public.deal_sessions(id) on delete cascade,
  box_number integer not null,
  prize_label text not null,
  opened_at timestamptz,
  primary key (session_id, box_number),
  constraint deal_boxes_number_check
    check (box_number between 1 and 24)
);

create table if not exists public.deal_banker_calls (
  id bigint generated by default as identity primary key,
  session_id uuid not null
    references public.deal_sessions(id) on delete cascade,
  offer_text text not null,
  status text not null default 'pending',
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  answered_at timestamptz,
  constraint deal_banker_calls_status_check
    check (status in ('pending', 'accepted', 'declined', 'cancelled'))
);

create unique index if not exists deal_one_pending_banker_call_idx
  on public.deal_banker_calls(session_id)
  where status = 'pending';

create or replace function public.nostra_deal_is_manager()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(public.nostra_has_role('manager'), false);
$$;

revoke all on function public.nostra_deal_is_manager() from public;
grant execute on function public.nostra_deal_is_manager() to authenticated;

create or replace function public.nostra_deal_random_prizes()
returns text[]
language sql
volatile
as $$
  select array_agg(pool.prize)
  from (
    select prize
    from unnest(array[
      '1 café offert',
      'Peinture offerte',
      '5 000 €',
      '10 000 €',
      '15 000 €',
      '25 000 €',
      '50 000 €',
      '75 000 €',
      '100 000 €',
      '150 000 €',
      '200 000 €',
      '250 000 €',
      '300 000 €',
      '400 000 €',
      '500 000 €',
      '650 000 €',
      '750 000 €',
      '1 000 000 €',
      '5 tours de circuit offerts',
      '10 tours de circuit offerts',
      'Essai d’un véhicule de la concession',
      '-5 % sur la prochaine commande',
      '-10 % sur la prochaine commande',
      'Carte fidélité Silver',
      'Livraison à domicile offerte',
      'Révision complète offerte',
      'Véhicule surprise',
      'Accès VIP à un événement',
      'Bon d’achat de 100 000 €',
      'Bon d’achat de 200 000 €',
      'Week-end véhicule prestige',
      'Cadeau mystère Nostra Group'
    ]::text[]) as values_list(prize)
    order by random()
    limit 24
  ) pool;
$$;

create or replace function public.nostra_create_deal_edition(
  p_title text,
  p_prizes text[] default null,
  p_use_random boolean default false
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_prizes text[];
  v_id bigint;
begin
  if not public.nostra_deal_is_manager() then
    raise exception 'manager_required';
  end if;

  if p_use_random then
    v_prizes := public.nostra_deal_random_prizes();
  else
    v_prizes := p_prizes;
  end if;

  if cardinality(v_prizes) <> 24
    or exists (
      select 1
      from unnest(v_prizes) as prize(value)
      where nullif(trim(value), '') is null
    )
  then
    raise exception 'invalid_prizes';
  end if;

  update public.deal_editions
  set
    status = 'closed',
    closed_at = now(),
    updated_at = now()
  where status = 'open';

  update public.deal_sessions
  set
    status = 'stopped',
    completed_at = now(),
    updated_at = now()
  where status in ('choosing', 'playing', 'banker_call');

  update public.deal_banker_calls
  set
    status = 'cancelled',
    answered_at = now()
  where status = 'pending';

  insert into public.deal_editions (
    title,
    box_count,
    prize_labels,
    status,
    created_by
  )
  values (
    coalesce(nullif(trim(p_title), ''), 'À Prendre ou à Laisser'),
    24,
    v_prizes,
    'open',
    auth.uid()
  )
  returning id into v_id;

  return v_id;
end;
$$;

create or replace function public.nostra_start_deal_game()
returns uuid
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  v_user_id uuid := auth.uid();
  v_edition public.deal_editions%rowtype;
  v_session_id uuid;
  v_player_name text;
begin
  if v_user_id is null then
    raise exception 'not_authenticated';
  end if;

  select *
    into v_edition
  from public.deal_editions
  where status = 'open'
  order by created_at desc
  limit 1;

  if v_edition.id is null then
    raise exception 'no_open_edition';
  end if;

  if exists (
    select 1
    from public.deal_sessions session
    where session.edition_id = v_edition.id
      and session.user_id = v_user_id
  ) then
    raise exception 'session_exists';
  end if;

  select nullif(
    trim(concat_ws(' ', profile.rp_first_name, profile.rp_last_name)),
    ''
  )
  into v_player_name
  from public.member_profiles profile
  where profile.user_id = v_user_id
  limit 1;

  if v_player_name is null then
    select nullif(
      trim(
        concat_ws(
          ' ',
          account.raw_user_meta_data ->> 'rp_first_name',
          account.raw_user_meta_data ->> 'rp_last_name'
        )
      ),
      ''
    )
    into v_player_name
    from auth.users account
    where account.id = v_user_id;
  end if;

  v_player_name := coalesce(v_player_name, 'Citoyen Nostra Group');

  insert into public.deal_sessions (
    edition_id,
    user_id,
    player_name,
    status
  )
  values (
    v_edition.id,
    v_user_id,
    v_player_name,
    'choosing'
  )
  returning id into v_session_id;

  insert into public.deal_boxes (
    session_id,
    box_number,
    prize_label
  )
  select
    v_session_id,
    row_number() over ()::integer,
    shuffled.prize
  from (
    select prize
    from unnest(v_edition.prize_labels) as prizes(prize)
    order by random()
  ) shuffled;

  return v_session_id;
end;
$$;

create or replace function public.nostra_choose_deal_box(
  p_box_number integer
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_session public.deal_sessions%rowtype;
begin
  if p_box_number not between 1 and 24 then
    raise exception 'invalid_box';
  end if;

  select session.*
    into v_session
  from public.deal_sessions session
  join public.deal_editions edition
    on edition.id = session.edition_id
  where session.user_id = auth.uid()
    and edition.status = 'open'
  order by session.created_at desc
  limit 1
  for update of session;

  if v_session.id is null then
    raise exception 'session_not_found';
  end if;

  if v_session.status <> 'choosing'
    or v_session.selected_box is not null
  then
    raise exception 'invalid_session_status';
  end if;

  update public.deal_sessions
  set
    selected_box = p_box_number,
    status = 'playing',
    updated_at = now()
  where id = v_session.id;
end;
$$;

create or replace function public.nostra_open_deal_box(
  p_box_number integer
)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  v_session public.deal_sessions%rowtype;
  v_prize text;
  v_remaining integer;
  v_selected_prize text;
begin
  if p_box_number not between 1 and 24 then
    raise exception 'invalid_box';
  end if;

  select session.*
    into v_session
  from public.deal_sessions session
  join public.deal_editions edition
    on edition.id = session.edition_id
  where session.user_id = auth.uid()
    and edition.status = 'open'
  order by session.created_at desc
  limit 1
  for update of session;

  if v_session.id is null then
    raise exception 'session_not_found';
  end if;

  if v_session.status = 'banker_call' then
    raise exception 'banker_call_pending';
  end if;

  if v_session.status <> 'playing' then
    raise exception 'invalid_session_status';
  end if;

  if p_box_number = v_session.selected_box then
    raise exception 'invalid_box';
  end if;

  update public.deal_boxes
  set opened_at = now()
  where session_id = v_session.id
    and box_number = p_box_number
    and opened_at is null
  returning prize_label into v_prize;

  if v_prize is null then
    raise exception 'invalid_box';
  end if;

  select count(*)::integer
    into v_remaining
  from public.deal_boxes box
  where box.session_id = v_session.id
    and box.opened_at is null
    and box.box_number <> v_session.selected_box;

  if v_remaining = 0 then
    select box.prize_label
      into v_selected_prize
    from public.deal_boxes box
    where box.session_id = v_session.id
      and box.box_number = v_session.selected_box;

    update public.deal_sessions
    set
      status = 'final',
      final_reward = v_selected_prize,
      selected_box_prize = v_selected_prize,
      completed_at = now(),
      updated_at = now()
    where id = v_session.id;
  else
    update public.deal_sessions
    set updated_at = now()
    where id = v_session.id;
  end if;

  return v_prize;
end;
$$;

create or replace function public.nostra_trigger_deal_banker_call(
  p_session_id uuid,
  p_offer_text text
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_call_id bigint;
  v_user_id uuid;
begin
  if not public.nostra_deal_is_manager() then
    raise exception 'manager_required';
  end if;

  if char_length(trim(coalesce(p_offer_text, ''))) not between 2 and 500 then
    raise exception 'invalid_offer';
  end if;

  select session.user_id
    into v_user_id
  from public.deal_sessions session
  join public.deal_editions edition
    on edition.id = session.edition_id
  where session.id = p_session_id
    and edition.status = 'open'
    and session.status = 'playing'
  for update of session;

  if v_user_id is null then
    raise exception 'invalid_session_status';
  end if;

  if exists (
    select 1
    from public.deal_banker_calls call
    where call.session_id = p_session_id
      and call.status = 'pending'
  ) then
    raise exception 'banker_call_pending';
  end if;

  insert into public.deal_banker_calls (
    session_id,
    offer_text,
    status,
    created_by
  )
  values (
    p_session_id,
    trim(p_offer_text),
    'pending',
    auth.uid()
  )
  returning id into v_call_id;

  update public.deal_sessions
  set
    status = 'banker_call',
    banker_offer = trim(p_offer_text),
    updated_at = now()
  where id = p_session_id;

  if to_regclass('public.user_notifications') is not null then
    insert into public.user_notifications (
      user_id,
      notification_type,
      title,
      message,
      target_url,
      source_type,
      source_id
    )
    values (
      v_user_id,
      'general',
      'Le banquier vous appelle',
      'Une proposition vous attend dans À Prendre ou à Laisser.',
      '/evenements/a-prendre-ou-a-laisser',
      'deal_banker_call',
      v_call_id::text
    );
  end if;

  return v_call_id;
end;
$$;

create or replace function public.nostra_answer_deal_banker_offer(
  p_decision text
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_session public.deal_sessions%rowtype;
  v_call_id bigint;
  v_offer text;
  v_selected_prize text;
begin
  if lower(coalesce(p_decision, '')) not in ('accept', 'decline') then
    raise exception 'invalid_decision';
  end if;

  select session.*
    into v_session
  from public.deal_sessions session
  join public.deal_editions edition
    on edition.id = session.edition_id
  where session.user_id = auth.uid()
    and edition.status = 'open'
    and session.status = 'banker_call'
  order by session.created_at desc
  limit 1
  for update of session;

  if v_session.id is null then
    raise exception 'invalid_session_status';
  end if;

  select call.id, call.offer_text
    into v_call_id, v_offer
  from public.deal_banker_calls call
  where call.session_id = v_session.id
    and call.status = 'pending'
  order by call.created_at desc
  limit 1
  for update;

  if v_call_id is null then
    raise exception 'banker_call_not_found';
  end if;

  if lower(p_decision) = 'accept' then
    select box.prize_label
      into v_selected_prize
    from public.deal_boxes box
    where box.session_id = v_session.id
      and box.box_number = v_session.selected_box;

    update public.deal_banker_calls
    set
      status = 'accepted',
      answered_at = now()
    where id = v_call_id;

    update public.deal_sessions
    set
      status = 'accepted',
      final_reward = v_offer,
      selected_box_prize = v_selected_prize,
      completed_at = now(),
      updated_at = now()
    where id = v_session.id;
  else
    update public.deal_banker_calls
    set
      status = 'declined',
      answered_at = now()
    where id = v_call_id;

    update public.deal_sessions
    set
      status = 'playing',
      banker_offer = null,
      updated_at = now()
    where id = v_session.id;
  end if;
end;
$$;

create or replace function public.nostra_stop_deal_session(
  p_session_id uuid
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.nostra_deal_is_manager() then
    raise exception 'manager_required';
  end if;

  update public.deal_banker_calls
  set
    status = 'cancelled',
    answered_at = now()
  where session_id = p_session_id
    and status = 'pending';

  update public.deal_sessions
  set
    status = 'stopped',
    completed_at = now(),
    updated_at = now()
  where id = p_session_id
    and status in ('choosing', 'playing', 'banker_call');
end;
$$;

create or replace function public.nostra_close_deal_edition()
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.nostra_deal_is_manager() then
    raise exception 'manager_required';
  end if;

  update public.deal_banker_calls
  set
    status = 'cancelled',
    answered_at = now()
  where status = 'pending';

  update public.deal_sessions
  set
    status = 'stopped',
    completed_at = now(),
    updated_at = now()
  where status in ('choosing', 'playing', 'banker_call');

  update public.deal_editions
  set
    status = 'closed',
    closed_at = now(),
    updated_at = now()
  where status = 'open';
end;
$$;

create or replace function public.nostra_get_deal_public_state()
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_edition public.deal_editions%rowtype;
  v_session public.deal_sessions%rowtype;
  v_session_json jsonb;
begin
  if v_user_id is null then
    raise exception 'not_authenticated';
  end if;

  select *
    into v_edition
  from public.deal_editions
  where status = 'open'
  order by created_at desc
  limit 1;

  if v_edition.id is null then
    return jsonb_build_object(
      'configured', true,
      'edition', null,
      'session', null
    );
  end if;

  select session.*
    into v_session
  from public.deal_sessions session
  where session.edition_id = v_edition.id
    and session.user_id = v_user_id
  limit 1;

  if v_session.id is null then
    v_session_json := null;
  else
    v_session_json := jsonb_build_object(
      'id', v_session.id,
      'status', v_session.status,
      'player_name', v_session.player_name,
      'selected_box', v_session.selected_box,
      'banker_offer', v_session.banker_offer,
      'final_reward', v_session.final_reward,
      'selected_box_prize', v_session.selected_box_prize,
      'opened_count', (
        select count(*)::integer
        from public.deal_boxes box
        where box.session_id = v_session.id
          and box.opened_at is not null
      ),
      'opened_boxes', coalesce((
        select jsonb_agg(
          jsonb_build_object(
            'box_number', box.box_number,
            'prize_label', box.prize_label,
            'opened_at', box.opened_at
          )
          order by box.opened_at, box.box_number
        )
        from public.deal_boxes box
        where box.session_id = v_session.id
          and box.opened_at is not null
      ), '[]'::jsonb),
      'created_at', v_session.created_at,
      'updated_at', v_session.updated_at
    );
  end if;

  return jsonb_build_object(
    'configured', true,
    'edition', jsonb_build_object(
      'id', v_edition.id,
      'title', v_edition.title,
      'box_count', v_edition.box_count,
      'prize_labels', to_jsonb(v_edition.prize_labels),
      'status', v_edition.status,
      'created_at', v_edition.created_at
    ),
    'session', v_session_json
  );
end;
$$;

create or replace function public.nostra_get_deal_dashboard_state()
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_edition public.deal_editions%rowtype;
begin
  if not public.nostra_deal_is_manager() then
    raise exception 'manager_required';
  end if;

  select *
    into v_edition
  from public.deal_editions
  where status = 'open'
  order by created_at desc
  limit 1;

  if v_edition.id is null then
    return jsonb_build_object(
      'edition', null,
      'sessions', '[]'::jsonb
    );
  end if;

  return jsonb_build_object(
    'edition', jsonb_build_object(
      'id', v_edition.id,
      'title', v_edition.title,
      'box_count', v_edition.box_count,
      'prize_labels', to_jsonb(v_edition.prize_labels),
      'status', v_edition.status,
      'created_at', v_edition.created_at
    ),
    'sessions', coalesce((
      select jsonb_agg(
        jsonb_build_object(
          'id', session.id,
          'user_id', session.user_id,
          'player_name', session.player_name,
          'status', session.status,
          'selected_box', session.selected_box,
          'banker_offer', session.banker_offer,
          'final_reward', session.final_reward,
          'selected_box_prize', session.selected_box_prize,
          'opened_count', (
            select count(*)::integer
            from public.deal_boxes opened_box
            where opened_box.session_id = session.id
              and opened_box.opened_at is not null
          ),
          'boxes', (
            select jsonb_agg(
              jsonb_build_object(
                'box_number', box.box_number,
                'prize_label', box.prize_label,
                'opened', box.opened_at is not null
              )
              order by box.box_number
            )
            from public.deal_boxes box
            where box.session_id = session.id
          ),
          'created_at', session.created_at,
          'updated_at', session.updated_at
        )
        order by session.updated_at desc
      )
      from public.deal_sessions session
      where session.edition_id = v_edition.id
    ), '[]'::jsonb)
  );
end;
$$;

alter table public.deal_editions enable row level security;
alter table public.deal_sessions enable row level security;
alter table public.deal_boxes enable row level security;
alter table public.deal_banker_calls enable row level security;

drop policy if exists "deal users read open edition"
on public.deal_editions;

create policy "deal users read open edition"
on public.deal_editions
for select
to authenticated
using (
  status = 'open'
  or public.nostra_deal_is_manager()
);

drop policy if exists "deal users read own sessions"
on public.deal_sessions;

create policy "deal users read own sessions"
on public.deal_sessions
for select
to authenticated
using (
  user_id = auth.uid()
  or public.nostra_deal_is_manager()
);

drop policy if exists "deal users read own boxes"
on public.deal_boxes;

create policy "deal users read own boxes"
on public.deal_boxes
for select
to authenticated
using (
  exists (
    select 1
    from public.deal_sessions session
    where session.id = deal_boxes.session_id
      and (
        session.user_id = auth.uid()
        or public.nostra_deal_is_manager()
      )
  )
);

drop policy if exists "deal managers read calls"
on public.deal_banker_calls;

create policy "deal managers read calls"
on public.deal_banker_calls
for select
to authenticated
using (
  public.nostra_deal_is_manager()
  or exists (
    select 1
    from public.deal_sessions session
    where session.id = deal_banker_calls.session_id
      and session.user_id = auth.uid()
  )
);

grant select on public.deal_editions to authenticated;
grant select on public.deal_sessions to authenticated;
grant select on public.deal_boxes to authenticated;
grant select on public.deal_banker_calls to authenticated;

revoke all on function public.nostra_create_deal_edition(text,text[],boolean) from public;
revoke all on function public.nostra_start_deal_game() from public;
revoke all on function public.nostra_choose_deal_box(integer) from public;
revoke all on function public.nostra_open_deal_box(integer) from public;
revoke all on function public.nostra_trigger_deal_banker_call(uuid,text) from public;
revoke all on function public.nostra_answer_deal_banker_offer(text) from public;
revoke all on function public.nostra_stop_deal_session(uuid) from public;
revoke all on function public.nostra_close_deal_edition() from public;
revoke all on function public.nostra_get_deal_public_state() from public;
revoke all on function public.nostra_get_deal_dashboard_state() from public;

grant execute on function public.nostra_create_deal_edition(text,text[],boolean) to authenticated;
grant execute on function public.nostra_start_deal_game() to authenticated;
grant execute on function public.nostra_choose_deal_box(integer) to authenticated;
grant execute on function public.nostra_open_deal_box(integer) to authenticated;
grant execute on function public.nostra_trigger_deal_banker_call(uuid,text) to authenticated;
grant execute on function public.nostra_answer_deal_banker_offer(text) to authenticated;
grant execute on function public.nostra_stop_deal_session(uuid) to authenticated;
grant execute on function public.nostra_close_deal_edition() to authenticated;
grant execute on function public.nostra_get_deal_public_state() to authenticated;
grant execute on function public.nostra_get_deal_dashboard_state() to authenticated;

notify pgrst, 'reload schema';

`;
