export const RACE_CONTROL_SETUP_SQL = String.raw`
-- NOSTRA GROUP V37 — CHRONOMÉTRAGE DE COURSE
-- Grille de départ, chronomètres simultanés, tours, meilleur tour,
-- résultats et classements F1 / GT3 RS.
--
-- Réexécutable : conserve les courses et les temps déjà enregistrés.

create extension if not exists pgcrypto;

create table if not exists public.race_control_events (
  id bigint generated by default as identity primary key,
  title text not null,
  competition_type text not null default 'general',
  target_laps integer not null,
  status text not null default 'ready',
  started_at timestamptz,
  completed_at timestamptz,
  published_at timestamptz,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint race_control_events_competition_check
    check (competition_type in ('f1', 'gt3rs', 'general')),
  constraint race_control_events_laps_check
    check (target_laps between 1 and 999),
  constraint race_control_events_status_check
    check (
      status in (
        'ready',
        'running',
        'finished',
        'published',
        'cancelled'
      )
    )
);

create index if not exists race_control_events_status_idx
  on public.race_control_events(status, created_at desc);

create table if not exists public.race_control_entries (
  id bigint generated by default as identity primary key,
  event_id bigint not null
    references public.race_control_events(id) on delete cascade,
  driver_name text not null,
  team_name text not null,
  grid_position integer not null,
  status text not null default 'ready',
  lap_count integer not null default 0,
  last_crossing_at timestamptz,
  finished_at timestamptz,
  total_time_ms bigint,
  best_lap_ms bigint,
  position integer,
  championship_points integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint race_control_entries_status_check
    check (status in ('ready', 'running', 'finished', 'dnf')),
  constraint race_control_entries_lap_count_check
    check (lap_count >= 0),
  constraint race_control_entries_grid_check
    check (grid_position >= 1),
  unique (event_id, grid_position)
);

create index if not exists race_control_entries_event_status_idx
  on public.race_control_entries(event_id, status, grid_position);

create table if not exists public.race_control_laps (
  id bigint generated by default as identity primary key,
  event_id bigint not null
    references public.race_control_events(id) on delete cascade,
  entry_id bigint not null
    references public.race_control_entries(id) on delete cascade,
  lap_number integer not null,
  lap_time_ms bigint not null,
  crossed_at timestamptz not null,
  recorded_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  constraint race_control_laps_number_check
    check (lap_number >= 1),
  constraint race_control_laps_time_check
    check (lap_time_ms >= 500),
  unique (entry_id, lap_number)
);

create index if not exists race_control_laps_event_time_idx
  on public.race_control_laps(event_id, lap_time_ms);

create or replace function public.nostra_race_is_commissioner()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select
    coalesce(public.nostra_has_role('manager'), false)
    or coalesce(public.nostra_has_role('commissioner'), false);
$$;

revoke all on function public.nostra_race_is_commissioner()
from public;

grant execute on function public.nostra_race_is_commissioner()
to authenticated;

create or replace function public.nostra_race_points_for_position(
  p_position integer
)
returns integer
language sql
immutable
as $$
  select case p_position
    when 1 then 25
    when 2 then 18
    when 3 then 15
    when 4 then 12
    when 5 then 10
    when 6 then 8
    when 7 then 6
    when 8 then 4
    when 9 then 2
    when 10 then 1
    else 0
  end;
$$;

create or replace function public.nostra_race_recalculate_event(
  p_event_id bigint
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_active integer;
begin
  update public.race_control_entries entry
  set
    best_lap_ms = lap_stats.best_lap_ms,
    updated_at = now()
  from (
    select
      lap.entry_id,
      min(lap.lap_time_ms)::bigint as best_lap_ms
    from public.race_control_laps lap
    where lap.event_id = p_event_id
    group by lap.entry_id
  ) lap_stats
  where entry.id = lap_stats.entry_id;

  with ranked as (
    select
      entry.id,
      row_number() over (
        order by
          case when entry.status = 'finished' then 0 else 1 end,
          case
            when entry.status = 'finished'
              then entry.total_time_ms
            else null
          end asc nulls last,
          case
            when entry.status = 'dnf'
              then entry.lap_count
            else null
          end desc nulls last,
          entry.finished_at asc nulls last,
          entry.grid_position
      )::integer as calculated_position
    from public.race_control_entries entry
    where entry.event_id = p_event_id
      and entry.status in ('finished', 'dnf')
  )
  update public.race_control_entries entry
  set
    position = ranked.calculated_position,
    updated_at = now()
  from ranked
  where entry.id = ranked.id;

  select count(*)::integer
    into v_active
  from public.race_control_entries entry
  where entry.event_id = p_event_id
    and entry.status in ('ready', 'running');

  if v_active = 0 then
    update public.race_control_events
    set
      status = case
        when status = 'published' then 'published'
        else 'finished'
      end,
      completed_at = coalesce(completed_at, now()),
      updated_at = now()
    where id = p_event_id;
  end if;
end;
$$;

create or replace function public.nostra_create_race_control_event(
  p_title text,
  p_competition_type text,
  p_target_laps integer,
  p_entries jsonb
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_event_id bigint;
  v_count integer;
begin
  if not public.nostra_race_is_commissioner() then
    raise exception 'commissioner_required';
  end if;

  if nullif(trim(coalesce(p_title, '')), '') is null
    or p_competition_type not in ('f1', 'gt3rs', 'general')
    or p_target_laps not between 1 and 999
    or jsonb_typeof(p_entries) <> 'array'
  then
    raise exception 'invalid_event';
  end if;

  select jsonb_array_length(p_entries) into v_count;

  if v_count not between 1 and 40
    or exists (
      select 1
      from jsonb_array_elements(p_entries) item
      where nullif(trim(item ->> 'driver_name'), '') is null
         or nullif(trim(item ->> 'team_name'), '') is null
    )
  then
    raise exception 'invalid_entries';
  end if;

  insert into public.race_control_events (
    title,
    competition_type,
    target_laps,
    status,
    created_by
  )
  values (
    left(trim(p_title), 160),
    p_competition_type,
    p_target_laps,
    'ready',
    auth.uid()
  )
  returning id into v_event_id;

  insert into public.race_control_entries (
    event_id,
    driver_name,
    team_name,
    grid_position,
    status
  )
  select
    v_event_id,
    left(trim(item.value ->> 'driver_name'), 120),
    left(trim(item.value ->> 'team_name'), 120),
    item.ordinality::integer,
    'ready'
  from jsonb_array_elements(p_entries)
    with ordinality as item(value, ordinality);

  return v_event_id;
end;
$$;

create or replace function public.nostra_start_race_control_event(
  p_event_id bigint
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_started_at timestamptz := clock_timestamp();
begin
  if not public.nostra_race_is_commissioner() then
    raise exception 'commissioner_required';
  end if;

  update public.race_control_events
  set
    status = 'running',
    started_at = v_started_at,
    updated_at = v_started_at
  where id = p_event_id
    and status = 'ready';

  if not found then
    raise exception 'invalid_event_status';
  end if;

  update public.race_control_entries
  set
    status = 'running',
    last_crossing_at = v_started_at,
    updated_at = v_started_at
  where event_id = p_event_id
    and status = 'ready';
end;
$$;

create or replace function public.nostra_race_crossing_time(
  p_started_at timestamptz,
  p_elapsed_ms bigint
)
returns timestamptz
language plpgsql
stable
as $$
declare
  v_elapsed bigint;
  v_server_elapsed bigint;
begin
  if p_started_at is null then
    raise exception 'invalid_lap';
  end if;

  v_server_elapsed := greatest(
    0,
    floor(
      extract(epoch from (clock_timestamp() - p_started_at))
      * 1000
    )::bigint
  );

  v_elapsed := coalesce(p_elapsed_ms, v_server_elapsed);

  if v_elapsed < 0
    or v_elapsed > v_server_elapsed + 3000
  then
    raise exception 'invalid_lap';
  end if;

  return p_started_at + (v_elapsed::double precision / 1000.0)
    * interval '1 second';
end;
$$;

create or replace function public.nostra_record_race_control_lap(
  p_entry_id bigint,
  p_elapsed_ms bigint
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_entry public.race_control_entries%rowtype;
  v_event public.race_control_events%rowtype;
  v_crossing_at timestamptz;
  v_lap_time_ms bigint;
  v_lap_number integer;
begin
  if not public.nostra_race_is_commissioner() then
    raise exception 'commissioner_required';
  end if;

  select entry.*
    into v_entry
  from public.race_control_entries entry
  where entry.id = p_entry_id
  for update;

  if v_entry.id is null or v_entry.status <> 'running' then
    raise exception 'invalid_entry_status';
  end if;

  select event.*
    into v_event
  from public.race_control_events event
  where event.id = v_entry.event_id
  for update;

  if v_event.status <> 'running' then
    raise exception 'invalid_event_status';
  end if;

  if v_entry.lap_count >= v_event.target_laps - 1 then
    raise exception 'use_finish_button';
  end if;

  v_crossing_at := public.nostra_race_crossing_time(
    v_event.started_at,
    p_elapsed_ms
  );

  v_lap_time_ms := floor(
    extract(
      epoch from (
        v_crossing_at
        - coalesce(v_entry.last_crossing_at, v_event.started_at)
      )
    ) * 1000
  )::bigint;

  if v_lap_time_ms < 500 then
    raise exception 'duplicate_crossing';
  end if;

  v_lap_number := v_entry.lap_count + 1;

  insert into public.race_control_laps (
    event_id,
    entry_id,
    lap_number,
    lap_time_ms,
    crossed_at,
    recorded_by
  )
  values (
    v_event.id,
    v_entry.id,
    v_lap_number,
    v_lap_time_ms,
    v_crossing_at,
    auth.uid()
  );

  update public.race_control_entries
  set
    lap_count = v_lap_number,
    last_crossing_at = v_crossing_at,
    best_lap_ms = case
      when best_lap_ms is null then v_lap_time_ms
      else least(best_lap_ms, v_lap_time_ms)
    end,
    updated_at = clock_timestamp()
  where id = v_entry.id;

  return v_event.id;
end;
$$;

create or replace function public.nostra_finish_race_control_entry(
  p_entry_id bigint,
  p_elapsed_ms bigint
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_entry public.race_control_entries%rowtype;
  v_event public.race_control_events%rowtype;
  v_crossing_at timestamptz;
  v_lap_time_ms bigint;
  v_lap_number integer;
  v_total_time_ms bigint;
begin
  if not public.nostra_race_is_commissioner() then
    raise exception 'commissioner_required';
  end if;

  select entry.*
    into v_entry
  from public.race_control_entries entry
  where entry.id = p_entry_id
  for update;

  if v_entry.id is null or v_entry.status <> 'running' then
    raise exception 'invalid_entry_status';
  end if;

  select event.*
    into v_event
  from public.race_control_events event
  where event.id = v_entry.event_id
  for update;

  if v_event.status <> 'running' then
    raise exception 'invalid_event_status';
  end if;

  if v_entry.lap_count < v_event.target_laps - 1 then
    raise exception 'laps_remaining';
  end if;

  if v_entry.lap_count = v_event.target_laps - 1 then
    v_crossing_at := public.nostra_race_crossing_time(
      v_event.started_at,
      p_elapsed_ms
    );

    v_lap_time_ms := floor(
      extract(
        epoch from (
          v_crossing_at
          - coalesce(v_entry.last_crossing_at, v_event.started_at)
        )
      ) * 1000
    )::bigint;

    if v_lap_time_ms < 500 then
      raise exception 'duplicate_crossing';
    end if;

    v_lap_number := v_entry.lap_count + 1;

    insert into public.race_control_laps (
      event_id,
      entry_id,
      lap_number,
      lap_time_ms,
      crossed_at,
      recorded_by
    )
    values (
      v_event.id,
      v_entry.id,
      v_lap_number,
      v_lap_time_ms,
      v_crossing_at,
      auth.uid()
    );
  else
    v_crossing_at := coalesce(
      v_entry.last_crossing_at,
      public.nostra_race_crossing_time(
        v_event.started_at,
        p_elapsed_ms
      )
    );

    v_lap_number := v_entry.lap_count;
  end if;

  v_total_time_ms := floor(
    extract(epoch from (v_crossing_at - v_event.started_at))
    * 1000
  )::bigint;

  update public.race_control_entries
  set
    status = 'finished',
    lap_count = v_lap_number,
    last_crossing_at = v_crossing_at,
    finished_at = v_crossing_at,
    total_time_ms = v_total_time_ms,
    best_lap_ms = (
      select min(lap.lap_time_ms)::bigint
      from public.race_control_laps lap
      where lap.entry_id = v_entry.id
    ),
    updated_at = clock_timestamp()
  where id = v_entry.id;

  perform public.nostra_race_recalculate_event(v_event.id);

  return v_event.id;
end;
$$;

create or replace function public.nostra_mark_race_control_entry_dnf(
  p_entry_id bigint,
  p_elapsed_ms bigint
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_entry public.race_control_entries%rowtype;
  v_event public.race_control_events%rowtype;
  v_finished_at timestamptz;
begin
  if not public.nostra_race_is_commissioner() then
    raise exception 'commissioner_required';
  end if;

  select entry.*
    into v_entry
  from public.race_control_entries entry
  where entry.id = p_entry_id
  for update;

  if v_entry.id is null
    or v_entry.status not in ('ready', 'running')
  then
    raise exception 'invalid_entry_status';
  end if;

  select event.*
    into v_event
  from public.race_control_events event
  where event.id = v_entry.event_id
  for update;

  if v_event.status not in ('ready', 'running') then
    raise exception 'invalid_event_status';
  end if;

  v_finished_at := case
    when v_event.started_at is null then clock_timestamp()
    else public.nostra_race_crossing_time(
      v_event.started_at,
      p_elapsed_ms
    )
  end;

  update public.race_control_entries
  set
    status = 'dnf',
    finished_at = v_finished_at,
    total_time_ms = case
      when v_event.started_at is null then null
      else floor(
        extract(epoch from (v_finished_at - v_event.started_at))
        * 1000
      )::bigint
    end,
    updated_at = clock_timestamp()
  where id = v_entry.id;

  perform public.nostra_race_recalculate_event(v_event.id);

  return v_event.id;
end;
$$;

create or replace function public.nostra_stop_race_control_event(
  p_event_id bigint
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_now timestamptz := clock_timestamp();
begin
  if not public.nostra_race_is_commissioner() then
    raise exception 'commissioner_required';
  end if;

  if not exists (
    select 1
    from public.race_control_events event
    where event.id = p_event_id
      and event.status in ('ready', 'running')
  ) then
    raise exception 'invalid_event_status';
  end if;

  update public.race_control_entries entry
  set
    status = 'dnf',
    finished_at = v_now,
    total_time_ms = case
      when event.started_at is null then null
      else floor(
        extract(epoch from (v_now - event.started_at)) * 1000
      )::bigint
    end,
    updated_at = v_now
  from public.race_control_events event
  where entry.event_id = p_event_id
    and event.id = p_event_id
    and entry.status in ('ready', 'running');

  update public.race_control_events
  set
    status = 'finished',
    completed_at = v_now,
    updated_at = v_now
  where id = p_event_id;

  perform public.nostra_race_recalculate_event(p_event_id);
end;
$$;

create or replace function public.nostra_publish_race_control_results(
  p_event_id bigint,
  p_destination text
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.nostra_race_is_commissioner() then
    raise exception 'commissioner_required';
  end if;

  if p_destination not in ('f1', 'gt3rs', 'general') then
    raise exception 'invalid_event';
  end if;

  perform public.nostra_race_recalculate_event(p_event_id);

  if not exists (
    select 1
    from public.race_control_events event
    where event.id = p_event_id
      and event.status in ('finished', 'published')
  ) then
    raise exception 'invalid_event_status';
  end if;

  update public.race_control_entries
  set
    championship_points = case
      when p_destination in ('f1', 'gt3rs')
        and status = 'finished'
      then public.nostra_race_points_for_position(position)
      else 0
    end,
    updated_at = now()
  where event_id = p_event_id;

  update public.race_control_events
  set
    competition_type = p_destination,
    status = 'published',
    published_at = now(),
    updated_at = now()
  where id = p_event_id;
end;
$$;

create or replace function public.nostra_get_race_control_dashboard_state()
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
begin
  if not public.nostra_race_is_commissioner() then
    raise exception 'commissioner_required';
  end if;

  return jsonb_build_object(
    'configured', true,
    'events', coalesce((
      select jsonb_agg(
        jsonb_build_object(
          'id', event.id,
          'title', event.title,
          'competition_type', event.competition_type,
          'target_laps', event.target_laps,
          'status', event.status,
          'started_at', event.started_at,
          'completed_at', event.completed_at,
          'published_at', event.published_at,
          'created_at', event.created_at,
          'participant_count', (
            select count(*)::integer
            from public.race_control_entries entry
            where entry.event_id = event.id
          ),
          'active_count', (
            select count(*)::integer
            from public.race_control_entries entry
            where entry.event_id = event.id
              and entry.status in ('ready', 'running')
          ),
          'finished_count', (
            select count(*)::integer
            from public.race_control_entries entry
            where entry.event_id = event.id
              and entry.status in ('finished', 'dnf')
          )
        )
        order by
          case event.status
            when 'running' then 0
            when 'ready' then 1
            when 'finished' then 2
            when 'published' then 3
            else 4
          end,
          event.created_at desc
      )
      from (
        select *
        from public.race_control_events
        order by created_at desc
        limit 30
      ) event
    ), '[]'::jsonb)
  );
end;
$$;

create or replace function public.nostra_get_race_control_event_state(
  p_event_id bigint
)
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_event public.race_control_events%rowtype;
begin
  if not public.nostra_race_is_commissioner() then
    raise exception 'commissioner_required';
  end if;

  select *
    into v_event
  from public.race_control_events
  where id = p_event_id;

  if v_event.id is null then
    return jsonb_build_object(
      'configured', true,
      'server_now', clock_timestamp(),
      'event', null,
      'entries', '[]'::jsonb,
      'best_lap', null
    );
  end if;

  return jsonb_build_object(
    'configured', true,
    'server_now', clock_timestamp(),
    'event', jsonb_build_object(
      'id', v_event.id,
      'title', v_event.title,
      'competition_type', v_event.competition_type,
      'target_laps', v_event.target_laps,
      'status', v_event.status,
      'started_at', v_event.started_at,
      'completed_at', v_event.completed_at,
      'published_at', v_event.published_at,
      'created_at', v_event.created_at
    ),
    'entries', coalesce((
      select jsonb_agg(
        jsonb_build_object(
          'id', entry.id,
          'driver_name', entry.driver_name,
          'team_name', entry.team_name,
          'grid_position', entry.grid_position,
          'status', entry.status,
          'lap_count', entry.lap_count,
          'last_crossing_at', entry.last_crossing_at,
          'finished_at', entry.finished_at,
          'total_time_ms', entry.total_time_ms,
          'best_lap_ms', entry.best_lap_ms,
          'last_lap_ms', (
            select lap.lap_time_ms
            from public.race_control_laps lap
            where lap.entry_id = entry.id
            order by lap.lap_number desc
            limit 1
          ),
          'position', entry.position,
          'championship_points', entry.championship_points,
          'laps', coalesce((
            select jsonb_agg(
              jsonb_build_object(
                'id', lap.id,
                'lap_number', lap.lap_number,
                'lap_time_ms', lap.lap_time_ms,
                'crossed_at', lap.crossed_at
              )
              order by lap.lap_number
            )
            from public.race_control_laps lap
            where lap.entry_id = entry.id
          ), '[]'::jsonb)
        )
        order by
          coalesce(entry.position, entry.grid_position),
          entry.grid_position
      )
      from public.race_control_entries entry
      where entry.event_id = v_event.id
    ), '[]'::jsonb),
    'best_lap', (
      select jsonb_build_object(
        'entry_id', entry.id,
        'driver_name', entry.driver_name,
        'team_name', entry.team_name,
        'lap_number', lap.lap_number,
        'lap_time_ms', lap.lap_time_ms
      )
      from public.race_control_laps lap
      join public.race_control_entries entry
        on entry.id = lap.entry_id
      where lap.event_id = v_event.id
      order by lap.lap_time_ms, lap.crossed_at
      limit 1
    )
  );
end;
$$;

create or replace function public.nostra_get_public_race_results(
  p_competition_type text
)
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
begin
  if auth.uid() is null then
    raise exception 'not_authenticated';
  end if;

  if p_competition_type not in ('f1', 'gt3rs') then
    return '[]'::jsonb;
  end if;

  return coalesce((
    select jsonb_agg(
      jsonb_build_object(
        'id', event.id,
        'title', event.title,
        'competition_type', event.competition_type,
        'target_laps', event.target_laps,
        'started_at', event.started_at,
        'completed_at', event.completed_at,
        'published_at', event.published_at,
        'best_lap', (
          select jsonb_build_object(
            'entry_id', best_entry.id,
            'driver_name', best_entry.driver_name,
            'team_name', best_entry.team_name,
            'lap_number', best_lap.lap_number,
            'lap_time_ms', best_lap.lap_time_ms
          )
          from public.race_control_laps best_lap
          join public.race_control_entries best_entry
            on best_entry.id = best_lap.entry_id
          where best_lap.event_id = event.id
          order by best_lap.lap_time_ms, best_lap.crossed_at
          limit 1
        ),
        'entries', (
          select jsonb_agg(
            jsonb_build_object(
              'position', entry.position,
              'driver_name', entry.driver_name,
              'team_name', entry.team_name,
              'status', entry.status,
              'lap_count', entry.lap_count,
              'total_time_ms', entry.total_time_ms,
              'best_lap_ms', entry.best_lap_ms,
              'championship_points', entry.championship_points
            )
            order by entry.position, entry.grid_position
          )
          from public.race_control_entries entry
          where entry.event_id = event.id
        )
      )
      order by event.published_at desc
    )
    from public.race_control_events event
    where event.status = 'published'
      and event.competition_type = p_competition_type
  ), '[]'::jsonb);
end;
$$;

create or replace function public.nostra_get_public_driver_standings(
  p_competition_type text
)
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
begin
  if auth.uid() is null then
    raise exception 'not_authenticated';
  end if;

  if p_competition_type not in ('f1', 'gt3rs') then
    return '[]'::jsonb;
  end if;

  return coalesce((
    select jsonb_agg(
      jsonb_build_object(
        'position', standing.position,
        'driver_name', standing.driver_name,
        'teams', standing.teams,
        'points', standing.points,
        'races', standing.races,
        'wins', standing.wins,
        'podiums', standing.podiums,
        'best_laps', standing.best_laps
      )
      order by standing.position
    )
    from (
      select
        row_number() over (
          order by
            sum(entry.championship_points) desc,
            count(*) filter (where entry.position = 1) desc,
            min(entry.best_lap_ms) asc nulls last,
            entry.driver_name
        )::integer as position,
        entry.driver_name,
        string_agg(distinct entry.team_name, ', ' order by entry.team_name)
          as teams,
        sum(entry.championship_points)::integer as points,
        count(*)::integer as races,
        count(*) filter (where entry.position = 1)::integer as wins,
        count(*) filter (where entry.position between 1 and 3)::integer
          as podiums,
        count(*) filter (
          where entry.best_lap_ms = (
            select min(other.best_lap_ms)
            from public.race_control_entries other
            where other.event_id = entry.event_id
              and other.best_lap_ms is not null
          )
        )::integer as best_laps
      from public.race_control_entries entry
      join public.race_control_events event
        on event.id = entry.event_id
      where event.status = 'published'
        and event.competition_type = p_competition_type
      group by entry.driver_name
    ) standing
  ), '[]'::jsonb);
end;
$$;

create or replace function public.nostra_get_public_team_standings(
  p_competition_type text
)
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
begin
  if auth.uid() is null then
    raise exception 'not_authenticated';
  end if;

  if p_competition_type not in ('f1', 'gt3rs') then
    return '[]'::jsonb;
  end if;

  return coalesce((
    select jsonb_agg(
      jsonb_build_object(
        'position', standing.position,
        'team_name', standing.team_name,
        'points', standing.points,
        'races', standing.races,
        'wins', standing.wins,
        'podiums', standing.podiums,
        'best_laps', standing.best_laps
      )
      order by standing.position
    )
    from (
      select
        row_number() over (
          order by
            sum(entry.championship_points) desc,
            count(*) filter (where entry.position = 1) desc,
            min(entry.best_lap_ms) asc nulls last,
            entry.team_name
        )::integer as position,
        entry.team_name,
        sum(entry.championship_points)::integer as points,
        count(distinct entry.event_id)::integer as races,
        count(*) filter (where entry.position = 1)::integer as wins,
        count(*) filter (where entry.position between 1 and 3)::integer
          as podiums,
        count(*) filter (
          where entry.best_lap_ms = (
            select min(other.best_lap_ms)
            from public.race_control_entries other
            where other.event_id = entry.event_id
              and other.best_lap_ms is not null
          )
        )::integer as best_laps
      from public.race_control_entries entry
      join public.race_control_events event
        on event.id = entry.event_id
      where event.status = 'published'
        and event.competition_type = p_competition_type
      group by entry.team_name
    ) standing
  ), '[]'::jsonb);
end;
$$;

alter table public.race_control_events enable row level security;
alter table public.race_control_entries enable row level security;
alter table public.race_control_laps enable row level security;

drop policy if exists "race control read events"
on public.race_control_events;

create policy "race control read events"
on public.race_control_events
for select
to authenticated
using (
  status = 'published'
  or public.nostra_race_is_commissioner()
);

drop policy if exists "race control read entries"
on public.race_control_entries;

create policy "race control read entries"
on public.race_control_entries
for select
to authenticated
using (
  public.nostra_race_is_commissioner()
  or exists (
    select 1
    from public.race_control_events event
    where event.id = race_control_entries.event_id
      and event.status = 'published'
  )
);

drop policy if exists "race control read laps"
on public.race_control_laps;

create policy "race control read laps"
on public.race_control_laps
for select
to authenticated
using (
  public.nostra_race_is_commissioner()
  or exists (
    select 1
    from public.race_control_events event
    where event.id = race_control_laps.event_id
      and event.status = 'published'
  )
);

grant select on public.race_control_events to authenticated;
grant select on public.race_control_entries to authenticated;
grant select on public.race_control_laps to authenticated;

revoke all on function public.nostra_create_race_control_event(
  text,
  text,
  integer,
  jsonb
) from public;

revoke all on function public.nostra_start_race_control_event(bigint)
from public;

revoke all on function public.nostra_record_race_control_lap(
  bigint,
  bigint
) from public;

revoke all on function public.nostra_finish_race_control_entry(
  bigint,
  bigint
) from public;

revoke all on function public.nostra_mark_race_control_entry_dnf(
  bigint,
  bigint
) from public;

revoke all on function public.nostra_stop_race_control_event(bigint)
from public;

revoke all on function public.nostra_publish_race_control_results(
  bigint,
  text
) from public;

revoke all on function public.nostra_get_race_control_dashboard_state()
from public;

revoke all on function public.nostra_get_race_control_event_state(bigint)
from public;

revoke all on function public.nostra_get_public_race_results(text)
from public;

revoke all on function public.nostra_get_public_driver_standings(text)
from public;

revoke all on function public.nostra_get_public_team_standings(text)
from public;

grant execute on function public.nostra_create_race_control_event(
  text,
  text,
  integer,
  jsonb
) to authenticated;

grant execute on function public.nostra_start_race_control_event(bigint)
to authenticated;

grant execute on function public.nostra_record_race_control_lap(
  bigint,
  bigint
) to authenticated;

grant execute on function public.nostra_finish_race_control_entry(
  bigint,
  bigint
) to authenticated;

grant execute on function public.nostra_mark_race_control_entry_dnf(
  bigint,
  bigint
) to authenticated;

grant execute on function public.nostra_stop_race_control_event(bigint)
to authenticated;

grant execute on function public.nostra_publish_race_control_results(
  bigint,
  text
) to authenticated;

grant execute on function public.nostra_get_race_control_dashboard_state()
to authenticated;

grant execute on function public.nostra_get_race_control_event_state(bigint)
to authenticated;

grant execute on function public.nostra_get_public_race_results(text)
to authenticated;

grant execute on function public.nostra_get_public_driver_standings(text)
to authenticated;

grant execute on function public.nostra_get_public_team_standings(text)
to authenticated;

notify pgrst, 'reload schema';

`;
