import Link from "next/link";
import { redirect } from "next/navigation";

import { acceptConciergeOfferV162, createConciergeRequestV162 } from "@/app/actions/v162";
import vipStyles from "@/components/v156/v156.module.css";
import styles from "@/components/v162/v162.module.css";
import { getRequestUser } from "@/lib/auth/request-context";
import { getVipCenterV156 } from "@/lib/v156/data";
import { getMyConciergeRequestsV162 } from "@/lib/v162/data";

export const dynamic="force-dynamic";
const money=(v:number|null)=>v==null?"—":v.toLocaleString("fr-FR",{style:"currency",currency:"EUR",maximumFractionDigits:0});
export default async function VipCenterPage({searchParams}:{searchParams:Promise<{concierge_created?:string;concierge_error?:string}>}){
 const user=await getRequestUser();if(!user)redirect("/");const [vip,requests,q]=await Promise.all([getVipCenterV156(user.id),getMyConciergeRequestsV162(user.id),searchParams]);const progress=vip.next?Math.min(100,Math.round((vip.points/Math.max(1,vip.next.minPoints))*100)):100;
 return <main className={vipStyles.page}>
  <section className={vipStyles.hero}><span className={vipStyles.eyebrow}>NOSTRA GROUP</span><h1>Centre VIP</h1><p>Ton statut Nostra, tes accès privés et désormais un service Concierge dédié aux demandes particulières.</p></section>
  {q.concierge_created&&<div className={styles.success}>Ta demande Concierge a été transmise à Nostra Motors.</div>}{q.concierge_error&&<div className={styles.error}>La demande Concierge n’a pas pu être traitée.</div>}
  <div className={vipStyles.grid2}><section className={vipStyles.vipTier}><span className={vipStyles.eyebrow}>TON STATUT</span><h2>{vip.current?.label??"Membre Nostra"}</h2><p>{vip.points.toLocaleString("fr-FR")} points Nostra</p>{vip.current?.description&&<p>{vip.current.description}</p>}<ul className={vipStyles.benefits}>{(vip.current?.benefits??[]).map((benefit:string)=><li key={benefit}>◆ {benefit}</li>)}</ul>{vip.next&&<><div className={vipStyles.row}><span>Prochain niveau</span><strong>{vip.next.label} · {vip.next.minPoints.toLocaleString("fr-FR")} pts</strong></div><div style={{height:10,borderRadius:999,background:"#1d1e22",overflow:"hidden"}}><span style={{display:"block",height:"100%",width:`${progress}%`,background:"#d5aa28"}}/></div></>}</section><section className={vipStyles.card}><span className={vipStyles.eyebrow}>ACCÈS PRIVÉS</span><h2>Avantages disponibles</h2><div className={vipStyles.stack}><Link className={vipStyles.buttonAlt} href="/ventes-privees">Ventes privées</Link><Link className={vipStyles.buttonAlt} href="/profil/fidelite">Ma fidélité</Link><Link className={vipStyles.buttonAlt} href="#concierge">Concierge Nostra</Link><Link className={vipStyles.buttonAlt} href="/casino/profil">Mon statut Nostra Cercle</Link></div></section></div>
  <section id="concierge" className={styles.hero}><span className={styles.eyebrow}>CONCIERGE NOSTRA</span><h1 style={{fontSize:"clamp(28px,3vw,42px)"}}>Une demande privée, un interlocuteur Nostra</h1><p>Recherche d’un véhicule rare, configuration précise, rendez-vous showroom privé, transport spécial ou demande liée à une collection.</p></section>
  <div className={styles.grid2}><section className={styles.panel}><span className={styles.eyebrow}>NOUVELLE DEMANDE</span><h2>Ouvrir un dossier Concierge</h2><form className={styles.form} action={createConciergeRequestV162}><label>Type de demande<select name="request_type" defaultValue="rare_vehicle"><option value="rare_vehicle">Recherche d’un véhicule rare</option><option value="private_showroom">Rendez-vous privé showroom</option><option value="priority_delivery">Livraison prioritaire</option><option value="special_transport">Transport spécial</option><option value="configuration">Configuration précise</option><option value="collection">Demande concernant une collection</option><option value="other">Autre demande privée</option></select></label><label>Sujet<input name="subject" required maxLength={180} placeholder="Ex. Recherche Ferrari Enzo rouge"/></label><label>Budget éventuel<input type="number" min="0" name="budget" placeholder="Facultatif"/></label><label>Détails<textarea name="description" required minLength={10} placeholder="Explique précisément ce que tu recherches ou ce que tu souhaites organiser."/></label><button className={styles.button}>Envoyer au Concierge</button></form></section><section className={styles.panel}><span className={styles.eyebrow}>MES DOSSIERS PRIVÉS</span><h2>{requests.length} demande(s)</h2><div className={styles.list}>{requests.length===0&&<div className={styles.empty}>Aucune demande Concierge.</div>}{requests.map(r=><article className={styles.card} key={r.id}><div className={styles.sectionTitle}><div><span className={styles.pill}>{r.requestNumber}</span><h3>{r.subject}</h3></div><strong>{r.status}</strong></div><p className={styles.muted}>{r.description}</p>{r.proposalMessage&&<div className={styles.notice}><strong>Proposition Nostra</strong><br/>{r.proposedVehicleLabel&&<><span>{r.proposedVehicleLabel}</span><br/></>}{r.proposedPrice!=null&&<><strong>{money(r.proposedPrice)}</strong><br/></>}{r.proposalMessage}{r.proposalExpiresAt&&<><br/><small>Valable jusqu’au {new Date(r.proposalExpiresAt).toLocaleString("fr-FR")}</small></>}</div>}{r.status==="proposal_sent"&&r.proposedVehicleId&&r.proposedPrice!=null&&<form action={acceptConciergeOfferV162}><input type="hidden" name="id" value={r.id}/><button className={styles.button}>Accepter l’offre et ajouter au panier</button></form>}</article>)}</div></section></div>
  <section className={vipStyles.sectionTitle}><span className={vipStyles.eyebrow}>VENTES PRIVÉES</span><h2>Offres accessibles</h2></section><div className={vipStyles.grid}>{vip.privateSales.map((sale:any)=><article className={vipStyles.card} key={sale.id}><span className={vipStyles.pill}>VIP</span><h3>{sale.title}</h3><p>{sale.brand} {sale.model}</p><Link className={vipStyles.button} href={`/motors/catalogue/${sale.vehicleId}/commande`}>Voir l’offre</Link></article>)}{!vip.privateSales.length&&<div className={vipStyles.notice}>Aucune vente privée n’est actuellement ouverte pour ton niveau.</div>}</div>
 </main>
}
