import { markConsignmentOwnerPaidV134, publishVehicleConsignmentV134, reviewVehicleConsignmentV134 } from "@/app/actions/vehicle-consignments";
import { DashboardHeader } from "@/components/dashboard/dashboard-header";
import { DashboardShell } from "@/components/dashboard/dashboard-shell";
import { UsedVehicleDashboardNav } from "@/components/used-vehicles/used-dashboard-nav";
import { getVehicleConsignmentsConfiguredV134, getVehicleConsignmentsV134 } from "@/lib/vehicle-consignments/data";
import styles from "@/components/used-vehicles/used-vehicles.module.css";
const money=(v:number|null)=>v==null?"—":v.toLocaleString("fr-FR",{style:"currency",currency:"EUR",maximumFractionDigits:0});
export default async function ConsignmentsDashboard({searchParams}:{searchParams:Promise<Record<string,string|undefined>>}){
 const [params,configured,rows]=await Promise.all([searchParams,getVehicleConsignmentsConfiguredV134(),getVehicleConsignmentsV134()]);
 return <DashboardShell allowedRoles={["manager","employee","commercial"]}><DashboardHeader title="Dépôts-vente" description="Gère les véhicules confiés à Nostra sans les enregistrer comme rachats."/><UsedVehicleDashboardNav current="/dashboard/occasion/depots-vente"/>
 {!configured?<section className="dashboard-setup"><span className="module-status">Activation nécessaire</span><h2>Exécute le SQL V134</h2></section>:<><div className="dashboard-feedback">Le gain réel de Nostra correspond uniquement à la commission. Le montant du propriétaire est suivi séparément.</div>{params.saved&&<div className="dashboard-feedback dashboard-feedback-success">Proposition enregistrée.</div>}{params.published&&<div className="dashboard-feedback dashboard-feedback-success">Véhicule publié dans les occasions.</div>}{params.paid&&<div className="dashboard-feedback dashboard-feedback-success">Règlement du propriétaire marqué comme effectué.</div>}{params.error&&<div className="dashboard-feedback dashboard-feedback-error">Impossible d’enregistrer l’action.</div>}
 <section className={styles.kpis}><article className={styles.kpi}><span>Dossiers</span><strong>{rows.length}</strong></article><article className={styles.kpi}><span>À traiter</span><strong>{rows.filter(r=>["new","reviewing","offer_sent","accepted"].includes(r.status)).length}</strong></article><article className={styles.kpi}><span>En vente</span><strong>{rows.filter(r=>r.status==="published").length}</strong></article><article className={styles.kpi}><span>Vendus</span><strong>{rows.filter(r=>r.status==="sold").length}</strong></article></section>
 <div className={styles.stack}>{rows.length===0&&<section className={styles.panel}><p className={styles.empty}>Aucun dépôt-vente.</p></section>}{rows.map(row=><article className={styles.panel} key={row.id}><div className={styles.caseHead}><div><span className={styles.badge}>{row.status}</span><h2>{row.consignment_number} · {row.brand} {row.model}</h2><p>{row.owner_name} · {row.registration||"Sans immatriculation"} · {row.mileage.toLocaleString("fr-FR")} km</p></div><strong>{money(row.agreed_sale_price??row.desired_price)}</strong></div>
 <div className={styles.moneyGrid}><div><span>Prix souhaité</span><strong>{money(row.desired_price)}</strong></div><div><span>Commission Nostra</span><strong>{money(row.commission_amount)}</strong></div><div><span>Net propriétaire</span><strong>{money(row.owner_net_amount)}</strong></div></div>
 {row.images.length>0&&<div className={styles.imageStrip}>{row.images.slice(0,4).map(image=><a href={image.url} target="_blank" rel="noreferrer" key={image.path}>{/* eslint-disable-next-line @next/next/no-img-element */}<img src={image.url} alt="Véhicule en dépôt-vente"/></a>)}</div>}
 {!['published','reserved','sold'].includes(row.status)&&<form action={reviewVehicleConsignmentV134} className={styles.form}><input type="hidden" name="consignment_id" value={row.id}/><label>Statut<select name="status" defaultValue={row.status}><option value="new">Nouveau</option><option value="reviewing">Étude</option><option value="offer_sent">Envoyer la proposition</option><option value="refused">Refuser</option><option value="cancelled">Annuler</option></select></label><label>Prix de vente<input name="agreed_sale_price" inputMode="decimal" defaultValue={row.agreed_sale_price??row.desired_price}/></label><label>Commission (%)<input name="commission_rate" inputMode="decimal" defaultValue={row.commission_rate??15}/></label><label>Commercial<input name="assigned_staff" defaultValue={row.assigned_staff??""}/></label><label className={styles.span2}>Description publique<textarea name="public_description" rows={3} defaultValue={row.public_description??row.description}/></label><label className={styles.span2}>Message / conditions<textarea name="staff_note" rows={3} defaultValue={row.staff_note??""}/></label><button className={styles.primary}>Enregistrer la proposition</button></form>}
 {row.status==="accepted"&&<form action={publishVehicleConsignmentV134} className={styles.actions}><input type="hidden" name="consignment_id" value={row.id}/><button className={styles.primary}>Publier dans les véhicules d’occasion</button></form>}{row.status==="sold"&&!row.owner_paid_at&&<form action={markConsignmentOwnerPaidV134} className={styles.actions}><input type="hidden" name="consignment_id" value={row.id}/><button className={styles.primary}>Confirmer le règlement propriétaire</button></form>}{row.owner_paid_at&&<p className={styles.notice}>Propriétaire réglé le {new Date(row.owner_paid_at).toLocaleDateString("fr-FR")}.</p>}
 </article>)}</div></>}
 </DashboardShell>;
}
