import { createTicketEventV153, deleteTicketEventV153, updateTicketEventV153 } from "@/app/actions/v153";
import { DashboardHeader } from "@/components/dashboard/dashboard-header";
import { DashboardShell } from "@/components/dashboard/dashboard-shell";
import { getTicketEventsV153 } from "@/lib/v153/data";
import styles from "@/components/v153/v153.module.css";
export const dynamic="force-dynamic"; const money=(n:number)=>n.toLocaleString("fr-FR",{style:"currency",currency:"EUR",maximumFractionDigits:0});const dt=(v:string|null)=>v?new Date(v).toISOString().slice(0,16):"";
export default async function TicketAdmin({searchParams}:{searchParams:Promise<Record<string,string|undefined>>}){const [events,p]=await Promise.all([getTicketEventsV153(true),searchParams]);return <DashboardShell><DashboardHeader title="Billetterie globale Nostra" description="Créer des billets pour les événements de tout le groupe et suivre les ventes." />
{(p.created||p.saved||p.deleted)&&<p className={styles.feedback}>Billetterie mise à jour.</p>}{p.error&&<p className={`${styles.feedback} ${styles.error}`}>Impossible d’enregistrer cet événement.</p>}
<section className={styles.card}><h2>Créer un événement billetterie</h2><form action={createTicketEventV153} className={styles.form}><label>Pôle<select name="pole" defaultValue="group"><option value="group">Nostra Group</option><option value="motors">Nostra Motors</option><option value="circuit">Nostra Circuit</option><option value="cercle">Nostra Cercle</option><option value="academy">Racing Academy</option><option value="events">Jeux & événements</option></select></label><label>Titre<input name="title" required/></label><label>Lieu<input name="location" required/></label><label>Prix du billet<input name="ticket_price" type="number" min="0" defaultValue="0"/></label><label>Début<input name="starts_at" type="datetime-local" required/></label><label>Fin<input name="ends_at" type="datetime-local"/></label><label>Capacité<input name="capacity" type="number" min="1" placeholder="Vide = illimité"/></label><label><span>Ventes ouvertes</span><input name="sales_open" type="checkbox"/></label><label><span>Publié</span><input name="published" type="checkbox"/></label><label className={styles.full}>Description<textarea name="description" rows={4}/></label><div><button className={styles.button} type="submit">Créer et enregistrer</button></div></form></section>
<section className={styles.stack} style={{marginTop:16}}>{events.map(e=><article className={styles.card} key={e.id} id={e.id}><div className={styles.row}><div><p className={styles.eyebrow}>{e.pole.toUpperCase()}</p><h2>{e.title}</h2><p>{new Date(e.startsAt).toLocaleString("fr-FR")} · {e.location} · {money(e.ticketPrice)}</p></div><span className={styles.pill}>{e.sold}{e.capacity?` / ${e.capacity}`:""} VENDU(S)</span></div><form action={updateTicketEventV153} className={styles.form}><input type="hidden" name="id" value={e.id}/><label>Pôle<select name="pole" defaultValue={e.pole}><option value="group">Groupe</option><option value="motors">Motors</option><option value="circuit">Circuit</option><option value="cercle">Cercle</option><option value="academy">Academy</option><option value="events">Événements</option></select></label><label>Titre<input name="title" defaultValue={e.title}/></label><label>Lieu<input name="location" defaultValue={e.location}/></label><label>Prix<input name="ticket_price" type="number" defaultValue={e.ticketPrice}/></label><label>Début<input name="starts_at" type="datetime-local" defaultValue={dt(e.startsAt)}/></label><label>Fin<input name="ends_at" type="datetime-local" defaultValue={dt(e.endsAt)}/></label><label>Capacité<input name="capacity" type="number" defaultValue={e.capacity??""}/></label><label><span>Ventes ouvertes</span><input name="sales_open" type="checkbox" defaultChecked={e.salesOpen}/></label><label><span>Publié</span><input name="published" type="checkbox" defaultChecked={e.published}/></label><label className={styles.full}>Description<textarea name="description" rows={3} defaultValue={e.description}/></label><div><button className={styles.button} type="submit">Enregistrer</button></div></form><form action={deleteTicketEventV153} style={{marginTop:12}}><input type="hidden" name="id" value={e.id}/><button className={styles.danger} type="submit">Supprimer l’événement</button></form></article>)}</section></DashboardShell>}
