import { redirect } from "next/navigation";
import { acceptVehicleConsignmentV134, cancelVehicleConsignmentV134, submitVehicleConsignmentV134 } from "@/app/actions/vehicle-consignments";
import { OptimizedImageInput } from "@/components/forms/optimized-image-input";
import { createClient } from "@/lib/supabase/server";
import { getOwnVehicleConsignmentsV134, getVehicleConsignmentsConfiguredV134 } from "@/lib/vehicle-consignments/data";
import styles from "@/components/used-vehicles/used-vehicles.module.css";

const labels: Record<string,string> = { new:"Dossier reçu",reviewing:"Étude en cours",offer_sent:"Proposition à accepter",accepted:"Contrat accepté",published:"En vente",reserved:"Réservé",sold:"Vendu",refused:"Refusé",cancelled:"Annulé" };
const money = (value: number | null) => value == null ? "Non défini" : value.toLocaleString("fr-FR", { style:"currency",currency:"EUR",maximumFractionDigits:0 });

export default async function ConsignmentPage({ searchParams }: { searchParams: Promise<Record<string,string|undefined>> }) {
  const supabase=await createClient(); const {data}=await supabase.auth.getUser(); if(!data.user) redirect("/");
  const [params,configured,rows]=await Promise.all([searchParams,getVehicleConsignmentsConfiguredV134(),getOwnVehicleConsignmentsV134(data.user.id)]);
  return <><section className="profile-heading"><span className="eyebrow">NOSTRA MOTORS</span><h1 className="page-title">Dépôt-vente</h1><p className="lead">Ton véhicule reste ta propriété. Nostra Motors le présente, gère la vente et prélève uniquement la commission acceptée.</p></section>
  {!configured&&<div className="dashboard-feedback dashboard-feedback-error">Le module doit être activé avec le SQL V134.</div>}{params.sent&&<div className="dashboard-feedback dashboard-feedback-success">Dépôt <strong>{params.sent}</strong> envoyé.</div>}{params.accepted&&<div className="dashboard-feedback dashboard-feedback-success">Proposition acceptée. Nostra Motors peut maintenant publier le véhicule.</div>}{params.error&&<div className="dashboard-feedback dashboard-feedback-error">Impossible d’enregistrer l’action. Vérifie les informations ou le SQL V134.</div>}
  {configured&&<div className={styles.serviceLayout}><section className={styles.panel}><div className={styles.panelHeader}><div><h2>Proposer un véhicule</h2><p>Aucun rachat n’est créé : le paiement du propriétaire intervient après la vente.</p></div></div><form action={submitVehicleConsignmentV134} className={styles.form}>
    <label>Marque<input name="brand" required /></label><label>Modèle<input name="model" required /></label><label>Version<input name="version" /></label><label>Immatriculation<input name="registration" /></label>
    <label>Kilométrage<input name="mileage" type="number" min="0" defaultValue="0" /></label><label>Année<input name="first_registration_year" type="number" min="1950" max="2100" /></label><label>État<select name="vehicle_condition" defaultValue="good"><option value="excellent">Excellent</option><option value="very_good">Très bon</option><option value="good">Bon</option><option value="fair">Correct</option><option value="repair">À réparer</option></select></label><label>Prix souhaité<input name="desired_price" inputMode="decimal" required /></label>
    <label>Téléphone<input name="owner_phone" /></label><label className={styles.span3}>Description<textarea name="description" minLength={10} required rows={4} /></label><label className={styles.span4}>Photos — 8 maximum<OptimizedImageInput name="images" maxFiles={8} targetKilobytes={800} /></label><button className={styles.primary}>Envoyer la demande</button>
  </form></section><section className={styles.panel}><div className={styles.panelHeader}><div><h2>Mes dépôts-vente</h2><p>Les montants sont verrouillés une fois ta proposition acceptée.</p></div></div><div className={styles.stack}>{rows.length===0&&<p className={styles.empty}>Aucun dépôt-vente.</p>}{rows.map((row)=><article className={styles.caseCard} key={row.id}><div className={styles.caseHead}><div><span className={styles.badge}>{labels[row.status]??row.status}</span><h3>{row.consignment_number} · {row.brand} {row.model}</h3></div><strong>{money(row.agreed_sale_price??row.desired_price)}</strong></div>
    <div className={styles.moneyGrid}><div><span>Prix de vente</span><strong>{money(row.agreed_sale_price)}</strong></div><div><span>Commission Nostra</span><strong>{money(row.commission_amount)} {row.commission_rate!=null?`(${row.commission_rate} %)` : ""}</strong></div><div><span>Net propriétaire</span><strong>{money(row.owner_net_amount)}</strong></div></div>{row.staff_note&&<p className={styles.notice}>{row.staff_note}</p>}
    {row.status==="offer_sent"&&<form action={acceptVehicleConsignmentV134}><input type="hidden" name="consignment_id" value={row.id}/><button className={styles.primary}>Accepter le prix et la commission</button></form>}{["new","reviewing","offer_sent"].includes(row.status)&&<form action={cancelVehicleConsignmentV134}><input type="hidden" name="consignment_id" value={row.id}/><button className={styles.danger}>Annuler le dépôt</button></form>}{row.status==="sold"&&<p className={styles.notice}><strong>Vente terminée.</strong> {row.owner_paid_at?"Le règlement propriétaire est enregistré.":"Le règlement propriétaire reste à effectuer."}</p>}
  </article>)}</div></section></div>}</>;
}
