import { createClient } from "@/lib/supabase/server";

export type JsonRow = Record<string, unknown>;
export type Citizen = { user_id:string; name:string; email:string|null; phone:string|null; address:string|null; role:string|null; roles:string[]|null; loyalty_tier:string|null; sav_count:number; recruitment_count:number; };
export type Recruitment = { id:number; application_number:string; user_id:string; applicant_name:string; desired_position:string; phone:string|null; availability:string; experience:string; motivation:string; attachment_name:string|null; status:string; manager_message:string|null; role_to_assign:string|null; created_at:string; };
export type SavTicket = { id:number; ticket_number:string; user_id:string; requester_name:string; category:string; priority:string; subject:string; description:string; reference:string|null; status:string; assigned_to:string|null; internal_note:string|null; attachment_name:string|null; last_message_at:string; created_at:string; };
export type SavMessage = { id:number; sender_name:string; sender_kind:string; body:string; attachment_name:string|null; created_at:string; };
const n=(v:unknown)=>Number.isFinite(Number(v))?Number(v):0;
const rows=(v:unknown):JsonRow[]=>Array.isArray(v)?v.filter((x):x is JsonRow=>!!x&&typeof x==='object'):[];

export async function citizenDirectory(q=''):Promise<Citizen[]>{ const s=await createClient(); const {data,error}=await (s as any).rpc('nostra_citizen_directory'); if(error||!Array.isArray(data))return[]; const search=q.trim().toLowerCase(); return data.map((r:JsonRow)=>({user_id:String(r.user_id??''),name:String(r.name??'Compte Nostra'),email:typeof r.email==='string'?r.email:null,phone:typeof r.phone==='string'?r.phone:null,address:typeof r.address==='string'?r.address:null,role:typeof r.role==='string'?r.role:null,roles:Array.isArray(r.roles)?r.roles.map(String):null,loyalty_tier:typeof r.loyalty_tier==='string'?r.loyalty_tier:null,sav_count:n(r.sav_count),recruitment_count:n(r.recruitment_count)})).filter((r:Citizen)=>!search||[r.name,r.email,r.phone,r.role,...(r.roles??[]),r.loyalty_tier].filter(Boolean).join(' ').toLowerCase().includes(search)); }
export async function citizenDetail(id:string):Promise<JsonRow|null>{ const s=await createClient(); const {data,error}=await (s as any).rpc('nostra_citizen_detail',{p_user:id}); return error||!data?null:data as JsonRow; }
const mapRec=(r:JsonRow):Recruitment=>({id:n(r.id),application_number:String(r.application_number??''),user_id:String(r.user_id??''),applicant_name:String(r.applicant_name??''),desired_position:String(r.desired_position??''),phone:typeof r.phone==='string'?r.phone:null,availability:String(r.availability??''),experience:String(r.experience??''),motivation:String(r.motivation??''),attachment_name:typeof r.attachment_name==='string'?r.attachment_name:null,status:String(r.status??'received'),manager_message:typeof r.manager_message==='string'?r.manager_message:null,role_to_assign:typeof r.role_to_assign==='string'?r.role_to_assign:null,created_at:String(r.created_at??'')});
export async function recruitments(userId?:string):Promise<Recruitment[]>{ const s=await createClient(); let req=(s as any).from('recruitment_applications').select('*').order('created_at',{ascending:false}); if(userId)req=req.eq('user_id',userId); const {data,error}=await req; return error?[]:(data??[]).map(mapRec); }
const mapTicket=(r:JsonRow):SavTicket=>({id:n(r.id),ticket_number:String(r.ticket_number??''),user_id:String(r.user_id??''),requester_name:String(r.requester_name??''),category:String(r.category??'other'),priority:String(r.priority??'normal'),subject:String(r.subject??''),description:String(r.description??''),reference:typeof r.reference==='string'?r.reference:null,status:String(r.status??'open'),assigned_to:typeof r.assigned_to==='string'?r.assigned_to:null,internal_note:typeof r.internal_note==='string'?r.internal_note:null,attachment_name:typeof r.attachment_name==='string'?r.attachment_name:null,last_message_at:String(r.last_message_at??''),created_at:String(r.created_at??'')});
export async function savTickets(userId?:string):Promise<SavTicket[]>{ const s=await createClient(); let req=(s as any).from('motors_sav_tickets').select('*').order('last_message_at',{ascending:false}); if(userId)req=req.eq('user_id',userId); const {data,error}=await req; return error?[]:(data??[]).map(mapTicket); }
export async function savDetail(id:number):Promise<{ticket:SavTicket;messages:SavMessage[]}|null>{ const s=await createClient(); const [t,m]=await Promise.all([(s as any).from('motors_sav_tickets').select('*').eq('id',id).maybeSingle(),(s as any).from('motors_sav_messages').select('*').eq('ticket_id',id).order('created_at',{ascending:true})]); if(t.error||!t.data)return null; return {ticket:mapTicket(t.data),messages:(m.data??[]).map((r:JsonRow)=>({id:n(r.id),sender_name:String(r.sender_name??''),sender_kind:String(r.sender_kind??'system'),body:String(r.body??''),attachment_name:typeof r.attachment_name==='string'?r.attachment_name:null,created_at:String(r.created_at??'')}))}; }
export async function auditLogs(q='',entity=''):Promise<JsonRow[]>{ const s=await createClient(); let req=(s as any).from('nostra_audit_logs').select('*').order('created_at',{ascending:false}).limit(250); if(entity)req=req.eq('entity_type',entity); const {data,error}=await req; if(error)return[]; const search=q.toLowerCase(); return rows(data).filter(r=>!search||[r.actor_name,r.action_key,r.entity_type,r.entity_id,r.summary].filter(Boolean).join(' ').toLowerCase().includes(search)); }
export async function backups():Promise<JsonRow[]>{ const s=await createClient(); const {data,error}=await (s as any).from('nostra_backup_snapshots').select('id,label,created_by_name,source,payload_size,created_at').order('created_at',{ascending:false}); return error?[]:rows(data); }
export async function securityOverview():Promise<JsonRow|null>{ const s=await createClient(); const {data,error}=await (s as any).rpc('nostra_security_overview'); return error||!data?null:data as JsonRow; }
